llvm/torch-mlir

.github/workflows/RollPyTorch.yml
The RollPyTorch action needs the `unzip` command to peek into WHL files
for fetching metadata.  This patch makes sure that the command is
installed before referencing it.
=> CI: install `unzip` before using it

python/torch_mlir_e2e_test/test_suite/basic.py, python/torch_mlir_e2e_test/test_suite/cast.py, python/torch_mlir_e2e_test/test_suite/constant_alloc.py, python/torch_mlir_e2e_test/test_suite/conv.py, python/torch_mlir_e2e_test/test_suite/elementwise.py, python/torch_mlir_e2e_test/test_suite/histogram_binning_calibration.py, python/torch_mlir_e2e_test/test_suite/index_select.py, python/torch_mlir_e2e_test/test_suite/nll_loss.py, python/torch_mlir_e2e_test/test_suite/reduction.py, python/torch_mlir_e2e_test/test_suite/scalar.py, python/torch_mlir_e2e_test/test_suite/scalar_comparison.py, python/torch_mlir_e2e_test/test_suite/slice_like.py, python/torch_mlir_e2e_test/test_suite/threshold.py, python/torch_mlir_e2e_test/test_suite/type_promotion.py
Random tensors used in e2e tests should be created using the `TestUtils` object passed to the registered test case to ensure that the compiled module and the golden trace receive the same tensors as input. This commit changes all the cases of `torch.rand` and `torch.randn` to use the `TestUtils` instead.
=> Replace `torch.rand` and `torch.randn` in e2e tests with `tu.rand`

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpBase.td, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.h, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.td, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/IR/TcpOps.cpp, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/misc.mlir
This PR adds grouping ops `tcp.group`, `tcp.isolated_group` and a `tcp.yield` op.
=> [Tcp] Add group, isolated_group, and yield ops

.github/workflows/RollPyTorch.yml, .github/workflows/bazelBuildAndTest.yml, .github/workflows/buildAndTest.yml, .github/workflows/buildRelease.yml, .github/workflows/gh-pages-releases.yml, .github/workflows/oneshotSnapshotPackage.yml, .github/workflows/releaseSnapshotPackage.yml
We have recently started seeing errors like:
```
Synchronizing submodule url for 'externals/llvm-project'
Synchronizing submodule url for 'externals/mlir-hlo'
/usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1
Error: fatal: Unable to create '/home/anush/actions-runner/_work/torch-mlir/torch-mlir/.git/modules/externals/llvm-project/index.lock': File exists.
```
As a workaround, this patch removes the workspace directory before the
checkout step.
=> CI: clear workspace directory before checkout

lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/refine-types.mlir
The data-flow analysis does not always propagate information to the entire graph. This results in some lattice elements being uninitialized. Currently the lattice elements are not checked to see if they are uninitialized before rewriting the graph, potentially resulting in invalid IR (see
https://github.com/llvm/torch-mlir/issues/1896).
This commit adds handling for uninitialized lattice elements.
=> Handle uninitialized lattice elements in RefineTypes

.github/workflows/buildRelease.yml, build_tools/python_deploy/build_linux_packages.sh, build_tools/python_deploy/build_macos_packages.sh, setup.py
This PR adds a build case in the `build_macos_packages.sh` for `torch-mlir-no-jit-importer`. This is probably not the best way to factor this, which is why I didn't go ahead and add such cases to the other platforms/targets.
=> Add `torch-mlir-no-jit-importer` build case for mac os wheels

.github/workflows/bazelBuildAndTestTcp.yml, .github/workflows/buildAndTestTcp.yml
Initially proposed [here](https://github.com/llvm/torch-mlir/pull/1878#issuecomment-1440834604). 
Idea is that all PRs landing to `mlir-tcp` branch will be gated by CI.
To minimize any likely overhead on GHA runners, we only enable 2 workflows:
* CMake (linux, PyTorch binary, in-tree)
* Bazel
Also, removes email notifications from mlir-tcp branches as suggested [here](https://github.com/llvm/torch-mlir/pull/1878#issuecomment-1442324391).
=> [TCP] Enable CI (with TCP enabled) for PRs to `mlir-tcp` branch

e2e_testing/xfail_sets.py, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py
The current implementation of `getScalarValue` does not check that the input to a `ValueTensorLiteralOp` is an i64 before extracting the value, and it does not check that the result type of the `PrimNumToTensorScalarOp` is also an i64. This leads to crashes or invalid IR generated when the `input` is something other than an i64 tensor or `!torch.int`.
This commit addresses those issues. In addition, the function `getScalarValue` is renamed to `getScalarIntValue` to make it clear that it *only* extracts scalar integers.
=> Fix handling of non-int tensors in `getScalarValue`

tools/torch-mlir-opt/torch-mlir-opt.cpp
I tried to use following commad to debug my program:
> ./torch-mlir/build/bin/torch-mlir-opt --chlo-legalize-to-hlo ./xxx-chlo.mlir
It showed torch-mlir-opt tool didn't support chlo dialect:
`error: Dialect 'chlo' not found for custom op 'chlo.broadcast_add'`
This PR tries to add stablehlo dialects support for this tool.
=> Adding stablehlo dialects support for torch-mlir-opt tool

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir_e2e_test/test_suite/basic.py, test/Dialect/Torch/refine-types-ops.mlir
Current type refinement implementation for cat is wrong when the operands have diffrent types
=> [TORCH] Improve type refinement for aten.cat.

lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Dialect/Torch/IR/TorchOps.cpp
The functions `isOneValue` and `getAllOnesValues` are deprecated. `isOne` and `getAllOnes` should be used instead.
=> Fix deprecation warnings for `isOneValue` and `getAllOnesValue`

e2e_testing/xfail_sets.py, include/torch-mlir/Dialect/Torch/Transforms/Passes.h, lib/Dialect/Torch/Transforms/CMakeLists.txt, lib/Dialect/Torch/Transforms/Passes.cpp, lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp, python/torch_mlir_e2e_test/test_suite/slice_like.py
This folds patterns of `fold` and then `copy_` into `index_put_`, since the initial pattern doesn't work with `MaximizeValueSemantics`.
=> Fold slice+copy_ into index_put_

lib/Dialect/Torch/IR/TorchTypes.cpp, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/invalid.mlir
Currently, the op `torch.tensor_static_info_cast` will not get canonicalized away if the result type has any shape or dtype information. This is because `isValidSubtype` only returns true when the tensor types being compared are exactly the same or the supertype has no shape and dtype information. Being unable to canonicalize away the `torch.tensor_static_info_cast` gets in the way of further optimizations, such as shape propagation.
This commit improves `isValidSubtype` by adding logic that compares the shapes and dtypes of the two tensor types to determine of one type is indeed a valid subtype of the other.
Fixes https://github.com/llvm/torch-mlir/issues/1926
=> Expand definition of tensor subtype to include shape/dtype info

utils/bazel/torch-mlir-overlay/BUILD.bazel
Fixes a broken bazel build from https://github.com/llvm/torch-mlir/pull/1887 causing the following build error:
```
ERROR: /root/.cache/bazel/_bazel_root/b89349c08f7224396763d14fe35cba11/external/torch-mlir/BUILD.bazel:819:10: Compiling tools/torch-mlir-opt/torch-mlir-opt.cpp failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-16/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer ... (remaining 366 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/torch-mlir/tools/torch-mlir-opt/torch-mlir-opt.cpp:16:10: fatal error: 'stablehlo/dialect/Register.h' file not …
```
=> [Bazel] Add StableHLO registration dependency

lib/Conversion/TorchToTcp/Elementwise.cpp, lib/Conversion/TorchToTcp/Utils.cpp
As titled.
Also fixes `s/llvm::makeArrayRef/llvm::ArrayRef/` per deprecation notice.
=> [TCP] Check and notifyMatchFailure for integer cases of `AtenDivTensorOp` -> TCP

lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, test/Dialect/Torch/verify-backend-contract-unimplemented-op.mlir
As discussed on discord [0], this PR will emit more direct errors like `unsupported by backend contract: Unimplemented operator 'aten.clamp.Tensor'` instead of diagnosing unknown ranks or missing value conversion.
[0] https://discordapp.com/channels/636084430946959380/742573221882364009/1083826291301679225
=> LowerToBackendContract: Explicitly error out on unimplemented operator

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Adds support for lowering aten::remainder.Scalar in TorchToTosa. Covered by existing e2e testing (added to Tosa passing list) and basic.mlir test.
=> Add support for aten_remainder in TorchToTosa

e2e_testing/xfail_sets.py, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.td, externals/llvm-external-projects/torch-mlir-dialects/lib/Conversion/TcpToLinalg/Elementwise.cpp, externals/llvm-external-projects/torch-mlir-dialects/test/Conversion/TcpToLinalg/unary.mlir, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/unary.mlir, lib/Conversion/TorchToTcp/Elementwise.cpp, test/Conversion/TorchToTcp/elementwise.mlir
- Add the tcp op definitions for floor and ceil operations
- Add the torch->tcp and tcp->linarg conversion for floor and ceil operations.
- Updated test cases to include floor and ceil operations
To test:
`./build/bin/llvm-lit externals/llvm-external-projects/torch-mlir-dialects/test/Conversion/TcpToLinalg/ -v`
`./build/bin/llvm-lit externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/ -v`
`./build/bin/llvm-lit test/Conversion/TorchToTcp/ -v`
`python -m e2e_testing.main --config=tcp -v -s`
=> [TCP] unary ops support for floor and ceil operations

include/torch-mlir/Dialect/Torch/Transforms/Passes.h, include/torch-mlir/Dialect/Torch/Transforms/Passes.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, lib/Dialect/Torch/Transforms/Passes.cpp, lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp, lib/Dialect/Torch/Transforms/ReifyAbstractInterpCalculationsUtils.cpp, lib/Dialect/Torch/Transforms/ReifyAbstractInterpCalculationsUtils.h, lib/Dialect/Torch/Transforms/ReifyDtypeCalculations.cpp, lib/Dialect/Torch/Transforms/ReifyShapeCalculations.cpp, python/test/compile_api/backend_legal_ops.py, python/torch_mlir/__init__.py, test/Dialect/Torch/decompose-complex-ops-legal.mlir, test/Dialect/Torch/torch-function-to-torch-backend-pipeline.mlir, test/python/custom_op_shape_dtype_fn.py
handles 2,3,4 from https://github.com/llvm/torch-mlir/issues/1963
```python
class CustomOpExampleModule(torch.nn.Module):
def __init__(self):
super().__init__()
@export
@annotate_args(
[
None,
([-1, -1], torch.float32, True),
]
)
def forward(self, a):
b = 2 * a
return torch.ops.goofy.identity(b)
mod = CustomOpExampleModule()
mod.eval()
abstract_interp_src = """\
func.func @__torch_mlir_shape_fn.goofy.identity(%arg0: !torch.list<int>) -> !torch.list<int> {
return %arg0 : !torch.list<int>
}
func.func @__torch_mlir_dtype_fn.goofy.identity(%arg0 : !torch.tuple<int, int>) -> !torch.int {
%0:2 = torch.prim.TupleUnpack %arg0 : !torch.tuple<int, int> -> !torch.int, !torch.int
return %0#1 : !torch.int
}
func.func @__torch_mlir_has_value_semantics_fn.goofy.identity() { return }
"""
tmp = …
```
=> Implementation for user-provided shape and dtype functions for custom ops

python/torch_mlir/__init__.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/library_generator.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/registry.py, test/python/custom_op_shape_dtype_fn.py
This commit adds the ability to specify extra abstract interpretation functions in `torch_mlir.compile` to use during type refinement. This allows users to easily add custom ops without having to interact with MLIR or C++ directly.
=> Add `extra_library` kwarg to `torch_mlir.compile`

include/torch-mlir/Conversion/Passes.td, include/torch-mlir/Conversion/TorchConversionToMLProgram/TorchConversionToMLProgram.h, lib/Conversion/PassDetail.h, lib/Conversion/TorchConversionToMLProgram/TorchConversionToMLProgram.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, test/Conversion/TorchConversionToMLProgram/multiple_functions.mlir
* Only create the global seed variable if it does not exist already.
* Make the pass a module pass. A func pass may not modify its parent op.
=> Minor fixes for `ConvertTorchConversionToMLProgram`.

.github/workflows/RollPyTorch.yml, .github/workflows/bazelBuildAndTest.yml, .github/workflows/buildAndTest.yml, .github/workflows/buildRelease.yml, .github/workflows/gh-pages-releases.yml, .github/workflows/oneshotSnapshotPackage.yml, .github/workflows/releaseSnapshotPackage.yml
Despite using sudo to delete the workspace directory, we still
occasionally run into checkout errors.  This patch thus drops the
deletion of the workspace prior to checkout.  It also restricts the
number of parallel jobs in the submodule fetch step to just one, to try
and resolve the checkout issue ("index.lock: File exists.").
=> CI: drop deletion of workspace and limit submodule fetch concurrency

.github/workflows/RollPyTorch.yml, .github/workflows/bazelBuildAndTest.yml, .github/workflows/buildAndTest.yml, .github/workflows/buildRelease.yml, .github/workflows/gh-pages-releases.yml, .github/workflows/oneshotSnapshotPackage.yml, .github/workflows/releaseSnapshotPackage.yml
Reverts llvm/torch-mlir#1921 since we still need the sudo rm to clean up after nightly builds.
=> Revert "CI: drop deletion of workspace and limit submodule fetch concurrency"

.github/workflows/buildRelease.yml
This is to potentially workaround the index.lock issue in git when we checkout new depth 1 submodules of recently updated mhlo.
=> Set fetch-depth 0

lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
https://github.com/llvm/torch-mlir/issues/1979
Here is the file for test:
[test_maked_fill.py](https://gist.github.com/AmosLewis/85b7c19409bfdbe45f216d689e947578#file-test_maked_fill-py),
test_masked_fill_torchscript_0327_transformers4.26.0.mlir
```
module attributes {torch.debug_module_name = "_lambda"} {
func.func private @__torch__.torch.fx.graph_module._lambda.__code_getter(%arg0: !torch.nn.Module<"__torch__.torch.fx.graph_module._lambda">) -> !torch.str {
%2 = torch.prim.GetAttr %arg0["_code"] : !torch.nn.Module<"__torch__.torch.fx.graph_module._lambda"> -> !torch.str
return %2 : !torch.str
}
func.func private @__torch__.torch.fx.graph_module._lambda.forward(%arg0: !torch.nn.Module<"__torch__.torch.fx.graph_module._lambda">, %arg1: !torch.tensor {torch.type_bound = …
```
=> [MLIR] Fold aten select and fill_ pattern

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpBase.td, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.h, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/misc.mlir, externals/llvm-external-projects/torch-mlir-dialects/tools/torch-mlir-dialects-opt/torch-mlir-dialects-opt.cpp, utils/bazel/torch-mlir-overlay/BUILD.bazel
Add quant datatype support in tcp dialect.
To test:
`./build/bin/llvm-lit externals/llvm-external-projects/torch-mlir-dialects/test/Conversion/TcpToLinalg/ -v`
`./build/bin/llvm-lit externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/ -v`
`./build/bin/llvm-lit test/Conversion/TorchToTcp/ -v`
`python -m e2e_testing.main --config=tcp -v -s`
=> [TCP] quant type support

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
https://github.com/nod-ai/SHARK/issues/986
[test_abs.mlir](https://gist.github.com/AmosLewis/e637465b23f6f96965487ad6e7e8f7b1#file-test_abs-mlir)
%149 = torch.aten.abs %137 : !torch.vtensor<[15,15],si64> -> !torch.vtensor<[15,15],si64>
=> [TOSA] Add aten.abs support

lib/Conversion/TorchToLinalg/TensorConstructors.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, python/torch_mlir_e2e_test/test_suite/rng.py
The current decomposition for `aten.randn.generator` does not specify the `dtype` argument of the empty tensors created to store the random values. This leads to invalid IR when the output type of the `randn` op is not the default PyTorch dtype.
=> Fix creation of empty tensor in decomposition for randn ops

e2e_testing/xfail_sets.py, python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp, python/torch_mlir_e2e_test/test_suite/basic.py, test/python/importer/jit_ir/ivalue_import/tensors.py
Bool tensors are represented in TorchScript as an array of `int8_t`s. However, when importing them into Torch-MLIR, the importer was assuming the array had `int32_t` elements, leading to the importer reading into memory that was out of bounds. This commit fixes the casting of the bool tensor.
=> Fix import of constant bool tensor parameters

utils/bazel/WORKSPACE.bazel
This un-breaks Bazel CI since https://github.com/llvm/torch-mlir/commit/b31c5fa1fbe412b9b278a0374b07cbc3a6f34498.
Manually triggered GHA: 
- https://github.com/sjain-stanford/torch-mlir/actions/runs/4764744603 (failed)
- https://github.com/sjain-stanford/torch-mlir/actions/runs/4769130681 (with buildifier fix)
=> [Bazel] Add `@llvm_zstd` to WORKSPACE

lib/Dialect/Torch/Transforms/ReifyAbstractInterpCalculationsUtils.cpp, test/Dialect/Torch/reify-shape-calculations.mlir
To keep things simple in shape functions, `Scalar` inputs are considered `float`s. This means that when inserting the shape functions into the IR, we must cast any `!torch.number`s into `float`s so that the operand type matches the expected type in the shape function. This commit adds the cast from `Scalar` to `float`.
=> Cherry-pick 4f6de745 "Cast `number` to `float` when shape function takes Scalar arg"

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/Pooling.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/pooling.py
When the user does not specify the `stride` value in 2d pooling ops, `stride` is given the value of an empty list. However, the current lowerings for pooling ops assumed that the `stride` operand would always be a list of two ints, leading to crashes when that was not the case. This commit fixes the crashes by setting the value of `stride` to `kernel_size` when `stride` is the empty list, since this is the default `stride` value specified in PyTorch docs. See: https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html#torch.nn.MaxPool2d
=> Fix default value of `stride` in 2d pooling ops in linalg and tosa

e2e_testing/main.py, e2e_testing/xfail_sets.py, python/torch_mlir/compiler_utils.py, python/torch_mlir_e2e_test/configs/torchdynamo.py
Per https://github.com/llvm/torch-mlir/pull/1996#discussion_r1169203933:
```
Summary:
Passed: 762
Failed: 59
Expectedly Failed: 40
```
cc @powderluv
=> [Dynamo] turn on `no_python=True` for dynamo tests

externals/llvm-external-projects/torch-mlir-dialects/CMakeLists.txt
Fixes https://github.com/llvm/torch-mlir/issues/2067
FYI you can land commits on behalf of people and still attribute like so:
```
git commit --amend --author="John Doe <jdoe@llvm.org>"
```
cc @tebartsch
=> Missing ";" bewtween includes in MHLOTargets.cmake

externals/llvm-external-projects/torch-mlir-dialects/tools/torch-mlir-dialects-opt/torch-mlir-dialects-opt.cpp, tools/torch-mlir-opt/torch-mlir-opt.cpp
This commit updates the `llvm-project` and `mlir-hlo` submodules to commits:
- llvm-project: 6875424135312aeb26ab8e0358ba7f9e6e80e741
- mlir-hlo: 92fd33a4bacbeb93ab276a49f38bdebd5f9d7487
The calls to `mlir::MlirOptMain` are updated to no longer specify the flag `preloadDialectInContext` that has been removed (see: https://reviews.llvm.org/D149039).
=> [build] Update llvm tag to 68754241

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
Simplify `to.dtype_layout` => `to.device/dtype` if layout is none.
=> [Torch Dialect] Add to.dtype_layout canonicalize patterns

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/CMakeLists.txt, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/Transforms/CMakeLists.txt, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/Transforms/FuseTcpOpsPass.h, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/Transforms/IsolateGroupOpsPass.h, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/Transforms/Passes.h, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/Transforms/Passes.td, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/CMakeLists.txt, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/CMakeLists.txt, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/FuseTcpOpsPass.cpp, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/IsolateGroupOpsPass.cpp, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/PassDetail.h, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/Passes.cpp, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/tcp-fusion.mlir, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/tcp-isolate-groups.mlir, externals/llvm-external-projects/torch-mlir-dialects/tools/torch-mlir-dialects-opt/CMakeLists.txt, externals/llvm-external-projects/torch-mlir-dialects/tools/torch-mlir-dialects-opt/torch-mlir-dialects-opt.cpp, utils/bazel/torch-mlir-overlay/BUILD.bazel
This PR adds 2 transformation passes in TCP:
1. A pass to fuse elementwise ops into `tcp.group` ops. This in turn uses a generic fuser that can be used to create groups to represent different kind of fusions.
2. A pass to convert `tcp.group` ops to `tcp.isolated_group` ops. This is useful when we want to lower from TCP to any backend that have a special way of handling the group.
=> [Tcp] Add passes to fuse TCP elementwise ops and isolate TCP groups

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/Tcp/Transforms/IsolateGroupOpsPass.cpp, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/tcp-isolate-groups.mlir
This PR fixes the handling of constants in the IsolateGroupOps pass. Specifically, any constant that is used within the isolated group op will now be cloned into the start of the block.
This also fixes another issue with duplicate input arguments in the isolated blocks, when there are multiple uses of that value.
=> [Tcp] Clone constants into the IsolatedGroup region

lib/Conversion/TorchToStablehlo/Pooling.cpp, lib/Conversion/TorchToStablehlo/Reduction.cpp, test/Conversion/TorchToStablehlo/pooling.mlir
Set `init_value` with -inf is more correct, which is the behavior of tf-to-mhlo.
=> [Stablehlo] fix reduce max init_value with -inf

lib/Conversion/TorchToLinalg/Pooling.cpp, lib/Conversion/TorchToLinalg/Reduction.cpp, test/Conversion/TorchToLinalg/pooling.mlir
This PR fix reduce max's init values to `-inf`, which is compatible with torch.
In torch:
```python
In [7]: b
Out[7]: tensor([-inf, -inf])
In [8]: torch.amax(b, 0)
Out[8]: tensor(-inf)
```
=> [Linalg] fix lowering reduce max with -inf

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.td, externals/llvm-external-projects/torch-mlir-dialects/test/Dialect/Tcp/misc.mlir
This PR updates the grouping ops in Tcp, `tcp.group`, `tcp.isolated_group`, and `tcp.yield`, to use `AnyType`, since these ops are meant to be used with ops from any MLIR dialect, not just Tcp.
=> [Tcp] Update Tcp group ops to use any MLIR type

.github/workflows/RollPyTorch.yml
The GitHub action for creating the PR expects that either the changes
are not committed (in which case it commits them with the specified
commit message) or that the commit exists but that it is also pushed to
remote.
Prior to this patch, we created the commit but did not push it to
remote, causing failures.  This patch leaves the changes uncommitted so
that they're committed and pushed to remote as part of the PR creation.
=> CI: let GitHub action create commit

.github/workflows/buildAndTest.yml, CMakeLists.txt, build_tools/python_deploy/build_windows_ci.sh, setup.py
This patch, by itself, doesn't fix caching on Windows, but once a new
release of ccache is available, caching for Windows builds should start
working again (validated by building ccache from source and using it
with LLVM builds).
Ccache rejects caching when either the `/Zi` or `/ZI` flags are used
during compilation on Windows, since these flags tell the compiler to
embed debug information in a PDB file (separate from the object file
produced by the compiler).  In particular, our CI builds add the `/Zi`
flag, making ccache mark these compiler invocations as uncacheable.
But what caused our CI to add debug flags, especially when we specified
`-DCMAKE_BUILD_TYPE=Release`?  On Windows, unless we specify the
`--config Release` flag during the CMake build step, CMake assumes a
debug build.  So …
=> CI: prepare CI for ccache updates for MSVC/Windows

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
This PR adds all legal casts (according to TOSA spec) from/to bf16 into the TorchToTosa lowering pass,
and it also adds the cast from i64 to i32 (which was missing).
I did not add end2end tests as per the discussion on discord [0] and because the torch-mlir end2end testing
framework is not ready for bf16:
- It doesn't have the compiler-rt builtins for f32 to bf16 conversions
- Numpy doesn't support bf16, so it cannot tell them apart from f16.
[0] https://discordapp.com/channels/636084430946959380/742573221882364009/1104136103314849844
=> TorchToTosa: Support casts from and to bf16

.github/workflows/RollPyTorch.yml, .github/workflows/buildAndTest.yml
We previously used a fork of the action/cache repository for the PyTorch
cache since the actions/cache repo did not support read-only caches.
Now that actions/cache supports separate read and write steps, this
patch switches back to the actions/cache repo.
=> CI: [nfc] Use actions/cache instead of modified fork

utils/bazel/torch-mlir-overlay/BUILD.bazel
Update the bazel rule `TorchMLIRInitAll` to include Tcp transformation passes.
=> [Tcp] Add Tcp passes bazel target to TorchMLIRInitAll

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h, include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir
Lowering torch operations that allow different compatible data types in its operands to tosa end up generating invalid tosa IR with mixed data types. In tosa spec, certain operations (generally elementwise operations) require all operands to have the same data type.
Add wrapper functions for those elementwise tosa ops to perform op creation with type conversion if necessary.
please note that I used lit tests because of the limited e2e support for bf16.
=> [tosa] support lowering basic torch binary ops with mixed dtypes

.github/workflows/RollPyTorch.yml
Since PRs created by the GitHub action bot cannot trigger workflows (and
thus build tests), this patch uses the token for a GitHub app that was
specifically created for the RollPyTorch action.
=> CI: Use GitHub app token for creating PRs

.github/actions/setup-build/action.yml, .github/workflows/buildRelease.yml
This patch adds a (default-true) input called `cache-enabled` to the
setup-build action, so that when the input is false, ccache is not setup
on the host machine.  This patch also sets the input to be false for the
release builds.
=> CI: disable caching for release builds

lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp, test/Dialect/Torch/maximize-value-semantics.mlir
When `use_tracing=True` is used to import a model into Torch-MLIR, several casts get inserted in the IR to bridge the untyped inputs and outputs with the typed body of the computation. These casts create extra aliases of tensors that cause the current analysis in `maximize-value-semantics` to fail.
In particular, the `maximize-value-semantics` analysis assumes that the only valid alias right after an overwrite is the overwritten alias. So, if there is a use of a casted version of the overwritten alias after the overwrite, the analysis fails.
This commit improves the analysis by identifying all cast-like aliases of the overwritten alias and allowing such aliases to be used after an overwrite.
Because this issue only arises when using tracing, it cannot be currently tested e2e, so only lit …
=> Add alias analysis for cast-like ops to maximize-value-semantics

.github/workflows/buildRelease.yml
(left over from a previous commit that was approved and landed in a branch on accident)
=> Remove spurious pip in Release builds

.github/workflows/buildRelease.yml, build_tools/python_deploy/build_linux_packages.sh, whl-requirements.txt
Creates a build_linux_arm64 job that builds the release on an arm64 self-hosted runner.  Drop Python 3.10 support
Pass  TM_TORCH_VERSION to choose the Stable PyTorch version (since arm64 doesn't have nightly builds)
=> Add ARM64 release builds

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
This might need better input size verification, but this compiles cross attention cases properly, fixing #2135.
=> Remove incorrect type checking for Torch::ScaledDotProductAttention

CMakeLists.txt, utils/bazel/torch-mlir-overlay/test/BUILD.bazel
This PR enables Tcp by default in the cmake as well as bazel builds in the `mlir-tcp` branch.
=> [Tcp] Enable Tcp by default in mlir-tcp branch

e2e_testing/main.py, e2e_testing/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/TorchOps.td, python/torch_mlir_e2e_test/test_suite/basic.py
Before inlining a global slot, the users of the global slot are checked to see if they are `ReadOnly` or `MemoryEffectFree` to make sure that the global slot is not being mutated. Because the op `copy.to_vtensor` currently does not have the `ReadOnly` trait, if a global slot is passed to `copy.to_vtensor`, the pass `InlineGlobalSlots` will fail.
The op `copy.to_vtensor` is `ReadOnly`, since it does not modify the contents of the input tensor; it simply makes a new copy. This commit adds the trait as well as an e2e test that generates the case of a global slot being passed to a `copy.to_vtensor`.
=> Add `ReadOnly` trait to `copy.to_vtensor`

.github/workflows/buildAndTest.yml
This PR contains two patches:
- CI: Skip (redundant) libtorch build when using stable PyTorch version
> When we use PyTorch stable builds, there is no need to build libtorch
> from source, making the stable-pytorch-with-torch-binary-OFF
> configuration redundant with stable-pytorch-with-torch-binary-ON.  This
> patch drops the redundant configuration from CI.
- CI: Simplify guard conditions for creating and using libtorch cache
> Whether libtorch is enabled or not is predicated on a host of conditions
> such as the platform, in-tree versus out-of-tree build, and stable
> versus nightly PyTorch builds.  Instead of repeating these conditions to
> guard whether to create or use the libtorch cache artifacts (and getting
> them almost incorrect), this patch predicates the relevant pipeline
> …
=> CI: Spot fixes related to nightly and stable PyTorch builds

.github/workflows/RollPyTorch.yml, .github/workflows/merge-rollpytorch.yml
Before enabling the actual merge, this patch dumps to the console the
bash commands that it plans to execute.
=> CI: Update script to (mock) merge of RollPyTorch PRs

python/CMakeLists.txt, python/torch_mlir/_version.py, python/torch_mlir/dynamo.py, python/torch_mlir_e2e_test/test_suite/__init__.py
The version comparison was wrong when the local version had a local suffix of `+cu117` (default torch package) instead of `+cpu` (as used by CI).
I extracted the stripping of that suffix into a separate function.
=> Fix version comparison against stable

.github/workflows/merge-rollpytorch.yml
This patch removes the mock commands, so that once the Build And Test
workflow has successfully completed on the RollPyTorch action, the PR is
merged and the branch is deleted.
=> CI: Merge RollPyTorch PR upon successful completion

e2e_testing/main.py, python/test/torchscript_e2e_test/compilation_failure.py, python/torch_mlir_e2e_test/reporting.py
When an end2end test fails or unexpectedly passes in CI, it sometimes takes me a bunch of scrolling to understand in which e2e config the test failed.
With this change, we show the name of the end2end config at the end of output.
=> Print name of the backend when tests fail to help debugging issues in CI

.github/workflows/merge-rollpytorch.yml
Without this patch, the gh command (for merging the PR) doesn't know
which repo we're referring to.
=> CI: Checkout repo so that gh knows where to look for the PR

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir
When converting the following `torch.aten.div` operation:
```
%int128 = torch.constant.int 128
%0 = torch.aten.div.Scalar %arg0, %int128 : !torch.vtensor<[?,?],si64>, !torch.int -> !torch.vtensor<[?,?],f32>
```
The following TOSA IR would be generated:
```
%0 = "torch_c.to_builtin_tensor"(%arg0) : (!torch.vtensor<[?,?],si64>) -> tensor<?x?xi64>
%1 = "torch.constant.int"() {value = 128 : i64} : () -> !torch.int
%2 = "tosa.const"() <{value = dense<128> : tensor<i64>}> : () -> tensor<i64>
%3 = "tosa.cast"(%0) : (tensor<?x?xi64>) -> tensor<?x?xf32>
%4 = "tosa.cast"(%2) : (tensor<i64>) -> tensor<f32>
%5 = "tosa.div"(%3, %4) : (tensor<?x?xf32>, tensor<f32>) -> tensor<?x?xf32>
```
Causing an error in the TOSA operation verifier:
```
'tosa.div' op operand #0 must be tensor of 32-bit signless …
```
=> [MLIR][TOSA] Fix aten.div conversion for integer inputs

lib/Dialect/Torch/Utils/Utils.cpp, test/Dialect/Torch/torch-function-to-torch-backend-pipeline.mlir
This is first PR for https://github.com/llvm/torch-mlir/pull/2184.
This PR fix `dtype inference` on torch.uint8.
=> [Torch Dialect] fix torch.uint8's dtype infer

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
Whenever we create floating point tosa.const, we need to ensure that they have the correct type.
Right now, they inherit the type for the C++ type (float/double), which doesn't allow to express f16 and bf16.
This adds an optional `dtype` argument to `getConstTensor`,
and updates all callsites of getConstTensor<float> to use it.
=> TorchToTosa: Cast float constants to correct type to support bfloat16

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, python/torch_mlir_e2e_test/test_suite/basic.py, test/Conversion/TorchToLinalg/basic.mlir
This commit adds the support for index.Tensor op when the index values are negative. This commit wraps around the index values by checking their values at run time.
Fixes https://github.com/openxla/iree/issues/13951.
=> [MLIR][TORCH] Add support for negative index values for index.Tensor op

tools/torch-mlir-lsp-server/CMakeLists.txt, tools/torch-mlir-lsp-server/torch-mlir-lsp-server.cpp, tools/torch-mlir-opt/CMakeLists.txt, tools/torch-mlir-opt/torch-mlir-opt.cpp
This patch updates the submodules to:
- llvm: 3f8d8c1aac3086f603ad73f18fe2bd4fb91fa10a
- mhlo: 4384a47b03dc377d651523037867899a340b0e96
The only change made is calling `registerAllExtensions` during dialect registration. See: https://reviews.llvm.org/D120368
=> [build] Update llvm tag to 3f8d8c1a

include/torch-mlir-c/TorchTypes.h, lib/CAPI/TorchTypes.cpp
Recently I added https://reviews.llvm.org/D150927 that enables downstream consumers (like PI) of the CAPI to branch based on the type of an `ir.Value` in python bindings (amongst other things). This only requires exposing the typeids through the CAPI. This PR does that (exposes the typeids for the various torch-mlir types). Note, [upstream follows the exact same pattern and exposes all builtin typeids](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir-c/BuiltinTypes.h#L25-L26).
cc @123epsilon
=> Add typeids to CAPI

python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/registry.py
Single element tuples in Python need a comma after the element. However, the `registry.py` file, which generates the expected abstract interpretation function signatures, was not inserting the comma. This commit changes the expected signature generator to add a comma after the last element in any non-empty default tuple argument.
=> Fix single-element tuple construction in abstract interp library

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
Since the semantics of aten.to.other op and aten.to.device op is too close, this patch canonicalizes the former into prim.device + prim.dtype + aten.to.device.
=> [Torch Dialect] Add canonicalizer for aten.to.other op

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
It seems generally better to preserve the information we have. This makes the live easier for TOSA, which doesn't handle dynamic shapes very well.
=> DecomposeComplexOps: Use static shape if available

e2e_testing/xfail_sets.py, include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, python/torch_mlir_e2e_test/test_suite/scatter.py, python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py
https://github.com/nod-ai/SHARK/issues/986
**0421 Update:**
> Since there is no lowering pass for **tosa::scatter to linalg** in llvm-project. So the e2e test won't pass. So this patch is not mature enough to merge. Let's just keep it separately in my local branch. 
Raw fail ops in t5 model:
`%30 = torch.aten._index_put_impl %21, %29, %24, %false, %false : !torch.vtensor<[1,4],si64>, !torch.list<optional>, !torch.vtensor<[1,3],si64>, !torch.bool, !torch.bool -> !torch.vtensor<[1,4],si64>`
python code
```
torch.ops.aten.index_put(torch.tensor([[0,1,2,3]]), (torch.tensor([0,0,0]),torch.tensor([1,2,3]) ),torch.tensor([4,5,6]))
a = torch.tensor([[1, 2, 3, 4]])
a[..., 1:] = torch.tensor([0, 0, 0])
a =  torch.tensor([[1, 0, 0, 0]])
torch.ops.aten.index_put(torch.tensor([[1, 2, 3, 4]]), …
```
=> [TOSA] Add aten._index_put_impl support

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
This can happen when the input comes from an unsupported operator.
`convertTensorToDtype` below relies on that information.
=> Don't crash when the input to aten.copy is unranked

lib/InitAll.cpp
[LLVM bump](https://github.com/llvm/torch-mlir/commit/ebda6111000710470bad61ac9c467b57b2744d1a) brought in this [commit](https://reviews.llvm.org/D120368) that required inline extension for the func dialect to be declared explicitly.
This was causing the Windows dll to crash in SHARK in all snapshots after https://github.com/llvm/torch-mlir/releases/tag/snapshot-20230620.875
=> Fixes Windows DLL crash

e2e_testing/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/type_conversion.py, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/decompose-complex-ops.mlir
Previous folder for aten.type_as op didn't check whether the operands' dtype are all known. It might cause the aten.type_as op to be wrongly eliminated by `canonicalize` pass.
This patch canonicalize the aten.type_as op to aten.to_dtype op.
--- Edit ---
Change to use decomposition pass to convert aten.type_as op to prim.dtype + aten.to_dtype op.
=> [torch-dialect] fix aten.type_as op's folder

python/torch_mlir/compiler_utils.py
Some idiot ([me](https://github.com/llvm/torch-mlir/commit/d70bb68c9e8efd4fa940cddeb36cdfb48e87c909)) added `TorchMlirCompilerError` but didn't understand that in Python [user-defined exceptions](https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions) don't take an argument. This causes the very inconvenient
```
TypeError: TorchMlirCompilerError.__init__() missing 1 required positional argument: 'value'
```
to confound actual compiler errors (for a long time now I guess). 
cc @123epsilon
=> Conform to Python custom exception api

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
It's actually fine to not check the rank of the indices, because the conversion anyways flattens the index tensor to be (1, numElements) before applying tosa::gather, and then anyways reshapes the output tensor to the output shape of the aten.embedding.
=> TorchToTosa: aten.embedding: Allow indices with any rank

lib/Conversion/TorchToStablehlo/GatherScatter.cpp, test/Conversion/TorchToStablehlo/scatter.mlir
Since for now `hlo-legalize-to-linalg` pass doesn't support `stablehlo::Scatter` op, this patch won't pass relevant E2E tests. Instead, we add a MLIR unittest case.
=> [Stablehlo] add converter for aten.scatter.src op

lib/CMakeLists.txt, utils/bazel/torch-mlir-overlay/BUILD.bazel
fix `torch-mlir-capi-torch-test` and `bazel` after merge.
=> fix cmake torch-mlir-capi linking and bazel build

e2e_testing/main.py, e2e_testing/xfail_sets.py, python/torch_mlir_e2e_test/test_suite/basic.py
Doing `module.to('lazy')` only moves the module member tensors to the device if they are created with `self.register_buffer` or `self.register_parameter`. Since the `self.tensor` tensor in `Add_Module` test is currently not created using the `self.register_*` methods, it is not being moved from CPU to lazy device, which is causing the test to fail on LTC backend. This commit uses `self.register_buffer` to fix the test on LTC backend.
This commit also seems to fix the test for torchdynamo.
Fixes https://github.com/llvm/torch-mlir/issues/2186
=> Use `register_buffer` to make `Add_Module` test work on lazy tensor

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir
This improves the error message when lowering to tosa fails by pointing at the actual op that is missing support.
The constants are never a problem because
- they are pure, so they will fold away if unused
- they don't return tensor types, so they cannot be used directly by the ReturnOp
Thus there is always some other op using them, and that op is the interesting one.
=> Ignore constants in the legality error

test/CAPI/CMakeLists.txt
I saw test failing when FileCheck wasn't build yet.
=> test/CAPI/CMakeLists.txt: Depend on FileCheck

python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp, python/torch_mlir/csrc/base_lazy_backend/utils/string_utils.h, python/torch_mlir/csrc/base_lazy_backend/utils/sys_utils.h, python/torch_mlir/csrc/reference_lazy_backend/reference_lazy_backend_pybind.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp, test/python/importer/jit_ir/node_import/debug-info.py
Added support for LTC stack trace propagation up to torch MLIR locations. This option is turned off by default. To enable debug info you need to specify these options:
* `LTC_IR_DEBUG=1` - enables debug info.
* `LTC_IR_DEBUG_ROOT_PATH="/home/gleb/torch-mlir/:/home/gleb/pytorch/"` - list of paths which are used to trim absolute paths for readability _(optional)._
To check how it works you can run LTC MNIST test with reference backend:
```
LTC_IR_DEBUG=1 python ./torch-mlir/examples/ltc_backend_mnist.py -d MLIR_EXAMPLE
```
This is an example of `addmm` operation locations which consist of `function_name/file_name/line_number` per `callsite`:
```
%4 = torch.aten.addmm %arg4, %arg0, %1, %2, %3 : !torch.vtensor<[10],f32>, !torch.vtensor<[1,5],f32>, !torch.vtensor<[5,10],f32>, !torch.int, …
```
=> LTC->MLIR Debug Info support

setup.py
Needed by `torch_mlir._version`. Resolves #2368.
=> Add packaging as an install dependency

.github/workflows/buildAndTest.yml
The CI jobs that use stable PyTorch are currently not required to pass in order for a patch to get merged in `main`. This commit makes sure that if a CI job for stable PyTorch fails, it does not cancel the other required jobs.
=> Prevent failed stable CI job from cancelling nightly jobs

python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/library_generator.py, test/python/custom_op_shape_dtype_fn.py
When using custom ops, sometimes PyTorch will insert namespaces to the abstract interpretation function name in the format: `__torch__.{namespace_1}.{namespace_2}...{op_name}`.  The extra namespaces are not part of the abstract interpretation function name, so it needs to be removed before generating the library of MLIR snippets of abstract interpretation functions. This commit adds support for removing the namespace information.
=> Add handling of namespaces to library generator

include/torch-mlir/Conversion/Utils/Utils.h, include/torch-mlir/Dialect/Torch/IR/TorchOps.td, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/Pooling.cpp, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToSCF/TorchToSCF.cpp, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/GatherScatter.cpp, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/Utils/Utils.cpp, lib/Dialect/Torch/IR/TorchOps.cpp
This commit updates the `llvm-project` and `mlir-hlo` submodules to commits:
llvm-project: a3f2751f782f3cdc6ba4790488ec20163a40ac37
mlir-hlo: 97c7e4b4506c3a2441c923e592833f45da439009
Changes made:
- Rename `getSuccessorEntryOperands` with `getEntrySuccessorOperands` and remove `operands` from
`getSuccessorRegions` (https://reviews.llvm.org/D157506)
- Make `TypeConverter` a `const` (https://reviews.llvm.org/D157601)
=> [build] Update llvm tag to a3f2751f

docs/code_owners.md
Sean has decided to move on to other ventures and has requested that I help him disengage by resuming top level accountability for the project.
=> Per request, swap Sean Silva for Stella Laurenzo in code owners.

include/torch-mlir/Dialect/Torch/IR/TorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
This a reverter for PR #2306 . PrimListConstructOp has so many complex usage scenarios. Canonializing it might not be a good idea. 
Here is an example. Suppose we have a IR like:
```mlir
%499 = torch.aten.chunk %498, %int4, %int0 : !torch.tensor, !torch.int, !torch.int -> !torch.list<tensor>
%500:4 = torch.prim.ListUnpack %499 : !torch.list<tensor> -> !torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor
%501 = torch.prim.ListConstruct %500#0, %500#1, %500#2, %500#3 : (!torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor) -> !torch.list<tensor>
%502 = torch.aten.cat %501, %int-1 : !torch.list<tensor>, !torch.int -> !torch.tensor
```
If we canonicalize the ListConstructOp, the `aten.cat` op will directly use the result from `aten.chunk`. It might fail some passes, since we often …
=> [Torch Dialect] revert canonicalizer for PrimListConstructOp

.github/workflows/buildAndTest.yml, build_tools/python_deploy/build_linux_packages.sh
This way, we can keep CI green without being forced to ignore _all_
errors that arise in stable PyTorch builds
=> CI: disable LTC e2e tests in stable PyTorch builds

e2e_testing/xfail_sets.py, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
Implements a decomposition for aten.rand that fills an empty tensor with uniformly generated values between 0 and 1. This passes tests in all backends except for `tosa`, there is an existing implementation (merged yesterday) that is specific to `stablehlo` from @Vremold. Please let me know if the implementation is correct :)
=> [MLIR][TORCH] add E2E support for aten.rand

lib/Conversion/Utils/Utils.cpp, lib/Dialect/Torch/Transforms/AbstractInterpLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
Found with a more strict set of warning flags on GCC 9.
=> Fix GCC warning recommending parens.

lib/Conversion/TorchToLinalg/Uncategorized.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py
Supports torch complex dtype tensor mul - `torch.mul`
Note that current torch-mlir does not support multiplication between two different dtype/precision.
(This will be addressed in the future)
=> implemented complex tensor aten mul

include/torch-mlir/Dialect/Torch/IR/TorchOps.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Dialect/Torch/IR/CMakeLists.txt, lib/Dialect/Torch/IR/TorchOps.cpp, test/Conversion/TorchToTosa/basic.mlir, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir, test/Dialect/Torch/invalid.mlir, test/Dialect/TorchConversion/verify-tosa-backend-contract.mlir
Corresponding commits:
* mlir-hlo: 16886a108eff5197f816ca0f1950cc5ff1b078d9
* stablehlo: 77a59815a82b34f7b08ed2d42a711d9920682d0e
* llvm-project: 4acc3ffbb0af5631bc7916aeff3570f448899647
=> Integrate llvm-project and mlir-hlo.

CMakeLists.txt, tools/torch-mlir-opt/CMakeLists.txt
At some point in the past month, stablehlo gained a number of patches that implement a non-trivial bit of threaded reference code. It fails to compile in Windows in pretty catastrophic ways.
But this isn't the main problem: by way of the MLIR CMake macros being used, if we include stablehlo before our code, we end up building the whole project, whether needed or not. This breaks badly on Windows because of the compilation issues.
=> Fix two CMake issues that were causing Windows compilation failures.

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpBase.td, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.td, lib/Conversion/TorchToTcp/DataMovement.cpp, lib/Conversion/TorchToTcp/Elementwise.cpp, test/Conversion/TorchToTcp/elementwise.mlir
This PR adds support for integer inputs in `tcp.sqrt`.
=> [Tcp] Handle int inputs in sqrt

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpBase.td, externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp/IR/TcpOps.td
This PR removes Complex type from TCP dialect. We do not support Complex type in any ops in TCP at this point. So, there is no reason to have it in the types at this time.
=> [Tcp] Remove Complex type

.gitmodules, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp, lib/Conversion/TorchToLinalg/Reduction.cpp, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
Picks up DenseResourceElementsAttr python support and fixes minf/maxf C++ rename.
=> Bump llvm-project to f66cd9e9556a53142a26a5c21a72e21f1579217c.

.github/workflows/RollPyTorch.yml, build_tools/python_deploy/build_linux_packages.sh
The pre-merge checks that build PyTorch from source use an out-of-tree
build whereas, before this patch, the RollPyTorch workflow used an
in-tree build.  This caused inconsistencies in the build output, so this
patch reconciles the differences.
=> CI: reconcile differences between RollPyTorch and pre-merge checks

lib/Conversion/TorchToLinalg/DataMovement.cpp
While trying to fix a bug in the `ConvertAtenViewOp` pattern in the linalg backend, I realized that the pattern had become quite complex and had accumulated some dead code, making it hard to reason about.
This commit simplifies the pattern quite a bit. The main changes are:
1. All the static helper functions in the `ConvertAtenViewOp` class have been simplified, both in their signature and their body. Each one now performs simple calculations on arrays, and take the least number of arguments necessary.
2. The body of [the `while` loop](https://github.com/ramiro050/torch-mlir/blob/9fce566b0cb64ff2b198693d1f6ee9580b8fa01f/lib/Conversion/TorchToLinalg/DataMovement.cpp#L407) inside the main pattern has been changed to work on `MutableArrayRef` slices, to avoid having to keep track of `start` …
=> [NFC] Clean-up `ConvertAtenViewOp` in linalg backend

lib/Conversion/TorchToLinalg/DataMovement.cpp, python/torch_mlir_e2e_test/test_suite/reshape_like.py
This commit adds to the lowering of `aten.view` handling for the
following cases:
- `(..., a.size(i))` -> `(..., a.size(i), 1, ..., 1)`
- `(..., a.size(i), 1, ..., 1)` -> `(..., a.size(i))`
Fixes: https://github.com/llvm/torch-mlir/issues/2448
=> [linalg] Fix handling of trailing size-1 dimensions in aten.view

.github/workflows/buildRelease.yml
The LTC backend has drifted from being able to pass tests on the stable PyTorch version, so pinning to nightly on ARM.
=> Use PyTorch nightly for Arm release build

include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Utils/Utils.cpp, test/Conversion/TorchToLinalg/basic.mlir
When importing dynamic shaped programs from Dynamo, via torch.compile or torch.export, we can assume that strict symbolic shape checks have been done prior to generating torch IR. Among other shape checking, this eliminates the case where an unknown dimension can be dynamically '1' in a way that signals a broadcast.
Adds a `isAssumingStrictSymbolicShapes` utility which consults a `torch.assume_strict_symbolic_shapes` attribute on an enclosing scope and returns true if present.
In the linalg pipeline, many runtime checks are elided when this returns true.
=> Elide dynamic broadcast checks when in strict symbolic shapes mode.

lib/Conversion/TorchToLinalg/DataMovement.cpp, python/torch_mlir_e2e_test/test_suite/reshape_like.py
After trying to generalize https://github.com/llvm/torch-mlir/pull/2474 to handle leading size-1 dims, it became clear that the approach used there was not the right one. Therefore, this PR:
- Reverts https://github.com/llvm/torch-mlir/pull/2474
- Adds to the lowering of `aten.view` handling for the following cases:
- `(..., a.size(i))` -> `(..., a.size(i), 1, ..., 1)`
- `(..., a.size(i), 1, ..., 1)` -> `(..., a.size(i))`
- `(a.size(i), ...)` -> `(1, ..., 1, a.size(i), ...)`
- `(1, ..., 1, a.size(i), ...)` -> `(a.size(i), ...)`
I recommend reviewing commits separately.
=> [linalg] Add handling for leadin and trailing size-1 dims in ViewOp

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
Strict symbolic shapes allow us to assume numpy-style dynamic broadcasts never occur. This allows us to strengthen the folder for broadcasts to cases where the rank is the same and all shapes match (including dynamic sentinel values).
=> Improve aten.broadcast_to folder when in strict symbol mode

lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Conversion/TorchToLinalg/Utils.h, test/Conversion/TorchToLinalg/broadcast.mlir
With strict symbolic shapes, we can assume numpy-style dynamic broadcasts never occur. This improves the lowering in the presence of this assumption.
=> [TorchToLinalg] Improve broadcast lowerings in strict symbolic modes

lib/RefBackend/CMakeLists.txt, test/Conversion/TorchToTosa/basic.mlir, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir
The main purpose is to bring in the new mesh dialect change. https://github.com/llvm/llvm-project/pull/68007
=> Update llvm-project to b44b3494f60296db6aca38a14cab061d9b747a0a

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, include/torch-mlir/Dialect/Torch/IR/TorchTypes.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
Attempt to solve https://github.com/llvm/torch-mlir/issues/2490
Changes for Non Value Semantic Ops having the `IsTrailingUnderscoreInplaceVariant` trait :
- AnyTorchTensorType -> Torch_NonValueTensorType
- AnyTorchOptionalTensorType -> AnyTorchOptionalNonValueTensorType
- AnyTorchListOfOptionalTensorType -> AnyTorchListOfOptionalNonValueTensorType
- AnyTorchListOfTensorType -> AnyTorchListOfNonValueTensorType
Created three new tensor types for optional and list non value tensors.
=> [torch] Implement stronger verifiers for non-value semantic ops

lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp, python/torch_mlir_e2e_test/test_suite/basic.py, test/Dialect/Torch/reduce-op-variants.mlir
NonValueSemantic Ops like Add_, div_, etc. expect result DType to be the same as the first input. However, current implementation would result in wrong result type for case like:
```python
a = torch.randn(3, 3).half() # float16
b = torch.randn(3, 3) # float32
a += b # i.e. torch.ops.aten.add_(a, b)
```
torch expects `a` to be float16, but dtype refinement would infer float32 type, since it's replaced by `aten.add`.
=> [Torch] Fix mixP case for non value semantic ops

utils/bazel/torch-mlir-overlay/BUILD.bazel, utils/bazel/torch-mlir-overlay/test/BUILD.bazel
Updates Bazel build to mirror project reorganization from https://github.com/llvm/torch-mlir/pull/2542.
GHA: https://github.com/sjain-stanford/torch-mlir/actions/runs/6744430250/job/18334262852
=> [Bazel] Mirror project reorganization

docs/development.md
Is there a way to disable some of CI for docs-only PR's?
=> Specify path of e2e_test.sh after directory change

docs/Torch-ops-E2E-implementation.md
Currently the docs are split into two places, the `docs/` directory and the Github Wiki of Torch-MLIR. This commit moves the wiki docs to `docs/` to consolidate everything into one place. This has the added benefit that users will get all the documentation when they clone the repository.
Note: there are 4 files in the wiki, but only one is truly needed
- Torch-ops-E2E-implementation.md: only file needed
- Coding-Style.md: the contents of this file are already in Torch-ops-E2E-implementation.md
- Weekly-LLVM-Update.md: this is outdated. We no longer have a weekly schedule for llvm updates
- Home.md: Contains links to talks and resources that are already present in the documentation in `docs/` or in
Torch-ops-E2E-implementation.md
=> Move Wiki to `docs/`

projects/pt1/python/torch_mlir/csrc/base_lazy_backend/utils/jit_utils.cpp
This PR updates the JIT pass util for implicit scalar conversion (introduced [here](https://github.com/pytorch/pytorch/pull/92095) and merged [here](https://github.com/llvm/torch-mlir/pull/1798)) and  to include boolean scalar type for conversion from `aten::ScalarImplicit` to `aten::IntImplicit`.
=> add bool scalar type to int implicit cast

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/invalid.mlir, test/Dialect/Torch/ops.mlir
- adds support for an optional verifier to the generated torch op tablegen (GeneratedTorchOps.td)
- uses the above to add a verifier for the torch permute op. 
Motivation: I hit an unclear error from linalg while developing a decomposition pass for pixel_shuffle. The error would have been clearer if the problem had been detected in the invalid  aten.permute op. 
Testing: new tests added. To run added tests, from the base directory run
```
./build/bin/llvm-lit  test/Dialect/Torch/invalid.mlir
```
=> Add verification for torch permute op

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/Conversion/TorchToLinalg/view.mlir
The logic for lowering the aten view op to linalg is fairly complex, and IMO a bit undertested. In this PR I have tried to follow all non-failing paths through the lowering and add unit tests. 
There is 1 logical change to the lowering: redundant tensor.cast ops (same source and destination type) are folded.
=> Additional tests for view lowering

include/torch-mlir/Conversion/CMakeLists.txt, include/torch-mlir/Conversion/TorchOnnxToTorch/CMakeLists.txt, include/torch-mlir/Conversion/TorchOnnxToTorch/Passes.h, include/torch-mlir/Conversion/TorchOnnxToTorch/Passes.td, include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, include/torch-mlir/Conversion/TorchOnnxToTorch/README.md, lib/CMakeLists.txt, lib/Conversion/CMakeLists.txt, lib/Conversion/TorchOnnxToTorch/CMakeLists.txt, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchOnnxToTorch/PassDetail.h, lib/Conversion/TorchOnnxToTorch/Passes.cpp, lib/Conversion/TorchOnnxToTorch/Patterns.cpp, lib/Conversion/TorchOnnxToTorch/TorchOnnxToTorch.cpp, lib/InitAll.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/unsupported_simple_ops.mlir
Adds a pipeline to convert custom ops and metadata represented as `torch.operator` custom ops to corresponding `torch` ops where possible.
This is part of a multi-part approach for building ONNX import in as a regular feature of torch-mlir. It is focused on the conversions vs the infra. We will end up maintaining a [pure-python importer](https://github.com/nod-ai/SHARK-Turbine/blob/main/python/shark_turbine/importers/onnx_importer.py) to go with this in torch-mlir, and we will also maintain test case generation utilities derived from it.
I have left substantial documentation in the README of the conversion directory, including the recommended approach that we will take to keep building this out.
(note that this organizes the code to coincide with the refactoring in #2442 versus the …
=> Initial TorchOnnxToTorch conversion pipeline.

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
Here the aten.reshape ops are replaced with prims.collapse and prims.split_dim ops, which means that the cases where the lowering of reshape from torch to linalg which are not supported, are avoided. 
Essentially, by using the collapse and split_dim ops instead of the reshape op, we are not "losing" the information that the reshapes do not arbitrarily mix dimensions. 
3 additional tests added: 
- fully dynamic, 
- dynamic only the spatial dimensions, 
- dynamic only in the non-spatial dimensions.
=> Improve decomposition of pixel_shuffle (support dynamic shapes)

.github/workflows/bazelBuildAndTest.yml, utils/bazel/torch-mlir-overlay/BUILD.bazel
Adapts to the TorchOnnxToTorch changes from https://github.com/llvm/torch-mlir/pull/2585. 
Also restores bazel builds in post-merge CI that was disabled in https://github.com/llvm/torch-mlir/commit/2148c4cd0d95d16ce11d44be7a545bdf2bda9889.
Bazel workflow: https://github.com/sjain-stanford/torch-mlir/actions/runs/7023912962
=> Add bazel targets for TorchOnnxToTorch conversion passes

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
decompose like:
```
import torch
def my_triu(x, diag):
rows = torch.ops.aten.size(x, -2)
cols = torch.ops.aten.size(x, -1)
row_indices = torch.ops.aten.arange(rows).unsqueeze(1)
col_indices = torch.ops.aten.arange(cols).unsqueeze(0)
cond = torch.ops.aten.ge(
col_indices, torch.ops.aten.add(row_indices, diag))
return torch.ops.aten.where(cond, x, 0)
x = torch.rand(5, 7)
assert torch.allclose(my_triu(x, 0), torch.triu(x, 0))
assert torch.allclose(my_triu(x, 1), torch.triu(x, 1))
assert torch.allclose(my_triu(x, 2), torch.triu(x, 2))
assert torch.allclose(my_triu(x, -1), torch.triu(x, -1))
```
=> [Torch Dialect] Decompose AtenTriuOp

include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Conversion/TorchToLinalg/Utils.h, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Dialect/Torch/Utils/Utils.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/constant_alloc.py
The function `getTypeForScalarType` currently takes an argument to specify the signedness of integer types. This is leakage of backend specific requirements into the torch dialect world. Because `getTypeForScalarType` is a utility function for the torch dialect, it should only produce types that match the sign conventions used by PyTorch (regular integers are signed and unsigned integers are unsigned).
This commit removes the signedness argument from
`getTypeForScalarType`, and moves the backend specific handling of integer types to the backend code.
=> Move handling of integer signedness to the backend conversions

build_tools/write_env_file.sh, docs/adding_an_e2e_test.md, docs/development.md
Some of docs referred to old file paths that no longer exists. This patch updates some of the instructions that I happened to notice were out of date. This is not a full update
=> Update out of date docs

lib/Conversion/TorchToLinalg/Reduction.cpp
MSVC-19 does not support constexprs of lambda captured constexpr values like this: https://godbolt.org/z/ej65rMzdr
Instead, this just drops the constexpr from the if statements.
See the discussion in https://discord.com/channels/689900678990135345/1062405112292712499/1182338050664185999
=> [TorchToLinalg] Drop constexpr from ifs in argmin/max.dim

.github/workflows/buildAndTest.yml, include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/Linear.cpp, lib/Conversion/TorchToStablehlo/StablehloLegalizeUtils.cpp, projects/pt1/e2e_testing/xfail_sets.py
llvm-project: bbd2b08b95fe76bea138c1b03c1cd42ed3ee04df
stablehlo: ab709fe48de88c67717abfbd7ef17425eb95ddaf
These commits were chosen in order to account for an MLIR API break from https://github.com/llvm/llvm-project/commit/3dbac2c007c114a720300d2a4d79abe9ca1351e7 which required a patch to stablehlo. We integrate a bit beyond that commit to deal with some revert/reapply cycles in the intervening range which were discovered in another downstream.
Further, it requires adaptation to the stablehlo API breaks introduced from https://github.com/openxla/stablehlo/pull/1872 which are along for the ride.
Since some stablehlo builders were changed to directly take int64_t array refs, also traced that up some call stacks to eliminate some signed/unsigned mismatches that result.
Also adds a few TOSA …
=> Advance llvm-project and stablehlo.

lib/Conversion/TorchToLinalg/Linear.cpp, projects/pt1/e2e_testing/xfail_sets.py
The linalg Op `linalg.conv_2d_ngchw_fgchw` had a bug where
1. Weights were accessed as G,F,C,H,W instead of as F,G,C,H,W
2. Output was accessed as N,F,G,H,W instead of as N,G,F,H,W
Now this has been fixed in https://github.com/llvm/llvm-project/pull/73855 which broke the torch-mlir lowering to that Op. 
This patch switches lowering in torch-mlir to the newly introduced `linalg.conv_2d_ngchw_gfchw` op which accesses weights in an order that is compatible with PyTorch's memory layout.
Fix https://github.com/llvm/torch-mlir/issues/2622
=> Grouped conv2d: Use MLIR Op which matches memory layout of weight dimensions

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
`AtenStackOp` defines this folder for list operand containing single element:
```
OpFoldResult AtenStackOp::fold(FoldAdaptor adaptor) {
auto list = getOperand(0).getDefiningOp<PrimListConstructOp>();
if (!list || !list->hasOneUse() || list.getElements().size() != 1)
return nullptr;
return list.getElements()[0];
}
```
However, unlike `AtenCatOp`, `AtenStackOp` cannot be folded away for single element list operand because the result from a stack operation contains an additional dimension (of size 1, like expand_shape).
This PR removes the `AtenStackOp::fold` method, and adds an e2e test for single element list input case, which fails on current `main` as follows:
```
Unexpected outcome summary: (linalg) …
```
=> Remove folder from `AtenStackOp` for single element list inputs

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Lowerings for `selu` lowerings for ONNX to the corresponding torch implementations.
Torch has no `selu` implementation and instead uses a generalize `elu` with the input scale
set to `1.0`.
=> [onnx] Lowerings from `onnx.selu`

include/torch-mlir/Conversion/Passes.td, include/torch-mlir/Conversion/TorchToTensor/TorchToTensor.h, lib/Conversion/CMakeLists.txt, lib/Conversion/Passes.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToTensor/CMakeLists.txt, lib/Conversion/TorchToTensor/TorchToTensor.cpp, test/Conversion/TorchToTensor/torch_to_tensor.mlir
Includes the lowering from the `aten` equivalent to `tensor` operations.
=> [onnx] Lowering for `onnx.shape` to `torch` and `tensor`

include/torch-mlir/RefBackend/Passes.h, include/torch-mlir/RefBackend/Passes.td, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/RefBackend/RefBackend.cpp, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/Conversion/TorchToLinalg/basic.mlir
This replaces the lowering of aten.cat with tensor.concat, allowing more efficient handling of concatenations in downstream flows. The refbackend populates concat decomposition patterns that can be used to recover the previous lowering.
Depends on #2654
=> [TorchToLinalg] Lower aten.cat to tensor.concat

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
General lowering for `onnx.Gemm` to `torch`
=> [onnx] Lower `onnx.Gemm` to `torch`

utils/bazel/torch-mlir-overlay/BUILD.bazel
Adapts bazel build per https://github.com/llvm/torch-mlir/pull/2648. 
https://github.com/sjain-stanford/torch-mlir/actions/runs/7233207462/job/19708228888
=> [Bazel] Add conversion targets for `TorchToTensor`

docs/development.md
Adding the `--progress` flag shows the same output as what `git clone` would show. This is very nice for slow connections. Without it, the command may run for many minutes without providing any indication that it is still doing something.
For `--depth=1`, I think it should be safe as most people have new enough git versions nowadays, but let's be safe and make it an optional suggestion. I ran all the tests fine with `--depth=1`, but I don't know whether things will keep working when the submodules get updated for systems with old git versions.
=> Tweak development.md for more speed

projects/pt1/python/torch_mlir/__init__.py, projects/pt1/python/torch_mlir/compiler_utils.py, test/python/compile.py
This PR adds the `enable_ir_printing` option to `torch_mlir.compile`, which can be used to print the IR for all intermediate passes.
When running the added test file via:
```shell
$ python test/python/compile.py 2> tiny.stderr
```
the file `tiny.stderr` is about 700 KB.
=> Allow printing all IR in `torch_mlir.compile`

docs/importers/onnx_importer.md
- Going through the `#torch-mlir` channel on the `llvm` discord, I realize that there are some useful commands that would be extremely helpful in creating Onnx lowers to Torch MLIR. Seems a lot of people are contributing to this. So, I thought it would be good to add this information to the docs.
These tools helped streamlined the development of this PR: https://github.com/llvm/torch-mlir/pull/2682
=> Mentioned helpful tooling to convert Onnx models to Torch MLIR

python/CMakeLists.txt, python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/basic_test.py
Changes made during upstreaming:
* Removed comments attributing some copied code back to torch-mlir (since it is now repatriated).
* Re-organized imports.
* Inlined RefMapping/RefTracker and TypeSubclassMap from an external utility module.
* Added FxImporter class comments.
* Updated stack trace extraction to be fail safe.
* Added an entry-point for `import_frozen_exported_program` which uses the shiny new upstream `torch.export.export()` API (versus the lower-level/older API that Turbine is presently using). This necessitated a small FX rewrite to line external state management up with current conventions.
* Adapted one of Turbine's importer tests to go with this initial submission. Turbine unfortunately has a lot of more-integration-ey tests, and I would like to extract those as more of …
=> [fx] Upstream the turbine FxImporter to torch-mlir.

python/torch_mlir/extras/onnx_importer.py
Some names for `onnx` identifiers are not legal in `mlir-ir`. Sanitize
so that the generated `ir` is legal.
=> [onnx] Fix importer variable names to make `mlir` legal

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds the OnnxToTorch support for GlobalAveragePool op.
Signed-Off By: vivekkhandelwal1424@gmail.com
=> [MLIR][ONNX] Add OnnxToTorch support for GlobalAveragePool op.

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/unsupported_fb_opt_ops.mlir
Addresses two of the ops from https://github.com/llvm/torch-mlir/issues/2689
@vivekkhandelwal1 let me know if the since values for Cast and Equal are set to 19 for compatibility reasons and if I should write separate lowerings for the older versions - I merely reduced the since-version to 1 in your code because they looked backward compatible to me.
Fixes #2700
=> Fix since-opset too high

CMakeLists.txt, projects/CMakeLists.txt, projects/onnx_c_importer/CMakeLists.txt, projects/onnx_c_importer/OnnxImporter.cpp, projects/onnx_c_importer/OnnxImporter.h, projects/onnx_c_importer/README.md, projects/onnx_c_importer/import-onnx-main.cpp
As noted in the plan when this work started, we need to produce an ORT EP plugin for a downstream project, and this will necessitate a C-based ONNX importer (as opposed to the existing Python one). Because this comes with dependencies that we do not want to impart on various projects, this is optional in torch-mlir. It is also factored so that it can be used as standalone sources in downstreams that need it. Since it only depends on public C APIs on the MLIR side, this will make build coupling a lot better (since a C++ dep is not needed on the compiler and it is trivial to dynamically load).
Our original plan was just to maintain this fork off to the side in our ORT plugin, but once work started, it seemed better to write it clean and contribute it upstream for anyone to use. We expect …
=> [onnx] Add torch-mlir-import-onnx native port as an optional tool/library.

projects/pt1/python/torch_mlir_e2e_test/configs/stablehlo_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/tosa_backend.py
The doc seems copy-and-paste from the linalg-on-tensors class
=> [torch-mlir] update e2e test class documentation

lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py, test/Conversion/TorchToLinalg/elementwise.mlir
The lowering for `aten.clamp` did not support integer types. Added
support for integer types including a signed integer test.
=> [linalg] Added `aten.clamp` support with integers to `torch-to-linalg`

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
Floating-point literals should use the correct type specifier.
=> Fixing implicit double->float truncation warnings.

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Handles the multiple cases of `onnx` constant values and converts them
to `torch` literal tensors. This can include splats with a single
integer or floating point value, a set of explicit integer values, or
an elements array attr of values.
=> [onnx] Convert `onnx.constant` to `torch` literal tensor

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Implemented ONNX.Range. The spec says the data type for start, limit, delta are 0-D can be double, float, int16, int32, int64, All int types mapped to !torch.int and all float types mapped to !torch.float
=> Onnx range

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
We can map the per_tensor case to the `torch.aten.quantize_per_linear`
operation. In this case we extract the `scale` and `zeropoint` values
and directly invoke the quantization, then return the integer
representation value.
=> [onnx] Support lowering quantize linear to `torch`

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds support for gather op in the onnx pipeline.
https://github.com/nod-ai/SHARK-Turbine/issues/242
=> [ONNX][MLIR] Add support for onnx.gather op

README.md
Overly specific docs can get stale easily. It looks like https://llvm.github.io/torch-mlir/package-index/ has included Windows packages since around https://github.com/llvm/torch-mlir/pull/1521.
Here's an example release: https://github.com/llvm/torch-mlir/releases/tag/snapshot-20240118.1087
```
torch-2.3.0.dev20240109+cpu-cp311-cp311-linux_x86_64.whl
torch-2.3.0.dev20240109+cpu-cp311-cp311-win_amd64.whl
torch-2.3.0.dev20240109+cpu-cp38-cp38-linux_x86_64.whl
torch-2.3.0.dev20240109-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
torch-2.3.0.dev20240109-cp311-none-macosx_10_9_x86_64.whl
torch_mlir-20240118.1087-cp311-cp311-linux_aarch64.whl
torch_mlir-20240118.1087-cp311-cp311-linux_x86_64.whl
torch_mlir-20240118.1087-cp311-cp311-macosx_11_0_universal2.whl …
```
=> Generalize install instructions to not exclude Windows.

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds mapping from `onnx.pad` op to `torch.pad` op. Currently it does not support `axes` parameter of `onnx.pad` op.
=> [ONNX][MLIR] Add support for pad op in the onnx pipeline

include/torch-mlir/Dialect/Torch/Transforms/Passes.h, include/torch-mlir/Dialect/Torch/Transforms/Passes.td, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/Transforms/CMakeLists.txt, lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp, lib/Dialect/Torch/Transforms/MatchQuantizedOps.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/ltc/csrc/base_lazy_backend/shape_inference.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/matmul.py, test/Dialect/Torch/fuse-quantized-ops.mlir, test/Dialect/Torch/match-quantized-customs-ops.mlir
This includes custom op matching for decomposed operations and fusing
dequantization into dense operations. As a validation we compare
to the dequant+mm torch implementation.
=> [torch][quant] Quantized `torch.mm` for linalg with end-to-end test

lib/Conversion/TorchToStablehlo/Pooling.cpp
Code used for testing.For the location of CumsumInputDtypeInt32Module in the repo you can see [here](https://github.com/llvm/torch-mlir/blob/311b6b0286bfa016346bc7fd8b441bbd50216060/projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py#L4148).
```python
import torch
import torch_mlir
class CumsumInputDtypeInt32Module(torch.nn.Module):
def __init__(self):
super().__init__()
def forward(self, val):
return torch.ops.aten.cumsum(val, 1)
module = torch_mlir.compile(CumsumInputDtypeInt32Module(), [torch.randn(2, 7, 4).to(torch.int32)], output_type="stablehlo")
print(module.operation.get_asm())
```
After fixing the bugs.
```
module attributes {torch.debug_module_name = "CumsumInputDtypeInt32Module"} {
func.func @forward(%arg0: tensor<2x7x4xi32>) -> tensor<2x7x4xi64> {
%0 = …
```
=> [Stablehlo]fix CumsumInputDtypeInt32Module_basic on stablehlo backend.

python/torch_mlir/extras/fx_importer.py
As that torch with py3.9 is also used widely.
=> [FxImporter] make FxImporter to fit python<=3.9

lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Dialect/Torch/IR/TorchTypes.cpp, test/Conversion/TorchToLinalg/sparse.mlir
This preserves sparsity at the most obvious places of lowering TORCH tensors to MLIR RankedTensorType tensors. Other places are marked for audit. With some initial lowering tests.
=> [torch-mlir][sparse] preserve sparsity during lowering torch to linalg

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
TypeRange is an ArrayRef<Type> and therefore cannot be safely instantiated from a list initializer.
=> Fix illegal use of TypeRange

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Torch does not have an equivalent matmul operation for integers. Instead
it sidechannels the information via its quantized types. For this
lowering we setup these sidechannels then invoke `torch.mm`.
=> [onnx] `onnx.MatMulInteger` lowering to `torch.mm` and `quint*` types

.git-blame-ignore-revs
This allows the following command to be used to ignore sweeping formatting changes.
```
git blame --ignore-revs-file .git-blame-ignore-revs <file_of_interest>
```
=> Add .git-blame-ignore-revs to allow ignoring sweeping formatting changes

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
We were seeing some assertion failures after some checks around folders were tightened up in LLVM: https://github.com/llvm/llvm-project/pull/75887 . This PR essentially moves the logic that used to be applied at the LLVM level into the folder, which seems to be the suggested fix.
I'm not sure if the IR that caused issues for us _should_ be valid?
```
%1 = torch.aten.detach %arg0 : !torch.tensor<[1],f32> -> !torch.tensor
```
A better fix might be to create a verifier ensuring the result of `aten.detach` has the same type as its operand.
=> Don't fold `aten.detach` if result isn't same type as input.

include/torch-mlir/Conversion/TorchToLinalg/Utils.h, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/conv.py, test/Dialect/Torch/fuse-quantized-ops.mlir
Linalg has quantized specific operations. We can lower to these
operations when there is a known zeropoint and scale operations. This
allows the `convolution` to occur with lower bitwidth's, improving the
overall performance.
=> [torch] Support `torch.convolution` quantized lowering to `linalg`

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/sparse_test.py
Note that we are waiting for actual FX traced graph support for sparse tensors. For details see
https://github.com/pytorch/pytorch/issues/117188
Until then, however, we provide this clever importer that builds the FX traced graph for for the dense case and then puts a sparse annotation back on the parameters.
With import test.
=> [torch-mlir] provide FX traced graph importer for sparse tensors

CMakeLists.txt, build_tools/ci/build_posix.sh, include/torch-mlir-c/Registration.h, include/torch-mlir-c/TorchTypes.h, lib/CMakeLists.txt, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/ltc/csrc/base_lazy_backend/CMakeLists.txt, projects/ltc/csrc/base_lazy_backend/dynamic_ir.cpp, projects/ltc/csrc/base_lazy_backend/mlir_lowering_context.h, projects/ltc/csrc/base_lazy_backend/mlir_native_functions.cpp, projects/ltc/csrc/base_lazy_backend/utils/sys_utils.h
Required some massaging of LTC to make it warning clean, and I had to manually disable some warnings on the generated source files (which we don't control).
The project is warning clean now.
The `-Werror` flag is disabled by default as we can't control everywhere people will try to build/install. The CI enables it via -DTORCH_MLIR_ENABLE_WERROR_FLAG=ON.
=> Enable -Werror in lib/ and LTC.

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
`onnx` explicitly specifies that `raw_data` is stored in `little-endian` layout. While converting
to `torch` we need to convert from a known endian format to an internal format of consistent
layout. This means endianness must be correct during the import of `onnx.Constant`.
=> [onnx] Convert resources to denseattr for `onnx.constant` to `torch`

python/torch_mlir/extras/onnx_importer.py
To handle the conversion from raw bytes to `DenseElementsAttr` we need
to handle the endianness conversion during `torch-onnx-to-torch`.
Therefore when importing `onnx.Constant` it is better to represent using
the `onnx` constant operation so that only one location requires the
endianness correction.
=> [onnx] Import `onnx` constants as `onnx.Constant` instead of literals

lib/Conversion/TorchToTensor/TorchToTensor.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/scalar.py
Extracting scalar values from tensors can be implemented via a lowering
to tensor.extract.
=> [torch] Support lowering `torch.item` to `tensor.extract`

lib/Conversion/TorchToLinalg/Pooling.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/pooling.py
We do not support average pool when `countIncludePad is set to false.
However if the input is unpadded then the setting of the boolean is
unneeded. Extended use by checking if padding is zero before rejecting
the lowering.
=> [torch] Support `!countIncludePad` when unpadded for average pool

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
`torch` requires that padding be symmetric for pooling operations. To
support non-symmetric pad we need to separately materialize out the
padding operation.
=> [onnx] Fix `pool` lowering for non-symmetric padding

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
`[build] D:\Dev\iree\third_party\torch-mlir\lib\Conversion\TorchOnnxToTorch\DefaultDomainGtoP.cpp(734): warning C4305: 'argument': truncation from 'double' to 'float'`
=> Fixing implicit double->float conversion warning.

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
The existing `flatten` lowering did not define what the intermediate
shape was. This could result in failures to lower further to linalg as
the intermediate shape was unknown. Added a shape refinement section.
=> [onnx] Fix `onnx-to-torch` lowering for flatten shape

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir, test/Dialect/Torch/fuse-quantized-ops.mlir
Leaning on the QDQ functionality in torch we can support the QLinearConv
operation by piggybacking through `torch.Convolution`. This includes
some changes such as allowing the `onnx` rewriter to run recursively.
Doing so allows `QLinearConv` to decopmose to `onnx.Convolution` which
is then lowered to `torch`.
=> [onnx] Convert `onnx.QLinearConv` to `torch`

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/basic_test.py
Adds an escape hatch from creating a DenseResourceElementsAttr for single value tensors into DenseElementsAttr.
For 0d or 1element, splats are better as DenseElementsAttr. Don't use DenseResourceElementsAttr for it
=> [fx_importer] Add support for 0D tensors

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, include/torch-mlir/Dialect/Torch/IR/TorchOps.h, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
Folds aten::index_select ops under the following conditions:
1. If the input and output are the same shape, the indexing operation is a NOP, so just return the input.
2. If the input has shape <1x1x...xNx...x1> (all 1's except for one dim), and the output shape is <1x1x...x1> (all 1's), then there is a single index, so extract the single element value and return a tensor with that value.
=> [torhc] aten.index_select folder

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit modifies the OnnxToTorch lowering of Onnx.Reshape op by creating the result shape list for the aten.reshape using the result shape values inferred from the op's result shape.
=> [MLIR][TORCH] Modify Onnx.Reshape lowering for static shape cases

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This PR contains three commits to update the validation checks in the ONNX ->
Torch conversion pass for the AveragePool, Pad, and Slice operators:
> onnx: fix preconditions for lowering AveragePool ops
> 
> The `pads` attribute of the AveragePool operator specifies the value to
> pad at both the beginning as well as the end of the axis (see
> https://onnx.ai/onnx/operators/onnx__AveragePool.html#attributes), so
> the size of this attribute should be twice the rank of the input tensor.
> However, our TorchOnnxToTorch bails out early since it incorrectly
> compares the pads attribute with the rank (not twice the rank) of the
> input tensor.
> 
> This patch fixes the code to match the spec and adds a lit test.
> onnx: allow optional constant value for Pad operator
> 
> The `constant_value` …
=> onnx: fix checks in TorchOnnxToTorch pass to match the ONNX spec

projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
This adds a few passes that will ensure linalg with sparse tensors are properly lowered to loops and can run using the ExecutionEngine for testing (a few details on parameter passing from PyTorch still TBD)
Test results:
$ ./tools/e2e_test.sh --config linalg
Summary:
Passed: 1144
Expectedly Failed: 8
$ python -m e2e_testing.main --config=torchdynamo -v
Summary:
Passed: 960
Expectedly Failed: 163
Filed issue:
https://github.com/pytorch/pytorch/issues/119407
=> [torch-mlir][sparse] add sparsification to linalg reference backend

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
If the input or result is a splat value we can just constant fold the
result. This is common for shape computations and can help with shape
inference.
=> [torch] Folder for torch.aten.select.int for splat cases

lib/Conversion/TorchToLinalg/Uncategorized.cpp
By updating convertScalarToDtype invocation pass original source and destination datatypes for the add op. Also fixes a potential problem with the sub op.
=> Fix test_add_uint8 failure to lower to linalg

projects/onnx_c_importer/CMakeLists.txt
This patch makes the Protobuf package mandatory in addition to forcing a
config mode search.  The (default) module mode search looks for the
CMake-provided FindProtobuf.cmake file, but this file does not list
Abseil as a dependency, causing linker issues like the one below:
```
ld: Undefined symbols:
absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, std::__1::basic_string_view<char, std::__1::char_traits<char>>), referenced from:
google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, …
```
=> build: find Protobuf using config mode search

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/sparse_test.py
Various improvements on sparsity metadata:
(1) define single data structure for all sparsity related metadata 
(2) handle batched dense dimensions, as well as dense subtensor dimensions
(3) refine sparsity propagation for deeper networks
=> [torch-mlir][sparse] sparsity metadata refinement

include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOps.td, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Dialect/TMTensor/IR/TMTensorOps.cpp, lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py, test/Dialect/Torch/reduce-op-variants.mlir
Some operations include a backend matcher for specialized operations. We
map these back to generics so they appropriately match to the high
performance versions. This is done for the attention operation.
=> [torch] Fix tm_tensor.attention for end-to-end

python/torch_mlir/extras/fx_importer.py, test-requirements.txt
this introduces an additional soft dependency on the python ml_dtypes python packages in order to support bfloat16
Addresses #2843
=> Add support for bfloat16 in fximporter

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
Just a minor update to skip the space char if included in the equation string
=> DecomposeComplexOps: update parseEquation to skip space char for AtenEinsumOp op

python/torch_mlir/extras/fx_importer.py, python/torch_mlir/fx.py, test/python/fx_importer/basic_test.py, test/python/fx_importer/sparse_test.py, test/python/fx_importer/v2.3/lit.local.cfg, test/python/fx_importer/v2.3/mutation_import.py
As of https://github.com/pytorch/pytorch/pull/118969, `ExportedProgram` has the long awaited fixes to correctly categorize various things relating to parameters, buffers, mutated inputs and constants.
With this additional modeling, we are finally able to implement (safely/soundly) the mutable semantics that were attempted on the TorchScript path. The difference is that on that path, we had to conservatively treat everything as mutable and run some dodgy heuristics (which have been the cause of many bugs relating to "MaximizeValueSemantics") to try to get back to an immutable state.
The new model supports mutability at the graph edges, allowing both user inputs and buffers to be mutated (there is some more support than that, but that is all I fully tracked through to implementation). …
=> [fx] Support mutation in ExportedProgram.

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
We are crashing due to indexing into a negative shape. Updated the lowering to avoid the crash.
=> [onnx] Fix crash when negative transpose values exist

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/e2e_testing/xfail_sets.py
Sample compilation crashes due to sigmoid with integer inputs/outputs. This fix avoids crashing but still experiences an error.
=> [onnx] Fix `onnx.sigmoid` for integer inputs/outputs

projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
Even though the reference compiler is not about performance, inlining the generated sparse helper methods has a rather big positive impact on performance, leaving a much better first impression. Therefore, we added this inlining pass (which leaves all other PyTorch modules unaffected, since they tend to be one big main() method to start with).
testing:
$./tools/e2e_test.sh --config linalg
Summary:
Passed: 1164
Expectedly Failed: 8
$ python -m e2e_testing.main --config=torchdynamo
Summary:
Passed: 976
Expectedly Failed: 162
=> [torch-mlir][sparse] inline sparse helper methods

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Onnx slice lowering used arange needlessly instead of directly constructing the constant dimension values. This makes lowerings to linalg struggle as multiple folders are required to get what is a constant index value.
=> [onnx] Simplify onnx.slice lowering

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/torch-nary-canonicalize.mlir
Simple folder for limited size aten tensor operations. This is primarily
useful for shape computation folding as they unfortunately can use
`aten` operators. Add, sub, mul are common examples of these folders.
=> [torch] Folders for `torch.aten.*.tensor` operators [add, sub, mul]

include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h, include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.td, lib/Dialect/TorchConversion/Transforms/BackendTypeConversionPasses.cpp, lib/Dialect/TorchConversion/Transforms/ConvertCustomQuantOp.cpp, lib/Dialect/TorchConversion/Transforms/PassDetail.h, lib/Dialect/TorchConversion/Transforms/Passes.cpp, lib/Dialect/TorchConversion/Transforms/UnpackQuantTensor.cpp, test/Dialect/TorchConversion/convert-custom-quant-op.mlir, test/Dialect/TorchConversion/finalizing-backend-type-conversion.mlir, test/Dialect/TorchConversion/unpack-quant-tensor.mlir
This enables better re-use in downstreams which use different func implementations and should have no impact on those that don't except in opt pipelines if using the old form. With interfaces, explicit pipelines via `--pass-pipeline=` must be used.
=> Migrate passes in TorchConversion to use FunctionOpInterface.

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, test/Conversion/TorchToTosa/cast_fp32_to_fp16.mlir
According to the [official TOSA spec](https://www.mlplatform.org/tosa/tosa_spec.html#_cast), `tosa.cast` allows a cast from `fp32` to `fp16`. We were not previously accounting for this in the `TorchToTosa` lowering.
Also did a tiny bit of cleanup in the code to make it easier to spot which conversions are currently allowed.
=> allow tosa.cast to convert from f32 to f16

include/torch-mlir/Dialect/Torch/IR/TorchOps.h, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py
Strided slicing can occur with a negative stride. In these cases we need to bound end differently. This included removing a function that was generating bad limits.
=> [torch] Fixed edge conditions for strided slicing

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/sparse_test.py
Also note that we are in the process of proposing SparseTensorMetadata to PyTorch FX graph export (see https://github.com/pytorch/pytorch/pull/117907). This will hopefully eventually replace the current data structures in torch-mlir.
=> [torch-mlir][sparse] add block sparsity to mlir lowering

python/torch_mlir/extras/fx_importer.py
This was found in a downstream that is pegged to an older PyTorch version.
=> Make a typing dependency that is not in older PyTorch backwards compatible.

include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOps.td, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Dialect/TMTensor/IR/TMTensorOps.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/scatter.py, test/Dialect/TMTensor/bufferize.mlir, test/Dialect/TMTensor/convert_to_loops.mlir, test/Dialect/TMTensor/invalid.mlir
We collapsed and broadcasted scatter indices to a single element
version. We should instead upport `tm_tensor.scatter`s support for
multiple indices and the implicitly broadcasted behavior. This avoids
the serialization and materializing a needlessly large indices tensor.
=> [torch] Rework lowering to tm_tensor.scatter to stop serialization

test/python/fx_importer/sparse_test.py
This required adding a "decompose" pass to the torch lowering, since torch.mv was not directly handled by lowering to linalg
=> [torch-mlir][sparse] add JIT test for block sparse SpMV

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py
The corrective transpose at the end is computed incorrectly. Is it actually computin the inverse transpose. Inverting the permutations fixes the issue.
=> [tosa] Fix TOSA batch matmul lowering to correct transpose ordering

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
The decomposition only suports a NCHW lowering however the operation can support arbitrary spatial dimensions. Updated the lowering to better support spatial dimensions.
=> [torch] Fix DecomposeAtenInstanceNorm decomposition

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
A bunch of small fixes are interlinked and trigger crashes if not addressed as a group. This includes:
- aten view when expand from a rank-0 tensor
- slice folder with negative indices
- `aten._shape_as_tensor` folder on a rank-0 tensor
- `aten.cat` of a tensor with a length-0 tensor
=> [torch]  Fix folders and `cat` and `view` torch lowerings

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This is the lowering of gridsampler from onnx to torch using our prior implementation of AtenGridSamplerOp. 
Here are several checks for cornercases implemented. We may decide to have part of these checks in AtenGridSamplerOp instead of the onnx lowering portion.
=> [onnx][torch] Lower `onnx.grid_sampler` to the `torch` equivalents

include/torch-mlir/Conversion/Utils/Utils.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/Utils/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the support for scalar conversion to byte. 
This commit also fixes the OnnxToLinalg lowering issue for Onnx.Sub and Onnx.Sum op.
Fixes https://github.com/nod-ai/SHARK-Turbine/issues/466 
Fixes https://github.com/nod-ai/SHARK-Turbine/issues/467
=> [MLIR][TORCH] Fix OnnxToLinalg lowering issue for sub and sum op

python/torch_mlir/extras/onnx_importer.py
The type returned was changed in https://github.com/llvm/torch-mlir/pull/2795. This led to errors in the downstream IREE project: https://github.com/openxla/iree/pull/16622.
=> [onnx] Fix type on create_module() in onnx_importer.py.

lib/Conversion/TorchToLinalg/DataMovement.cpp, projects/pt1/e2e_testing/xfail_sets.py
Collapsing to a rank-0 tensor using `aten.view` was currently bailing out. Added the special case.
=> [torch] Support `aten.view` rank-0 collapse

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
If an input is length-0 along the dimension of canonicalization we can
remove the tensor from the list
=> [torch] Add an `aten.cat` length-0 canonicalization

python/torch_mlir/extras/fx_importer.py
* that `dataclass`'s `slots` is supported after python 3.10.
=> [FxImporter] remove dataclass slots to support python3.9

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/constant_alloc.py, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
`getRawBuffer` expects a densely packed vector of `i1` values however `onnx` does not densely pack the values. Include code to handle the packing / unpacking.
=> [onnx] Add support for constants of `i1`s

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py
Current implementation depends on using `aten.view` which has issues inferring tensor collapse/expand operations during the lowering to `linalg`. Using flatten and unsqueeze better infers what the later reshape behavior.
=> [torch] Rework `aten.repeat` to use flatten and unsqueeze

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
We can support `onnx.Size` by requesing the size of each dimensions and taking the product of the results, then packing it into a tensor.
=> [onnx] Adding lowering for `onnx.Size` operation

README.md
The file was renamed by PR https://github.com/llvm/torch-mlir/pull/2842.
=> Fix link to roadmap in README.md

python/torch_mlir/extras/fx_importer.py
uses version checking since attributes exist in both versions, the only thing that changes is what we're receiving as an fx graph
=> fximporter: support newer torch versions

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
If the broadcast shape is length-1 at a dim while `?` in the input dim then we need to broadcast to the dynamic dim. This is equivalent to taking a max of two dimensions.
=> [onnx] Fix expand operation for dynamic shape max

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py
* torch-mlir may not handle `aten.warn`. But it could be handled by custom users' backend which involves torch-mlir.
=> [Torch Dialect] emit aten::warn

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Reduce mean lowerings did not succesfully lower to `linalg` via torched. There were two separate paths that could be consolidated to a single simpler pass. This resulted in a significant improvement in test coverage.
=> [onnx] Fix onnx.ReduceMean lowering

projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/configs/torchdynamo.py
This commit provides dummy solution to support elmentwise operations (mul, add) with scalar argument. ( op(Tensor, Scalar) )
It replaces `torch.aten.add.Tensor` with `torch.aten.add.Scalar`.
```
Unexpected outcome summary: (torchdynamo)
****** Unexpectedly Passed tests - 22 tests
XPASS - "AddCDivModule_basic"
XPASS - "BatchNorm1DModule_basic"
XPASS - "BatchNorm1DStaticShapeModule_basic"
XPASS - "BatchNorm1DWith2DInputModule_basic"
XPASS - "BatchNorm2DModule_basic"
XPASS - "BatchNorm3DModule_basic"
XPASS - "ElementwiseAddScalarInt64Module_basic"
XPASS - "ElementwiseAddScalarIntModule_basic"
XPASS - "ElementwiseMulScalarModule_basic"
XPASS - "ElementwiseMulScalarModule_float"
XPASS - "ElementwiseMulScalarModule_int"
XPASS - "GroupNormModule_basic"
XPASS - …
```
=> [TorchDynamo] Enable Elemtwise ops for Scalar arg

lib/Dialect/Torch/IR/TorchOps.cpp
Splat operators required the output is 1-D. This was not a required restriction and was loosened to 2d.
=> [torch] Update folders for splat operators

.gitignore, setup.py
* setuptools not steal the build directory name https://github.com/llvm/torch-mlir/pull/3021#issuecomment-1994447855
* support pre-built LLVM
* support CMAKE_BUILD_TYPE env
=> Setuptools uses a separate build directory

python/torch_mlir/fx.py, test/python/fx_importer/basic_test.py
https://github.com/llvm/torch-mlir/pull/2992 dropped `constraints` from the fx importer API, [breaking](https://github.com/cruise-automation/mlir-tcp/actions/runs/8284385380/job/22669774071) downstream AOT compile tests in `mlir-tcp` that use it. This knob has been soft-deprecated for a while now, replaced by `dynamic_shapes` - a more ergonomic interface. This PR brings back dynamic_shapes constraints in the new supported form. Also added a python lit test with dynamic shaped annotations.
=> Bring back `dynamic_shapes` constraints in fx importer API

projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/abstract_interp_lib_gen.py, python/torch_mlir/extras/fx_importer.py, python/torch_mlir/extras/onnx_importer.py, setup.py, test/python/fx_importer/sparse_test.py
Although we provide a wheel package for Python 3.8, it may actually throw the following exception:
`TypeError: 'type' object is not subscriptable`
=> Normalize type hints to be compatible with multiple Python versions

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, projects/pt1/e2e_testing/xfail_sets.py
2 modifications:
1. torch.int64 is enum 4 in TORCH_DTYPE_TO_INT
2. add int32 support
=> [onnx] Fix onnx.cast cases between int32 and int64

lib/CMakeLists.txt, lib/Dialect/TorchConversion/Transforms/CMakeLists.txt, lib/Dialect/TorchConversion/Transforms/Passes.cpp, lib/InitAll.cpp, projects/pt1/python/torch_mlir_e2e_test/stablehlo_backends/linalg_on_tensors.py
as that stablehlo is better than chlo as the boundary between frontend compiler and backend compiler.
=> [Stablehlo] lowering chlo to stablehlo in torch-to-stablehlo pipeline

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
The only difference between version 7 and newer versions is support for different data types. We should allow this pattern to match as early as 7. Earlier versions have a more manual broadcast specification through attributes, so I did not include those versions. 
See: [onnx.Div docs](https://onnx.ai/onnx/operators/onnx__Div.html#l-onnx-doc-divl)
=> [ONNX] Reduces onnx.Div sinceVersion to 7

lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToTensor/TorchToTensor.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
SExtValue was used for `int` and `uint` clamp values. This caused the result to always be outputed as `zero`.
=> [torch] Fix clamp ranges on quantize_per_tensor on unsigned

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/special_forms_test.py
At some point, this op became kwarg-only instead of arg/kwarg. Discovered when upgrading to PyTorch 2.3.
Also adds a test as this was untested in-tree (was caught out of tree).
=> [fx] Make the lift_fresh_copy -> clone special form use kwargs.

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the OnnxToTorch lowering for the Mish, Softplus, HardSwish, Trilu, ThresholdedRelu op
=> [MLIR][TORCH] Add OnnxToTorch lowering for ops

python/torch_mlir/extras/fx_importer.py
This is a partial landing of #3046 while waiting for an upstream change for the rest of it.
=> [fx] Accept `func_visibility=` and return created func op.

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, include/torch-mlir/Dialect/Torch/Transforms/Passes.h, include/torch-mlir/Dialect/Torch/Transforms/Passes.td, lib/Conversion/CMakeLists.txt, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToArith/TorchToArith.cpp, lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp, lib/Conversion/TorchToTensor/TorchToTensor.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/CMakeLists.txt, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/configs/onnx_backend.py, test/Dialect/Torch/scalarize-shapes.mlir
Reshaping tensors depend on directly matching individual dimensions to their corresponding dim in the `torch.view` reshape dimensions. This involves decoupling dynamic dimensions from their static counterparts and support cleanup / canonicalization.
=> [torch] Improve shape inference for `torch-to-linalg` path for reshapes

python/torch_mlir/extras/fx_importer.py, python/torch_mlir/fx.py, test/python/fx_importer/v2.3/auto_functionalized.py, test/python/fx_importer/v2.3/lit.local.cfg
* Also adds the basic scaffolding for handling more of these, which will be needed for cond, while, etc.
* Refactors some of the support in the generic OpOverload emitter so it can be shared with these other special forms.
This has been on my list for a while, but it just so happens that as part of upgrading to PyTorch 2.3 and a pure upstream flow in Turbine, we were using a feature that required integration with auto_functionalized. This is perhaps the "weirdest" of the higher-order ops and a poor place to start, but needs must. We have testing for this in Turbine.
Full support in Turbine has an entire custom ops facility. I've reduced this down to a unit test in torch-mlir.
=> [fx] Implement auto_functionalized higher order op.

utils/bazel/torch-mlir-overlay/BUILD.bazel
https://github.com/llvm/torch-mlir/pull/3055 adds `lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp`, which depends on `torch-mlir/Dialect/TorchConversion/Transforms/BackendTypeConversion.h`. 
```
ERROR: /root/.cache/bazel/_bazel_root/b89349c08f7224396763d14fe35cba11/external/torch-mlir/BUILD.bazel:170:11: Compiling lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-16/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer ... (remaining 101 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging …
```
=> [Bazel] Add dep from `TorchPasses` to `TorchBackendTypeConversion`

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/e2e_testing/xfail_sets.py
Two e2e tests (AdaptiveAveragePool1/2dUnitOutputSizeDynamic) were failing due to numerics. This was as a result of passing -1 as the kernel size in the lowering for the corresponding onnx op GlobalAveragePool.
=> [ONNX] Fixes Issue with Dynamic Dims in GlobalAveragePool -> Torch Conversion

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py
This was found while tracing backwards graphs: the convolution_backwards op will return None if the first result is not needed. Confirmed by defining a custom op with a `Tensor` return signature and having its meta kernel return None.
=> [ods] Allow all tensor returns to be optional.

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
Fix bug of DecomposeAtenSelectIntOp. Because it may use resultTy when resultTy has not been inferred.
```
auto resultTy = op.getType().cast<BaseTensorType>();
if (sliceTy.getSizes().size() == resultTy.getSizes().size()) {
rewriter.replaceOp(op, slice);
return success();
}
```
So I add restriction.
=> [Torch] Fix bug of DecomposeAtenSelectIntOp

lib/Conversion/TorchToArith/TorchToArith.cpp, test/Conversion/TorchToArith/basic.mlir
Now there no lowing for `aten.Int.bool` in `convert-torch-to-arith` pass. this PR add this support.
Below is the UT.
```
func.func @torch.aten.Int.bool(%arg0: !torch.bool) -> !torch.int {
%0 = torch.aten.Int.bool %arg0 : !torch.bool -> !torch.int
return %0 : !torch.int
}
```
=> [MLIR][TORCH]Add support lowing aten.Int.bool to arith

include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td, lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp, test/Dialect/TorchConversion/canonicalize.mlir
When lowering `torch.aten.convolution`, it is expected that the 'transposed' argument is a torch.constant operation. In some cases, the argument was a `from_i1` operation converting an `arith.constant` operation into a torch.bool. This is not wrong semantically, but instead of generalizing the legality of the `torch.aten.convolution` op, we canonicalize `arith.constant` ops followed by `from_i1` ops to `torch.bool` ops.
For example:
```
//===-------------------------------------------===//
Legalizing operation : 'torch.aten.convolution'(0x124705b90) {
%33 = "torch.aten.convolution"(%arg0, %20, %21, %31, %29, %30, %19, %32, %0) : (!torch.vtensor<[1,1,28,28],f32>, !torch.vtensor<[10,1,5,5],f32>, !torch.vtensor<[10],f32>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, …
```
=> [MLIR][Torch] Canonicalize torch.from_i1 and torch.to_i1

lib/Conversion/TorchToLinalg/Reduction.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/reduction.py
Add support for complex-type input tensors for norm, vector norm, and Frobenius norm operations.
=> Add complex support for aten.norm and similar operations

lib/Conversion/TorchToLinalg/Linear.cpp, test/Conversion/TorchToLinalg/convolution.mlir
The `convertTensorToElementType` function expects it's argument to have a valid tensor type that is not `Torch::NoneType`. This PR checks that the bias tensor is not of type `Torch::NoneType` before calling `convertTensorToElementType` on the bias tensor argument in the `matchAndRewrite` member function of the `ConvertAtenConvolutionOp` class.
=> [MLIR][Torch] Do not convert bias tensor to element type if NoneType

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
This adds explicit result types instead of relying on shape/dtype computations. 
Solves a regression issue with IREE: #3092
=> Adds result types to a prelu decomp

utils/bazel/docker/Dockerfile, utils/bazel/torch-mlir-overlay/BUILD.bazel
Bazel builds broke with the recent LLVM bump due to union select of dictionaries: 
```bazel
substitutions = {
"#cmakedefine01 MLIR_DEPRECATED_GPU_SERIALIZATION_ENABLE": "#define MLIR_DEPRECATED_GPU_SERIALIZATION_ENABLE 0",
"#cmakedefine01 MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS": "#define MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS 0",
"#cmakedefine MLIR_GREEDY_REWRITE_RANDOMIZER_SEED ${MLIR_GREEDY_REWRITE_RANDOMIZER_SEED}": "/* #undef MLIR_GREEDY_REWRITE_RANDOMIZER_SEED */",
"#cmakedefine01 MLIR_ENABLE_NVPTXCOMPILER": "#define MLIR_ENABLE_NVPTXCOMPILER 0",
"#cmakedefine01 MLIR_ENABLE_PDL_IN_PATTERNMATCH": "#define MLIR_ENABLE_PDL_IN_PATTERNMATCH 1",
"#cmakedefine01 MLIR_ENABLE_ROCM_CONVERSIONS": "#define MLIR_ENABLE_ROCM_CONVERSIONS 0",
} | if_cuda_available(
{"#cmakedefine01 …
```
=> [Bazel] Use bazel 6 to support dict select union

lib/Conversion/TorchToLinalg/DataMovement.cpp, projects/pt1/python/torch_mlir_e2e_test/configs/torchdynamo.py
Squeezes can be ambiguous without the output shape information. For instance (1, 1, 256) squeezed can be either (1, 256) or (256). We need to check the resulting shape to know what the shape should look like.
=> [torch] Fix aten.squeeze lowering to use result shape

lib/Dialect/TorchConversion/Transforms/CMakeLists.txt
* as that `TorchMLIRTorchConversionPasses` missing dependencies of `TorchMLIRTorchToStablehlo` and `TorchMLIRTorchToTensor`.
* use `TorchMLIRConversionPasses` instead of scattered targets.
=> [cmake] link TorchMLIRTorchConversionPasses to TorchMLIRConversionPasses

test/python/fx_importer/sparse_test.py
This tests COO for more than 2-dim. Note that sparsity should really propagate into the relu activation and the output, but such cleverness needs to wait for the pending work in the PyTorch tree.
=> [torch-mlir][sparse] add a COO test for 3-dim

build_tools/python_deploy/build_linux_packages.sh
Workaround for https://github.com/llvm/torch-mlir/issues/3120. This should bring prebuilt releases back to green: https://github.com/llvm/torch-mlir-release/actions.
=> Disable LTC from release builds to bypass linker issue

test/python/fx_importer/sparse_test.py
first sparse-in/sparse-out example, will be used
to make actual sparse output work!
=> [torch-mlir][sparse] add ID-net example

build_tools/autogen_ltc_backend.py, build_tools/ci/build_posix.sh, build_tools/python_deploy/build_linux_packages.sh, projects/ltc/csrc/base_lazy_backend/backend_impl.cpp, projects/ltc/csrc/base_lazy_backend/backend_impl.h, projects/ltc/csrc/base_lazy_backend/ir_builder.h, projects/ltc/csrc/base_lazy_backend/mlir_native_functions.cpp, projects/ltc/csrc/base_lazy_backend/mlir_node_lowering.cpp, projects/ltc/csrc/base_lazy_backend/ops/to_copy.h, projects/ltc/csrc/base_lazy_backend/shape_inference.cpp, projects/ltc/csrc/base_lazy_backend/utils/tensor_utils.cpp, projects/ltc/csrc/base_lazy_backend/utils/tensor_utils.h
They replaced all `c10::optional` usages with `std::optional` in torchgen'd code in https://github.com/pytorch/pytorch/commit/fb90b4d4b25f0ebdd7d8c12b9963769774ef4873 causing the LTC build to break.
Replacing all usages of `c10::optional` with `std::optional` in `projects/ltc` has fixed the issue
Issue: #3120
=> Replace c10::optional with std::optional

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/scatter.py
If there is only a single value scattered there can be an implicit batch dimension. This includes a check for the implicit batch dimension when reshaping the update tensor. It includes an e2e test to verify correctness.
=> [torch] Support implicit batch for index_put

projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/python/fx_importer/sparse_test.py
Sparse inputs and outputs are now fully supported! They always consist of their constituents buffers, passed as numpy arrays. Sparse on!
=> [torch-mlir][sparse] support sparse tensor output

docs/development.md, setup.py
As this issuecomment(https://github.com/llvm/torch-mlir/pull/3021#issuecomment-2031248199) suggests, `setup.py` should only be used for building Python packages, so:
* disabled the develop command
* refactor the environment variable parameters
* add more doc for the usage and env var of setup.py
=> Refactor the parameters and usage instructions of the setup script.

lib/Conversion/TorchToStablehlo/Linear.cpp, projects/pt1/e2e_testing/xfail_sets.py
To pass test "MatmulStaticBroadcast_basic" in stablehlo:
```python
class MatmulStaticBroadcast(torch.nn.Module):
def __init__(self):
super().__init__()
@export
@annotate_args([
None,
([4, 1, 6, 7], torch.float32, True),
([8, 1, 5, 7, 6], torch.float32, True),
])
def forward(self, lhs, rhs):
return torch.matmul(lhs, rhs)
@register_test_case(module_factory=lambda: MatmulStaticBroadcast())
def MatmulStaticBroadcast_basic(module, tu: TestUtils):
module.forward(tu.rand(4, 1, 6, 7), tu.rand(8, 1, 5, 7, 6))
```
=> [Stablehlo] Enhance broadcast pattern in matmul Ops

lib/Conversion/TorchToLinalg/Linear.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/__init__.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/matmul.py
The new cases added for quantized matmuls are:
1. vec-vec
2. vec-mat
3. mat-vec
each of which are now lowered to expand(s), quantized_matmul, and collapse.
=> [TorchToLinalg] Adds Support for Remaining Quantized Matmul Cases

lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/index_select.py
Need to perform an expand in the case where the indices is rank-0.
=> [torch] Support rank-0 index for torch index select

lib/Conversion/TorchToLinalg/DataMovement.cpp, projects/pt1/e2e_testing/main.py, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/reshape_like.py, test/Conversion/TorchToLinalg/view.mlir
We can map to `tensor.reshape` for handling multiple output dynamic shapes. Later we can perform a more complex analysis for indentifying expand/collapse cases from the tensor.reshape.
Initially we planned to handle this identification at the `torch` level however it will be easier to handle once converted to core mlir-dialects.
=> [torch] Add support for `torch.view` with dynamic shapes

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Previous implementation erroneously mixed up num_outputs with slice_size. New version correctly computs the slice size and directly performs slicing rather than leveraging `aten.split.tensor`. This is due to `onnx` supporting a fixed number of splits making the size computation more easily computeable when lowering to `aten` rather than deferring to `aten.split.tensor`.
=> [onnx] Fix `onnx.split` by directly handling slicing

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py
Version number was set too high. Lowered to support more cases allows more tests to pass.
=> [onnx] Extend op version number of `onnx.ScatterElements`

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, include/torch-mlir/Dialect/Torch/IR/TorchOps.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit also cleans up the OnnxToTorch lowering for the Squeeze and Unsqueeze op and adds the support for handling edge cases.
=> [onnx] Fix OnnxToLinalg lowering issue for `onnx.Squeeze` and `onnx.Unsqueeze`

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
All e2e iree tests compiled, but they have the run issue of mismatch of dtype like the following
```
expected:
1x1x2x2xsi32=[[[12 16][24 28]]]
actual:
1x1x2x2xi32=[[[12 16][24 28]]]
```
=> [onnx] Add OnnxToTorch support for `onnx.ConvInteger`

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/unsupported_simple_ops.mlir
The tests listed in https://github.com/nod-ai/SHARK-Turbine/issues/635 all compiled, but having run issue of dtype mismatch of i/si.
=> Support select_last_index attribute of onnx argmax op

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/unsupported_simple_ops.mlir
The tests listed in https://github.com/nod-ai/SHARK-Turbine/issues/648 all compiled, and the values of results match, but having runtime issue of dtype mismatch of i/si.
=> Support select_last_index attribute of onnx argmin op

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
- Fix pad size to data_rank for dynamic paddingSize Tensor.
- This fix is in accordance with [input specification](https://onnx.ai/onnx/operators/onnx__Pad.html#inputs) for onnx.Pad
- Impl will need to be updated for dynamic padSize when support for `axes` is added.
=> [onnx] handle dynamic padSize tensor in onnx.Pad

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/e2e_testing/xfail_sets.py
[onnx] Support `onnx.OneHot` lowering to `torch`
Leverage the `aten.onehot` implementation along with `aten.transpose` and
`aten.where.scalar`.
=> [onnx] Support `onnx.OneHot` lowering to `torch`

projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/_dynamo_fx_importer.py
Four xfailed cases due to this reason. They can pass after fixing it.
```
ElementwiseDivRoundingModeFloorModule_basic
ElementwiseDivRoundingModeTruncModule_basic
RandnGeneratorF64Module_basic
RandnGeneratorModule_basic
```
=> [dynamo] Verify the default value is passed by kwargs

.github/workflows/pre-commit-all.yml, .pre-commit-config.yaml
The pre-commit hook will only run on changed files, whereas this runs on push and will check everything.
=> Enable post commit run of pre-commit hooks over all files.

.pre-commit-config.yaml, build_tools/scrape_releases.py, projects/pt1/examples/torchscript_stablehlo_backend_tinybert.py, projects/pt1/python/torch_mlir/_dynamo_fx_importer.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/configs/onnx_backend.py, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/slice_like.py, projects/pt1/test/python/importer/jit_ir/ivalue_import/debug-module-name.py, projects/pt1/test/python/importer/jit_ir/ivalue_import/object-identity-torch-bug.py, projects/pt1/test/python/importer/jit_ir/ivalue_import/quantization.py, projects/pt1/test/python/importer/jit_ir/node_import/debug-info.py, projects/pt1/test/python/importer/jit_ir/node_import/elif.py, projects/pt1/test/python/importer/jit_ir/node_import/function-derefine.py, projects/pt1/test/python/importer/jit_ir/node_import/if.py, projects/pt1/test/python/importer/jit_ir/node_import/loop.py, projects/pt1/test/python/importer/jit_ir/node_import/prim.py, projects/pt1/test/python/importer/jit_ir/node_import/tuple.py, projects/pt1/test/python/importer/jit_ir/node_import/types-bool.py, projects/pt1/test/python/importer/jit_ir/node_import/types-none.py, projects/pt1/test/python/importer/jit_ir/node_import/utils.py, python/torch_mlir/extras/fx_importer.py, python/torch_mlir/extras/onnx_importer.py
* Update black version to support 3.11/3.12
* Reformat code
=> [NFC] Update black version

build_tools/ci/build_posix.sh
The LTC Build was disabled in https://github.com/llvm/torch-mlir/pull/3210 due to a regression in the packaging of the torch nightly wheels (https://github.com/pytorch/pytorch/issues/124941) which is now resolved.
So, re-enabling LTC build in this PR
=> Re-enable LTC Build

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
iree tests `test_sinh` and `test_sinh_example` passed
=> Fix onnx sinh lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
iree tests `test_asinh` and `test_asinh_example` passed
=> Fix onnx asinh lowering

build_tools/python_deploy/build_linux_packages.sh
Fixes https://github.com/llvm/torch-mlir/issues/3258
In addition disabling the LTC builds since they are already covered in CI (build_posix.sh) and I am not aware of a consumer of this flow in the binary releases of torch-mlir (the main dependency there is from source).
=> [Release Builds] Use `-no-build-isolation` to decouple from `pyproject.toml`

projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
For some sparse programs (and I am sure other not-seen corner cases for dense), some passes were missing in the reference pipeline, eventually resulting in e.g. a unresolved unrealized cast issue. This PR adds some very obvious missing passes to avoid this situation.
=> [torch-mlir][sparse] add a few missing passes to the ref pipeline

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
While playing with TorchDynamo on ResNet18. I notice following issues:
-  `prims.convert_element_type` can’t  be canonicalized even if the input and the output share the same type
- `aten.max_pool2d_with_indices` is always used instead of `aten.max_pool2d`, even if the second returned output (indices) has no user
This PR fixes above issues by adding a folder to the PrimsConvertElementTypeOp and a canonicalizer to the AtenMaxPool2dWithIndicesOp
Lit test:
`cmake --build build --target check-torch-mlir-all`
=> Folder and Canonicalizer for PrimsConvertElementTypeOp and AtenMaxPool2dWithIndicesOp

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Adds OnnxToTorch lowering for the `onnx.HammingWindow` op.
=> [torch] Add OnnxToTorch lowering for `onnx.HammingWindow`

test/python/fx_importer/sparse_test.py
While waiting for the full resolution of feature request https://github.com/pytorch/pytorch/issues/117188
(which will propagate sparsity the right way in upstream PyTorch for all FX Graphs), this minor change allows us to start testing sparsity "within" a network, rather than just the parameters. Feel free to add your own rules for testing (but within reason for what will be done upstream).
Note, two TODOs need to be addressed to work around some pending issues to make the JIT execution work.
=> [torch-mlir][sparse] add simple sparsity "propagation" rules

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, projects/pt1/e2e_testing/xfail_sets.py
The is a draft PR. Currently in our project, we decompose all index_put like ops (e.g. `aten.index_put.hacked_twin`) to `aten._index_put_impl`. But we have little support for the possible `None` index in the operands in the conversions or transforms.  
Previously, I proposed a PR (#2344 ) that replaces the `None` indices in the `aten.index.Tensor` ops with manually generated indices. Maybe we can duplicate the work here. This will simplifies all backend conversions. And the place I came up to put the implementation is ops' canonicalizers. A draft code is as follows.  
I would like to hear your opinions @ramiro050 @vivekkhandelwal1 @qingyunqu . If it's ok, I will also move the implementation of index.Tensor to the TorchOps.cpp.
=> [Torch Dialect] decompose all index_put-like op to aten.index_put.hacked_twin for stricter semantics

CMakeLists.txt, include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, test/Conversion/TorchToLinalg/flatten.mlir, test/Conversion/TorchToLinalg/unsqueeze.mlir, test/Conversion/TorchToLinalg/view.mlir, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir, test/Dialect/TorchConversion/convert-custom-quant-op.mlir
This continues the work from #3279 , now with the upsteam LLVM fix 62bed56efdde1bed5dcebec5ceb375ffce223691 for the issue that PR ran into.
Disabling deprecated-declarations warning for now.
Not yet incorporating other fixes from @aartbik in #3282 but maybe we need to, let's see what CI says.
=> Integrate llvm-project at dabdec1001dc368373dd581cf72f37a440873ce3

test/python/fx_importer/sparse_test.py
Example of introducing sparsity into the forward pass. With a bespoke propagation (but upstream PyTorch will support this).
=> [torch-mlir][sparse] test for sparse "activation"

projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/python/fx_importer/sparse_test.py
(1) test full pytorch output for eltwise
(2) use "random" input for LIF, to get general sparse tensor 
(3) introduce way to get true sparsity into network (needs backend fix first)
=> [torch-mlir][sparse] minor tweaks in sparse tests

lib/Conversion/TorchToLinalg/DataMovement.cpp, python/torch_mlir/extras/fx_importer.py, test/Conversion/TorchToLinalg/view.mlir, test/Conversion/TorchToLinalg/view_strict.mlir
* Enables assume_strict_symbolic_shapes on fx_importer imported programs, indicating strict shape semantics.
* Reworks the view->reshape lowering to take advantage of strict mode and do one of:
* Collapse to 0D
* Flatten/Unflatten when there is an inferred dim.
* Fallback to tensor.reshape
* Splits some test cases up and adds an attribute to control the old pattern (so new corners can be tested in strict mode in isolation).
* Dynamic inferred mode needs upstream work to generalize expand_shape (so that case is suppressed here).
* Deletes the assert from the existing tensor.reshape lowering if strict shape mode is enabled (since the condition it is dynamically asserting cannot happen).
=> [linalg] Implement strict mode lowering for aten.view.

lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp
After running the model tests in SHARK-TestSuite, I noticed a few model failures due to half-fusion. 
Notably, RDN_pytorch_vaiq_int8 had a depth=5 convolution chain with multiple AtenViewOp's.
=> Expands Q Commuting Ops

test/python/fx_importer/sparse_test.py
Downstream MLIR sparsifier has some (rudimentary) support for ReLU now, and this test can now be enabled with correct end-to-end behavior.
Also see discussion at:
https://discourse.llvm.org/t/min-max-abs-relu-recognition-starter-project/78918
=> [torch-mlir][sparse] enable test on ReLu

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
https://github.com/nod-ai/SHARK-Turbine/issues/658
=> [MLIR][ONNX] Add OnnxToTorch support for GlobalMaxPool Op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
As mentioned in issue #3290 , the difference between onnx.Transpose in versions 1 and 13 is minimal, and therefore should be supported with the same conversion pattern.
=> [ONNX] Reduces Transpose Opset Version

lib/Dialect/Torch/IR/TorchOps.cpp
In constant folding progress, a new constant op will be created according to the origin op's result type.
See the code in TorchDialect.cpp.
```cpp
Operation *TorchDialect::materializeConstant(OpBuilder &builder,
Attribute value, Type type,
Location loc) {
if (auto integerType = dyn_cast<Torch::IntType>(type))
return builder.create<Torch::ConstantIntOp>(loc, cast<IntegerAttr>(value));
if (auto floatType = dyn_cast<Torch::FloatType>(type))
return builder.create<Torch::ConstantFloatOp>(loc, cast<FloatAttr>(value));
if (auto numberType = dyn_cast<Torch::NumberType>(type)) {
if (auto floatValue = dyn_cast<mlir::FloatAttr>(value)) {
return builder.create<Torch::ConstantNumberOp>(loc, floatValue);
} else if (auto intValue = dyn_cast<mlir::IntegerAttr>(value)) {
return …
```
=> [Torch] Fix PrimNumToTensorScalarOp::fold

lib/Conversion/TorchToStablehlo/Reduction.cpp, projects/pt1/python/torch_mlir/torchscript.py
* not to decompose `aten.amax` on `stablehlo` backend. Because it could be lowering to `stablehlo.reduce` directly.
* lowering `aten.max.dim` to `stablehlo.reduce apply max` when `AtenMaxDimOp.getIndices()` doesn't have users. It's more simple.
=> [Stablehlo] refactor amax, max, max.dim's lowering to stablehlo

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
Similar to https://github.com/llvm/torch-mlir/pull/2824, we were seeing some assertion failures after the addition checks around folders were tightened up in LLVM: https://github.com/llvm/llvm-project/pull/75887 . This PR essentially moves the logic that used to be applied at the LLVM level into the folder, which seems to be the suggested fix.
=> Don't fold `aten.clone` if result isn't same type as input

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchToLinalg/resize.mlir
The old lowering only had logic for 2d (i.e. images). this patch allows interpolation for n spatial dims, which is required for some 3d vision models such as 
- onnx/models/pytorch-3dunet_vaiq_int8
which successfully compiles and runs with this patch.
=> onnx.Resize and aten._interpolate : allow n spatial dims. 

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/e2e_testing/xfail_sets.py
This commit fixes the onnx.MaxPool op lowering which was lacking the indices result support.
=> [torch] Fix `onnx.MaxPool` lowering

.gitignore, include/torch-mlir/Dialect/Torch/Transforms/Passes.h, lib/Dialect/Torch/Transforms/Passes.cpp, python/torch_mlir/fx.py
Discord Thread: https://discord.com/channels/636084430946959380/1238330633328005243
[This](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/fx.py#L61) was updated to support e2e tests for the TorchDynamo frontend in Torch-MLIR, where we run FX decompositions and import the FX IR to generate Torch dialect, followed by `torch-function-to-torch-backend-pipeline`, skipping only the shape/type refinement for now. However, we should be able to skip many of the torch simplification passes, as depicted in the [frontend roadmap](https://github.com/llvm/torch-mlir/blob/main/docs/images/roadmap_frontend.png).
Based on IREE's TorchDynamo [pipeline](https://github.com/iree-org/iree/blob/main/compiler/plugins/input/Torch/InputConversion/Passes.cpp#L29), the only two passes we seem to …
=> [Pipeline] Use dedicated simplification pipeline for TorchDynamo frontend

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit fixes the bugs for the `onnx.OneHot` operator by:
1) Converting negative indices to non-negative indices
2) Handling both `int` and `float` types for `off` and `on` values
3) Using the correct result type
It also includes a new unit test.
=> [ONNX] Fix bugs for the `onnx.OneHot` operator

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchToArith/TorchToArith.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Conversion/TorchToArith/basic.mlir, test/Dialect/Torch/decompose-complex-ops.mlir
This PR fixes the bugs for `Torch::AtenOneHotOp` by:
1) Using `Torch::kUnknownSize` as the default value for `numClasses` in
the pattern matching stage in `DecomposeAtenOneHotOp`
2) Adding `AtenIntScalarOp` to the patterns in `TorchToArith`
3) Handling both `int` and `float` types for `off` and `on` values in `TorchOnnxToTorch` conversion
It also includes:
1) A new test in `TorchToArith/basic.mlir`, for `torch.aten.Int.Scalar`, and
2) A new test in `decompose-complex-ops.mlir`, for `torch.aten.one_hot`
**Dependencies**
This PR is dependent on #3334.
=> [Torch] Fix bugs for `Torch::AtenOneHotOp`

lib/Conversion/TorchToLinalg/DataMovement.cpp
std::accumulate needs 64-bit init value to perform 64-bit arithmetic on a list of integers.
=> [MLIR] Fix 64-bit product during aten.view lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
A PR landed when moving away from a deprecated cast function. Updated the corresponding lines to pass.
=> [NFC] Fix member cast change to global for landing collision

docs/development.md
@kuhar mentioned in the previous PR that we should use ld.lld. I kept using ld because for my LLD version, it worked.
After updating to a new LLD version, that became necessary.
=> Update development.md to use ld.lld

python/torch_mlir/extras/fx_importer.py
Resolving `bool` literals can result in a type change to uint8. This needs to be converted back to the expected type before returning to the wrapped `torch` operators.
=> Add conversion operation for bool resolved_literal

include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td, include/torch-mlir/Dialect/TorchConversion/Transforms/BackendTypeConversion.h, include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h, include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/GatherScatter.cpp, lib/Conversion/TorchToStablehlo/TorchToStablehlo.cpp, lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversionPasses.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, lib/InitAll.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/stablehlo_backends/linalg_on_tensors.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/type_conversion.py
Support lowering unsigned integer type to stablehlo as discussed in https://github.com/llvm/torch-mlir/pull/2184.
The things I do in this PR:
1. create `setupBackendTypeConversionForStablehlo()`, `createFuncBackendTypeConversionForStablehloPass` and `createFinalizingBackendTypeConversionForStablehloPass`.
2. remove `InferTypeOpInterface` from `torch_c.to_builtin_tensor`, because it's different result type between linalg backend and stablehlo backend:
```
// linalg backend
func.func @forward(%arg0: !torch.vtensor<[3],ui8>) -> tensor<3xf32> {
%c = torch_c.to_builtin_tensor %arg0 : (!torch.vtensor<[3], ui8> -> tensor<3xi8>
%0 = tensor.empty() : tensor<3xf32>
%1 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel"]} ins(%arg0 : tensor<3xi8>) outs(%0 : tensor<3xf32>) { …
```
=> [Stablehlo] support uint8

utils/bazel/torch-mlir-overlay/BUILD.bazel
#3367 and #3364 introduced new dependencies, causing the [Bazel workflow](https://github.com/llvm/torch-mlir/actions/workflows/bazelBuildAndTest.yml) to fail. These need to be fixed in Bazel.
=> [Bazel] Fix bazel deps

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit also adds the Torch declaration for aten.max_unpool2d and aten.max_unpool3d op. The TorchToLinalg lowering for the same will be added in a follow-up commit.
=> [ONNX] Add OnnxToTorch Lowering for MaxUnpool op

utils/bazel/torch-mlir-overlay/BUILD.bazel
This is needed after https://github.com/llvm/torch-mlir/pull/3372.
=> [Bazel] Add BuiltinDialectTdFiles dep to MLIRTorchOpsIncGen

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Supports asymmetric padding by performing a torch.nn.functional.pad on the input before performing the convolution.
=> [ONNX] Conv op adds support for asymmetric padding.

include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h, lib/Dialect/Torch/Utils/Utils.cpp
Linalg conversion requires mapping for f8 types
=> [torch] Add support for f8 types for linalg conversion

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/IR/TorchTypes.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
* Let `toBuiltinTensor()` reflects the original dtype of `!torch.vtensor`.
* Backend handles dtype conversion themselves.
=> [Torch] fix toBuiltinTensor()

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/custom_op_test.py
Tests the basic constructs of registering a custom op and its abstract implementations (with FakeTensors) in python, going through TorchDynamo export, followed by importing the shape expressions in the Torch dialect.
Also fixes the importer were previously the symbolic bind op insertion was not gated in one place.
=> Test custom op import with symbolic shapes

lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchToLinalg/resize.mlir
This patch fixes several failing tests in our [external test suite](https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests/onnx/node/generated), and addresses some of the issues discussed in #3420
=> [ONNX] Fix resize ceil numerics and add half_pixel_symmetric support

include/torch-mlir-c/TorchTypes.h, include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, include/torch-mlir/Dialect/Torch/IR/TorchTypes.td, include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h, lib/CAPI/TorchTypes.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Dialect/Torch/IR/TorchTypes.cpp, lib/Dialect/Torch/Transforms/MatchQuantizedOps.cpp, lib/Dialect/Torch/Utils/TorchUpstream.cpp, lib/Dialect/Torch/Utils/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Dialect/Torch/ops.mlir
There is currently no int16 quantization support in torch. This patch adds a new mlir type to correspond to the missing "torch.qint16" type, and enables lowering of quantization-related onnx ops using int16 types. 
In follow-up patches, custom quantization logic for ops like aten.matmul/aten.mm/aten.convolution may need to be revisited to allow support for qint16. The passes in FuseQuantizedOps.cpp may also need slight modifications.
=> [ONNX] add int16 quantization support

python/torch_mlir/extras/onnx_importer.py, python/torch_mlir/tools/import_onnx/__main__.py
Adds the following arguments:
- "--clear-domain": enabling this flag (default False) will delete the domain attribute from each node in the onnx model before importing. Shape inference does not seem to work for onnx ops in custom domains. In the rare case when these ops have a corresponding counterpart in base onnx, enabling this flag might allow shape inference to work properly. 
- "--opset-version": allows setting the opset version manually. This will cause the importer to attempt to update the opset_version of the onnx model before importing. Newer opset versions sometimes have more robust shape inference patterns.
=> [ONNX] add some args to the onnx importer to assist shape_inference

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchToLinalg/Pooling.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/pooling.py
Issues was found here https://github.com/nod-ai/SHARK-Turbine/issues/643
count_include_pad pytorch implementation:
https://github.com/pytorch/pytorch/blob/4a6dfbe4806b361c43210dfd56db64c4097c66bb/aten/src/ATen/native/cpu/AvgPoolKernel.cpp#L78
=> [ONNX] Fix AveragePool attributes support

projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/dynamo.py, python/torch_mlir/extras/fx_decomp_util.py
decomposition table for fx/dynamo
Let torch do the decomposition for
aten._scaled_dot_product_flash_attention_for_cpu when importing through Fx/Dynamo. By doing so, some SDPA related e2e tests can be marked as expectly success
=> Add aten._scaled_dot_product_flash_attention_for_cpu to default decomposition table

include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Dialect/Torch/Utils/TorchUpstream.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This implements the Onnx.NegativeLogLikelihoodLoss op using the signature provided [here](https://onnx.ai/onnx/operators/onnx__NegativeLogLikelihoodLoss.html) by replacing it with a `NLLLossForward` op.
Additionally, I included a helper function `get_loss_reduction_enum` to convert from a string `reduction` parameter to the corresponding intended integer value since this is an operation that will be reused for any loss function module. This differs from `get_reduction_enum` in `TorchUpstream.cpp` which handles the `reduce` parameter from `scatter_reduce` type operations.
=> [ONNX] Add OnnxToTorch lowering for Onnx.NegativeLogLikelihoodLoss Op

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds support for lowering
Onnx LRN op to aten.
=> Add onnx op LRN lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Taking `abs` is required to mimic same logic as onnx/onnxruntime. 
Without `abs`, it wouldn't produce correct results for negative values. 
Reference code : 
https://github.com/microsoft/onnxruntime/blob/f5b6f6dc26a55ddf7523d832ac5dc56930225264/onnxruntime/core/providers/cpu/nn/pool_functors.h#L604
https://github.com/onnx/onnx/blob/375c161c67855fea9612c15b83ebff40fca838a4/onnx/reference/ops/op_lp_pool.py#L31
CC : @zjgarvey  @vivekkhandelwal1
=> [ONNX] Add missing "Abs" in GlobalLpPool 

include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/Utils/Utils.cpp, test/Conversion/TorchToLinalg/convolution.mlir
1. truncates zero-points to i32
2. modifies the default accumulator type for i8 from i64 to i32. 
3. now uses the input dtype to infer accumulator dtype.
=> [TorchToLinalg] Fix Quantized Convolution Accumulator Type

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [ONNX] Fix Onnx.Hardsigmoid lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchToLinalg/Pooling.cpp
To fix dilations issue: https://github.com/llvm/torch-mlir/issues/3428
Test by: https://github.com/nod-ai/SHARK-TestSuite/pull/268
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu
| tests                      | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:---------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/operators/AveragePool | passed      | passed        | passed       | passed         | passed      |
=> [ONNX] Add averagepool dilations support

test/Dialect/Torch/canonicalize.mlir
In one of our downstreams, we encountered an internal assertion failure in an intermediate pass from `AtenTensorOp::fold` invocation:
```
external/llvm-project/llvm/include/llvm/Support/Casting.h:650: decltype(auto) llvm::dyn_cast(const From &) [To = mlir::torch::Torch::NonValueTensorType, From = mlir::Type]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
```
for this snippet in the IR:
```
%arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[1,1,15360],f32>}
...
%218 = torch.aten.size %arg1 : !torch.tensor -> !torch.list<int>
%219 = torch.aten.tensor %218, %none, %none, %false : !torch.list<int>, !torch.none, !torch.none, !torch.bool -> !torch.tensor
```
Turns out this was [fixed](https://github.com/llvm/torch-mlir/pull/3189/files#diff-dc8ed165c207918 …
=> `AtenTensorOp::fold` should not fold when result type is not fully specified

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/scatter.py
The `index_put` operation, `input[indices] = values`, allows for the values to be any shape that is broadcastable to the slice `input[indices]`. This commit adds broadcasting support to the Linalg lowering of `IndexPutHackedTwinOp`.
Fixes: #3465
=> [LINALG] Broadcast `values` to shape of slize in `index_put`

lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Conversion/Utils/Utils.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp, test/Conversion/TorchToLinalg/elementwise.mlir, test/Conversion/TorchToLinalg/pooling.mlir, test/Conversion/TorchToLinalg/view_strict.mlir, test/Conversion/TorchToSCF/basic.mlir, test/Conversion/TorchToStablehlo/elementwise.mlir, test/Conversion/TorchToStablehlo/linear.mlir, test/Conversion/TorchToStablehlo/view_like.mlir
Before this PR, a statically shaped aten.convolution would generate dynamically shaped linalg IR, and even `-canonicalize` would not be able to fold it back into static shapes. This PR ensure that shape calculations are folded on construction to directly generate statically shaped linalg IR.
We achieve that by ensuring that `arith` ops involved in computing shapes are created via `createOrFold`, so that later uses of `getAsOpFoldResult` see constants instead of those ops.
For example
```
module {
func.func @forward(%arg0: !torch.vtensor<[32,336,112,112],f32>,
%arg1: !torch.vtensor<[336,168,3,3],f32>, 
%arg2: !torch.vtensor<[336],f32>) 
-> !torch.vtensor<[32,336,56,56],f32> {
%false = torch.constant.bool false
%int2 = torch.constant.int 2
%int1 = torch.constant.int 1
%0 = …
```
=> TorchToLinalg: Try folding shape computations to keep static shapes when possible

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/ops.mlir
Due to the custom operation parser, the print and parser were expecting two different forms. 
One having the dictionary before the value and the other after. Following the format of the other constants ops, the constant.int will follow the `value attr-dict` format. Updated the parser accordingly.
=> [Torch] Fix torch.constant.int operation parsing

lib/Conversion/TorchToLinalg/Utils.cpp
Inlines a variable into an assertion that is not used elsewhere to fix build warnings.
=> Fix unused variable warning from assertion variable

lib/Conversion/TorchToLinalg/DataMovement.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToLinalg/view.mlir
Addresses an issue with onnx.Gather lowering to linalg: <https://github.com/nod-ai/SHARK-Turbine/issues/242>
The builder for tensor.expand_shape, without an explicitly provided output shape, fails to infer an output shape in the case of multiple dynamic reassociation dims. I tried adding the output shape explicitly for tensor.expand_shape, but ran into compilation issues later on (see <https://github.com/iree-org/iree/issues/17760>). 
This PR adds support by lowering this op to tensor.reshape when multiple dynamic reassociation dims are provided.
=> Add support for multiple dynamic reassociation dims for unflatten.int

python/torch_mlir/extras/fx_decomp_util.py, test/python/fx_importer/sparse_test.py
Fixes https://github.com/llvm/torch-mlir/issues/3499
=> [torch-mlir][sparse] add decomposition features to sparse compiler

projects/pt1/python/torch_mlir_e2e_test/framework.py
so that we could run `python3 -m e2e_testing.main -v` to specify `verbose=True`
=> support both option -v and TORCH_MLIR_TEST_VERBOSE

projects/pt1/e2e_testing/xfail_sets.py, python/torch_mlir/extras/onnx_importer.py, python/torch_mlir/tools/import_onnx/__main__.py, test-requirements.txt
This commit adds the support for new data types: uint4, and int4 and uint8 tensor protos. Also, it moves some tests from failing to crashing.
Fixes https://github.com/llvm/torch-mlir/issues/3507
=> Bump Onnx Version to 1.16.1

lib/Conversion/TorchToStablehlo/Basic.cpp
* use lhs tensor's element type as compute type when rhs is scalar.
* previously `a != 1.0`(a is a fp32 tensor) will lowering to `%6 = stablehlo.compare  EQ, %4, %5,  FLOAT : (tensor<2x5xf64>, tensor<2x5xf64>) -> tensor<2x5xi1>`
* now it will lowering to `%6 = stablehlo.compare  EQ, %4, %5,  FLOAT : (tensor<2x5xf32>, tensor<2x5xf32>) -> tensor<2x5xi1>`
=> [Stablehlo] fix compareOp with scalar's lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Fix the pad tensor rearrangement such that we change the representation from [x1_begin, x2_begin, ..., x1_end, x2_end,...] to [xn_begin, xn_end, ...., x2_begin, x2_end, x1_begin, x1_end] where x1, x2 .. xn are the dimensions of the pads tensor argument.
=> [ONNX] Fix bug in ONNXToTorch PadOp's pads tensor rearrangement

include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/GatherScatter.cpp, lib/Conversion/TorchToStablehlo/Linear.cpp, lib/Conversion/TorchToStablehlo/Pooling.cpp, lib/Conversion/TorchToStablehlo/Reduction.cpp, lib/Conversion/TorchToStablehlo/StablehloLegalizeUtils.cpp, lib/Conversion/TorchToStablehlo/ViewLike.cpp, test/Conversion/TorchToStablehlo/linear.mlir, test/Conversion/TorchToStablehlo/pooling.mlir, test/Conversion/TorchToStablehlo/scatter.mlir, test/Conversion/TorchToStablehlo/view_like.mlir
For example, the original IR is:
```
module attributes {torch.debug_module_name = "Matmul3D"} {
func.func @forward(%arg0: tensor<?x?x?xf32>, %arg1: tensor<?x?x?xf32>) -> tensor<?x?x?xf32> {
%c0 = arith.constant 0 : index
%c1 = arith.constant 1 : index
%c2 = arith.constant 2 : index
%dim = tensor.dim %arg1, %c0 : tensor<?x?x?xf32>
%0 = arith.index_cast %dim : index to i64
%dim_0 = tensor.dim %arg1, %c1 : tensor<?x?x?xf32>
%1 = arith.index_cast %dim_0 : index to i64
%dim_1 = tensor.dim %arg1, %c2 : tensor<?x?x?xf32>
%2 = arith.index_cast %dim_1 : index to i64
%from_elements = tensor.from_elements %0, %1, %2 : tensor<3xi64>
%3 = stablehlo.dynamic_broadcast_in_dim %arg1, %from_elements, dims = [0, 1, 2] : (tensor<?x?x?xf32>, tensor<3xi64>) -> tensor<?x?x?xf32>
%4 = stablehlo.dot_general …
```
=> [Stablehlo] use index type as dim size, avoid to generate index_cast

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
We used to move the SmallVector into an ArrayRef and then the SmallVector left the scope.
Found by asan.
=> TorchOnnxToTorch: Fix stack-use-after-free

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The LpNormalization lowering was previously just computing the norm, which is incorrect. This computes the norm then divides the input tensor by it's norm.
I've tested this against some simple onnx models locally. I'll look into adding a test case for this in an external test suite.
=> [ONNX] Fix LpNormalization Lowering

python/torch_mlir/compiler_utils.py, python/torch_mlir/fx.py
This is a non-functional change. It merely allows intercepting the Torch dialect during TorchDynamo export at two stages:
1. `OutputType.RAW`: This gets us the torch dialect as-imported from the FX graph
2. `OutputType.TORCH`: This gets us the torch dialect after the raw torch goes through DecomposeComplexOps and ReduceOpVariants.
Prior to this, there was no way of accessing the Torch dialect in backend compliant form (right after running the `torchdynamo-export-to-torch-backend-pipeline`) because both [here](https://sourcegraph.com/github.com/llvm/torch-mlir@5e4f00acb13f3f849a05e5ac28ee39307a5fdbff/-/blob/python/torch_mlir/fx.py?L33) and [here](https://sourcegraph.com/github.com/llvm/torch-mlir@5e4f00acb13f3f849a05e5ac28ee39307a5fdbff/-/blob/python/torch_mlir/compiler_utils.py?L138) the …
=> [NFC] Expose both raw Torch dialect and Torch dialect in backend form with Dynamo/FX

test/python/fx_importer/symbolic_shape_expr_test.py
We do have support for translating unbacked symbolic_ints that arise from data-dependent ops like `aten.nonzero`. This PR adds the python lit test coverage for the same.
=> [Symbolic Shapes] Test coverage for unbacked symint from data dependent ops

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/custom_op_test.py
This PR adds support to `fx_importer.py` for handling custom ops that return an array of tensors.  As long as the length of the array is consistent across runs (determined statically), then this patch will work.  This does not require that the number of tensors returned is determined by the op's definition.
CC @sjain-stanford
=> Allow custom ops to return an array of tensors

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
* so that it could support like `i64 + f64 => f64`.
* also unify `aten.log`'s folder code to use `naryFolderHelper`.
=> [Torch] enhance naryFolderHelper to support mixed dtypes

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Added support for splitToSequence ops lowering
Added test case with filecheck
=> Implementation of SplitToSequence ops lowering 

lib/Conversion/TorchToLinalg/Uncategorized.cpp
Pytorch and ONNX apparently round to nearest, ties go to nearest even, but we were using `math::round` for the torch-to-linalg conversion of `quantize_per_tensor`, which rounds away from zero on ties.
=> Align Quantization Rounding Scheme with ONNX/Pytorch

include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/GatherScatter.cpp, lib/Conversion/TorchToStablehlo/StablehloLegalizeUtils.cpp
For now, at most one dynamic dim of index tensors in aten.index/aten.index_put-like op is supported.
=> [stablehlo] support dynamic-shaped index in stablehlo conversion for aten.index-like ops

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp
There were two issues related to `ignore_index` being set
(1) the onnx-to-linalg pass as not reading the value correctly (2) the mean pass was not considering the `ignore_index` value
For (2) when taking the mean we need to know how many of the values were considered in the sum and therefore we cannot divide by the total number of elements. Adding a summation across the total number should correct this issue.
=> [onnx][torch] Fix `onnx.SoftmaxCrossEntropyLoss` for ignore index

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
We need to adjust for negative scatter indice values. Added materializing out the inbounds adjustment.
=> [onnx] Fix `onnx.ScatterElements` for negative indices

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
We were defaulting to `0.0` for `onnx.Elu` when it is supposed to be `1.0`.
=> [onnx] Fix default `alpha` for `onnx.Elu`

lib/Conversion/TorchToLinalg/Uncategorized.cpp
Uses arith::MaximumFOp and arith::MinimumFOp instead of comparison and select ops to improve readability of IR.
=> [TorchToLinalg] Simplify QuantizePerTensor lowering

lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchToLinalg/resize.mlir
Following up from the discussion in <https://github.com/llvm/torch-mlir/pull/3550>, I've edited the lowering to prevent OOB extracts in a more direct fashion (i.e., just clamping directly). 
I don't think this affects the lit tests at all, but I've tested the changes in our external test suite at <https://github.com/nod-ai/SHARK-TestSuite/tree/main/>. I found the issue when I was unexpectedly getting `nan`'s along the output image border for a resize test there.
=> [TorchToLinalg] Fix possible OOB access in Interpolate lowering

lib/Dialect/Torch/IR/TorchOps.cpp
Lambda needs a return value to avoid a build failure.
=> Avoid warnings-as-errors build failure

projects/pt1/python/torch_mlir_e2e_test/framework.py
It will exit immediately. So it doesn't need to wait 6 min.
=> [e2e_testing] check process exitcode early in e2e

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit lowers onnx.scan op to torch.prim.Loop op and adds the lowering in the onnx pipeline.
=> [MLIR][ONNX] Add support for onnx.scan op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
`onnx.Shape` can select only a subset of indices using attributes. Add support for these attributes.
=> [onnx] Fix `onnx.Shape` to include `start` and `end` processing

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This fixes the result type of the `torch.aten.lt.Scalar` and `torch.aten.ge.Scalar` ops created during the lowering of `onnx.Shrink` to Torch.
=> [onnx] Fix lowering `onnx.Shrink` to Torch

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
The pattern `m_OnnxListOfConstantInts` previously only checked if the attr inside an `onnx.Constant` op is a `DenseResourceElementsAttr`, but didn't handle `ElementsAttr`'s. This patch adds support for `ElementsAttr` and provides an example of it's use via a lit test for `onnx.Unsqueeze`.
=> [Onnx] expand support for constant matching

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The saga of aligning onnx and torch padding conventions continues. 
```python
onnx_pads = [low_x, low_y, low_z, high_x, high_y, high_z]
torch_pads = [low_z, high_z, low_y, high_y, low_x, high_x]
```
So not only is the lexicographical ordering hierarchy swapped (low/high x spatial-dim -> spatial-dim x low/high) but the ordering in the the spatial-dim specification is also reversed. 
This patch properly reverses the pad ordering (and actually uses the `shuffledPadding` to pad).
=> [ONNX] fix padding for `onnx.MaxPool`

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
It is possible that the unpacked tensor does not match the same inferred shapes. This is pretty common when ingesting form the `onnx` frontend.
=> [torch] Unpacking sometimes misses shape inference

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
The attribute does not exist in all variants of the operation. It can be inferred from the number of results so we should just do that.
=> [onnx] `onnx.Split` may not have `num_outputs` which can be inferred

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Fp8 needs a slightly different path for dequantization as the `torch` dequantize operation does not support `fp8` types.
=> [onnx] Add support for `fp8` `onnx.DequantizeLinear`

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
We need to directly decompose quantize linear for `fp8` types as the equivalent torch operations do not support the operation.
=> [onnx] Support `fp8` for `onnx.QuantizeLinear`

projects/pt1/e2e_testing/main.py, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, projects/pt1/python/torch_mlir_e2e_test/stablehlo_backends/linalg_on_tensors.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/constant_alloc.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/scalar.py, test/python/fx_importer/sparse_test.py
This adds the `generate-runtime-verification` pass into the linalg refbackend, and moves all tests that now abort at runtime into the crash set, sorted by their respective errors.
I have fixed on set of errors found that way, which are mismatches between the static dimensions we cast to and the actual dynamic dimensions. This was caused by wrong annotations on the test cases, like in https://github.com/llvm/torch-mlir/pull/3615/files#diff-48bfbf41fcad5fa01b49197d251114f84a2b8de4f1d87ab938a061aedd1419b1R1931
=> e2e: Enable generate-runtime-verification pass

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Just uploading what I have till now
[Gist](https://gist.github.com/PhaneeshB/761f75f5522d9f4a40ef949a328e93fe) of pytorch impl that I'm following to implement the OnnxToTorch lowering
Additional Details - (also pasted as comment in gist)
[Op Description](https://github.com/onnx/onnx/blob/main/docs/Operators.md#melweightmatrix) in Onnx Documentation
[Example](https://github.com/onnx/onnx/blob/main/docs/Operators.md#examples-93) Used the same example in this file.
the Expected output is shown in the example
[Reference Onnx Impl](https://github.com/onnx/onnx/blob/4c3ed5e08be75bbe1eeb6818e490b1b6a370183e/onnx/reference/ops/op_mel_weight_matrix.py#L13) - This is the base for the above code.
Till now I'm at a point where we have [cast the …
=> onnx.MelWeightMatrix TorchOnnxToTorch

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The lowering to torch makes assumption about the dimensions / types of reduce max and onehot. We need to correct for expected torch behavior.
=> [onnx] Fix `onnx.Hardmax` lowering to torch

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
1-d/2-d input and output
implemented based on the description and example test cases in
https://github.com/onnx/onnx/blob/main/docs/Operators.md#TfIdfVectorizer
and some notes from
https://github.com/onnx/onnx/blob/main/onnx/reference/ops/op_tfidf_vectorizer.py#L128
=> onnxtotorch tfidfvectorizer 1-d

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/reshape_like.py
The einsum lowering was missing the behavior for duplicate indices in the equation. This amounts to a diagonalization along duplicate pairs of indices in the equation.
=> [torch] Support diagonal `einsum.Diagonal`

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
A case where unsqueeze was require was missed causing compilation failures.
=> [onnx] Fix `onnx.Gather` for bad expansion

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Pow is not support for the `torch` operator. Add casting for integer types.
=> [onnx] Support integer types for `onnx.Pow`

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
This commit extends the OnnxToTorch lowering for BatchNormalization op for supporting the case when training=True.
=> [ONNX] Add training mode support for BatchNormalization op

lib/RefBackend/CMakeLists.txt
Discovered in https://github.com/llvm/torch-mlir/issues/3104
Most likely when building with stablehlo, while waiting for it missing dependency was generated to location shared with another dependency.
=> Add missing dependency to TorchMLIRRefBackend target

README.md
Current pip installation command raises error
```
ERROR: Could not find a version that satisfies the requirement torch-mlir (from versions: none)
ERROR: No matching distribution found for torch-mlir
```
(checked on Ubuntu 22.04.2 LTS with `venv` and with `conda`)
Because it is trying to install torch-mlir from pytorch repository. The installation command was wrongly split into 2 in #3073. I just merged them back to 1 installation command with both pytorch and llvm/torch-mlir channels.
=> Fixed installation command in README.md

lib/Conversion/TorchOnnxToTorch/OnnxRecurrentLayerOpExpanders.cpp
The implementation was short circuiting the second result. Updated to guarantee we do not short circuit.
=> [onnx] Fix shortcircuit path

lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/e2e_testing/xfail_sets.py
torch.isclose has tosa lowering but no linalg lowering. Add linalg lowering to fix the failure of isclose related tests on linalg backend.
=> [TorchToLinalg] Support torch.isclose lower to linalg

projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/framework.py, projects/pt1/python/torch_mlir_e2e_test/registry.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/__init__.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/timeout.py
Previously we only had full suite timeouts, making it impossible to identify
which specific tests were hanging. This patch adds:
1. Per-test timeout support in the test framework
2. A default 600s timeout for all tests
3. A deliberately slow test to verify the timeout mechanism works
The timeout is implemented using Python's signal module. Tests that exceed
their timeout are marked as failures with an appropriate error message.
This should help catch and isolate problematic tests that enter infinite 
loops, without needing to re-run the entire suite multiple times.
=> Add per-test timeouts to catch infinite loops

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds the shape info for the tensors created during the decomposition of GroupNorm op.
=> MLIR][TORCH] Fix GroupNorm decomposition by adding shape info

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py
Support dtype conversion between types. This is useful for bitcasting buffers between differing bit depths.
=> [torch] Add `torch.aten.view.dtype` to op list

lib/Conversion/TorchToLinalg/Uncategorized.cpp
I missed adding second operand conversion and adding them to the set of rewrite patterns.
=> [torch] Fix lowerings of rshift and lshift

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The `axis` attribute is optionally available. Added support by computing the pad based on the axis values.
=> [onnx] Support for optional `axis` attribute for `onnx.Pad`

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Dialect/Torch/decompose-complex-ops.mlir
The following case was failing to lower for einsum. This fixes up the inner product issue.
=> [onnx] Handle `torch.aten` for inner product case

python/TorchMLIRModule.cpp, python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/basic_test.py
New sympy type is introduced to represent integer infinity in upstream PyTorch repo. Subsequently, sympy.oo is no longer used to represent infinity upper bound for dynamic dimensions where the upper bound is unknown. Instead `int_oo` is used to represent integer infinity. This commit updates the `_sympy_int_to_int` utility in light of this change.
=> [FxImporter] Fix sympy_int_to_int utility

lib/Conversion/TorchToLinalg/Linear.cpp
The current implementation uses a `linalg.generic` to broadcast the bias tensor for the lowering of convolutions. This is suboptimal for later pattern matching. This patch changes it to use the respective named op, `linalg.broadcast`, instead.
=> [TorchToLinalg] Use `linalg.broadcast` instead of `generic` for conv bias

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Supports the result with dynamic shape and scalar indices like
```
func.func @test_gather_scalar(%arg0: !torch.vtensor<[3,4,5],f32>, %arg1: !torch.vtensor<[], si64>) -> !torch.vtensor<[?,?],f32> attributes {torch.onnx_meta.opset_version = 13 : si64} {
%0 = torch.operator "onnx.Gather"(%arg0, %arg1) {torch.onnx.axis = 0 : si64} : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[], si64>) -> !torch.vtensor<[?,?],f32>
return %0 : !torch.vtensor<[?,?],f32>
}
```
`Torch::AtenSqueezeOp` is referring to the result shape, so it will failed on lowering if the result shape is dynamic.
=> Fix onnx.Gather lowering with dynamic shapes

test/Conversion/TorchToLinalg/convolution.mlir
This patch add a test for 638ef14, which use `linalg.broadcast` instead of `generic` for convolution bias.
=> [TorchToLinalg][test] Add test for ConvertAtenConvolutionOp

python/torch_mlir/extras/fx_importer.py
Downstream projects don't necessarily register this C++ module. This package removes the dependency and uses `torch.iinfo` to access the max and min values instead.
=> [fximporter] Avoid importing from `_torchMlir`

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py
Addresses an issue in <https://github.com/llvm/torch-mlir/issues/3651> where some unflatten ops generated from onnx models weren't propagating static shape information. It may be necessary to add further optimizations for the more general case when some static information is present in the unflatten (or possibly reshape/view) op's `sizes` list, but not reflected in the output shape. These ops will only successfully infer shapes if the `sizes` list is gotten from a list of constant ints (with possibly one -1). A common example where this fails is when some of the `sizes` are determined from `aten.size.int` ops on dynamic tensors, and other `sizes` are known statically. 
This PR includes:
- a canonicalizer for `aten.unflatten.int` which converts to `aten.unsqueeze` when it is expanding one …
=> Add a canonicalization pattern for `aten.unflatten.int`

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/Conversion/TorchToLinalg/basic.mlir
The lowering pattern for `aten.T` uses transposition implemented via `linalg.generic`. For downstream passes it is advantageous to use named ops wherever possible, so this patch changes the lowering to use `linalg.transpose` instead.
=> [TorchToLinalg] Use `linalg.transpose` instead of `generic` when lowering `aten.T`

CMakeLists.txt, README.md, build_tools/ci/build_posix.sh, build_tools/ci/test_posix.sh, build_tools/update_abstract_interp_lib.sh, build_tools/update_torch_ods.sh, docs/add_ops.md
Temporary fix for Disable TORCH_MLIR_ENABLE_PYTORCH_EXTENSIONS #3654
Disable TORCH_MLIR_ENABLE_JIT_IR_IMPORTER by default
- Only enable it in CI for update_abstract_interp_lib.sh and update_torch_ods.sh usage.
TODO:
- Deeper doc change  https://github.com/llvm/torch-mlir/issues/3696
- Pure python verion of torch_ods_gen.py and abstract_interp_lib_gen.py https://github.com/llvm/torch-mlir/issues/3695
=> Disable TORCH_MLIR_ENABLE_JIT_IR_IMPORTER by default

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Add logic for `auto_pad` attribute in the conversion of `onnx.Conv` torch dialect.
Add lit tests covering different configurations of `auto_pad`.
=> [onnx] Add support for `auto_pad` in `onnx.Conv`

lib/Dialect/Torch/Transforms/InlineGlobalSlots.cpp, test/Conversion/TorchToStablehlo/linear.mlir
Bump forward and refactor inline global slots to no longer track via symlinks. This appears to make the tests past until we manage to remove torchscript work.
=> Bump llvm/llvm-project@b6603e1bf11dee4761e49af6581c8b8f074b705d

CMakeLists.txt, python/CMakeLists.txt, setup.py
Trying to build empty libraries causes weird failures based on clang/gcc and doesn't work with certain versions of python as well. We should avoid this wherever possible, and this specifically has been leading to the following issues/failures:
https://github.com/llvm/torch-mlir/issues/3663
https://github.com/llvm/torch-mlir-release/actions/runs/10558518843/job/29248139823
=> Redefine TorchMLIRPythonModules to avoid building empty libraries.

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Previously, if the value was absent, this conversion was creating a dense resource of value 0 with shape equal to the result shape, then later re-extracting a splat value. This only works if the shape is statically known, and even when the shape is known, this is completely unnecessary since the value's shape should be `[1]` and not the result shape. 
This patch simply sets the `splatvalue` to a `torch.constant.float 0.0` when the onnx op's `value` attr is absent, and adds `nullptr` checks to the subsequent conditionals to avoid them in the case where an `attr` is not given.
Addresses <https://github.com/nod-ai/SHARK-Turbine/issues/831>.
=> [ONNX] Fix issue with absent value in onnx.ConstantOfShape

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
Current version does not work for a mixture of dynamic and static shaped batch dimensions. Rework to grab the correct dynamic shapes.
=> [torch] Fix attention on linalg for dynamic shapes

docs/development.md
This documents which CMake options must be set to be able to use `torch_mlir_e2e_test`, required e.g. for
`projects/pt1/tools/e2e_test.sh`.
Makes progress on #3696.
Closes #3719.
=> Document requirements for `torch_mlir_e2e_test`

lib/Dialect/Torch/IR/TorchOps.cpp
Fixes https://github.com/iree-org/iree/issues/18562.
During canonicalization pass on `AtenUnflattenIntOp`, if the second dim was statically equal to one, we would create an `AtenAddIntOp` to add one to the dimension obtained from `op.getDim()`. This, when passed into `Torch::unsqueezeTensor()`, would make it get interpreted as non-constant, which would lead to MLIR failing an assertion when `UnsqueezeOp` would later get lowered into `ExpandShapeOp`, as the output of the `UnsqueezeOp` would consist of only dynamic dims.
This patch fixes this behavior, by extracting the integer value from the dim if it was constant, and then emitting a `ConstantIntOp` from (dim+1). This creates an output with static shape.
=> [torch] Fix unsqueezed output shape in canonicalization of AtenUnflattenIntOp

lib/Dialect/Torch/Utils/Utils.cpp
Instead of 
`Unhandled type in getScalarTypeForType`
You now get
Unhandled type in getScalarTypeForType: (type name)
Type properties:
Is integer: yes
Bit width: 
...
The root cause is https://github.com/llvm/torch-mlir/issues/3720, at least for unsigned integer issues.
=> Better errmsg upon getScalarTypeForType failure

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Address https://github.com/nod-ai/SHARK-Turbine/issues/826
=> [onnx] Fix onnx.Shape lowering with scalar input

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir
- Add lowering from Torch to TOSA for aten.diagonal
- Clean up some code
- Update xfail_sets.py with the new e2e results
- Update basic_mlir with the new op mlir test
Signed-off-by: Justin Ngo <justin.ngo@arm.com>
Change-Id: I99bed685455752d09ed96edd837c4dfbee152701
=> [TOSA] Add legalization for aten.diagonal

docs/development.md
The `python` command is only available on Ubuntu if the `python-is-python3` package is installed, see
https://packages.ubuntu.com/jammy/python-is-python3 and https://packages.ubuntu.com/jammy/all/python-is-python3/filelist. As Python 2 isn't supported anyway, it's safe to point to `python3` here instead.
=> Update instructions on creating a virtual env

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/invalid.mlir
The op can be valid with no attached shape symbols if they are not required by the corresponding affine map. Fix the verifier to consider number of arguments for both.
=> [torch.bind_symbolic_shape] Fix verifier for shapeSymbol detection

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
Address https://github.com/nod-ai/SHARK-Turbine/issues/833
=> [onnx] Add IDF and TFIDF modes to TFIDF Vectorizer

build_tools/python_deploy/build_linux_packages.sh, build_tools/python_deploy/build_macos_packages.sh, setup.py
As of Sep 14, the torch-mlir binary [wheels](https://github.com/llvm/torch-mlir-release/releases/tag/dev-wheels) got renamed to `torch-mlir-core` from `torch-mlir`: ![image](https://github.com/user-attachments/assets/152e4977-71ef-4f57-8757-6dc75f72b670) 
This was an unintended side-effect of the recent change of `TORCH_MLIR_ENABLE_ONLY_MLIR_PYTHON_BINDINGS=True` (https://github.com/llvm/torch-mlir/pull/3711) which skips setting `NAME = "torch-mlir"` in [setup.py](https://github.com/llvm/torch-mlir/blob/main/setup.py#L226-L232).
To avoid having multiple downstreams fix their pip deps, this change allows using the same `torch-mlir` name for binaries, and reserves a separate `torch-mlir-ext` name for the (less popular) binaries with extensions enabled.
=> [Release] Fix binary name for downstream compatibility

lib/Conversion/TorchOnnxToTorch/OnnxRecurrentLayerOpExpanders.cpp
Issue: https://github.com/nod-ai/SHARK-ModelDev/issues/856
Related tests:
=> Fixed GRU quality issues exposed by e2e tests

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, projects/pt1/python/torch_mlir_e2e_test/configs/onnx_backend.py, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Addresses ~200 onnx model compile failures in <https://github.com/nod-ai/SHARK-TestSuite> related to <https://github.com/iree-org/iree/issues/18631>.
This change simplifies the result of the generated broadcast op substantially, but reduces the case coverage slightly. 
The case which will become unsupported: 
- trying to actually broadcast a dynamic dim that is secretly 1. 
When does this case appear in practical scenarios?
- for a model where onnx shape inference cannot figure out that a dim should be 1. 
Why do I think we should not support this case for now?
1. For all models with dynamic dim expand ops, the previous path uniformly generates uglier linalg IR (making it harder for IREE to fuse properly with other ops).
2. For models failing shape inference castastrophically enough to …
=> [RFC] [ONNX] simplify shapes fed to broadcast in Expand lowering

lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchToLinalg/elementwise.mlir
This is motivated by the fact that shapes are stored as tensors in ONNX, and IREE tries to perform tensor arithmetic on the device. This causes unnecessary dispatches, and makes it harder for the compiler to reason about shapes. 
Here is a small snippet of torch-IR that is typical seen coming from ONNX models:
```mlir
module {
func.func @main_graph(%arg0: !torch.vtensor<[?,?,768],f32>, %arg1: !torch.vtensor<[?,?,768],f32>) -> !torch.vtensor<[],si64> {
%int0 = torch.constant.int 0
%0 = torch.vtensor.literal(dense<0> : tensor<1xsi64>) : !torch.vtensor<[1],si64>
%1 = torch.aten._shape_as_tensor %arg1 : !torch.vtensor<[?,?,768],f32> -> !torch.vtensor<[3],si64>
%2 = torch.aten.index_select %1, %int0, %0 : !torch.vtensor<[3],si64>, !torch.int, !torch.vtensor<[1],si64> -> …
```
=> [TorchToLinalg] perform rank0 elementwise computations outside linalg generic ops

lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchToLinalg/elementwise.mlir
Reverted due to downstream model changes. Will reland with fixes post integration.
This reverts commit 6e8c7bed4b12117764274e79bc60a93443d5bdd5.
=> Revert "[TorchToLinalg] perform rank0 elementwise computations outside linalg generic ops (#3762)"

include/torch-mlir/Conversion/TorchToLinalg/Utils.h, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Conversion/TorchToLinalg/Utils.cpp
This commit adds the support for negative step values in aten.slice.Tensor op. Although, PyTorch does not allow negative step value for slice op but the Onnx.Slice op supports negative step value which eventually lowers to torch.aten.slice.Tensor op. Hence, the support is added for handling those kind of values during the Torch->Linalg lowering of aten.slice.Tensor op.
=> [MLIR][TORCH] Add support for negative step in aten.slice.Tensor op

lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, test/Dialect/Torch/scalarize-shapes.mlir
This patch adds two things:
1. support for folding scalar patterns like [1]---squeeze--->[] ---unsqueeze--->[1]. 
2. a canonicalizer for aten.view that applies when we can statically or dynamically (through the scalarized view shapes) infer that it is a flatten or unflatten op in the last dim. 
I'm not sure if this is the right place to be adding such a view canonicalizer. Catastrophically, there is a decomposition from flatten and unflatten into aten.view. Until this gets deleted (and it definitely should be deleted), I felt like this would be an appropriate temporary home. We run scalarize shapes after lowering to the backend contract (i.e., decomposing), and scalarize shapes is required to be able to infer dynamic dims coming from size int ops.
=> adds a few common patterns to scalarize shapes pass

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py
This was preventing dynamic dims in an ONNX model from being reified (causing the generation of `tensor.cast`s and preventing fusion in iree):
```mlir
%2 = torch.vtensor.literal(dense<[4, 256]> : tensor<2xsi64>) : !torch.vtensor<[2],si64>]
%7 = torch.prim.ListConstruct %int2 : (!torch.int) -> !torch.list<int>
%8 = torch.aten.reshape %2, %7 : !torch.vtensor<[2],si64>, !torch.list<int> -> !torch.vtensor<[2],si64>
//... chain of foldable ops linking %2 to the `shape` operand of a `torch.aten.broadcast_to ... -> !torch.vtensor<[?,?],si64>`
```
=> [Torch] Fold no-op reshape

lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, test/Dialect/Torch/scalarize-shapes.mlir
-Adds patterns for propagating shapes through AtenWhereSelf and AtenEqTensor
-Adds fold pattern for a rank0 squeezeDim of a full op 
-Adds support for getting a list from a splat ValueTensorLiteralOp for materializing scalar comparisons in where.self and eq.tensor
With a bit of hammering, these changes should unblock several IREE inference failures.
=> Add more patterns to scalarize-shapes pass

lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp, test/Dialect/Torch/simplify-shape-calculations.mlir
Some ops were failing to infer the static component of partially dynamic shapes, and the cause was a missing aten.slice.t pattern.
The lit test included here is an IR dump created before DropAbstractInterpCalculations for an unflatten op that was failing to infer shapes before the change.
=> Add AtenSliceTOp Canonicalization to SimplifyShapeCalculations pass

lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, test/Conversion/TorchToLinalg/embeddingBag.mlir
Torch-to-linalg pass fails for `EmbeddingBag` when the training only specific properties of the operator are set to `true.` For instance, this operator's `sparse` input/property is training-specific, and if the value of this property is `true,` the existing lowering bails out. However, we don't need to check for training-specific parameters and bailout from the legalization since we don't care about these properties during the eval/inference mode.
=> Remove checking for training specific parameters in EmbeddingBag lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Adds onnx ConvTranspose support for autopadding (https://github.com/nod-ai/SHARK-ModelDev/issues/839).
- Adds support for attribute auto_pad="SAME_UPPER" or "SAME_LOWER" which will automatically calculate padding of input based on output shape.
- Adds support, during auto-padding, for output_shape=[H,W] which overrides the default output shape of input_shape[i]*stride[i] (for spatial dimensions only).
- Adds lit test for auto-padding.
- Tests are added by https://github.com/nod-ai/SHARK-TestSuite/pull/370
NOTE: ConvTranspose still doesn't support asymmetric padding, therefore multiple original onnx tests still won't pass.
=> Adds onnx ConvTranspose support for autopadding.

CMakeLists.txt, build_tools/python_deploy/build_windows_ci.sh
I'm trying to build python wheel for windows similar to as done for linux in https://github.com/llvm/torch-mlir-release/ however turns out the build process on windows is broken without the following fixes:
1. Building stablehlo for windows fails due to https://github.com/openxla/stablehlo/issues/1772 -- so disabling stablehlo in `build_windows_ci.sh` that will be used for building the python wheels. 
2. Add `USE_MATH_DEFINES` to resolve `torch-mlir\lib\Conversion\TorchOnnxToTorch\DefaultDomainGtoP.cpp(709): error C2065: 'M_LOG10E': undeclared identifier`
=> Disable building STABLEHLO and specify USE_MATH_DEFINES for windows builds.

include/torch-mlir/Dialect/Torch/Transforms/Passes.h, lib/Dialect/Torch/Transforms/Passes.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/python/torch_mlir_e2e_test/configs/onnx_backend.py, test/Dialect/Torch/torch-onnx-to-torch-backend-pipeline.mlir
This commit adds the torch-onnx-to-torch-backend pipeline which
converts the Torch Onnx IR to Torch Backend IR.
This commit also moves the `ScalarizeShapes` pass from the
`torch-backend-to-linalg-on-tensors-backend-pipeline` to the
`torch-onnx-to-torch-backend` pipeline since the primary goal of
this pass is to scalarize the shapes in the IR coming from the
Onnx models.
=> [MLIR][TORCH] Add torch-onnx-to-torch-backend pipeline

lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, test/Dialect/Torch/scalarize-shapes.mlir, test/Dialect/Torch/torch-onnx-to-torch-backend-pipeline.mlir
1. Propagates `aten.broadcast_to` ops of a single value to an `aten.full` op
2. Propagates arithmetic operations through a templated class which associates some tensor arithmetic ops to their integer-scalar counterparts. These are a major blocker right now, since some models have a bunch of rank 0 arithmetic being done with tensor ops. See the lit test for an interesting example that pads an input to the smallest shape which will become divisible by twelve in `dim0`. If you think this is convoluted, you haven't been staring at ONNX generated IR long enough.
3. Adds a stronger folder for `aten.eq.int` to fold `size.int == 0` to `false`. See the comment in that conversion pattern for more justification as to why it is acceptable to make this assumption here. This is another major blocker …
=> Add More Scalarize Shapes Patterns

lib/Conversion/TorchToLinalg/Linear.cpp, test/Conversion/TorchToLinalg/convolution.mlir
I've upstreamed the necessary quantized linalg Op with the "channel-first" ordering used by torch (https://github.com/llvm/llvm-project/pull/107740) for 2d convolution.
This patch changes the lowering for the quantized 2d case of `aten.convolution` accordingly, which saves three transpositions per convolution (input, weights, result) and therefore removes the requirement to try to optimize these away in downstream passes.
=> [TorchToLinalg] Use Op with native channel order for quantized conv2d

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Added autopad. and passed 3 tests 
test_maxpool_2d_precomputed_same_upper
test_maxpool_2d_same_lower'
test_maxpool_2d_same_upper
Address : https://github.com/nod-ai/SHARK-ModelDev/issues/843 
2 attributes yet to complete : storage_order, indices output
=> Added support for Maxpool (Autopad)

test/CAPI/torch.c
Compiling with clang 16.0 on macOS I have warnings about incorrect printf format (see below).
Values to be printed are `int64_t`, but they are printed with `%zu` and `%ld`, which are not portable way to print this type.
```
<...>/torch-mlir/test/CAPI/torch.c:52:3: warning: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'int64_t' (aka 'long long') [-Wformat]
52 |   DEFINE_CHECK(NonValueTensor)
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
<...>/torch-mlir/test/CAPI/torch.c:37:13: note: expanded from macro 'DEFINE_CHECK'
36 |     fprintf(stderr, #TTT "Type %s rank: %zu\n", testName,                      \
|                                         ~~~
37 |             torchMlirTorch##TTT##TypeGetRank(TTT##Type));                      \
| …
```
=> Fix clang warning about printf format

lib/Dialect/Torch/IR/TorchOps.cpp
Removes a boolean variable that is used only for an assertion, and inlines the condition into the assertion.
=> Remove variable used for only assertion

lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
- bumps llvm-project to https://github.com/llvm/llvm-project/commit/6c64c8a6f3f77c30745c751d4163ff6bf2fc323b
- bumps stablehlo to https://github.com/openxla/stablehlo/commit/6e403b1aa6a71f5eaa09cc720e4ad42f692745e6
- Updates type conversion materialization functions to return Value after API change in llvm-project.
=> Bump LLVM to llvm/llvm-project@6c64c8a6f3f7

lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
Addition of bools saturate which equates to an `or` operator. Updated to avoid some noticed downstream failures.
=> [linalg] Fix torch.aten.add of `torch.bool`

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
Attention often broadcasts a mask across the batch dimension as masking is usually performed the same across attention heads. Added this materialization to the mask dimensions optionally.
=> [linalg] Broadcast batch for mask on sdpa lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
Fixes https://github.com/nod-ai/SHARK-ModelDev/issues/696#issuecomment-2442016530
=> Fix onnx.If lowering with scalar condition tensor

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
The onnx ingest sometimes has poorly propagated shape information. E.g.:
```mlir
...
%9020 = torch.prims.squeeze %9010#1, %9019 : !torch.vtensor<[?,384,1],f32>, !torch.list<int> -> !torch.vtensor<[1,384],f32>
return %9015, %9020 : !torch.vtensor<[1,384],f32>, !torch.vtensor<[1,384],f32>
}
}
```
This occurred at the boundary of the onnx model `migraphx_bert__bert-large-uncased`. Evidently, the output value tensor info had more information than could be propagated forward. The `PrimsSqueeze` lowering was returning a `!torch.vtensor<[?,384],f32>` which was causing a type mismatch with the `func.return`.
=> Add an info cast to `prims.squeeze` decomposition

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Dialect/Torch/canonicalize.mlir
1. Clamps OOB start index to 0 in slice folder
2. Adds a more descriptive `emitError` in slice folder if the creation of the `DenseElementsAttr` would fail due to a bad result shape.
3. Fixes the `onnx.Shape` lowering to default to `inputRank` for `end` instead of `-1`. When `end==-1` the last element was missing when slicing.
=> Fix Slice Folder OOB Crash and onnx.Shape lowering

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
Add tosa::getConstTensor with int8_t template used in https://github.com/llvm/torch-mlir/pull/3827
=> Add tosa::getConstTensor with int8_t template

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir
- Add Torch to TOSA legalization for aten.as_strided op
- Update xfail_sets with the following:
+ New aten.as_strided results
+ Changes from this commit: https://github.com/llvm/torch-mlir/commit/7f9f99c6f8c84323d896b47fcd67c4bc668f6577
+ Failed tests from new PyTorch version update
- Add new LIT test to basic.mlir
Change-Id: I6f471ea116ca47f2bf9537b62950fce75a2c624f
=> [TOSA] Add legalization for aten.as_strided

include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h, lib/Conversion/TorchToStablehlo/GatherScatter.cpp, lib/Conversion/TorchToStablehlo/StablehloLegalizeUtils.cpp, projects/pt1/e2e_testing/xfail_sets.py
In torch.index_put like ops, `values` is only required to be broadcastable to `input[indices]`, rather than exact dimension match. This patch fixes the problem by add additional stablehlo.dynamic_broadcast_in_dim before creating stablehlo.scatter op. BTW, this patch also enhance the `getBroadcastResultShape` utility in hlo namespace.
=> [stablehlo] fix: enhance torch's index-like op lowering to stablehlo's gather/scatter

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
For the op `index_put_`, if accumulate == false, the behavior is undefined if the indicies aren't unique (https://pytorch.org/docs/stable/generated/torch.Tensor.index_put_.html). So, when converting `AtenIndexPutHackedTwinOp` to a TMTensor scatter op, mark the indices as unique if when `accumulate == false`.
This should have no functional effect (unless users are relying on UB) and assuming unique indices has the benefit of unlocking better optimizations in further compiler stages.
=> Create scatter op with unique indicies

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
- Refactors more "onnx.ReduceXXX" patterns through helper function.
- Fixes bug with iterating unconditionally on `output_dim == 1` during `dimList` inference.
This change results in passes for the following 11 models:
crossvit_15_240
crossvit_15_dagger_240
crossvit_15_dagger_408
crossvit_18_240
crossvit_18_dagger_240
crossvit_18_dagger_408
crossvit_9_240
crossvit_9_dagger_240
crossvit_base_240
crossvit_small_240
crossvit_tiny_240
=> [ONNX] rework some reduction op lowerings

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
This commit removes the equivalence check for kernel shape and weight shape from the Onnx.conv lowering since those checks seem to be of no use (not sure why were they part of the lowering in the first place).
=> [ONNX] Remove kernel shape and weight shape equivalence check from Onnx.Conv lowering

lib/Dialect/TorchConversion/Transforms/UnpackQuantTensor.cpp
This commit bumps the llvm-project to https://github.com/llvm/llvm-project/commit/813f7c3820d00349fe23bfc6ba26159764541540.
This commit also updates the usage of `APInt` in `unpack-quant-tensor` pass by explicitly setting the `implicitTrunc` arg to be `True` whose default value was changed from True to False here https://github.com/llvm/llvm-project/commit/3494ee95902cef62f767489802e469c58a13ea04.
=> Bump LLVM to 813f7c3

python/torch_mlir/tools/import_onnx/__main__.py
The method `onnx.load_external_data_for_model` function does not admit `pathlib.Path` as an input.
=> Fix a bug for large models in onnx importer.

lib/Conversion/TorchToLinalg/Utils.cpp, test/Conversion/TorchToLinalg/datamovement.mlir
This PR changes the lowering to use `linalg.transpose` instead of `linalg.generic` in `torch_to_linalg::permuteTensor`.
=> [TorchToLinalg] Use `linalg.transpose` instead of `generic` in `permuteTensor`

lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, test/Dialect/Torch/scalarize-shapes.mlir
Addresses a bug when trying to materialize a non fp64 attr to a constant float op in scalarize shapes.
=> convert to double before float materialization in scalarize shapes

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Dialect/Torch/decompose-complex-ops.mlir
Addresses <https://github.com/iree-org/iree/issues/19262#issue>
=> address uneccessary dynamic shapes in argmax decomposition

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
Fixes https://github.com/nod-ai/SHARK-ModelDev/issues/888
If stash_type is different from input_dtype/result_dtype:
1. convert x dtype to stash_type
2. calculate mean and var in stash_type since x is in stash_type already
3. convert back to result_dtype before stage two calculation
4. convert mean_dtype and var_dtype if they are different from stash_type
e2e test added in https://github.com/nod-ai/SHARK-TestSuite/pull/399
=> Support stash_type attribute for onnx.LayerNormalization

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Fixes `onnx.Pow(float,int)` and `Pow(int,float)` accuracy. Torch uses `double` internally to compute pow if one argument is integer and the other one is floating point (due to C++ promotion rules).
This PR keeps `onnx.Pow(int,int)` as is, which still produces numeric mismatches for values that overflow. torch uses a pure-integer implementation, where torch-mlir currently maps it to `Pow(float,float)`
=> aten.pow / onnx.Pow: Fix (float,int) / (int, float) accuracy

build_tools/ci/build_posix.sh
This commit disables the LTC build from the Torch-MLIR CI since after the recent GH runner version upgrade the Torch-MLIR build in CI is failing with an LTC related error.
The tracking issue for the same can be found here: https://github.com/llvm/torch-mlir/issues/3910
=> [CI] Disable LTC build from CI

python/torch_mlir/extras/onnx_importer.py
Dense Resources cannot have `-` characters as part of the resource keys. Many ONNX models, however, do have these characters in `TensorProto` or initializer names.
This patch adds an unconditional replace function in the sanitization of initializer names that replaces all `-` characters with `_` (underscores) when the dense resources are created, which allows successful parsing of the IR.
In case the name was legal before sanitization, the function has no effect. Unnecessary additional time complexity is avoided by omitting an `if` condition to check containment.
=> [onnx][importer] Sanitize '-' characters in TensorProto names

python/torch_mlir/extras/onnx_importer.py
Refactors https://github.com/llvm/torch-mlir/pull/3901 by merging illegal character sanitization into the regex and removing call to `replace()`.
=> [onnx][importer] Merge character sanitization into regex

.github/actions/setup-build/action.yml, .github/workflows/RollPyTorch.yml, .github/workflows/bazelBuildAndTest.yml, .github/workflows/buildRelease.yml, .github/workflows/gh-pages-releases.yml, .github/workflows/merge-rollpytorch.yml, .github/workflows/oneshotSnapshotPackage.yml, .github/workflows/pre-commit-all.yml, .github/workflows/pre-commit.yml, .github/workflows/releaseSnapshotPackage.yml
This pins and updates most actions. The PR is limited to those actions that seem actively maintained and updated. The actions left unpined should be reevaluated and eventually replaced with other actions. The rational for pinning actions is to follow the suggestions by OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.
=> Pin and update actions

.github/workflows/bazelBuildAndTest.yml, .github/workflows/buildRelease.yml, .github/workflows/gh-pages-releases.yml, .github/workflows/merge-rollpytorch.yml, .github/workflows/pre-commit-all.yml, .github/workflows/pre-commit.yml, .github/workflows/releaseSnapshotPackage.yml
While `ubuntu-latest` uses Ubuntu 22.04 for now, thils will change soon (rollout already started), see
https://github.com/actions/runner-images/issues/10636. The version can be updated from 22.04 to 24.04 in a follow up.
=> Replace `ubuntu-latest` with specific version

.github/workflows/oneshotSnapshotPackage.yml, .github/workflows/releaseSnapshotPackage.yml
This replaces the `actions/create-release` with
`ncipollo/release-action` as the former is unmaintained.
=> Replace unmaintained `create-release` action

include/torch-mlir/Conversion/TorchToTosa/TorchToTosa.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp
This PR refactors TorchToTosa to separate the construction of legal/illegal ops and conversion patterns in their own functions:
1. populateTorchToTosaConversionLegalOps -- populate any ops that are legal after the conversion pass
2. populateTorchToTosaConversionIllegalOps -- populate any ops that are illegal after the conversion pass
3. populateTorchToTosaConversionPatterns -- populate the ops conversion patterns
Currently the (il)legality of the ops that are (il)legal after the conversion pass runs is embedded within the conversion pattern. Our end goal is to write a new pass pipeline that converts `torch` ops to a mix of `tosa`, `linalg`, `tensor`, etc dialect ops. The reason we want to also emit `tosa` ops (instead of using the existing `TorchToLinalg` to emit `linalg`+`tensor`+...) is …
=> [TorchToTosa] Refactoring to separate construction of legal/illegal ops and conversion patterns.

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The onnx output tensor has a shape of ((n, z)), where (n) is the number of dimensions in the input tensor and (z) is the number of non-zero elements2. This is different from PyTorch's default behavior, where the dimensions are reversed.
This help to debug decompose torch.nonzero https://github.com/llvm/torch-mlir/pull/3876
=> [ONNX] Fix nonzero output type difference  between onnx and torch

lib/InitAll.cpp
We incorrectly relied on the fact that StableHLO registers the sparse tensor dialect, but when building for e.g. just LinAlg, the dependency was missing. This fixes this shortcoming.
FIXES: https://github.com/llvm/torch-mlir/issues/3816
=> [torch-mlir][sparse] register sparse tensor dialect for all rewriting

lib/Conversion/TorchToLinalg/Linear.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
Batch matmul was using the result type as the accumulator. Updated to use the preferred accumulator based on input type.
=> [torch] Update `torch.bmm` to use accumulator type

README.md
Rationale:
In addition to IREE and Blade, MPACT provides an MLIR-based example of a PyTorch compiler that uses TORCH-MLIR. It also illustrates propagating sparsity from sparse PyTorch into MLIR, a feature that is not widespread in DL compilers yet.
=> [torch-mlir] add MPACT as an example torch-mlir based compiler

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/reshape_like.py, test/Conversion/TorchToTosa/basic.mlir
* Add Torch to TOSA legalization for torch.aten.unfold
* Update e2e results in xfail_sets.py
* Fix a minor detail in one of the unfold e2e tests
* Add LIT tests for aten.unfold
Change-Id: I6583019d1c2569bdaf9f0b67cf44b33067448af7
=> [TOSA] Add legalization for torch.aten.unfold

docs/add_ops.md
- removes section regarding Turbine Camp
- Each line of detail either:
- already existed internally in Confluence
OR
- was severely out of date!
- Was beyond the concerns of Torch-MLIR
- adjusts link to LLVM style guide
- was directed to a specific style guide rule rather than the start of the style guide in general
- adds missing h2
- cleans up style using markdown linter
- prefers formatted links over intentionally bare URLs
- enforces explicitly-define language in code blocks
- prefers implicitly-ordered, 1-based lists
- avoids less-common 0-based lists since that would require deviation from the default linter config
- wraps bare urls/emails
- enforces unordered list nested indentation
- enforces space around headers
- enforces space around code fence blocks
- removes extraneous blank …
=> [docs] Refresh add_ops.md

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/scatter.py
To fix https://github.com/nod-ai/SHARK-ModelDev/issues/898.The issue arise from arith::trunci i1 to i64. Should use  arith.extui instead.
- arith::trunci: The integer truncation operation takes an integer input of width M and an integer destination type of width N. The destination bit-width must be smaller than the **input bit-width (N < M)**. The top-most (N - M) bits of the input are discarded.
Also add dynamic e2e test for aten.scatter_add op in passing.
Follow up of onnx.Compress op https://github.com/nod-ai/SHARK-ModelDev/issues/893#issuecomment-2574158920
```
torch-mlir-opt -pass-pipeline='builtin.module(torch-onnx-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints,aten.unflatten.int})' ./compress.onnx.mlir > compress.torch.mlir
(mlir_venv) (test_suite.venv) ➜ …
```
=> [TMTensor] Cast i1 to i32by extsi instead of trunci for aten scatter_add

python/torch_mlir/compiler_utils.py, python/torch_mlir/fx.py
This PR makes module imports relative in `fx.py` and `compiler_utils.py`. When torch-mlir python package is embedded into python package of other MLIR based project, there won't be `torch_mlir` top level package for absolute import.
=> [python] Make module imports relative in `fx.py` and `compiler_utils.py`

CMakeLists.txt
This MR enables `torch_mlir` project to accept path to external stablehlo and include those directories. This in turn enables `torch_mlir` to be part of bigger compiler project when `stablehlo` is already a
dependency.
=> [cmake] Enable accepting external stablehlo project

include/torch-mlir/Dialect/Torch/IR/TorchOps.td
=> Clarify `min_val` semantics for `torch.symbolic_int` op

.github/workflows/ci.yml, build_tools/ci/build_posix.sh, build_tools/ci/install_python_deps.sh, build_tools/ci/test_posix.sh, build_tools/update_abstract_interp_lib.sh, build_tools/update_torch_ods.sh, test/python/compile.py
This commit contains the ccache and python changes neccessary to migrate the ci.yml workflow to an azure kubernetes cpubuilder cluster.
Timings before and after the infra change are in the same ballpark (~10 mins).
Previously, `test/python/compile.py` was unnecessarily excluding the python site packages, which needed to be changed for the cluster.
We also make use of `hendrikmuhs/ccache-action` now and use a key of `${{ github.job }}-${{ matrix.torch-version }}` which works as intended: https://github.com/llvm/torch-mlir/actions/runs/12828039126/job/35771248056#step:7:4657
=> Migrate ci.yml to AKS cpubuilder cluster.

python/CMakeLists.txt, python/torch_mlir/tools/opt/__main__.py, setup.py
This adds the `torch-mlir-opt` tool to the Python wheels, which allows to use the commandline tool via a pip installed package instead of having to compile the torch-mlir project yourself. The executable is still installed to the deault location and copied over via the `setup.py` to be included in the Python wheel. This could be refactored and handled within CMake in a follow-up.
=> Include `torch-mlir-opt` in Python wheels

setup.py
Due to the wrong entry point, calling `torch-mlir-import-onnx` currently fails with
```
$ torch-mlir-import-onnx
File "venv-torch/bin/torch-mlir-import-onnx", line 5, in <module>
from torch_mlir.tools.import_onnx import _cli_main
ImportError: cannot import name '_cli_main' from 'torch_mlir.tools.import_onnx' (unknown location)
```
=> Fix `torch-mlir-import-onnx` entry point

.github/workflows/ci.yml
Pins the actions to a specific version and hash. The rational for pinning actions is to follow the suggestions by OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.
=> Pin `actions/cache/{restore,save}` actions

lib/Conversion/Utils/Utils.cpp, test/Conversion/TorchToLinalg/elementwise.mlir
To fix issue https://github.com/llvm/torch-mlir/issues/3962 : 'arith.extf' op operand type 'bf16' and result type 'f16' are cast incompatible
=> [Linalg] Add conversion between bf16 and f16 

python/torch_mlir/fx.py
Added `backend-legal-ops` argument in `fx.import_and_export` to stop decomposition of certain torch ops.  This PR is based on this [issue](https://github.com/llvm/torch-mlir/issues/3953)
=> Backend-legal-ops argument for fx lowering

build_tools/python_deploy/build_linux_packages.sh, docs/development.md
Drops Python 3.8, which is EOL, see
https://devguide.python.org/versions/, and adds Python 3.12, which is the default e.g. on Ubuntu 24.04 LTS.
=> Update default Python versions

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
When center_point_box=1, the supplied boxes come with a format of [x_center, y_center, width, height], this patch converts the format into [x1, y1, x2, y2] format before they are consumed.
The e2e test is added in nod-ai/SHARK-TestSuite#436
=> Add center_point_box=1 support in NonMaxSuppression.

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
The `or`/`and` alternate spellings are not supported on all compilers without additinoal flags (https://learn.microsoft.com/en-us/cpp/cpp/logical-or-operator-pipe-pipe?view=msvc-170#operator-keyword-for-).
This code started producing errors in the downstream IREE project when building with MSVC on Windows: https://github.com/iree-org/iree/actions/runs/12985792116/job/36211327035#step:9:7446
```
[6452/8792] Building CXX object compiler\plugins\input\Torch\torch-mlir\CMakeFiles\iree_compiler_plugins_input_Torch_torch-mlir_TorchDialectPasses.objects.dir\__\__\__\__\__\third_party\torch-mlir\lib\Dialect\Torch\Transforms\DecomposeComplexOps.cpp.obj
FAILED: compiler/plugins/input/Torch/torch-mlir/CMakeFiles/iree_compiler_plugins_input_Torch_torch-mlir_TorchDialectPasses.objects.dir/__/__/__/__/_ …
```
=> Fix logical `or`/`and` usage for MSVC compilation.

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, lib/Dialect/TMTensor/Transforms/Bufferize.cpp, lib/Dialect/TMTensor/Transforms/ConvertToLoops.cpp, lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp, lib/Dialect/Torch/Transforms/MatchQuantizedOps.cpp, lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp, lib/Dialect/Torch/Transforms/PrepareForGlobalizeObjectGraph.cpp, lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RestructureNonConstantAxes.cpp, lib/Dialect/Torch/Transforms/ScalarizeShapes.cpp, lib/Dialect/Torch/Transforms/SimplifyDtypeCalculations.cpp, lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp, lib/Dialect/Torch/Utils/Utils.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversionPasses.cpp, lib/Dialect/TorchConversion/Transforms/UnpackQuantTensor.cpp, lib/RefBackend/RefBackend.cpp, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/Conversion/TorchToTosa/basic.mlir, test/Dialect/TMTensor/bufferize.mlir, test/Dialect/Torch/adjust-calling-conventions.mlir, test/RefBackend/mlprogram-bufferize.mlir
Update LLVM to
https://github.com/llvm/llvm-project/commit/e2402615a5a76d46a433dfcc1de10b38a1263c9d
Update StableHlo to
https://github.com/openxla/stablehlo/commit/8cd9444b78ccec3e42a4b21105a5a547c021e823
Updates API calls from:
1. `applyPatternsAndFoldGreedily` -> `applyPatternsGreedily`
2. `applyOpPatternsAndFold` -> `applyOpPatternsGreedily`
This commit also inlines the `BufferizeTypeConverter` in Torch-MLIR
which has been removed from the LLVM project here:
https://github.com/llvm/llvm-project/commit/2ff2e871f5e632ea493efaf4f2192f8b18a54ab1.
This commit also updates the `AdjustCallingConventions` pass in order to
align with the changes made for `TypeConverter` upstream. Some of the
tests from the `adjust-calling-conventions.mlir` are disabled for the
time being since they are not …
=> Integrate LLVM at e2402615a5a76d46a433dfcc1de10b38a1263c9d

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, lib/Dialect/Torch/Utils/Utils.cpp, test/Conversion/TorchToTosa/basic.mlir
Update llvm-project to 5d6d982df61d16b6d498e6d59dd91c059679d3d8
Update stablehlo to b62dc66da9946b4c400c0d99c9d5bb8e04edaee6
Co-authored-by: Justin Ngo <justin.ngo@arm.com>
=> Bump llvm to llvm/llvm-project@5d6d982

build-requirements.txt
Reverting this commit since the package is required and is not a reason for failure here: https://github.com/llvm/torch-mlir-release/actions/runs/13067265659
Reverts llvm/torch-mlir#3997
=> Revert "Revert "[BUILD] Add nanobind to build-requirements""

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py, test/Conversion/TorchToLinalg/constraints.mlir, test/Dialect/Torch/decompose-complex-ops.mlir
1. aten::sym_constrain_range
2. aten::sym_constrain_range_for_size
3. aten::_assert_scalar
=> [torch-mlir] Support lowering of aten constraint ops

projects/ltc/csrc/base_lazy_backend/shape_inference.cpp
Added required but missing Shape inference for `aten.prod`
=> Missing Shape Inference for Prod

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
A preliminary refactor to support #3945 
- extracts several new helper functions
- removes cruft
=> refactor(ONNX): replaces `getValueList` helper with `createScalarSublist`

lib/Conversion/TorchToTosa/TorchToTosa.cpp
```
[build] D:\dev\projects\iree\third_party\torch-mlir\lib\Conversion\TorchToTosa\TorchToTosa.cpp(3498): warning C4305: 'argument': truncation from 'double' to 'const T'
[build]         with
[build]         [
[build]             T=float
[build]         ]
[build] D:\dev\projects\iree\third_party\torch-mlir\lib\Conversion\TorchToTosa\TorchToTosa.cpp(3504): warning C4305: 'argument': truncation from 'double' to 'const T'
[build]         with
[build]         [
[build]             T=float
[build]         ]
```
(Not sure why the half/one/three lines were warning free, might as well fix them too.
=> Fix some type conversion warnings on MSVC.

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
=> fix(ONNX): avoids resizing unsupported dimensions 

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
Uses `llvm_unreachable` to mark path unreachable to fix compiler error
```
DefaultDomainQtoZ.cpp:194:1: error: non-void function does not return a value in all control paths
```
=> Fix no return in NDEBUG builds

python/torch_mlir/extras/fx_importer.py
Fixes https://github.com/iree-org/iree-turbine/issues/281.
**_TL;DR:_**
The `weakref.finalize` objects cause the model parameters to be kept in memory in-between consecutive `aot.export` calls in the same process. We remove them to enable releasing the memory, this does not change the behavior of `RefTracker` or `RefMapping` classes anyhow else.
=> [FxImporter] remove weakref finalizer of reftracker

build_tools/autogen_ltc_backend.py
I fixed two calls to yaml.load to explicitly use the Safe Loader.  I copied the code from other repos that do it this way.
=> Augmented calls to yaml.load to use the safe loader.

lib/Conversion/TorchToArith/TorchToArith.cpp
Addresses an issue introduced by <https://github.com/llvm/torch-mlir/pull/3945> in an external test suite.
=> [TorchToArith] Add a lowering for `AtenEqFloat`

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h, include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, test/Conversion/TorchToTosa/basic.mlir, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir, test/python/fx_importer/v2.3/mutation_import.py
Update LLVM to https://github.com/llvm/llvm-project/commit/a854c266b98468ad4479a7d3c56a3fa76437e30d
TOSA Updates Summary:
[TOSA] Update tosa.mul's shift as input
[TOSA] Update tosa.slice's start and size to !tosa.shape type
[TOSA] Refactor: Use tosaCastTensorToType() function to create tosa.cast
---------
Signed-off-by: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>
Co-authored-by: Justin Ngo <justin.ngo@arm.com>
=> Integrate LLVM at a854c266b98468ad4479a7d3c56a3fa76437e30d

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
Pure floating point pow operations no-longer support negative base values (see <https://github.com/llvm/llvm-project/pull/126338>), but many models coming from ONNX use floating point representations of integers as the exponent. 
This change:
1. matches on constant rank-0 exponents and converts them to scalar constants.
2. matches on constant floating-point scalar exponents and converts them to ints if possible. 
3. lowers `Tensor(float)^int` cases to `math.fpowi` 
Addresses some remaining test failures related to <https://github.com/iree-org/iree/issues/19996>.
=> Convert float exponents in `aten.pow` to int when possible

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
No appreciable difference between the lower opset version and the newer one. See
<https://onnx.ai/onnx/operators/onnx__Greater.html> and <https://onnx.ai/onnx/operators/onnx__Gather.html>
=> [ONNX] reduce min opset versions for Greater and Gather

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/pooling.py, test/Conversion/TorchToTosa/basic.mlir
This PR fixes two issues:
1. Avg(Max)Pool2d allows (C, H, W) as input which causes a failure when creating `tosa.avg_pool2d` or `tosa.max_pool2d` as those ops expects 4D (N, H, W, C) tensor. Fix is to add a N=1 dimension before creating the tosa ops.
2. Avg(Max)Pool2d also allows kernel/stride to be specified as a tuple of single int, in which case the value is repeated for both H and W dims. This is currently not handled as well causing a segv when trying to access `kernel[1]/stride[1]`. Fix is to expand `kernel/stride` to be size 2 by repeating the first element.
=> [tosa] : Handle CHW input for avgpool2d.

lib/Dialect/TorchConversion/Transforms/UnpackQuantTensor.cpp, projects/jit_ir_common/csrc/jit_ir_importer/mlir_utils.h
ubsan detected 'lib/Dialect/TorchConversion/Transforms/UnpackQuantTensor.cpp:109:21: runtime error: left shift of negative value -16' and asan detected `memcpy` with nullptr when we passed and empty vector with `.data() == nullptr` to mlirOperationStateAddResults.
Detected using https://github.com/llvm/torch-mlir/pull/4046
=> Fix sanitizers issues

docs/development.md
- splits CLI commands so copy button can be used individually
- nests details for step 3 accordingly
=> [docs] Restructure the "Clone the Repository" section

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
When broadcasting the mask we need to use the query shapes and not the keys. This is due to the key for GQA having different batch dimensions than the expanded output.
=> [linalg] Use query shapes for attention broadcast

lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp, test/Dialect/Torch/adjust-calling-conventions.mlir
This PR updates AdjustCallingConventionsPass to the dialect conversion framework API updates introduced in https://github.com/llvm/llvm-project/pull/116470. This may not be an optimal use of the new API, but it is functional. Suggestions welcome!
fixes #3983
=> Re-enable torch-adjust-calling-conventions tests

python/torch_mlir/extras/onnx_importer.py, test/python/onnx_importer/constants.py
Currently the shape and element type of boolean tensor attributes are incorrect, since they use the shape/dtype of the packed numpy array rather than of the original tensor value. Specifying the shape and element type explicitly resolves this.
=> [ONNX] Fix import of boolean tensor constants

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/Conversion/TorchToTosa/basic.mlir, test/python/fx_importer/sparsity/sparse_test.py
Update LLVM to https://github.com/llvm/torch-mlir/commit/b0b70577610ec65606b27ec8992ef0350e78a6a8
This commit replaces the use of `buffer-deallocation` pass with the `buffer-deallocation-pipeline` as specified here:  https://discourse.llvm.org/t/psa-bufferization-new-buffer-deallocation-pipeline/73375#migration-guide-1.
Also, this commit disables the failing sparsity tests.
TOSA Updates Summary:
1. [TOSA] Update tosa.clamp's min/max pair
* Update tosa.clamp's `min` and `max` according to TOSA 1.0 spec:
https://www.mlplatform.org/tosa/tosa_spec.html#_clamp
* Update LIT tests
Signed-off-by: Justin Ngo <justin.ngo@arm.com>
Change-Id: I6013c440c08f7c37f11ef4b5f46cbce1a3fae54f
2. [TOSA] Update tosa.resize's scale, offset, border as inputs
* In TOSA 1.0, tosa.resize's scale, offset, and border …
=> Integrate LLVM at b0b70577610ec65606b27ec8992ef0350e78a6a8

projects/ltc/csrc/base_lazy_backend/shape_inference.cpp
PR adds support for `aten.randn.generator`, the generator object (if passed) will not affect shape inference.
=> Update shape_inference.cpp for randn.generator

lib/Conversion/TorchToLinalg/DataMovement.cpp
Add runtime asserts to check padding constraints of aten.reflection.pad_2d for dynamic dims
=> Add runtime asserts for aten.reflection.pad_2d

lib/Conversion/TorchToLinalg/Utils.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Conversion/TorchToLinalg/broadcast.mlir
Not all dimensions in `torch.repeat` may need to be broadcasted. Skip unsqueezing and flattening these dimensions together.
=> [torch] Rework `torch.repeat` to not broadcast unary case

lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir
Update LLVM to https://github.com/llvm/llvm-project/commit/6d847b1aada50d59c3e29f2e7eff779c0ee8182c
TOSA Updates Summary:
1: [TOSA] Update tosa.transpose's perms as attributes
Update tosa.transpose's perms to attributes according to TOSA 1.0
Update LIT tests
2: [TOSA] Rename ReduceProd to ReduceProduct
Update ReduceProd name to ReduceProduct in align with TOSA 1.0 spec
3: [TOSA] Change PadOp's pad_const to rank 1
Require PadOp's pad_const to be rank 1 in align with TOSA 1.0 spec
4: [TOSA] Generate correct parameters for conv ops
Bug fix: According to TOSA spec
(https://www.mlplatform.org/tosa/tosa_spec.html#_conv2d), full height and width values must be divisible by stride values. This commit adds checks for that divisibility and modifies pad values and/or slices input to generate …
=> Integrate LLVM at 6d847b1aada50d59c3e29f2e7eff779c0ee8182c

projects/pt1/python/torch_mlir_e2e_test/configs/fx_importer_backend.py, python/torch_mlir/fx.py
* make `verbose` (aka `-v`) option's behavior to be same with other backends. `verbose=True` would print the IR of each stage.
* clear `verbose` and `enable_ir_printing` option.
=> [test] refine fx_importer_backend with verbose option

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp, test/Dialect/Torch/decompose-complex-ops.mlir
This commit adds the support for handling the cases when any result of the convolution backward op is none.
This commit also adds the support for handling none results in SimplifyShapeCalculations pass.
=> [MLIR][TORCH] Add support for none result for convolution_backward op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit extends the OnnxToTorch Lowering for Onnx.QLinearMatMul op by adding the support for per-column quantization for the input argument `b`.
Since the `QuantizedMatmulOp` in the downstream pipeline ("Linalg") does not support the per-column (per-channel) quantization for the input arg `b`, hence we add the support by performing matmul over the dequantized inputs i.e., `a` and `b` and then quantizing the output.
Fixes https://github.com/nod-ai/SHARK-ModelDev/issues/916.
Signed-off-by: Vivek Khandelwal vivekkhandelwal1424@gmail.com
=> [ONNX] Add per-column quantization support for Onnx.QLinearMatMul op

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/torchscript.py, projects/pt1/python/torch_mlir_e2e_test/configs/fx_importer_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/jit_importer_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/torchdynamo.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/pooling.py
* also move `backend_legal_ops` into `fx_importer_backend` and `jit_importer_backend`, so that `onnx/fx/jit` importer test maintain their own `backend_legal_ops` config.
* TODO: unify different `backend_legal_ops` into one.
=> support decomposition of aten.adaptive_max_pool2d

lib/Dialect/Torch/IR/TorchOps.cpp
Fixes the following warning when compiling with gcc 11.4:
```
torch-mlir/lib/Dialect/Torch/IR/TorchOps.cpp:4111:42: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
4111 |            (stride < 0 && begin > limit) &&
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
4112 |                "aten.slice.Tensor iteration args are statically invalid.");
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix warning on parentheses around ‘&&’ within ‘||’

docs/development.md
- Makes the "in-tree" and "out-of-tree" LLVM contexts adjacent to each other
=> [docs] Move extra cmake command options in development.md

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Handle dynamic shaped inputs for "onnx.Conv" operator. This is required for some of the onnx zoo models which have dynamic shaped inputs for conv. Currently, only static inputs are being handled for the same.
=> [ONNX] Handle dynamic shaped inputs for conv

include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Utils/Utils.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/constant_alloc.py, test/Dialect/Torch/decompose-complex-ops.mlir
Prior to the change in this PR `torch-mlir-opt --convert-torch-to-linalg` was running into the following error:
```
error: 'tensor.cast' op operand type 'tensor<200x200x26xf32>' and result type 'tensor<200x200x26xf64>' are cast incompatible
%1 = torch.aten.empty.memory_format %0, %none, %none, %none, %false, %none : !torch.list<int>, !torch.none, !torch.none, !torch.none, !torch.bool, !torch.none -> !torch.vtensor<[200,200,26],f64>
^
note: see current operation: %12 = "tensor.cast"(%11) : (tensor<200x200x26xf32>) -> tensor<200x200x26xf64
```
This is because when `dtype` of the `aten.empty.memory_format` is `none`, by default `f32` was being selected as the element type of the resulting tensor which doesn't match with the actual element type of the result.
=> Use op.dtype to create aten.empty.memory_format during decomposition.

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/Conversion/TorchToLinalg/datamovement.mlir
"aten.reflection_pad2d" was lowered to linalg using affine maps of the form {indexing_maps = [affine_map<(d0, d1) -> (d0, -d1 + 1)>, affine_map<(d0, d1) -> (d0, d1)>]}. 
This causes lowering issues in downstream passes such as ""BinaryOpExpr(AffineBinaryOpExpr): Assertion `cast(expr.getRHS()).getValue() > 0 && "nonpositive multiplying coefficient"' failed."
Using linalg.index with tensor.extract op instead of the above affine map helps in successful compilation of the same.
=> Use linalg.index to lower aten.reflection_pad2d

lib/Conversion/TorchToLinalg/Utils.cpp, test/Conversion/TorchToLinalg/elementwise.mlir
This change is made to reduce the pattern-matching load for fusing elementwise generic ops with non-broadcasting unit dims. 
For example, adding tensors with shapes `[6,1]` and `[1]`, the output shape will be `[6,1]`. Before this change, the indexing maps were inconsistent between the inputs and outputs for the unit-dim (constant 0 for inputs, and a dim expression for the output).
=> [TorchToLinalg] simplify non-broadcast unit dim indexing maps in elementise generics

include/torch-mlir/Conversion/Passes.td, include/torch-mlir/Conversion/TorchToTosa/TorchToTosa.h, include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp
Add "require-full-tosa-conversion" option to TorchToTosa pipeline pass. The default option is "true". When this option is set to "false", models with non-legalized aten ops can still be partially converted with a mixed of Torch and TOSA ops in the IR.
Example usage:
"builtin.module(torch-backend-to-tosa-backend-pipeline{require-full-tosa-conversion=false})"
=> [TOSA] TorchToTosa option to emit partial conversion with Torch IR

lib/Conversion/TorchToStablehlo/CMakeLists.txt, lib/Conversion/TorchToStablehlo/PopulatePatterns.h, lib/Conversion/TorchToStablehlo/TorchToStablehlo.cpp, lib/Conversion/TorchToStablehlo/Uncategorized.cpp, test/Conversion/TorchToStablehlo/quantization.mlir
The following changes have been introduced in the PR
1. Onnx to torch-mlir conversion for per channel quantization/dequantization.
2. Torch-mlir to stablehlo conversion for per tensor quantization/dequantization.
3. Torch-mlir to stablehlo conversion for per channel quantization/dequantization.
=> Add support for Quantization/Dequantization

docs/development.md
- the use-case for this doc leans more toward "development" rather than "release"
- ergo, debugging flags should be assumed rather than suggested
=> [docs] Include MLIR debugging by default in development.md

python/torch_mlir/extras/onnx_importer.py, python/torch_mlir/tools/import_onnx/__main__.py
As per title. Changes tested on SHARK-TestSuite's `alt_e2eshark`.
=> [onnx_importer.py] Fix dim_value None not correctly processed and missing Float8E4M3FNUZType.

docs/development.md
- emphasize the common options between "in-tree extended", "in-of-tree base", and "out-of-tree"
=> [docs] Rearrange cmake configuration options in development.md

docs/development.md
- include prerequisite
- number the steps
- put "vanilla" command first
- separate fenced code blocks to leverage GitHub's copy button
=> [docs] Restructure the "Initiate Build" section in development.md

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds the support for non-scalar zero points for Onnx->Torch lowering of MatmulInteger op.
=> [ONNX] Add support for non-scalar zero points for Onnx.MatmulInteger op

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, lib/Conversion/TorchOnnxToTorch/ComMicrosoftDomain.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the Onnx->Torch lowering for [Onnx.QLinearLeakyRelu](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.QLinearLeakyRelu) op.
=> [ONNX] Add support for Onnx.QLinearLeakyRelu op

lib/Conversion/TorchOnnxToTorch/ComMicrosoftDomain.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the Onnx->Torch lowering for [Onnx.QLinearConcat](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.QLinearConcat) op.
=> [ONNX] Add support for Onnx.QLinearConcat op

lib/Conversion/TorchOnnxToTorch/ComMicrosoftDomain.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the Onnx->Torch lowering for Onnx.[QLinearGlobalAveragePool](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#commicrosoftqlinearglobalaveragepool) op.
=> [ONNX] Add support for Onnx.QLinearGlobalAveragePool op

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir, test/Conversion/TorchToTosa/torch-backend-to-tosa-backend-pipeline.mlir, test/Dialect/Torch/invalid.mlir
Update LLVM to https://github.com/llvm/llvm-project/commit/72144d119a7291f8b6b8e022a2947fbe31e66afc
TOSA Updates Summary:
1: [TOSA] Update rescale input_/output_zp and double_round attribute
Update tosa.rescale input_/output_zp as inputs according to TOSA 1.0
Update double_round bool attribute to rounding_mode in alignment with
TOSA 1.0. rounding_mode supports "SINGLE_ROUND", "INEXACT_ROUND", and
"DOUBLE_ROUND". Existing double_round behaviours are mapped as followed:
double_round = true -> rounding_mode = "DOUBLE_ROUND"
double_round = false -> rounding_mode = "SINGLE_ROUND"
2: [TOSA] Update tosa.negate's zero-points to inputs
Update LIT tests and XFAIL sets
3: [TOSA] Update tosa.int_div to tosa.intdiv
Update LIT tests
---------
Signed-off-by: Vivek Khandelwal …
=> Integrate LLVM at 6d38dbf6eb56fd2b3399565af455de96a99ffa0f

docs/development.md
CMake issued a warning upon fresh configuration:
> Manually-specified variables were not used by the project:
>     LIBTORCH_CACHE
>     LIBTORCH_SRC_BUILD
>     LIBTORCH_VARIANT
=> [docs] Remove unused libtorch options

docs/development.md
- Adjust wording for optional cmake testing flags
- Make code snippet easier to copy/append to base command
=> [docs] Refresh cmake section for testing flags

lib/Conversion/TorchOnnxToTorch/ComMicrosoftDomain.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the Onnx->Torch lowering for
[Onnx.QLinearAveragePool](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.QLinearAveragePool) op.
=> [ONNX] Add support for Onnx.QLinearAveragePool op

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/pooling.py, test/Conversion/TorchToTosa/basic.mlir
TOSA requires (inputDim + padBefore + padAfter - kernel) to be fully divisible by stride. This update adds pad and input size modifications for pooling ops (AvgPool2d and MaxPool2d) to satisfy that requirement by TOSA.
=> [TOSA] Fix output size calculation for pool ops

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit modifies the Onnx.MatMulInteger op lowering to fix the Torch->Linalg lowering path of the op.
Fixes https://github.com/nod-ai/SHARK-ModelDev/issues/906.
=> [ONNX] Simplify Onnx.MatMulInteger op lowering

lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/e2e_testing/xfail_sets.py
Add the following passes to TorchBackendToTosaBackendPipeline:
- TosaLayerwiseConstantFoldPass: fold full-layer operations on TOSA consts
- TosaReduceTransposes: remove unnecessary TOSA transposes to reduce data movements
=> [TOSA] Add TosaLayerwiseConstantFoldPass and TosaReduceTransposes passes

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Dialect/Torch/decompose-complex-ops.mlir
DecomposeAtenNativeLayerNormOp assumed that intermediate tensors (mean and rstd) had the same dtype as the input tensor, which is incorrect when inputs are BF16. The mean and rstd are computed in F32 even when inputs are BF16. This would result in emitting an invalid AtenExpandAsOp that changes the shape but also the dtype.
This patch inserts explicit AtenToDtypeOp casts to convert the intermediate mean and rsdt tensors back to BF16 before further broadcasting (AtenExpandAs).
=> [Torch] Fix dtype mismatch when decomposing AtenNativeLayerNormOp for BF16 types

CMakeLists.txt
The option enables the `-Werror` compiler flag, which turns warnings into errors, not errors into warnings.
=> Correct `TORCH_MLIR_ENABLE_WERROR_FLAG` help text

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Hi @sjarus, 
The motivation for this change is to help the internal MathWorks branch with the tosa-linalg pass. Without this change, `torch.aten.index.Tensor_hacked_twin` will fail when converting to tosa-linalg. With this change, the conversion succeeds.
This change adds a check during torch-to-tosa conversion for the `torch.aten.index.Tensor_hacked_twin` operation with dynamically-shaped inputs. With this change, torch-to-tosa conversion will throw
**failed to legalize operation 'torch.aten.index.Tensor_hacked_twin' that was explicitly marked illegal**
In torch-to-tosa conversion, `torch.aten.index.Tensor_hacked_twin` lowers to a series of operations including `tosa.gather`, which does not handle dynamic shape. (`torch.gather`, which also lowers to `tosa.gather`, errors out for dynamic …
=> [tosa] error out for dynamic shape input to Tensor_hacked_twin

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Fixes a bug where not all operands of `tosa.select` had same rank. Looked at other uses of `tosa.select` op in the code and they all looked correct to me.
=> [Tosa] : Equalize ranks for all operands for tosa.select + Slice conv inputs for dynamic batch as long as spatial dims are static.

lib/Conversion/TorchToStablehlo/Pooling.cpp, test/Conversion/TorchToStablehlo/pooling.mlir
Pytorch passes an argument `ceilMode` into MaxPool op.
Currently, torch to stablehlo conversion does not use it to determine stablehlo output shape.
This change intends to use the same logic as torch to use ceilMode when calculating output shape.
During conversion, we make up the size difference using padding.
Changes:
- Use `ceilMode` param the way torch uses it.
- Added tests for both floor and ceil cases.
=> Use ceilMode from pytorch MaxPool in shlo to get correct output shape

lib/Conversion/TorchToTosa/TorchToTosa.cpp
clang report warning for object lifetime issue
indexShape is ArrayRef and makeShapeTorchCompatible will return
SmallVector. The Vector will be destroyed before using indexShap.
```bash
torch-mlir/lib/Conversion/TorchToTosa/TorchToTosa.cpp:4232:18: warning: object backing the pointer indexShape will be destroyed at the end of the full-expression [-Wdangling-assignment-gsl]
4232 |     indexShape = makeShapeTorchCompatible({1});
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [tosa][NFC] fix ArrayRef lifetime issue for indexShap

projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir
Update LLVM to https://github.com/llvm/llvm-project/commit/03f616eb3acf1ae5a219ea247d9efe3cbfd41b59.
This commit also updates the tosa test related to aten.scatter op because of the op changes made in the downstream tosa.scatter op here: https://github.com/llvm/llvm-project/commit/c14078318c1fc6576dc301f8023a785ef98be112.
=> Integrate LLVM at 03f616eb3acf1ae5a219ea247d9efe3cbfd41b59

python/torch_mlir/extras/fx_importer.py
Adds support in fx_importer for:
- torch.float8_e5m2
- torch.float8_e4m3fn
- torch.float8_e5m2fnuz
- torch.float8_e4m3fnuz
=> Add float8 dtype support to FX importer

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
Going all the way to f64 is undesirable, especially for low-precision tensors in bf16 or f8 variants. Upcast only to the next type, e.g., bf16->f32 or f8->bf16. This is consistent with what Pytorch seems to be doing internally.
=> Upcast gradually when computing variance

lib/Conversion/TorchToLinalg/TensorConstructors.cpp, test/Conversion/TorchToLinalg/basic.mlir
The change refactors implementations of ReplicationPad1d/2d/3d to share common utility functions. The newly added utility function replicationPad takes numDims as input and does ReplicationPad for 1d/2d/3d
Fixes #4254
=> [TorchToLinalg] Refactor replication pad 1d/2d/3d to share common implementation

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/invalid_canonicalize.mlir
This fixes a SEGFAULT in the GreedyPatternRewriteDriver and adds a missing size check to the `torch.aten._assert_tensor_metadata` operation.
Erasing an operation during folding is not allowed. Folding the operation may eithermodify it in place or return a set of replacements, but may not erase the operation. (see https://github.com/llvm/llvm-project/blob/e56384ff540e68f9d0500fa27a95354c0730e37b/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L492-L508) 
Doing this causes a SEGFAULT (witnessed on macOS Sequoia 15.5, Apple M4):
```
Stack dump:
0.	Program arguments: build/bin/torch-mlir-opt -canonicalize --split-input-file -verify-diagnostics test/Dialect/Torch/invalid_canonicalize.mlir
#0 0x0000000104091524 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) …
```
=> lib/Dialect/Torch/IR/TorchOps.cpp: fix: use-after-free: erasing an operation during folding

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, test/Conversion/TorchToTMTensor/basic.mlir
Signed-off-by: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>
Co-authored-by: Kunwar Grover
=> [MLIR][TORCH] Undo indices conversion to `i32` for TMTensor ops

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
This commit adds the e2e support for the aten.as_strided op by decomposing it into a series of other torch operations.
Fixes https://github.com/llvm/torch-mlir/issues/4191.
The failing tests for Tosa config are tracked by https://github.com/llvm/torch-mlir/issues/4272.
=> [MLIR][TORCH] Add E2E support for aten.as_strided op

lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
Using `ConversionPatternRewriter::replaceAllUsesWith` + `ConversionPatternRewriter::eraseOp` is not supported at the moment, and will fail an assert after integrating https://github.com/llvm/llvm-project/commit/2929a2978cc3bdb0ff12a0e5d0a9236ff221f668.
The workaround is to use `replaceOp` instead, see: https://github.com/llvm/llvm-project/pull/155244#issuecomment-3272023121
=> Workaround for ConversionPatternRewriter::eraseOp issue

utils/bazel/docker/Dockerfile
This only fixes the failure in https://github.com/llvm/torch-mlir/actions/runs/17864459407/job/50803266616#step:6:1273, however, `bazel` builds have been failing for a long time due to https://github.com/llvm/torch-mlir/actions/runs/17758450172/job/50465645001#step:8:2688.
=> [CI] : Copy llvm python requirements.txt to bazel workdir.

build_tools/write_env_file.sh, docs/development.md
The documentation for setting the PYTHONPATH in development.md points to an incorrect directory. The python package is now located at `build/python_packages/torch-mlir` instead of `build/tools/torch-mlir/python_packages/torch_mlir`.
This commit corrects the path to help new users correctly set up their environment.
=> docs: Fix incorrect python package path in development.md

lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir_e2e_test/test_suite/type_conversion.py, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/decompose-complex-ops.mlir
This commit teaches `AtenToDtypeOp::fold` to constant-fold dtype conversions when the operand is a splat `DenseElementsAttr`.
Folding is done according to torch's rounding behavior, i.e.
* Bool: 0 and -0.0 → false; nonzero/NaN/±Inf → true.
* Float → Int: round toward zero.
* Int → Float: sign-aware, rmNearestTiesToEven.
* Float ↔ Float: use builtin `mlir::FloatType::getFloatSemantics()`.
* Int ↔ Int: use `zextOrTrunc` / `sextOrTrunc` based on source signedness.
Folding is only performed when `non_blocking == false`, `copy == false`, and `memory_format` is None.
=> [Torch] Fold `aten.to.dtype` on splat constants.
