README.md, docs/features.md
=> Update broken python test links.

.github/workflows/buildAndTest.yml, test/lit.cfg.py, tools/bash_helpers.sh
The RuntimeShlib.so now lives in /lib.
=> Fix build again

README.md, frontends/README.md, frontends/pytorch/README.md
* Adds/updates readmes with some notes about code organization and direction.
* Meant to prepare a space for upcoming integration of #30.
=> Create frontends/pytorch directory.

frontends/pytorch/docs/compatibility.md
* As reported by Bryce Arden on Discord.
=> Add compatibility notes regarding unpacking quantized weights.

tools/CMakeLists.txt, tools/bash_helpers.sh, tools/mnist-playground/CMakeLists.txt, tools/mnist-playground/README.md, tools/mnist-playground/fc.mlir, tools/mnist-playground/mnist-playground.cpp
This unblocks backend progress while the PyTorch frontend work is coming
online. Hopefully we can delete this soon.
See tools/mnist-playground/README.md for more context on what this tool
is for, next steps, and current status.
=> Add hopefully short-lived mnist-playground utility.

lib/Dialect/ATen/ATenToStd.cpp
Date:   Mon Oct 12 11:26:50 2020 -0700
=> Bump llvm-project to 820e65f9e2369d2990fde4b3e7cfceb64f0df9c8

test/Dialect/TCP/bufferize.mlir
More test coverage in light of the TCP_mul typo (fixed in 30adf9e6b0c1e94db38050a9e143f20a5a461d17).
=> Add TCP mul test

frontends/pytorch/examples/mul_maximum_e2e.py, include/npcomp/Backend/RefJIT/PythonModule.h, include/npcomp/Python/PybindUtils.h, lib/Backend/RefJIT/PythonModule.cpp, lib/Conversion/TCFToStd/TCFToStd.cpp, lib/RefBackend/RefBackend.cpp, python/CMakeLists.txt, python/NpcompModule.cpp, python/npcomp/compiler/generic/backend/refjit.py, python/npcomp/compiler/pytorch/backend/refjit.py
* A bit gross because I took the chance to upgrade all of the backend bits to the new MLIR Python bindings and we still co-mingle the old and new for now.
* Since the Python created PassManagers are configured for explicit nesting, I had to upgrade some of the pass pipelines to be explicit.
* The demo in mul_maximum_e2e.py now compiles, runs through PyTorch and through the JIT, prints and asserts the same results.
* I am not claiming that this is the prettiest API in this patch: consider that this is just directly using low-level APIs and there should be an intervening high level API.
* Requires upstream https://reviews.llvm.org/D91232
=> Repurpose numpy-compiler compiler/runtime flow for PyTorch.

.github/workflows/buildAndTest.yml
* Not sure why auto-detection is not working.
=> Make CMAKE_PATH_PREFIX explicit for now

docs/features.md
Point to correct files instead of 404's.
=> Update links in features.md

include/npcomp/Dialect/TCP/IR/TCPOps.td, lib/Dialect/TCP/Transforms/Bufferize.cpp, test/Dialect/TCP/bufferize.mlir, test/Dialect/TCP/ops.mlir, test/npcomp-run-mlir/pad.mlir, tools/npcomp-run-mlir/npcomp-run-mlir.cpp
Pads a tensor with a fill value along the borders of each dimension according to padding specifications.
=> Import TCP pad

frontends/pytorch/csrc/builder/module_builder.cpp
This is needed so that output shows up properly in a Jupyter notebook.
=> Add MLIR diagnostic handler that prints to `sys.stderr`.

frontends/pytorch/csrc/builder/acap_dispatch.cpp
Modify ACAP_Dispatch to work with latest pytorch
-Remove boxed from convolution's m.impl
-Use redispatch and constrainted keyset to replace deprecated
callwithdispatchkey
to track with this change: https://github.com/pytorch/pytorch/commit/2303c244fcce204bde4073b5266bb4cf62875668#diff-f735cd7aa68f15b624100cbc4bb3b5ea76ffc7c9d3bec3b0ccabaa09609e5319
Inputs are super welcomed! :)
=> adapt acap_dispatch to latest pytorch nightly ("1.9.0.dev20210215+cpu")

frontends/pytorch/csrc/builder/node_importer.cpp, frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp, frontends/pytorch/test/node_import/loop.py, frontends/pytorch/test/node_import/prim.py, include/npcomp/Dialect/Torch/IR/TorchOps.h, include/npcomp/Dialect/Torch/IR/TorchOps.td, lib/Dialect/Torch/IR/CMakeLists.txt, lib/Dialect/Torch/IR/TorchOps.cpp
recommend reviewing individual commits for clarity
=> progress towards resnet

frontends/pytorch/csrc/builder/node_importer.cpp, frontends/pytorch/test/node_import/prim.py, include/npcomp/Dialect/Torch/IR/TorchOps.td
* Add's basic support for the `prim::TupleUnpack` and the `prim::ListUnpack` operations. 
@silvasean
=> [prim] Add TorchScript import support for List|TupleUnpack

.github/workflows/buildAndTest.yml, frontends/pytorch/csrc/builder/module_builder.cpp, frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp, include/npcomp/Dialect/Basicpy/IR/BasicpyOps.td, include/npcomp/Dialect/Torch/IR/TorchOps.td, lib/Backend/RefJIT/CMakeLists.txt, lib/CAPI/CMakeLists.txt, lib/Dialect/ATen/Transforms/ATenLoweringPass.cpp, lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp, lib/RefBackend/JITHelpers/JITModule.cpp, python/npcomp/__init__.py, python/npcomp/dialects/_ods_common.py
Per MLIR Python API updates in https://reviews.llvm.org/D98096
=> Bump llvm-project to e31c77b

docs/roadmap.md
Hi folks, at the last npcomp community meeting, there was strong desire to have a published roadmap. Putting this up as a PR to literally collaborate on it in the PR -- all questions/feedback/contributions/etc. are encouraged!
=> Start of a roadmap.

frontends/pytorch/csrc/builder/ivalue_importer.cpp, frontends/pytorch/csrc/builder/node_importer.cpp, frontends/pytorch/e2e_testing/torchscript/main.py, frontends/pytorch/e2e_testing/torchscript/vision_models.py, frontends/pytorch/python/torch_mlir/torchscript/e2e_test/configs/ref_backend.py, frontends/pytorch/python/torch_mlir/torchscript/e2e_test/framework.py, frontends/pytorch/python/torch_mlir/torchscript/e2e_test/reporting.py, frontends/pytorch/test/node_import/loop.py, frontends/pytorch/test/node_import/prim.py, frontends/pytorch/test/torchscript_e2e_test/basic.py, frontends/pytorch/test/torchscript_e2e_test/miscompile.py, include/npcomp/Dialect/Torch/IR/TorchOps.td, include/npcomp/Dialect/Torch/Transforms/Passes.h, lib/Backend/Common/VerifyBackendContract.cpp, lib/Dialect/Torch/Transforms/CMakeLists.txt, lib/Dialect/Torch/Transforms/Passes.cpp, python/npcomp/compiler/pytorch/backend/frontend_lowering.py
We still can't compile it, but we can now import it and work on the bugs with a fairly ergonomic developer experience.
Recommended review order: commit by commit
=> Changes while working on ResNet18

docs/roadmaps/2021Q2.md, docs/roadmaps/2021Q3.md
This is an open discussion and review!
=> RFC: 2021Q3 roadmap

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
- Fold more for aten.gt.int, aten.ne.int and Aten__Getitem__TOp
- Some format cleaning up
=> More folding for aten.gt.int, aten.ne.int and Aten__Getitem__TOp.

include/npcomp/Conversion/Passes.td, include/npcomp/Conversion/TorchToSCF/TorchToSCF.h, lib/Conversion/CMakeLists.txt, lib/Conversion/Passes.cpp, lib/Conversion/TorchToSCF/CMakeLists.txt, lib/Conversion/TorchToSCF/TorchToSCF.cpp, lib/Dialect/Torch/Transforms/Passes.cpp, test/Conversion/TorchToSCF/basic.mlir
1. Add TorchToSCF pass.
2. Convert prim.If and prim.If.yield.
=> Add TorchToSCF pass.

.github/workflows/buildAndTest.yml
The underlying issue seems to be resolved now:
https://github.com/pytorch/pytorch/issues/60485
=> Undo CI pinning.

.github/workflows/buildAndTest.yml, tools/torchscript_e2e_test.sh
This includes IREE and RefBackend.
=> Add E2E tests to CI

frontends/pytorch/e2e_testing/torchscript/basic.py, frontends/pytorch/e2e_testing/torchscript/conv.py, frontends/pytorch/e2e_testing/torchscript/main.py, frontends/pytorch/e2e_testing/torchscript/xfail_sets.py, frontends/pytorch/python/torch_mlir/torchscript/e2e_test/reporting.py, include/npcomp/Dialect/Torch/IR/TorchOps.h, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/IR/TorchOps.cpp
1. Add m_TorchConstantIntList
2. Lowering for aten.conv2d
3. Lowering aten.AdaptiveAvgPool2d
=> Linalg lowering for aten.conv2d and aten.AdaptiveAvgPool2d

README.md, build_tools/write_env_file.sh
Add scripts for generating .env and update instructions in README.
=> Update readme and scripts for setting the new PYTHONPATH

frontends/pytorch/examples/torchscript_resnet18_e2e.py
Show an example of classifying image from
https://commons.wikimedia.org/wiki/File:YellowLabradorLooking_new.jpg
with Resnet18
=> Add an e2e example for Resnet18

frontends/pytorch/e2e_testing/torchscript/basic.py, frontends/pytorch/e2e_testing/torchscript/conv.py, frontends/pytorch/e2e_testing/torchscript/elementwise.py, frontends/pytorch/e2e_testing/torchscript/xfail_sets.py, frontends/pytorch/python/torch_mlir_torchscript/e2e_test/reporting.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/Passes.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Conversion/TorchToLinalg/flatten.mlir, test/Dialect/Torch/refine-types.mlir
- torch.aten.flatten.using_ints to linalg lowering
- torch.aten.max_pool2d to linalg lowering
- Support torch.aten.conv2d for more flexible dilation and strides values
=> Add torch.aten.flatten.using_ints and aten.MaxPool2d linalg lowering

frontends/pytorch/e2e_testing/torchscript/xfail_sets.py
All tests pass after https://github.com/google/iree/pull/6666 :)
=> Update IREE xfail sets.

CMakeLists.txt
Ninja generators transform `DEPFILE`s from `add_custom_command()`
since Cmake3.20
=> Deal with CMP0116

lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
* Requires patch https://reviews.llvm.org/D108527
=> Integrate from upstream.

frontends/pytorch/e2e_testing/torchscript/main.py, frontends/pytorch/python/torch_mlir_torchscript/e2e_test/framework.py
=> Make verbose testing also report compile/trace/run messages.

frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/refine-types.mlir
This should cover all the ops that are left in MT.
=> Refine types continue.

e2e_testing/torchscript/basic.py, external/torch-mlir/lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
This is the transpose.int lowering. There also seems to be one using Dimnames, but I'm not sure if that's in the scope of what I'm doing. Please let me know if I'm missing anything - this is my first PR to an LLVM project.
=> Added transpose lowering

external/torch-mlir/build_tools/update_torch_ods.sh
Fixes a couple of path issues that were missed in #311 .
=> Update update_torch_ods.sh to use new torch_mlir python layout

e2e_testing/torchscript/basic.py, e2e_testing/torchscript/xfail_sets.py, external/torch-mlir/lib/RefBackend/RefBackend.cpp, python/npcomp/compiler/pytorch/backend/refbackend.py, python/test/torchscript_e2e_test/runtime_failure.py, python/torch_support/npcomp_torchscript/e2e_test/framework.py, python/torch_support/npcomp_torchscript/e2e_test/reporting.py
=> Add i64 tensor argument support and bring back GatherModule_basic

README.md, build_tools/torchscript_e2e_heavydep_tests/README.md
Clean up the Readme.md to make it easy and focussed on checkout and build. 
Will update Demos next.
=> Updates to Readme.md

build_tools/build_standalone.sh, e2e_testing/torchscript/basic.py, e2e_testing/torchscript/xfail_sets.py, examples/torchfx/examples/example_add_tanh_sigmoid.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
This brings in the fix for the obscure RefBackend bug we were hitting.
=> Update llvm-project to 204d301bb1921431a853c0bfba32007c018df1d5

README.md
Makes some of the longer code blocks easier to parse.
=> Add shell markdown formatting to README.md

.gitignore, build_tools/build_python_wheels.sh, setup.py
Will add a CI job that builds and uploads snapshot packages next.
=> Bring back Python packaging.

e2e_testing/torchscript/elementwise.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
I feel like I'm doing something wrong with the amount of casts I have to do, but what I have is working. Please let me know if there's something I'm missing.
=> Add rsub.Scalar

e2e_testing/torchscript/elementwise.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
=> Lowered aten.sqrt to linalg

e2e_testing/torchscript/backprop.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
The e2e testing for aten_tanh_backward op has been added.
The testing is done for ref_backend.
=> Add e2e testing for aten_tanh_backward op.

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Add a bunch of op legalizations.
=> [tosa] Add structure for eltwise ops

include/torch-mlir/Dialect/Torch/IR/TorchTypes.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Conversion/TorchToSCF/TorchToSCF.cpp, lib/Conversion/TorchToStd/TorchToStd.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Dialect/Torch/IR/TorchTypes.cpp, lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp, lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp, lib/RefBackend/RefBackend.cpp, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
Update AsmPrinter/Parser and MatchAndRewrite
=> Update llvm upstream to 0b17336f793108a7b10c3fa913039144ef1d0f61

e2e_testing/torchscript/backprop.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
This commit adds minor non functional changes to the aten.gelu_backward
operation.
=> [NFC] Cleanup code for aten.gelu_backward operation.

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
Share code in `log_softmax_backward` and `softmax_backward` ops.
=> Refactor to share code in DecomposeComplexOps pass

e2e_testing/torchscript/basic.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
=> [TORCH][MLIR] Add E2E support for aten._softmax operation.

e2e_testing/torchscript/elementwise.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
Following the template of other recent additions.
=> Add leakyrelu support

e2e_testing/torchscript/main.py, e2e_testing/torchscript/scalar.py, lib/Conversion/TorchToStd/TorchToStd.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Conversion/TorchToStd/basic.mlir
I'm not super familiar with LIT testing, so if I did something weird there please lmk
=> add aten.add.int lowering in TorchToStd

e2e_testing/torchscript/basic.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
=> Add dropout op

e2e_testing/torchscript/xfail_sets.py, lib/Dialect/TorchConversion/Transforms/Passes.cpp
Fixes broken e2e test ElementwiseAddModule_basic
=> [tosa] Add TosaMakeBroadcastable pass to torch-to-tosa pipeline.

e2e_testing/torchscript/basic.py, e2e_testing/torchscript/elementwise.py, e2e_testing/torchscript/type_promotion.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
Mirrors the sub logic to provide type promotion for elementwise ops.
=> Add scalar type promotion for mul and div

e2e_testing/torchscript/xfail_sets.py, lib/Dialect/Torch/IR/TorchDialect.cpp
The external llvm is updated to point to
https://reviews.llvm.org/rG966b72098363d44adf2882b9c34fcdbe344ff913.
Some of the changes wrt. NamedAttr has been addressed.
=> Update external llvm.

e2e_testing/torchscript/basic.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp
This commit adds lowering of `aten.zeros` op.
=> [MLIR][TORCH] Add E2E support for aten.zeros op

lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
https://github.com/llvm/torch-mlir/pull/464#discussion_r765065092
=> [MLIR][Torch] Resolve styling issues related to aten zeros/ones op

e2e_testing/torchscript/index_select.py, e2e_testing/torchscript/main.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
This commit adds lowering of `aten.index_select` op.
=> [MLIR][TORCH] Add E2E support for aten.index_select op

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> * [tosa] Support for Rsqrt legalization

lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
This is to address C++17 extension requirement warning added by #474. 
The existing implementation of `ConvertConstantTensorAllocOp<>` requires
a C++17 feature `if constexpr ()`. This commit removes the use of that
feature to support the implementation even for lower C++ versions.
=> [TORCH]MLIR] Fix C++17 extension warning

lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Dialect/TorchConversion/Transforms/VerifyTosaBackendContract.cpp
=> [tosa] Implement Argmax support

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> * [tosa] Support for Maximum and Minimum

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> [tosa] Support for Torch.squeeze

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
Templated variants for squeeze and squeeze.dim
=> [tosa] Implement squeeze.dim support

lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> [tosa] Add missing overrride-s to fix compiler warnings

e2e_testing/torchscript/main.py, e2e_testing/torchscript/threshold.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
This commit adds lowering of `aten.threshold` op
This commit adds lowering of `aten.threshold_backward` op
=> [MLIR][TORCH] Add E2E support for aten.threshold, aten.threshold_backward op

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, lib/Dialect/TorchConversion/Transforms/VerifyTosaBackendContract.cpp, test/Conversion/TorchToTosa/basic.mlir
=> * [tosa] Support for AtenPowTensorScalarOp with constant Scalar as input

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
- Common code as TF repository, being moved to MLIR core.
- Will support further legalizations to be published.
=> [tosa] Add more common utility functions

lib/Conversion/TorchToTosa/TorchToTosa.cpp
- Also handles braodcasting n-D tensors, dynamic shapes
=> [tosa] Implement matmul, mm and bmm support

e2e_testing/torchscript/basic.py, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/reduce-op-variants.mlir
This commit adds lowering of `aten.index.Tensor` op
=> [MLIR][TORCH] Add E2E support for aten.index.Tensor op

e2e_testing/torchscript/xfail_sets.py, include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToTosa/TorchToTosa.cpp, lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
=> [tosa] Implement conv2d support

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
* [tosa] Support for AtenBatchNormOp
=> * [tosa] Support for AtenReshapeOp

lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp
* external/llvm-project 881ff4e4ebe8...84fe34a0b7fd (466):
> [MLIR] Workaround for python detection problems.
=> Bump LLVM to 84fe34a0b7fdd7bbf179981d1583693d5d5ec68b

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> [tosa] Add maxpool2d and adaptive_avgpool2d support

e2e_testing/torchscript/vision_models.py, e2e_testing/torchscript/xfail_sets.py, lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/refine-types.mlir
Handles Linear, Adaptive_AvgPool2D and FlattenUsintInts
Adds ResNet18 static model for TOSA
=> RefineTypes fixes for TOSA backend

e2e_testing/torchscript/batchnorm.py, e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
* [tosa] Support for AtenPermuteOp
=>    * [tosa] Support for AtenNativeLayerNormOp

e2e_testing/torchscript/rng.py
Also change the input 3rd dimension to be smaller so that CI can pass without 
killing the process.
=> Fix uniform argument type

e2e_testing/torchscript/elementwise.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
This commit adds support for the aten.clone op.
=> [TORCH][MLIR] Add E2E support for aten.clone

e2e_testing/torchscript/rng.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h, include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Utils/Utils.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/decompose-complex-ops.mlir
aten.bernoulli is decomposed to aten.gtTensor(aten.uniform(x), x).
=> Add aten.bernoulli decomposition.

e2e_testing/torchscript/basic.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/decompose-complex-ops.mlir
This commit adds lowering of `aten.Hardsigmoid` op.
=> [LINALG] Add E2E support for `aten.Hardsigmoid` op

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, include/torch-mlir/Dialect/Torch/IR/TorchOps.h, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
New str argument approximation is added.
=> [TORCH] Fix the torch-op definition of aten.gelu

e2e_testing/torchscript/basic.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/decompose-complex-ops.mlir
`aten.hardswish` op is decomposed into (x/6) * Relu6(x+3).
=> [LINALG] Decompose aten_hardswish op.

e2e_testing/torchscript/basic.py, e2e_testing/torchscript/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/decompose-complex-ops.mlir
Decomposition of aten.silu.op is added as silu(x) = x * sigmoid(x).
=> Decompose aten.silu op

e2e_testing/torchscript/elementwise.py, include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td, lib/Conversion/TorchToLinalg/TorchToLinalg.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
=> [MLIR][TORCH] Add E2E support for aten.erf op.

e2e_testing/torchscript/constant_alloc.py, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, include/torch-mlir/Dialect/Torch/IR/TorchOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, test/Dialect/Torch/decompose-complex-ops.mlir
This commit adds decomposition of `aten.zero_` op.
=> [LINALG] Add E2E support for `aten.zero_` op

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> [tosa] Support for Aten[Unsqueeze|Contiguous|Dropout|Reshape|View] ops

python/torch_mlir/eager_mode/ir_building.py, python/torch_mlir/eager_mode/torch_mlir_dispatch.py, python/torch_mlir/eager_mode/torch_mlir_tensor.py
=> Small bug fixes in eager mode

README.md, examples/eager_mode.py, examples/eager_mode_resnet18.py
Add a simple and ResNet18 example for Eager mode. Also add a bit of description in the README
=> Eager mode examples and README

.github/workflows/buildAndTest.yml, build_tools/build_python_wheels.sh, requirements.txt, setup.py
I am investigating the breakage.
=> Pin the CI to the latest working PyTorch.

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> [tosa] Support for Aten[Gelu|GeluBackward] ops

include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, python/torch_mlir_e2e_test/test_suite/constant_alloc.py
torch.layout information has been added.
=> [LINALG] Add torch.layout information

lib/Dialect/TorchConversion/Transforms/VerifyInvariantsBeforeBackendLowering.cpp, test/Dialect/TorchConversion/verify-invariants-before-backend-lowering.mlir
RefineTypes doesn't handle shape refinement anymore.
=> Fix error message.

python/test/eager_mode/build_script_function.py, python/test/eager_mode/framework.py, python/test/eager_mode/normalize_args_kwargs.py, python/torch_mlir/eager_mode/torch_mlir_dispatch.py
Add unit tests for `build_script_function`.
NB: this PR is stacked on top of https://github.com/llvm/torch-mlir/pull/740, so only the most recent commit is the actual diff.
=> Add unit tests for `build_script_function`

build_tools/build_python_wheels.sh
Builds whl package for OSX. Need to validate smoke tests next.
=> Remove CCACHE settings and validate on OSX

include/torch-mlir/Conversion/Utils/Utils.h, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Conversion/Utils/Utils.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/basic.py
This commit adds lowering of `aten::max_pool2d_with_indices_backward` op.
=> [MLIR][TORCH] Add E2E support for aten::max_pool2d_with_indices_backward op

e2e_testing/torchscript/xfail_sets.py, lib/RefBackend/RefBackend.cpp, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, python/torch_mlir_e2e_test/test_suite/__init__.py, python/torch_mlir_e2e_test/test_suite/return_types.py
Added the dynamic registration of return function to the execution
engine. This makes sure that  different/multiple return types are supported.
=> [REFBACKEND] Add support for returning multiple different return types.

.github/workflows/buildManylinux.yml, build_tools/python_deploy/build_macos_packages.sh, pyproject.toml
Update pinned pytorch version. Will submit a follow on PR to bump.
Also update artifacts directory
=> Enable OSX (Intel, Apple Silicon Builds)

include/torch-mlir/Conversion/Utils/Utils.h, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, lib/Conversion/TorchToLinalg/Pooling.cpp, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Conversion/Utils/Utils.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
Comparing index type instead of integer types solves the problem.
=> [LINALG] Bug fix i64 vs i32 type comparison.

.github/workflows/buildRelease.yml, build_tools/python_deploy/build_linux_packages.sh, build_tools/python_deploy/build_macos_packages.sh
env vars seems to be lost in manylinux docker. Use a version file like IREE does.
=> Fix version information in Release builds

build_tools/torchscript_e2e_heavydep_tests/hf_sequence_classification.py, build_tools/torchscript_e2e_heavydep_tests/main.py, build_tools/torchscript_e2e_heavydep_tests/vision_models.py
This commit adds e2e heavydep tests for the torch benchmarks.
=> [MLIR][TORCH] Add heavydep tests for torch benchmarks

python/torch_mlir/dialects/torch/importer/jit_ir/cmake/modules/TorchMLIRPyTorch.cmake
Compiling torch-mlir against a source version of PyTorch or an official wheel compiled with the new C++ stdlib ABI fails, as torch-mlir doesn't know how to set compiler flags to remain compatible. This changes the way torch-mlir looks at PyTorch and tries to more closely match the ABI settings, regardless of whether it's the common official wheel or some other version.
Tagging @stellaraccident due to your work on #138.
=> Enhance PyTorch C++ ABI compatibility checking

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToStd/TorchToStd.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/scalar.py, test/Conversion/TorchToStd/basic.mlir, test/Dialect/Torch/canonicalize.mlir
This commit adds lowering of `aten.ceil.float` op.
=> [MLIR][TORCH] Add E2E support for `aten.ceil.float` op

build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh, build_tools/torchscript_e2e_heavydep_tests/hf_sequence_classification.py, build_tools/torchscript_e2e_heavydep_tests/vision_models.py
BART, BigBird and GPT2 are not being serialized and hence removed.
Also, changed the script to obtain the resnest model.
=> Remove heavy_deps models that don't get serialized.

build_tools/python_deploy/build_macos_packages.sh
Useful when we are only building for one architecture.
=> Provide a way to override MacOS target and arch

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/basic.py
As per Yi's comment in the other PR, here's aten.flip in its own PR.
=> Add aten.flip

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
It would change the result type.
=> Fix TupleIndex canonicalizer.

include/torch-mlir/Dialect/Torch/Transforms/Passes.h, lib/Dialect/Torch/Transforms/Passes.cpp
add option that allows skipping decomposition of complex operation
=> add no decompose option

build_tools/python_deploy/build_macos_packages.sh, build_tools/python_deploy/build_upload_m1_snapshot.sh
Fix up wheels per python version on OSX
=> Use delocate to make portable wheels on OSX

build_tools/python_deploy/build_macos_packages.sh
Previously only system default versions were built. Now we build
binaries for both 3.9 and 3.10
=> Build each OSX python version in an venv

python/test/compile_api/basic.py, python/torch_mlir/__init__.py
This can help with development and reporting bugs.
=> torch_mlir.compile: Add OutputType.RAW

development.md
There is more detail to be added here, but this is a start.
=> development.md: Add details about testing.

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToStd/TorchToStd.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/elementwise_comparison.py, test/Conversion/TorchToStd/basic.mlir
This commit adds lowering of `aten.any.bool` op.
=> [MLIR][TORCH] Add E2E support for `aten.any.bool` op

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp
Looks like they renamed it in location
=> Fix new location for PackedParams.h

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp, requirements.txt
Also update the PyTorch nightly URL
=> Change to the real PackedParams.h location

README.md, development.md
Make the bazel build a little more visible to potential users.
cc: @asaadaldien
=> Include Bazel BUILD steps to development.md

python/test/annotations-sugar.py, python/test/compile_api/basic.py
Just taking over  https://github.com/llvm/torch-mlir/pull/988
with Sean's suggestion
TEST: passes on my system that failed previously
=> Update test to pass with  newer versions of tanh

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
=> [tosa] aten.embedding op support

python/torch_mlir_e2e_test/torchscript/framework.py
Issue is tracked in https://github.com/llvm/torch-mlir/issues/994
=> Fix multi-threaded tests on macOS

lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/refine-types.mlir
The canonicalizer converts `torch.prim.dtype` ops into integer constants
for valid types, but the type may not be known until type refinement is
complete.  However, type refinement cannot make progress until
`torch.prim.dtype` ops have been resolved to their corresponding integer
constants, thus creating a circular dependency.
This patch creates a tight coupling between type refinement and the
lowering of `torch.prim.dtype` ops by handling such ops as they are
encountered during type refinement.  The unit test in this patch aims to
check whether the type refinement pass can now handle chains of
operations that alternate between type construction and type refinement.
=> torch: handle `torch.prim.dtype` ops during type refinement

lib/Conversion/TorchToLinalg/DataMovement.cpp
This commit addresses the remaining comments on lowering of
slice_scatter and select_scatter.
Signed-Off-By: Prateek Gupta <gprateek93@gmail.com>
=> [TORCH][MLIR] Fix some comments in slice_scatter/select_scatter lowering.

e2e_testing/torchscript/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> [tosa] aten.max.dim , aten.slice.tensor ops

build_tools/autogen_ltc_backend.py, python/torch_mlir/csrc/base_lazy_backend/CMakeLists.txt, python/torch_mlir/csrc/base_lazy_backend/ir_builder.h, setup.py
Fix autogen script and cmake to work with nightly PyTorch build.
Requires that the changes from https://github.com/pytorch/pytorch/pull/81424 make it into the nightly build
=> Fix LTC autogen for CI with nightly PyTorch

python/torch_mlir/compiler_utils.py
For the purposes of catching when calling `run_pipeline_with_repro_report`. Regarding the `lstrip()` bit, the print looks like this:
```
File "/home/mlevental/dev_projects/PiPPy/pippy/collect_flops.py", line 77, in <module>
compile_ops(model, x)
File "/home/mlevental/dev_projects/PiPPy/pippy/collect_flops.py", line 65, in compile_ops
print(make_sub_layer(ts_traced, inp_shapes))
File "/home/mlevental/dev_projects/PiPPy/pippy/utils.py", line 57, in make_sub_layer
run_pipeline_with_repro_report(mb.module, ",".join(PIPELINE), "")
File "/home/mlevental/miniconda3/envs/PiPPy/lib/python3.10/site-packages/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
raise TorchMlirCompilerError(trimmed_message) from None …
```
=> Add named exception `TorchMlirCompilerError`

build_tools/python_deploy/build_macos_packages.sh
=> Disable deallocate add src

lib/Conversion/TorchToMhlo/CMakeLists.txt, lib/Conversion/TorchToMhlo/GatherOp.cpp, lib/Conversion/TorchToMhlo/PopulatePatterns.h, lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, test/Conversion/TorchToMhlo/gather.mlir
See RFC: https://github.com/llvm/torch-mlir/issues/999
Co-authored-by: Bairen Yi yibairen.byron@bytedance.com
Co-authored-by: Jiawei Wu xremold@gmail.com
Co-authored-by: Tianyou Guo tianyou.gty@alibaba-inc.com
Co-authored-by: Xu Yan yancey.yx@alibaba-inc.com
Co-authored-by: Ziheng Jiang ziheng.jiang@bytedance.com
=> [MHLO] Init MHLO gather op patterns

lib/Conversion/TorchToMhlo/BasicOp.cpp, lib/Conversion/TorchToMhlo/CMakeLists.txt, lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp, lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h, test/Conversion/TorchToMhlo/basic.mlir
=> [MHLO] Init MHLO basic op conversion

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/stats.py, test/Dialect/Torch/decompose-complex-ops.mlir
Signed-Off By: Phaneesh Barwaria <phaneesh@nod-labs.com>
=> [MLIR][TORCH] Add decomposition for aten.std.dim op

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/Transforms/ConvertToLoops.cpp
As part of this update, this patch also updates MHLO tag to ad54b43.
=> llvm: update tag to 02b3a35

lib/Conversion/TorchToMhlo/Linear.cpp, test/Conversion/TorchToMhlo/linear.mlir
=> [MHLO] Add convolution op pattern

.github/workflows/buildAndTest.yml, python/CMakeLists.txt, python/torch_mlir/csrc/reference_lazy_backend/CMakeLists.txt, python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt, setup.py
Addresses #1149 and clarifies details about LTC CMake hack
=> Update LTC CMake hack documentation

e2e_testing/torchscript/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/elementwise.py
trying to fix failing CI
CI fails on Tosa backend.
=> E2E support for AtenRemainderScalarOp

.github/workflows/buildAndTest.yml, e2e_testing/torchscript/xfail_sets.py, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
This ensures that they are always up to date.
This also updates the shape lib to make the new CI actually pass :)
=> Add CI for generated files.

build_tools/python_deploy/build_linux_packages.sh
No idea how this slipped by. Sorry about that.
Fixes #1334
=> Fix generated file checks

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/elementwise.py
This commit adds lowering of `aten.lift_fresh_copy` op.
=> [MLIR][TORCH] Add E2E support for aten.lift_fresh_copy op

lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir_e2e_test/test_suite/elementwise.py
=> [MLIR][TORCH] Fix shape calculation for `aten::pow.Tensor_Tensor` op

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir_e2e_test/test_suite/basic.py
Currently debugging this to try and figure out a segfault. I think I might have set up the Scan wrong, but I'm not sure.
=> Add lowering for aten::cumsum

e2e_testing/xfail_sets.py
=> [MLIR][TORCH] Add failing test to xfail_sets.py

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
=> [MLIR][TORCH] Add TorchToTosa lowering for `aten.broadcast_to` op

e2e_testing/xfail_sets.py, python/torch_mlir_e2e_test/test_suite/slice_like.py, python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py
=> [tosa] Add "-tosa-to-tensor" pass in the lowering pipeline

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Based on the similar code in TorchToMhlo
Signed-off-by: Eric Kunze <eric.kunze@arm.com>
=> Convert torch si literals into signless for TOSA

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> [tosa] Fix torch.vtensor.literal lowering

e2e_testing/xfail_sets.py, include/torch-mlir/Conversion/Utils/Utils.h, lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp, lib/Conversion/Utils/Utils.cpp, lib/Dialect/Torch/Utils/Utils.cpp, lib/RefBackend/RefBackend.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, python/torch_mlir_e2e_test/test_suite/scalar.py, test/Conversion/TorchToLinalg/basic.mlir, test/python/importer/jit_ir/ivalue_import/tensors.py
[https://github.com/llvm/torch-mlir/issues/1383](https://github.com/llvm/torch-mlir/issues/1383)
=> Add Byte type support

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> [tosa] Add TorchToTosa lowering for `aten.arange.start_step` op

docs/development.md
Use "$PWD" as it works across Powershell / Windows, macOS and Ubuntu/Linux.
Tested on macOS, Windows and Linux
=> doc: Use $PWD as cross platform way to get working dir

python/torch_mlir/compiler_utils.py
=> Update torch-mlir-opt error message.

utils/bazel/WORKSPACE.bazel
This should fix current bazel build
=> [Bazel] Update bazel_skylib version

e2e_testing/xfail_sets.py, lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
See https://github.com/llvm/torch-mlir/issues/1491
=> Add better error message for single-tensor tuple returns.

e2e_testing/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
=> [MLIR][TORCH] Add E2E support for `aten.addcmul_` and `aten.addcdiv_` op

.github/workflows/buildRelease.yml
Set the correct package version for Windows release builds
=> Set proper version info for Windows

docs/code_owners.md
As per discussion in the community meeting.
=> Add Suraj to TorchToTOSA owners

python/torch_mlir/__init__.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir_e2e_test/eager_backends/refbackend.py, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, python/torch_mlir_e2e_test/mhlo_backends/linalg_on_tensors.py, python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py, test/Dialect/Torch/torch-function-to-torch-backend-pipeline.mlir
also update MHLO to 57ba12a2(branch greencommit/2022-11-07-a2620e00)
change -pass-pipeline format to make tests pass.
=> update llvm tag to a2620e00.

python/torch_mlir/__init__.py
=> [torch_mlir.compile] Fixes issue with the PR#1557

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp, lib/Dialect/Torch/Transforms/RefineTypes.cpp, lib/Dialect/Torch/Transforms/ShapeLibrary.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/basic.py
Fixes https://github.com/llvm/torch-mlir/actions/runs/3436624848/jobs/5730358356
=> [MLIR][TORCH] Fix aten.upsample_nearest2d_backward op

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
This issue is found when converting deberta model [deberta to tosa](https://github.com/nod-ai/SHARK/issues/493)
=> [TOSA] Add more tosa::cast type support

python/test/compile_api/already_scripted.py, python/test/compile_api/multiple_methods.py, python/torch_mlir/__init__.py
Closes #1582
Closes #1583
@Abhishek-Varma PTAL
=> [torch_mlir.compile] Handle the case of already-scripted models better

lib/RefBackend/RefBackend.cpp, python/torch_mlir_e2e_test/configs/native_torch.py, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, test/RefBackend/munge-calling-conventions.mlir
Also remove some unused imports.
=> [cleanup] Make diagnostics better

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
This issue is found when converting deberta model https://github.com/nod-ai/SHARK/issues/493
=> [TOSA] Add aten.clamp op tosa support

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/test_suite/basic.py, test/Dialect/Torch/canonicalize.mlir
=> [MLIR][TORCH] Add aten.sort.int op

python/torch_mlir_e2e_test/test_suite/basic.py
=> [MLIR][TORCH] Fix numel tests for Roll PyTorch action

lib/Dialect/Torch/Transforms/RefineTypes.cpp, test/Dialect/Torch/refine-types.mlir
This commit fixes https://github.com/llvm/torch-mlir/issues/1599.
=> [MLIR][TORCH] Fix refine types crash

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
-- This commit adds decompose logic for `aten._softmax` when
`half_to_float` is `True`.
-- I've added an MLIR lit test.
-- An e2e test case will be added once support for half to float conversion for
`aten._softmax` is added.
Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>
=> [MLIR][TORCH] Add lowering for `aten._softmax` when `half_to_float=True`

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
Some more TD-related fixes.
Recommended review order: commit-by-commit
=> [torchdynamo] more fixes

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, python/torch_mlir/__init__.py, test/Dialect/Torch/decompose-complex-ops.mlir
Reverts llvm/torch-mlir#1622
Will resent the PR once one of the three backends e2e tests passed: linalg, tosa, mhlo.
=> Revert "Decompose torch.slice_scatter"

python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py
This should run faster and is overall clearer.
=> [cleanup] Use a single function pipeline for TOSA->Linalg

python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp, python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h, python/torch_mlir/csrc/base_lazy_backend/utils/tensor_utils.cpp
* Extended TorchMLIRLoweringContext with virtual `CreateComputation` method, so we can override it to create our custom computation.
* Fixed `device_data_cast` return value.
=> Extended TorchMLIRLoweringContext with virtual CreateComputation method

.github/workflows/buildRelease.yml, build_tools/python_deploy/build_linux_packages.sh
See https://github.com/llvm/torch-mlir/issues/1709
=> Disable pypi publishing

e2e_testing/xfail_sets.py, lib/RefBackend/RefBackend.cpp, python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py, python/torch_mlir_e2e_test/test_suite/return_types.py
This will require https://reviews.llvm.org/D139121 patch to go through.
=> Add float16 support in the refbackend.

e2e_testing/xfail_sets.py, lib/Conversion/TorchToMhlo/Basic.cpp
Added gelu_backward op for MHLO.
=> Added GeluBackward: MHLO support

lib/Conversion/TorchToMhlo/Linear.cpp, test/Conversion/TorchToMhlo/linear.mlir
1. aten.linear input can be any rank, weight should be 2-D tensor, according to https://pytorch.org/docs/stable/generated/torch.nn.Linear.html
2. currently, use bmm to address linear not have good performance, use reshape and mhlo.dot to get better performance.
=> [MHLO] reimplement linear lowering torchToMhlo

utils/bazel/torch-mlir-overlay/BUILD.bazel
=> [Bazel] Fix Bazel build

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Transforms/SimplifyDtypeCalculations.cpp, lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
=> Revert "rebase llvm: 5f24f893cac7aaea292c70f8aa83b021499114be"

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
Courtesy @BraunPhilipp.
---
Philipp, I rebased your changes on top of the main branch and resolved conflicts, since there was another change between the time you submitted your updated PR and the CI rules ran.
Eric, the changes in this patch are identical to those in PR https://github.com/llvm/torch-mlir/pull/1399.
=> [TOSA] Add LeakyReLU conversion pass

utils/bazel/torch-mlir-overlay/BUILD.bazel
=> Use global for MLIRTorchOpsIncGenTdFiles

python/torch_mlir/dynamo.py
=> [torchdynamo] Add native_group_norm and split op to the decomp list

python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp
Sometimes ago we found an issue with `c10::ListType` comparison in JIT schema matching. But unfortunately the fix [wasn't accepted ](https://github.com/pytorch/pytorch/pull/86947) by PyTorch, so in this PR I added a workaround on our side, so we can handle operations like `torch.stack`. For example:
```py
class Model(torch.nn.Module):
def __init__(self):
super().__init__()
self.fc1 = torch.nn.Linear(5, 5)
def forward(self, x):
return torch.stack([self.fc1(x), self.fc1(x)])
```
without this fix, this model will fail with:
```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
aten::stack(Tensor[] tensors, int dim=0) -> Tensor:
Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'List[Tensor]'.
Empty lists default to …
```
=> Fix JIT schema matching when ListType is used

lib/Conversion/TorchToLinalg/Uncategorized.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py
=> [TorchToLinalg] Lower AtenRoundOp to math::RoundEvenOp (Fixes #1811)

README.md
Fix https://github.com/llvm/torch-mlir/issues/1818
=> Update README.md and put Python 3.10 a prerequisite

python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
Week of 01/30/2023:
Green LLVM commit: e31ee6417c33a6e2f0e8440b1a86d5365279ad68
Green MHLO commit: c2a6f4064d426567b9ef7b0d29d5ab86dc7b2b02 (branch greencommit/2023-01-30-e31ee641)
=> Update LLVM and MHLO submodules.

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py
Fixes https://github.com/llvm/torch-mlir/issues/1829
=> [MLIR][TORCH] Add support for clone op with channels last memory format

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
Adds the operation definition for aten::scatter_reduce.
=> Add aten.scatter_reduce op definition

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/Reduction.cpp, python/torch_mlir_e2e_test/test_suite/__init__.py, python/torch_mlir_e2e_test/test_suite/reduction.py
=> [MLIR][TORCH] Add support for integer type input for `max.dim` op

e2e_testing/xfail_sets.py
- Update llvm tag to 5e111eb275eee3bec1123b4b85606328017e5ee5
- mhlo now points to a99159c45ee5c497f8dce01eff807a6d57629b61
=> build: update llvm tag to 5e111eb275

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
This commit adds the op definition for the aten.clamp.Tensor op.
=> [TORCH-MLIR] Add ODS for aten.clamp.Tensor op.

utils/bazel/docker/Dockerfile, utils/bazel/torch-mlir-overlay/BUILD.bazel
Fix broken build
Run: https://github.com/asaadaldien/torch-mlir/actions/runs/4257678022
=> [Bazel] Fix clang version, missing mhlo deps and add reqs files

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorBase.td, include/torch-mlir/Dialect/Torch/IR/TorchBase.td, include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionBase.td
- Remove `useFoldAPI`.
- Update tags llvm: b5bf6f6392a3408be1b7b7e036eb69358c5a2c29 mhlo: bb1ed5b47c036993b954e881cce7c7aab00f9962
=> build: update llvm tag to b5bf6f63

e2e_testing/xfail_sets.py, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py, python/torch_mlir_e2e_test/configs/torchdynamo.py, python/torch_mlir_e2e_test/test_suite/basic.py, test/Dialect/Torch/canonicalize.mlir
The e2e test failed. The error is similar with #1849.
=> [Torch Dialect] add folder for aten.sub.float

.github/workflows/buildRelease.yml, build_tools/python_deploy/build_linux_packages.sh, build_tools/python_deploy/build_macos_packages.sh, setup.py
=> rename no-jit -> core

lib/Conversion/TorchToTcp/Misc.cpp, test/Conversion/TorchToTcp/misc.mlir
=> [TCP] Lower torch integer constants -> tcp.const

lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/Torch/Transforms/DropAbstractInterpCalculations.cpp, python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py, test/Conversion/TorchToMhlo/linear.mlir
- mergeBlockBefore -> inlineBlockBefore
- move tosa-to-tensor pass ordering
https://github.com/llvm/torch-mlir/issues/1178#issuecomment-1476217922
=> Update to LLVM 029313cc979ae71877b65794b1063d4e51184cc8

e2e_testing/xfail_sets.py, lib/Conversion/TorchToTosa/TorchToTosa.cpp, python/torch_mlir_e2e_test/test_suite/pooling.py
This PR implements the support for lowering torch.aten.max_pool2d to tosa with ceil_mode==true.
=> Max pool2d ceil mode to tosa

README.md
This PR fixes an issue with the line break in the README.md. If the current display is intentional, please feel free to close this PR.
=> [README] fix line break

e2e_testing/xfail_sets.py, include/torch-mlir/Conversion/Utils/Utils.h, include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Conversion/TorchToArith/TorchToArith.cpp, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, lib/Conversion/Utils/Utils.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Utils/Utils.cpp, python/torch_mlir_e2e_test/test_suite/basic.py, python/torch_mlir_e2e_test/test_suite/scatter.py, test/Conversion/TorchToArith/basic.mlir
Signed-Off By: Vivek Khandelwa<vivek@nod-labs.com>
=> [MLIR][TORCH] Support 2-d index for aten.index_put_impl op

e2e_testing/xfail_sets.py, python/torch_mlir/dynamo.py
=> [TorchDynamo] Add aten.squeeze op to the decomposition list

lib/Conversion/TorchToTosa/TorchToTosa.cpp
Fix https://github.com/llvm/torch-mlir/issues/2010
=> [MLIR][TOSA] Add support for sliceOp end < 0

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
https://github.com/nod-ai/SHARK/issues/986
=> [TOSA] Add todtype f32 to i64

e2e_testing/xfail_sets.py
- Update tags llvm: 225d255a583ea3d50bbba49d949ca76be6a880bf mhlo: beb5d2b04c33c19d23e02bd3c5e50ddecba11664
Fixes https://github.com/llvm/torch-mlir/issues/1859.
=> build: update llvm tag to 225d255a

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/Transforms/Bufferize.cpp
- Update tags 
llvm: 3abae1c88416858cf2e9a7ed9417bc52033933b4
mhlo: 70ebc73a28767b772e09e0dd03cf3e47457435a2
- Replace uses of `getDynOperands` utility with `createDynamicDimensions`.
=> build: update llvm tag to 3abae1c8

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
This PR
- Adds aten.nll_loss2d_forward and aten.nll_loss2d_backward op
- Also add UTs
=>  Add ODS for aten.nll_loss2d Op

e2e_testing/xfail_sets.py
This silently was a mistake because these are flaky tests to begin with...
=> [Dynamo] fix TORCHDYNAMO_CRASHING_SET

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Dialect/Torch/IR/TorchOps.cpp, lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp, test/Conversion/TorchToTosa/basic.mlir
LLVM: 26ee8947702d79ce2cab8e577f713685a5ca4a55
MHLO: 4805d8498dfb81566076f56f52273b426c1cc5bf
Per: https://github.com/llvm/torch-mlir/issues/1178#issuecomment-1538492185
=> Integrate LLVM

e2e_testing/main.py, e2e_testing/xfail_sets.py, python/CMakeLists.txt, python/test/dynamo_fx_importer/basic.py, python/torch_mlir/__init__.py, python/torch_mlir/_dynamo_fx_importer.py, python/torch_mlir_e2e_test/configs/torchdynamo.py, python/torch_mlir_e2e_test/test_suite/basic.py
This PR adds a pure fx graph importer based on dynamo.
cc @powderluv
=> Pure-Python FX importer.

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/csrc/base_lazy_backend/shape_inference.cpp, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
Adds ODS and shape-inference for mse_loss_backward.
=> add mse_loss_backward

include/torch-mlir-c/TorchTypes.h, lib/CAPI/TorchTypes.cpp
=> [CAPI] add isValidSubtype to CAPI

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
This commit adds ODS for the aten.sign op.
=> [TORCH-MLIR] Add ODS for aten.sign op.

build-requirements.txt, build_tools/python_deploy/build_linux_packages.sh
Tested on Ubuntu 23.04 on Ampere Altra instance.
=> [arm64] Fix release builds for ARM64

.github/actions/setup-build/action.yml
Original PR was accidentally merged to a branch (https://github.com/llvm/torch-mlir/commit/f72c1cd786c406ea653c6458d24a7d4ae0d2ab67) . Re-landing same PR to main now
=> only setup python for non-docker platforms

lib/Conversion/TorchToLinalg/Uncategorized.cpp, python/torch_mlir_e2e_test/test_suite/nll_loss.py
=> [MLIR][TORCH] Add support for the `total_weight` for `aten.nll_loss_forward` op

e2e_testing/xfail_sets.py, python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
This PR will fix https://github.com/llvm/torch-mlir/issues/2084. But there is another thing failed when I add e2e test.
=> [Importer] import constant tuple

.github/actions/setup-build/action.yml, .github/workflows/RollPyTorch.yml, .github/workflows/bazelBuildAndTest.yml, .github/workflows/bazelBuildAndTestTcp.yml, .github/workflows/buildAndTest.yml, .github/workflows/buildAndTestTcp.yml, .github/workflows/buildRelease.yml, .github/workflows/merge-rollpytorch.yml
As titled. Should fix issues like [this](https://github.com/llvm/torch-mlir/actions/runs/5314715542/jobs/9647290496?pr=2224).
=> Fix GHA workflows on `mlir-tcp`

lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
https://github.com/llvm/torch-mlir/commit/a46b5c6af2f73d932cb12d2b0a9726b945e11850
=> [TORCH] Fix recompose off by -1 error

torchvision-requirements.txt
torch version: 2.1.0.dev20230701
torch commit hash: bb3df0bb7c6bce70941199401f6b3550e10cba50
torchvision version: 0.16.0.dev20230702
=> update PyTorch version to 2.1.0.dev20230701

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/DataMovement.cpp, lib/Conversion/TorchToLinalg/Utils.cpp, lib/Conversion/TorchToLinalg/Utils.h, python/torch_mlir_e2e_test/test_suite/basic.py
-- This commit adds support for dynamic dimension in BroadcastTo op.
Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>
=> [Torch-to-Linalg] Add dynamic dimension support for BroadcastTo op

include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h, include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.td, lib/Conversion/TorchToLinalg/Linear.cpp, lib/Dialect/Torch/IR/TorchTypes.cpp, lib/Dialect/TorchConversion/Transforms/CMakeLists.txt, lib/Dialect/TorchConversion/Transforms/UnpackTensor.cpp
add two passes
- unpack quantized weights
- convert custom op to linalg
=> Support brevitas custom op

e2e_testing/xfail_sets.py, externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/Transforms/Bufferize.cpp
- update llvm tag to 4592543a01609feb4b3c19e81a9d54743e15e329
- mhlo now points to f6615343fdab2c74bebd23c78366cf097f9a72df
=> build: update llvm tag to 4592543a01609fe

lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
=> [MLIR][TORCH] Fix `aten.cumsum` lowering for int32 input

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, python/torch_mlir_e2e_test/test_suite/basic.py
Fixes https://github.com/nod-ai/SHARK/issues/1710.
=> [MLIR][TORCH] Add support for dtype arg for softmax.int op

.github/workflows/merge-rollpytorch.yml
=> Update merge-rollpytorch.yml with approved actors

utils/bazel/WORKSPACE.bazel, utils/bazel/torch-mlir-overlay/BUILD.bazel
Aligns with https://github.com/llvm/torch-mlir/pull/2460 and fixes bazel build.
GHA workflow: https://github.com/sjain-stanford/torch-mlir/actions/runs/6178894329
=> [Bazel] Replace mlir-hlo with stablehlo

lib/Conversion/TorchToTosa/TorchToTosa.cpp
MSVC (and other compilers with implicit narrowing warnings) don't like this type mismatch.
=> Fixing implicit double to float casts.

e2e_testing/xfail_sets.py, include/torch-mlir/Conversion/Utils/Utils.h, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Conversion/Utils/Utils.cpp, python/torch_mlir_e2e_test/test_suite/__init__.py, python/torch_mlir_e2e_test/test_suite/elementwise.py
=> [MLIR][TORCH] Add support for conversion to int8 dtype

.github/workflows/buildRelease.yml
Also, revert https://github.com/llvm/torch-mlir/pull/2488. 
Disabling LTC based on the discussion here:
https://discord.com/channels/636084430946959380/742573221882364009/1156272667813494824
=> Disable LTC for arm release

e2e_testing/xfail_sets.py, lib/Conversion/TorchToLinalg/Uncategorized.cpp, python/torch_mlir_e2e_test/test_suite/elementwise.py
=> [MLIR][TORCH] Add support for int8 dtype for sub, add, and bitwise_and op

lib/Conversion/TorchToTosa/TorchToTosa.cpp, test/Conversion/TorchToTosa/basic.mlir
=> update AtenClampOp in torch-to-tosa to handle fp inputs

lib/Conversion/TorchToTosa/TorchToTosa.cpp
=> Update dtype check in torch-to-tosa clamp op

build_tools/build_libtorch.sh, include/torch-mlir/Dialect/Torch/Transforms/Passes.td, include/torch-mlir/Dialect/Torch/Utils/Utils.h, python/torch_mlir/csrc/base_lazy_backend/README.md, python/torch_mlir/csrc/base_lazy_backend/mlir_native_functions.cpp, python/torch_mlir/csrc/base_lazy_backend/mlir_node.h, python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp, python/torch_mlir/csrc/base_lazy_backend/ops/ivalue.h
=> Fix typos in comments

pytorch-hash.txt, pytorch-requirements.txt, torchvision-requirements.txt
torch version: 2.2.0.dev20231110
torch commit hash: edbf22fa03bafd1d2849ba41db75a2bea172dbcc
torchvision version: 0.17.0.dev20231110
=> update PyTorch version to 2.2.0.dev20231110

lib/Dialect/Torch/IR/TorchTypes.cpp
Refer: https://github.com/pytorch/pytorch/issues/58734
=> [MLIR][TORCH] Add support for unsigned integer types

test/Conversion/TorchConversionToMLProgram/basic.mlir, utils/bazel/WORKSPACE.bazel
Bump LLVM to `5e5a22caf88ac1ccfa8dc5720295fdeba0ad9372` and StableHLO to `83f095e7217c897f1eccac5652600ceb944cb0e0`. 
Bazel GHA: https://github.com/sjain-stanford/torch-mlir/actions/runs/7027647674
=> Bump LLVM and StableHLO

lib/Dialect/Torch/Utils/Utils.cpp
=> [MLIR][TORCH] Add support for Short(si16) data type

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds the OnnxToTorch support for Matmul.
=> [MLIR][ONNX] Add OnnxToTorch support for matmul ops

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Added the less or equal operation to OnnxToTorch. 
onnx.LessOrEqual
=> [onnx] add support for onnx.LessOrEqual

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit adds support for `LeakyRelu and GatherElements` op in the onnx pipeline.
=> [ONNX][MLIR] Add support for LeakyRelu and GatherElements op

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
This commit adds the OnnxToTorch support for AveragePool op.
Signed-Off By: vivekkhandelwal1424@gmail.com
=> [MLIR][ONNX] Add OnnxToTorch support for AveragePool op.

build_tools/write_env_file.sh, docs/development.md
Modify PYTHONPATH to new related directory in docs.
=> Update PYTHONPATH in development.md

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
TorchOnnxToTorch
For Erf function
=> [ONNX] ONNX -> TORCH for Erf

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
This commit adds the OnnxToTorch support for Conv op.
Fixes https://github.com/nod-ai/SHARK-Turbine/issues/253, https://github.com/nod-ai/SHARK-Turbine/issues/283.
Signed-Off By: vivekkhandelwal1424@gmail.com
=> [MLIR][ONNX] Add OnnxToTorch support for Conv op.

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
=> [MLIR][ONNX] Fix onnx.conv lowering to handle bias tensor

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
lower onnx min op to torch aten minimum op
=> lower onnx max op to torch aten maximum op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/unsupported_fb_opt_ops.mlir
(instead of an input)
Addresses part of #2689. fixes #2702
=> support Onnx opset 1-13 ReduceMean where axes is supplied as an attr

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h
=> Added tensorResultTypeAtIndex to  Patterns.h

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/unsupported_fb_opt_ops.mlir
=> add basic cumsum. this doesn't support the exclusive and reverse attrs

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
=> [MLIR][ONNX] Add OnnxToTorch support for Dropout and Elu op

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
=> [MLIR][ONNX] Add OnnxToTorch support for Bernoulli and CastLike op

include/torch-mlir/Dialect/Torch/Utils/Utils.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, lib/Dialect/Torch/Utils/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
=> [MLIR][ONNX] Add TorchToOnnx Support for DepthToSpace op

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, lib/Conversion/TorchOnnxToTorch/CMakeLists.txt, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
https://github.com/nod-ai/SHARK-Turbine/issues/244
=> [MLIR][ONNX] Add OnnxToTorch support for Maxpool Op

lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp, test/Dialect/Torch/canonicalize.mlir, test/Dialect/Torch/decompose-complex-ops.mlir, test/Dialect/Torch/simplify-shape-calculations.mlir
- Add fixes for https://github.com/llvm/llvm-project/commit/af78e5daf0791135485dbd7972ffedb927727a6b
- Add fixes for https://github.com/llvm/llvm-project/commit/bb6d5c220004a5d7e466a669324001285a688918
=> Bump LLVM to llvm/llvm-project@0cb024b

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
We can make the per-tensor version of the operation to the dequantize operation via marking with the make quantized tensor component. This introductions the `qint*` and `quint*` tensor type that can be lowered to teh appropriate dequantization behavior during the torch-to-linalg conversion.
=> [onnx] Lowering `onnx.dequantize_linear` to `torch`

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This is the initial NotNull op implementation
=> Initial commit of NonZero op

lib/Conversion/TorchToLinalg/Pooling.cpp
Introduced in 704cfdaf0893fa4078ab744a915a56367282dcaa of @wu-s-john 
g++ compiler error: 
Pooling.cpp:177:13: error: explicit specialization in non-namespace scope ‘class 
Design looks good, g++ is just freaking out for no good reason. Un-nesting the template classes fixes the error. 
We don't have g++ CI. This hopefully happens infrequently enough that we can just fix manually. My service to those folks who really like building with g++... :)
=> g++ build fix

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
https://github.com/nod-ai/SHARK-Turbine/issues/331
=> [ONNX][TORCH-MLIR] Add TopK support

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
https://github.com/nod-ai/SHARK-Turbine/issues/312
=> [ONNX][MLIR] Add support for onnx.Exp op

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [MLIR][TORCH] Support for `onnx.LayerNormalization`

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
=> [MLIR][TORCH] Add support for dynamic shape for Onnx.Transpose op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
https://github.com/nod-ai/SHARK-Turbine/issues/352
=> OnnxToTorch ReduceMax lowering

.github/workflows/RollPyTorch.yml
=> [CI] Change Roll PyTorch runner

docs/development.md
Change should be visible : https://github.com/newling/torch-mlir/blob/docs_update/docs/development.md
=> Describe how to get --debug and --debug-only flags in dev notes 

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
If a tensor is initialized by a list with a single constant integer, this folder turns it into a torch.vtensor.literal
=> Rob's atenTensor folder

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
A chunk off
https://github.com/llvm/torch-mlir/pull/2856
https://github.com/llvm/torch-mlir/pull/2860
=> AtenSortOp Folder

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
Includes `slice` folder and lit tests
=> [torch] AtenSliceOp folder that produces splat results

test/python/fx_importer/sparse_test.py
=> [torch-mlir][sparse][NFC] fixed typo

lib/Conversion/TorchToLinalg/DataMovement.cpp
For some reason we did not directly use the step size dynamically despite its constructed using the dynamic value.
=> [torch] Support dynamic step size for `torch.slice`

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Conversion/TorchToStablehlo/basic.mlir, test/Dialect/Torch/canonicalize.mlir
Useful for `slice` lowerings that depend on tensors made form scalars.
=> [torch] Add folder for `prim.NumToTensor.Scalar`

python/torch_mlir/extras/fx_importer.py, python/torch_mlir/fx.py, test/python/fx_importer/basic_test.py
=> Expose `func_name` to the main fx import API

lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
Fixes https://github.com/nod-ai/SHARK-Turbine/issues/461
=> [MLIR][TORCH] Add support for tanh approximation for Gelu op

python/torch_mlir/extras/fx_importer.py, test/python/fx_importer/sparse_test.py
**DO NOT MERGE!**: Still waiting llvm-project be synced with https://github.com/llvm/llvm-project/pull/82449
=> [torch-mlir][sparse] support e2e sparse kernels with COO inputs.

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
A handful of operations are commonly used in shape calculations (slice, concat, broadcast). Added these additional folders to better propagate simple shape computations.
=> [torch] Additional folders for shape computations

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/slice_like.py
Convert to individiual slices and tuple together as a list.
=> [torch] Add support for `torch.split_with_sizes` via decompose

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchToLinalg/TensorConstructors.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/padding.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The current padding operation was not functional for dynamic shapes.
Updated and enabled tests so that onnx.pad tests pass.
Work TBD for reflection padding.
=> [onnx] Fix constant pad for dynamic shape

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [onnx] support for lowering mod op from onnx to torch

python/torch_mlir/extras/fx_importer.py
Lift this from 2-dim only to n-dim for n>=2
=> [torch-mlir][sparse] higher dimension COO

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Dialect/Torch/IR/TorchOps.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Dialect/Torch/canonicalize.mlir
support fold with literal vtensor.  
change it to canonicalize because this pattern will create new op.
=> [Torch Dialect] enhance aten.int.tensor's canonicalize

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/reshape_like.py
=> [Torch] support decompose aten.einsum with ellipsis slicing

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The indices should be expanded before the torch.gather operation.
=> [MLIR][ONNX] Fix onnx.gather_nd implementation

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchToLinalg/Pooling.cpp, projects/pt1/e2e_testing/xfail_sets.py
=> [MLIR][Torch] Fix OnnxToLinalg lowering for AvgPool op

README.md
Source: https://github.com/llvm/torch-mlir/issues/3068#issuecomment-2024109412 Verified commands locally on Ubuntu 22.04 with pyenv virtualenv created for python 3.11.
=> [README] update links to snapshot packages

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit also cleans up the OnnxToTorch lowering for the ReduceMean op and adds the support for handling edge cases.
Signed-Off By: Vivek Khandelwal vivekkhandelwal1424@gmail.com
=> [MLIR][TORCH] Fix OnnxToLinalg lowering issue for ReduceMean op

include/torch-mlir/Conversion/TorchOnnxToTorch/Utils.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchOnnxToTorch/Utils.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
=> [MLIR][TORCH] Fix Onnx.ReduceSum lowering for failing e2e tests

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
=> [MLIR][TORCH] Add OnnxToTorch lowering for Einsum op

lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Dialect/TorchConversion/Transforms/Passes.cpp, projects/pt1/python/torch_mlir_e2e_test/stablehlo_backends/linalg_on_tensors.py
* promote to f64 to do division, avoid division on i64 (floor div)
* refactor torch-to-stablehlo-pipeline
=> [Stablehlo] fix aten.arange's lowering to stablehlo

lib/Dialect/Torch/IR/TorchOps.cpp
=> Avoid Type Mismatch in Slice Folder

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Adds OnnxToTorch Lowering for the ReduceL1 op.
=> [MLIR][TORCH] Add OnnxToTorch lowering for ReduceL1 Op

projects/pt1/e2e_testing/xfail_sets.py
Reclassifying what the source of failures are for various bugs so we can reprioritize what failures are common.
=> [onnx] Update the failure triage for onnx

projects/pt1/python/torch_mlir/torchscript.py
* so that it could be specified by user.
=> [torchscript] export extra library file name to user

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
iree tests `test_cosh` and `test_cosh_example` passed
=> Fix onnx cosh lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
iree tests `test_acosh` and `test_acosh_example` passed
=> Fix onnx acosh lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
iree tests `test_atanh` and `test_atanh_example` passed
=> Fix onnx atanh lowering

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir
Adds OnnxToTorch lowering for the `onnx.HannWindow` op. Also factors out common implementation between the window functions.
=> [torch] Add OnnxToTorch lowering for `onnx.HannWindow`

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_a_to_f.mlir, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
We should be using the `torch` path and handling decomposition in the `math` dialect.
=> Revert hyperbolic trigonometric decompositions

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
=> [ONNX] Add OnnxToTorch lowering for SoftmaxCrossEntropyLoss op

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Dialect/Torch/decompose-complex-ops.mlir
=> Revert "Decompose AtenNonzeroOp"

projects/pt1/e2e_testing/xfail_sets.py
=> Temporarily remove QuantizedMLP_basic

lib/Conversion/TorchToStablehlo/Basic.cpp, test/Conversion/TorchToStablehlo/elementwise.mlir
* lowering gelu("none") to erf
* lowering gelu("tanh") to tanh
=> [Stablehlo] fix lowering gelu(x, tanh)

test/python/fx_importer/sparse_test.py
Objective: make the to_sparse work end-to-end!
=> [torch-mlir][sparse] add a true network to our NN tests

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/Conversion/TorchToLinalg/sparse.mlir
also maps simply to sparse_tensor.convert
the sparsity types do the rest!
=> [torch-mlir][sparse] recognize to_dense primitive

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit handles the one-input case for the "Max" ONNX operator. A new unit test has also been added.
=> [ONNX] Handle one-input case for `onnx.Max` operator

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
This commit handles the one-input case for the "Min" ONNX operator. A new unit test has also been added.
=> [ONNX] Handle one-input case for Min ONNX operator

utils/bazel/torch-mlir-overlay/BUILD.bazel
Required after https://github.com/llvm/torch-mlir/pull/3318 landed.
GHA: https://github.com/sjain-stanford/torch-mlir/actions/runs/9120607050/job/25078271790
=> [Bazel] Add SparseTensorDialect deps

lib/CAPI/TorchTypes.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
=> Replace some depreciated uses of cast

projects/pt1/python/torch_mlir/torchscript.py, projects/pt1/python/torch_mlir_e2e_test/configs/fx_importer_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/lazy_tensor_core.py, projects/pt1/python/torch_mlir_e2e_test/configs/linalg_on_tensors_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/native_torch.py, projects/pt1/python/torch_mlir_e2e_test/configs/onnx_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/stablehlo_backend.py, projects/pt1/python/torch_mlir_e2e_test/configs/torchdynamo.py, projects/pt1/python/torch_mlir_e2e_test/configs/torchscript.py, projects/pt1/python/torch_mlir_e2e_test/configs/tosa_backend.py, projects/pt1/python/torch_mlir_e2e_test/framework.py
so that `python3 e2e_testing/main.py -v` would print intermediate IR.
=> enhance verbose option in e2e_testing

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/matmul.py
* support aten.linear with more rank.
=> [Torch] fix aten.linear's decomposition

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [ONNX] Add OnnxToTorch Lowering for LpNormalization op

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This PR adds OnnxToTorch support for Scatter op
=> [MLIR][ONNX] Add OnnxToTorch support for Scatter Op

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
=> [Onnx] reduce MatMul OpsetVersion to 1

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
=> [Onnx] Add Onnx->Torch lowering for Onnx.Shrink Op

python/torch_mlir/extras/fx_importer.py
Missing types for tracing float8 types.
=> Add f8 types to fx importer

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the lowering for SequenceAt, SequenceEmpty, SequenceInsert, SequenceErase op
Signed-Off By: Vivek Khandelwal<vivekkhandelwal1424@gmail.com>
=> [ONNX] Add OnnxToTorch Lowering for Sequence Ops

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
=> [ONNX] Lower Onnx.Concat lowering version

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/python/fx_importer/sparse_test.py
this fixes the following issue:
https://github.com/llvm/torch-mlir/issues/3418
=> [torch-mlir][sparse] re-enable all sparse tests

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, lib/Conversion/TorchToLinalg/Uncategorized.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir, test/Conversion/TorchToLinalg/resize.mlir
half_pixel is also the default mode used by ONNX, see https://onnx.ai/onnx/operators/onnx__Resize.html
=> onnx.resize: Add support for coordTfMode "half_pixel"

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp
Handles onnx exporters emitting default-valued attributes.
=> [onnx] Resize supports default-valued attributes

lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
This would require to bump stablehlo at the same time.
=> Update to llvm/llvm-proect@27ac46e6bea2 (2024-6-12)

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Solves https://github.com/nod-ai/SHARK-Turbine/issues/727
Uses AvgPool to implement GlobalLpPool similar to this https://github.com/onnx/onnx/blob/main/onnx/reference/ops/op_lp_pool.py
cc: @vivekkhandelwal1
=> [ONNX] add onnx lowering for global lp pool operator

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [ONNX] Add OnnxToTorch Lowering for GroupNormalization op

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [ONNX] Add OnnxToTorch lowering for Optional, OptionalGetElement op

test/Conversion/TorchToArith/basic.mlir, test/Conversion/TorchToLinalg/basic.mlir, test/Conversion/TorchToLinalg/elementwise.mlir, test/Conversion/TorchToLinalg/sparse.mlir, test/Conversion/TorchToSCF/basic.mlir, test/Conversion/TorchToStablehlo/basic.mlir, test/Conversion/TorchToStablehlo/elementwise.mlir, test/Conversion/TorchToStablehlo/gather.mlir, test/Conversion/TorchToStablehlo/linear.mlir, test/Conversion/TorchToStablehlo/scatter.mlir, test/Conversion/TorchToTosa/basic.mlir, test/Dialect/TMTensor/bufferize.mlir, test/Dialect/Torch/adjust-calling-conventions.mlir
Update to llvm/llvm-project@5207632f8698a2fab0c4cdcdf2f7ad9aaf96e06f
Update to openxla/stablehlo@d41390c3a731ba038e6363f75fcd135e6f727039
=> [torch-mlir] bump stablehlo/llvm version

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
=> [ONNX] Add OnnxToTorch lowering for OptionalHasElement op

lib/Conversion/TorchToStablehlo/Reduction.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/reduction.py
* refactor `TorchToStablehlo/Reduction.cpp`
* add `ConvertAtenReduceWithIndicesOp` patterns
=> [Stablehlo] support aten.any.dim, aten.min.dim

include/torch-mlir/Conversion/TorchToStablehlo/StablehloLegalizeUtils.h, lib/Conversion/TorchToStablehlo/Basic.cpp, lib/Conversion/TorchToStablehlo/Linear.cpp, lib/Conversion/TorchToStablehlo/Pooling.cpp, lib/Conversion/TorchToStablehlo/StablehloLegalizeUtils.cpp
only provide `outElementType` when promoteType
=> [Stablehlo] simplify promoteType

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
also add shape infer in decomposition, see https://github.com/llvm/torch-mlir/issues/3312
=> [Torch Dialect] fix aten.nan_to_num's decomposition when inf=None

lib/Dialect/Torch/IR/TorchOps.cpp, test/Dialect/Torch/canonicalize.mlir
so that it could support folding slice with any static shape.
=> [Torch] enhance fold of aten.slice.Tensor

lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
=> [ONNX] Reduce Onnx.Flatten op version

include/torch-mlir/Conversion/TorchOnnxToTorch/Patterns.h, include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Adds OnnxToTorch Lowering for the `Onnx.Unique` op.
=> [torch] Add OnnxToTorch lowering for Onnx.Unique op

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/basic.py
- Broadcasts index list tensors
- Adds torch.nn.Unfold test
=> [TOSA] Fix Tensor.hacked_twin to support diff size indexes

lib/Conversion/TorchToStablehlo/GatherScatter.cpp
Current StableHlo lowering strategy works well when `src` tensor's rank is no bigger than `dst` tensor's. The new patch make it succeed in other cases. The following is an example.
```
%190 = torch.prim.ListConstruct %arg4 : (!torch.vtensor<[1,1024],si64>) -> !torch.list<vtensor>
%191 = torch.aten.index_put.hacked_twin %189, %190, %186, %true : !torch.vtensor<[1024,768],f32>, !torch.list<vtensor>, !torch.vtensor<[1,1024,768],f32>, !torch.bool -> !torch.vtensor<[1024,768],f32>
```
=> [stablehlo]: fix aten.index_put_hacked_twin lowering to StableHlo

python/torch_mlir/extras/fx_decomp_util.py, python/torch_mlir/extras/fx_importer.py, python/torch_mlir/fx.py
=> [FxImporter] small fixes for fx importer compatibility issues between different pytorch versions

lib/Conversion/TorchToLinalg/Linear.cpp, test/Conversion/TorchToLinalg/basic.mlir
Change linalg.matmul_unsigned to linalg.matmul with unsigned type_fn
=> Change linalg.matmul_unsigned to linalg.matmul with unsigned type_fn

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
Add a check for negative indices and offset appropriately for `onnx.GatherElements`.
=> [onnx] Handle negative indices for `onnx.GatherElements`

lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp
To fix https://github.com/nod-ai/SHARK-Turbine/issues/253#issuecomment-2271815640
Prevent fusion for 1d convolution ops and just do it as an f32 conv since there isn't a linalg named op for quantized 1-d convolution yet.
Get 24 onnx eca* models passed in iree-comiple.
```
onnx/models/eca_nfnet_l0.ra2_in1k_vaiq
onnx/models/eca_nfnet_l0.ra2_in1k_train_vaiq
onnx/models/eca_nfnet_l1.ra2_in1k_vaiq
onnx/models/eca_nfnet_l1.ra2_in1k_train_vaiq
onnx/models/eca_nfnet_l2.ra3_in1k_vaiq
onnx/models/eca_nfnet_l2.ra3_in1k_train_vaiq
onnx/models/ecaresnet101d_vaiq
onnx/models/ecaresnet101d_pruned_vaiq
onnx/models/ecaresnet101d_pruned_test_vaiq
onnx/models/ecaresnet101d_test_vaiq
onnx/models/ecaresnet26t_vaiq
onnx/models/ecaresnet26t_train_vaiq
onnx/models/eca_resnet33ts.ra2_in1k_vaiq …
```
=> [Torch] Disable 1-d quantized convolution

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
For length-0 on `onnx.ReduceMax` the length 0 case was incorrect due to a copy paste error.
=> [onnx] Fix edge condition for `onnx.ReduceMax`

lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp, lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_g_to_p.mlir
The post onehot transposition code was unexercised. Fixed the test and transformation to check use.
=> [onnx] Fix transposition code for `onnx.OneHot`

lib/Conversion/TorchToLinalg/Pooling.cpp
If we pass an integer type to the pooling operation we incorrectly pad with an integer value with causes downstream compilation failures.
=> [torch] Add integer support for pooling operations

projects/pt1/e2e_testing/xfail_sets.py
=> Bump llvm to 585523750e2bbe374d1cb3bf4ff9d53de29b9593

lib/Conversion/TorchOnnxToTorch/OnnxRecurrentLayerOpExpanders.cpp
The `layout` attribute was not considered for the `onnx.RNN` operation. Added support for the attribute to transpose the inputs / outputs of the RNN when valid.
=> [onnx] Fix `onnx.RNN` for layout attribute

lib/Conversion/TorchToLinalg/Uncategorized.cpp
The determinant lowering had some extract / insert shape mismatches. Replumbed shape manipulations to correctly implement the determinant operation.
=> [onnx] Fix `torch` lowering for determinant

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Result type was not fetched causing a crash on construction
=> [onnx] Fix onnx.ThresholdedRelu crash

docs/ltc_examples.md
=> Update links to examples

test/Conversion/TorchToSCF/basic.mlir, test/Conversion/TorchToStablehlo/basic.mlir, test/Conversion/TorchToStablehlo/pooling.mlir, test/Conversion/TorchToTosa/basic.mlir, test/Dialect/TMTensor/bufferize.mlir
=> Bump llvm to f9031f00f2c9

lib/Conversion/TorchToStablehlo/Basic.cpp, projects/pt1/e2e_testing/xfail_sets.py
previous PR(https://github.com/llvm/torch-mlir/pull/3702)
=> [Stablehlo] fix aten compare ops' promote rules

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td, lib/Conversion/TorchToLinalg/Uncategorized.cpp, projects/pt1/e2e_testing/xfail_sets.py, projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py, projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
Add the operation with lowering to linalg. Includes a test for end-to-end correctness.
=> [torch] `torch.aten.complex` operation with lowering

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h, lib/Conversion/TorchToStablehlo/Linear.cpp, lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py, test/Conversion/TorchToTosa/basic.mlir, test/Dialect/TMTensor/bufferize.mlir, test/python/compile.py
=> Bump to llvm/llvm-project@e813750354bbc08551cf23ff559a54b4a9ea1f29

lib/Conversion/TorchToLinalg/DataMovement.cpp, test/Conversion/TorchToLinalg/squeeze.mlir
Address https://github.com/nod-ai/SHARK-ModelDev/issues/846
Assume the dynamic squeezed dim is 1.
=> torch.aten.squeeze.dim lowering with dynamic dims

lib/Conversion/TorchToStablehlo/Basic.cpp
I think we should use template parameters. @yyp0 @qingyunqu
=> [Stablehlo] fix template typo

lib/Conversion/TorchToTosa/TorchToTosa.cpp, projects/pt1/e2e_testing/xfail_sets.py
Change-Id: I2699bf9007723fe629edb1c524c10ef8142e0234
=> [TOSA] Add promote type to unary ops and aten.cat lowering

README.md
=> [torch-mlir][doc] remove MPACT as example

build-requirements.txt
=> Revert "[BUILD] Add nanobind to build-requirements"

build_tools/ci/test_posix.sh
Adds 1 minute to CI time (7 vs 8 minutes in this PR vs some other open PR).
=> ci: run fx_importer_tosa on nightly

projects/pt1/e2e_testing/xfail_sets.py
Resolves <https://github.com/llvm/torch-mlir/issues/4007>
=> Add failing tests to TOSA fx importer xfails

include/torch-mlir-c/TorchTypes.h, python/torch_mlir/extras/fx_importer.py
=> chore: remove redundant words

lib/Conversion/TorchOnnxToTorch/DefaultDomainQtoZ.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
Add check for default value of the resize op attribute keep_aspect_ratio_policy = "stretch"
=> [TorchOnnxToTorch] Handle default value for Resize op attribute

projects/ltc/csrc/base_lazy_backend/shape_inference.cpp
Added shape inference for AtenAsStridedOp
=> Add shape inference for AtenAsStrided

lib/Conversion/TorchToLinalg/Pooling.cpp
Fixes https://github.com/llvm/torch-mlir/issues/4085.
Sample errors before: https://github.com/iree-org/iree/actions/runs/13761122447/job/38477287335#step:9:7692
```
FAILED: compiler/plugins/input/Torch/torch-mlir/CMakeFiles/iree_compiler_plugins_input_Torch_torch-mlir_ConversionPasses.objects.dir/__/__/__/__/__/third_party/torch-mlir/lib/Conversion/TorchToLinalg/Pooling.cpp.obj 
C:\ProgramData\chocolatey\bin\ccache "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe"  /nologo /TP  -IC:\home\runner\_work\iree\iree -IC:\mnt\azure\b\095504 -IC:\home\runner\_work\iree\iree\third_party\torch-mlir\include -IC:\home\runner\_work\iree\iree\compiler\plugins\input\Torch -IC:\mnt\azure\b\095504\compiler\plugins\input\Torch …
```
=> Fix constexpr usage in TorchToLinalg/Pooling.cpp for MSVC.

lib/Conversion/TorchOnnxToTorch/ComMicrosoftDomain.cpp, test/Conversion/TorchOnnxToTorch/simple_ops_q_to_z.mlir
This commit adds the Onnx->Torch lowering for
Onnx.[QLinearSigmoid](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#commicrosoftqlinearsigmoid) op.
=> [ONNX] Add support for Onnx.QLinearSigmoid op

lib/Dialect/Torch/Utils/Utils.cpp, test/Dialect/Torch/torch-function-to-torch-backend-pipeline.mlir
Fixes https://github.com/iree-org/iree/issues/20570.
=> [TORCH] Add f8 support in `getConstantWithGivenDtypeAndValue` utility

lib/Conversion/TorchOnnxToTorch/OnnxRecurrentLayerOpExpanders.cpp, test/Conversion/TorchOnnxToTorch/ops/lstm.mlir
Issue: [nod-ai/SHARK-ModelDev#947](https://github.com/nod-ai/SHARK-ModelDev/issues/947)
- Implement dynamic dimension support for input tensor `X`
=> [ONNX] Add support for dynamic dimensions in onnx.LSTM

docs/development.md
- prefer numbered list over nesting of headers
=> [docs]: Make steps under "Configure for Building" easier to see

lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
Update LLVM to https://github.com/llvm/llvm-project/commit/8404b29b4151d95135ccc8d0d985be5ec8bb6f49
Changes made to function type APIs as per https://github.com/llvm/llvm-project/commit/7318074168e324097b7f6ec93e34915463bf70f1.
=> Integrate LLVM at 8404b29b4151d95135ccc8d0d985be5ec8bb6f49
