llvm/torch-mlir

CMakeLists.txt
lib/runtime/CMakeLists.txt
python/CMakeLists.txt
tools/npcomp-opt/CMakeLists.txt
tools/npcomp-run-mlir/CMakeLists.txt

* Since the manylinux images do not hard-link against python libs (resolving them at runtime), the module must be built without resolving undefined references.
* For some reason, builds on this platform are stricter, exposing dependency ordering issues.
* The CMake bits to build the extension are still somewhat of a mess. I have better versions both upstream and in IREE and will be reconciling. For now, don't look too closely.

Misc fixes to enable building/testing on manylinux2014 images.

---

CMakeLists.txt
lib/CMakeLists.txt
lib/Dialect/Basicpy/IR/CMakeLists.txt
lib/Dialect/Numpy/IR/CMakeLists.txt
lib/E2E/CMakeLists.txt
lib/JITRuntime/CMakeLists.txt
lib/Python/CMakeLists.txt
lib/runtime/CMakeLists.txt
python/CMakeLists.txt
tools/npcomp-opt/CMakeLists.txt

Mostly this is CMake cleanup.  Several library dependencies are missing, which
is often revealed with shared library builds.

[cmake] Updates for basic shared library support

---

lib/Python/CMakeLists.txt

This debug rule only works with add_mlir_library.

Fix build error

---

.gitmodules
build_tools/find_version_hashes.py

* I expect that mlir-hlo will be a non-optional dependency of the project, so adding as a sub-module.
* IREE is an optional dependency and I'm keeping this as an out-of-tree checkout for the moment.
* The script will compute the join across both iree and mlir-hlo to find a common LLVM version.
* The script needs some more work (like a flag that says to update the version, etc). Likely needs more testing through an integrate or two.

Add mlir-hlo as a submodule and add a script to find versions.

---

python/npcomp/torch/opdefs/aten_ops.py
python/npcomp/torch/opdefs/registry.py

* This extracts metadata from python invocations (nearly) sufficient to generate ODS and a Torch IR translation table for most of the ops.
* It also has the side effect of creating a data structure with meaningfully runnable examples suitable for an automated regression test.
* There are some ops that are sufficiently complex/weird (like _convolution) that we'll just manually handle those.
* See example output: https://gist.github.com/stellaraccident/60a58457b15e9184e224fa98a2658769

Initial work on a torch op registry.

---

lib/Dialect/Npcomprt/IR/NpcomprtOps.cpp

* mlir-hlo: 062a3ac4a0671d15b5199ed2cd3a9ce02a5bf077
Fixes:
* numInputs() just returns an int instead of requiring a call to .getLimitedValue()

Integrate upstream LLVM at 8d9c13f37d2081c11186718ae8b5aef8b507d152.

---

lib/Conversion/NumpyToTCF/Passes.cpp
lib/Conversion/TCFToTCP/TCFToTCP.cpp
lib/Conversion/TCPToLinalg/TCPToLinalg.cpp
lib/Dialect/ATen/ATenLoweringPass.cpp

This is a first step to register the dialects within the passes. It can be tested with 
```
--- a/tools/npcomp-opt/npcomp-opt.cpp
+++ b/tools/npcomp-opt/npcomp-opt.cpp
@@ -90,7 +90,8 @@ int main(int argc, char **argv) {
if (failed(MlirOptMain(output->os(), std::move(file), passPipeline, registry,
splitInputFile, verifyDiagnostics, verifyPasses,
-                         allowUnregisteredDialects))) {
+                         allowUnregisteredDialects,
+                         /*preloadDialectsInContext=*/false))) {
```
and fixes some of the tests.

Register dialects in conversion and ATen lowering passes

---

lib/Conversion/TCPToLinalg/TCPToLinalg.cpp
lib/E2E/E2E.cpp
lib/E2E/LowerRankedShapes.cpp
lib/E2E/LowerToHybridTensorMemRef.cpp
lib/E2E/LowerToLLVM.cpp
lib/E2E/LowerToNpcomprtABI.cpp

This make further progress on registering the dialects within the appropriate passes. It can be tested with
```
--- a/tools/npcomp-opt/npcomp-opt.cpp
+++ b/tools/npcomp-opt/npcomp-opt.cpp
@@ -90,7 +90,8 @@ int main(int argc, char **argv) {
if (failed(MlirOptMain(output->os(), std::move(file), passPipeline, registry,
splitInputFile, verifyDiagnostics, verifyPasses,
-                         allowUnregisteredDialects))) {
+                         allowUnregisteredDialects,
+                         /*preloadDialectsInContext=*/false))) {
```
with now only the following test still failing:
```
Failed Tests (3):
NPCOMP_OPT :: Dialect/Numpy/canonicalizers.mlir
NPCOMP_OPT :: Dialect/Numpy/public_functions_to_tensor.mlir
NPCOMP_OPT :: Dialect/Numpy/types_attrs.mlir
```

Register dialects in E2E passes

---

include/npcomp/Dialect/ATen/ATen.td
include/npcomp/Dialect/ATen/ATenDialect.h
include/npcomp/Dialect/Basicpy/IR/BasicpyDialect.h
include/npcomp/Dialect/Basicpy/IR/BasicpyDialect.td
include/npcomp/Dialect/Basicpy/IR/BasicpyOps.h
include/npcomp/Dialect/Npcomprt/IR/NpcomprtDialect.h
include/npcomp/Dialect/Npcomprt/IR/NpcomprtOps.h
include/npcomp/Dialect/Numpy/IR/NumpyDialect.h
include/npcomp/Dialect/Numpy/IR/NumpyDialect.td
include/npcomp/Dialect/Numpy/IR/NumpyOps.h
include/npcomp/Dialect/TCF/IR/TCFDialect.h
include/npcomp/Dialect/TCF/IR/TCFOps.h
include/npcomp/Dialect/TCP/IR/TCPDialect.h
include/npcomp/Dialect/TCP/IR/TCPOps.h
lib/Dialect/ATen/ATenDialect.cpp
lib/Dialect/Basicpy/IR/BasicpyOps.cpp
lib/Dialect/Npcomprt/IR/NpcomprtOps.cpp
lib/Dialect/Numpy/IR/NumpyOps.cpp
lib/Dialect/TCF/IR/TCFOps.cpp
lib/Dialect/TCP/IR/TCPOps.cpp

This refactors the namespace handling that has changed upstream. Furthermore, this 
*  bumps LLVM to llvm/llvm-project@7d1ed69 and
*  bumps MLIR-HLO to tensorflow/mlir-hlo@1880f87.

Refactor namespace handling

---

README.md
build_tools/cmake_configure.sh
build_tools/install_mlir.sh
docker/pytorch-1.3/Dockerfile
frontends/pytorch/csrc/type_dispatch/python_bindings.cpp
frontends/pytorch/lib/aten_ops.cpp
lib/JITRuntime/JITModule.cpp

* Includes pybind11 directly (for some reason using the pytorch helper header for this depends on a source file not in the image).
* Installs nnpack into the image.
* Installs new-clang and LLD and configures environment to use it (otherwise, link time is terrible).
* Fixes a gcc compile error (in the off chance you build with default gcc compiler).
* Tests are failing based on some dialect registration stuff that must not have been factored correctly. Will followup with a fix.

Update docker, instructions and some fixes for the pytorch 1.3 build.

---

docker/pytorch-1.3/Dockerfile
frontends/pytorch/csrc/type_dispatch/mlir_gen.cpp
frontends/pytorch/csrc/type_dispatch/mlir_gen.h

* This gets the pytorch frontend broadly working and what is left appears to be legitimate failures in 9 tests.
* Errors noted in #46

Explicitly load aten and std dialects when constructing a context.

---

include/npcomp/Dialect/TCF/IR/TCFOps.td
include/npcomp/Dialect/TCP/IR/TCPOps.td
lib/Conversion/TCFToTCP/TCFToTCP.cpp
lib/E2E/BypassShapes.cpp
lib/E2E/LowerShapeConstraints.cpp
lib/E2E/LowerToLLVM.cpp
lib/E2E/TensorToMemref/LowerShapedResultsToMemref.cpp
test/Conversion/TCFToTCP/basic.mlir
test/Dialect/TCF/ops.mlir
test/Dialect/TCP/ops.mlir
test/E2E/lower-shape-constraints.mlir
test/E2E/lower-shaped-results-to-memref.mlir
test/E2E/lower-to-llvm.mlir
test/npcomp-run-mlir/invalid-matmul.mlir
test/npcomp-run-mlir/matmul.mlir
tools/run_lit.sh

(also, a couple miscellaneous commits in this PR and an integrate (pending upstream submission of a patch))
I'm pretty happy with how this turned out. It looks pretty much like it
should -- one change at each layer. This particular op bottoms out on
linalg which takes care of the rest.
- Add tcf.matmul
- Add tcp.matmul
- Add TCF->TCP lowering
- Add tcp.matmul shape transfer function (BypassShapes.cpp)
- Add tcp.matmul -> linalg.matmul lowering (LowerShapedResultsToMemref.cpp)
- Add support to LowerShapeConstraints for lowering the new
shape.cstr_require
This matmul op is pretty limited in its capabilities. There is no
batching and no multidimensional contraction. Certainly more design work
will be needed to find the right abstractions that aren't too general
but also help to canonicalize …

[RefE2E] Add support for matmul.

---

lib/E2E/TensorToMemref/LowerStructuralToMemref.cpp
test/E2E/lower-structural-to-memref.mlir
test/npcomp-run-mlir/control-flow-basic.mlir

This also required adding a lowering for ForOp in our tensor->memref
conversion.

[RefE2E] Add interesting control flow example.

---

include/npcomp/Dialect/TCF/IR/TCFOps.td
include/npcomp/Dialect/TCP/IR/TCPOps.td
lib/Conversion/TCFToTCP/TCFToTCP.cpp
lib/E2E/BypassShapes.cpp
lib/E2E/TensorToMemref/LowerShapedResultsToMemref.cpp
test/Dialect/TCF/ops.mlir
test/Dialect/TCP/ops.mlir
test/E2E/bypass-shapes.mlir
test/E2E/lower-shaped-results-to-memref.mlir
test/npcomp-run-mlir/binary-elementwise.mlir

This cleans up the lowering pipeline to easily allow extending to
multiple binary ops. It looks fairly repetitive at multiple levels, but
I don't want to prematurely generalize. I think that in principle we
could derive a large swatch of TCF + TCP from a single linalg-style
specification. Another direction is to use an OpInterface (something
like "buildLinalgGenericBody"). I'm keeping my eye on it.
In a subsequent commit, I'll mechanically add a set of binary ops
modeled off of the std arithmetic ops.

[RefE2E] Add support for "max".

---

frontends/pytorch/csrc/c10_dispatch/CMakeLists.txt
frontends/pytorch/csrc/c10_dispatch/acap_dispatch.h
frontends/pytorch/csrc/c10_dispatch/func_builder.cpp
frontends/pytorch/csrc/c10_dispatch/func_builder.h
frontends/pytorch/csrc/c10_dispatch/module_builder.cpp
frontends/pytorch/csrc/c10_dispatch/module_builder.h
frontends/pytorch/csrc/c10_dispatch/python_bindings.cpp
frontends/pytorch/csrc/init_python_bindings.h
frontends/pytorch/csrc/pybind.h
frontends/pytorch/csrc/type_dispatch/python_bindings.cpp
frontends/pytorch/test/c10_dispatch/module_builder.py
include/npcomp-c/Types.h
lib/CAPI/CMakeLists.txt
lib/CAPI/Types.cpp
test/CAPI/CMakeLists.txt
test/CAPI/ir.c
test/CAPI/lit.local.cfg
test/CMakeLists.txt
test/lit.cfg.py

* Adds at::Tensor -> MlirValue tracking.
* Adds conversions for tensor and scalar types to MLIR types.
* Adds npcomp C APIs for constructing custom types.
* Reworks pybind include so as to get Torch pybind helpers (needed to pass at::Tensor type from Python->C++).

Add capture function arguments.

---

lib/E2E/TensorToMemref/LowerShapedResultsToMemref.cpp
test/E2E/lower-shaped-results-to-memref.mlir
test/npcomp-run-mlir/matmul.mlir

I was seeing some miscompiles due to the uninitialized data read here
before. Interestingly, this was masked in some of our previous test
cases, since the uninitialized data "always" was so small that it would
present as a rounding error for the 1.0-10.0 sized values that the
matmul was computing on.

[RefE2E] Initialize the linalg matmul accumulator buffer.

---

frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp
frontends/pytorch/csrc/c10_dispatch/acap_dispatch.h
frontends/pytorch/csrc/c10_dispatch/func_builder.cpp
frontends/pytorch/csrc/c10_dispatch/func_builder.h
frontends/pytorch/csrc/c10_dispatch/module_builder.cpp
frontends/pytorch/csrc/c10_dispatch/python_bindings.cpp
frontends/pytorch/test/c10_dispatch/module_builder.py
include/npcomp/Dialect/Torch/IR/TorchBase.td
include/npcomp/Dialect/Torch/IR/TorchOps.td

* Had to stop short of modifying the function return signature because of a missing C-API upstream.
* Committing here is good enough for a test and will resolve the various TODOs about upstream APIs next.

Implement torch.kernel_call capture.

---

README.md
build_tools/cmake_configure.sh
build_tools/docker_shell_funcs.sh
build_tools/install_mlir.sh
docker/pytorch-1.6/Dockerfile
docs/pytorch13_build.md

* Forks a subset of my shell functions into docker_shell_funcs.sh, specifically needed to create docker images that run as yourself.
* Extends the readme with the three command bootstrap to get a dev container running.
* Step by step instructions for configuring VSCode for Intellisense in either npcomp or LLVM.
* Changes LLVM config options to enable tests. This setup is now suitable for upstream changes as well without rebuilding.

Add scripts/documentation for VSCode setup with a docker dev image.

---

include/npcomp/RefBackend/RefBackend.h
lib/RefBackend/JITHelpers/JITModule.cpp
lib/RefBackend/RefBackend.cpp
test/RefBackend/e2e-basic.mlir
test/RefBackend/e2e-constants.mlir
test/RefBackend/e2e-mixed-ranks.mlir

Now the reference backend is cleanly accepts "TCP"+scalar ops.
We introduce tcf-refback-lowering-pipeline which also does TCF->TCP
conversion for convenience until we have a "target interface".

[RefBackend] Split out TCF->TCP conversion.

---

frontends/pytorch/test/acap_export/test_export_ResA.py
frontends/pytorch/test/acap_export/test_export_add3.py
frontends/pytorch/test/acap_export/test_export_batchnorm.py
frontends/pytorch/test/acap_export/test_export_conv2d_back.py
frontends/pytorch/test/acap_export/test_export_multi_out.py
frontends/pytorch/test/acap_export/test_export_resnet18.py
frontends/pytorch/test/acap_export/test_export_vgg11.py
frontends/pytorch/test/lit.cfg.py

* Sadly, non-trivial ones fail.
* Bugs filed and marked XFAIL.

Port prior acap export tests to new dispatcher based versions.

---

include/npcomp/Dialect/Refback/IR/RefbackOps.td
lib/Dialect/Refback/IR/RefbackOps.cpp
lib/RefBackend/RefBackend.cpp
lib/RefBackend/TensorToMemref/LowerConstantTensorsToMemref.cpp
lib/RefBackend/TensorToMemref/LowerShapedResultsToMemref.cpp
lib/RefBackend/TensorToMemref/LowerStdToMemref.cpp
lib/RefBackend/TensorToMemref/LowerStructuralToMemref.cpp
test/Dialect/Refback/canonicalize.mlir
test/RefBackend/lower-constant-tensors-to-memref.mlir
test/RefBackend/lower-shaped-results-to-memref.mlir
test/RefBackend/lower-std-to-memref.mlir
test/RefBackend/lower-structural-to-memref.mlir
tools/bash_helpers.sh

Now that it has grown source/target materialization capabilities
(spelled with ops tensor_load/tensor_to_memref), we can use it. We can
also now delete refback.memref_to_tensor/refback.tensor_to_memref.
This is also a first step to reducing the downstream functionality
needed in the refback dialect.

[RefBackend] Use upstream BufferizeTypeConverter

---

README.md
build_tools/docker_shell_funcs.sh
docker/pytorch-nightly/Dockerfile
frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp
frontends/pytorch/csrc/c10_dispatch/acap_dispatch.h
frontends/pytorch/csrc/c10_dispatch/func_builder.cpp
frontends/pytorch/csrc/c10_dispatch/func_builder.h
frontends/pytorch/test/CMakeLists.txt
frontends/pytorch/test/acap_export/test_export_batchnorm.py
include/npcomp-c/Types.h
include/npcomp/Dialect/Numpy/IR/NumpyDialect.h
include/npcomp/Dialect/Torch/IR/TorchBase.td
lib/CAPI/Types.cpp
lib/Dialect/Numpy/IR/NumpyDialect.cpp

* Now gets far enough to capture batch_norm.
* Has some issues still with in-place ops.
* Can materialize constants.
* Includes an upgrade to PyTorch nightly, which has important bug fixes for fallback and boxed kernel dispatch.
* Fixes #78, #79, #80.
* Will do more testing in a follow-up once further bugs are fixed that facilitate getting at the other features.

More progress on PyTorch acap device capture.

---

.github/workflows/buildAndTest.yml

The add-path command is deprecated and should be replaced as stated in
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Replace deprecated add-path in GitHub Action

---

lib/Python/CMakeLists.txt

Fix linker error:
lib/Python/libNPCOMPPythonCommon.a(MlirInit.cpp.o): in function `mlir::npcomp::python::npcompMlirInitialize()':
mlir-npcomp/build/../lib/Python/MlirInit.cpp:46: undefined reference to `npcompInitializeLLVMCodegen'

Add missing dependency on NPCOMPCAPI from NPCOMPPythonCommon

---

include/npcomp/Dialect/TCF/IR/TCFOps.td
include/npcomp/Dialect/TCP/IR/TCPOps.td
lib/Conversion/TCFToTCP/TCFToTCP.cpp
lib/Dialect/TCP/Transforms/Bufferize.cpp
test/npcomp-run-mlir/elementwise.mlir

Register the following for the multiply op:
- tcf.mul
- tcp.mul
- TCP->TCP lowering
- Shape transfer, broadcasted multiplicands
- Lower to standard `MulFOp` op

[RefBackend] Support element-wise multiply op

---

frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp
frontends/pytorch/csrc/c10_dispatch/acap_dispatch.h
frontends/pytorch/csrc/c10_dispatch/func_builder.cpp
frontends/pytorch/test/acap_export/test_conv_nllloss_grads.py

* This is sufficient to capture the forward and backward pass and gradients of a convolutional model with an nllloss.
* As with the forward conv, the backward conv is a special case wrapped in an enigma on the PyTorch side. There aren't many like it, so special casing is just what we do.
* When I traced this, I found that the copy_ op is not yet boxing compatible so I had to map it manually. If there are many more like this, I'll probably do something a bit more clever to reduce duplication.
* This exposes new signature patterns that will need to be handled by the ATen lowering. Will take care of that next: It will be nice to have an e2e of a non-trivial case with full gradients.
* Fixes #97.

Capture backward conv and copy_ kernels.

---

frontends/pytorch/examples/mul_maximum_e2e.py
frontends/pytorch/python/torch_mlir_utils/codegen/torch_signature_ods_gen.py
include/npcomp/Conversion/ATenToTCF/Passes.h
include/npcomp/Conversion/ATenToTCF/Patterns.h
include/npcomp/Conversion/Passes.td
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.cpp.inc
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.td
lib/Conversion/ATenToTCF/CMakeLists.txt
lib/Conversion/ATenToTCF/ConvertATenToTCFPass.cpp
lib/Conversion/ATenToTCF/CoreOpConversionPatterns.cpp
lib/Conversion/CMakeLists.txt
lib/Conversion/Passes.cpp
test/Conversion/ATenToTCF/core_op_conversions.mlir

* Conversions are very simple, suporting mul, maximum and add (alpha=1 only).
* Example added with pass pipeline needed to run.
* Much missing off of the golden path but sufficient for such simple cases.

Add aten.maximum op and conversions from aten->tcf.

---

include/npcomp/Conversion/Passes.td
include/npcomp/Conversion/TCFToLinalg/TCFToLinalg.h
include/npcomp/Conversion/TCFToStd/TCFToStd.h
include/npcomp/Dialect/TCP/IR/TCPOps.td
lib/Conversion/CMakeLists.txt
lib/Conversion/Passes.cpp
lib/Conversion/TCFToLinalg/CMakeLists.txt
lib/Conversion/TCFToLinalg/TCFToLinalg.cpp
lib/Conversion/TCFToStd/CMakeLists.txt
lib/Conversion/TCFToStd/TCFToStd.cpp
lib/Conversion/TCFToTCP/TCFToTCP.cpp
lib/Dialect/TCP/Transforms/Bufferize.cpp
lib/RefBackend/RefBackend.cpp
test/Conversion/TCFToLinalg/basic.mlir
test/Conversion/TCFToStd/basic.mlir
test/Conversion/TCFToTCP/basic.mlir
test/Dialect/TCP/bufferize.mlir
test/Dialect/TCP/ops.mlir

This removes most ops from our homegrown "TCP" dialect and replaces them with std elementwise ops + linalg named ops on tensors.
This seems like a strict improvement over the homegrown "tcp.add". But we're still very much experimenting in how far we can take std elementwise + linalg named ops on tensors. Definitely the "init tensor" stuff is a bit clunky, and the builders are pretty hard to use (they look more or less like the ones on linalg.generic, rather than a simple  `create<Matmul>(loc, lhs, rhs)`).
Suggest reviewing individual commits for clarity (sorry, can't stack PR's on github).

Replace most of "TCP" with std elementwise ops + linalg named ops on tensors

---

include/npcomp/Dialect/Refback/IR/RefbackOps.td
lib/Dialect/TCP/Transforms/Bufferize.cpp
lib/RefBackend/RefBackend.cpp
test/RefBackend/lower-alloc-memref-ops.mlir

It was annoying that we were creating shape.get_extent in the middle of
the bufferization pipeline, as it required running convert-shape-to-std
at an awkward place. To make that cleaner, just open-code the
extract_element ops that shape.get_extent expands into.
This is a little gross, but it helps with the macroscopic pipeline
ordering issues. Anyway, the train is long-gone of trying to treat
shapes as some special data type that should only be operated on with
shape ops.
Also,
- reorder tensor constant bufferize (which is a module pass) to bracket
all the bufferization function passes, to make the parallelism
opportunities there clearer. Now we have a very clean little
bufferization segment of our pipeline construction.

[RefBackend] Open-code shape.get_extent as extract_element

---

include/npcomp/RefBackend/RefBackend.h
lib/RefBackend/RefBackend.cpp

This allows invoking TCF to TCP-level conversion more easily, and starts
us towards a path of factoring it out of the RefBackend.

[RefBackend] Add refback-tcf-to-tcp-pipeline

---

frontends/pytorch/csrc/builder/CMakeLists.txt
python/CMakeLists.txt
tools/mnist-playground/CMakeLists.txt

After the recent change of cmake variables
from PYTHON_INCLUDE_DIRS to Python3_INCLUDE_DIRS
and PYTHON_LIBRARIES to Python3_LIBRARIES, there were
a few files that still had references to the old
variables. This patch fixes that.

Update PYTHON cmake variables to Python3

---

frontends/pytorch/examples/mm_e2e.py
frontends/pytorch/python/torch_mlir_utils/codegen/torch_signature_ods_gen.py
include/npcomp/Dialect/ATen/IR/ATenOpStatisticsUtils.h
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.cpp.inc
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.td
include/npcomp/Dialect/ATen/IR/LegacyGeneratedATenOps.td
lib/Conversion/ATenToTCF/CoreOpConversionPatterns.cpp
lib/Dialect/ATen/IR/ATenDialectOpStats.cpp
python/npcomp/compiler/pytorch/backend/refjit.py

Note that unlike aten.matmul which has dynamic behavior
depending on the argument ranks (can do matrix-matrix, matrix-vector,
batch matmul, etc.), aten.mm is just a vanilla matrix
multiply, which can be lowered precisely to tcf.matmul.
The "test" is really just an example that I stared at while getting my
feet wet with this. We probably want something that actually tests this
as part of `ninja check-npcomp`.

Add aten.mm op and "test" it e2e.

---

README.md
build_tools/cmake_configure.sh

Also, update README.md to use the canonical .env file written by
`cmake_configure.sh`.

cmake_configure.sh: Add mlir native modules to PYTHONPATH

---

frontends/pytorch/csrc/CMakeLists.txt
frontends/pytorch/csrc/builder/CMakeLists.txt
frontends/pytorch/csrc/builder/acap_dispatch.cpp
frontends/pytorch/csrc/builder/acap_dispatch.h
frontends/pytorch/csrc/builder/func_builder.cpp
frontends/pytorch/csrc/builder/func_builder.h
frontends/pytorch/csrc/builder/graph_importer.cpp
frontends/pytorch/csrc/builder/graph_importer.h
frontends/pytorch/csrc/builder/module_builder.cpp
frontends/pytorch/csrc/builder/module_builder.h
frontends/pytorch/csrc/builder/python_bindings.cpp
frontends/pytorch/csrc/pybind.h
frontends/pytorch/test/acap_export/test_export_add3.py
frontends/pytorch/test/graph_export/test_script_add3.py
frontends/pytorch/test/graph_export/test_script_debug_info.py
include/npcomp-c/Types.h
lib/CAPI/Types.cpp

* Does not handle all features yet but should conservatively fail on unsupported things.
* Location tracking is still somewhat mismatched between what TorchScript and MLIR do. Likely need a better heuristic for tracking locations from defs for nodes that do not carry location.
* Sets the ground-work for a specialized/generic split but only implements the generic side.
* Had some evidence that this requires a recent bump of PT nightly (within the last month) to pick up pybind11 2.6, which includes some cross-module symbol fixes (vs the previously sync'd version). No source changes, but older versions fail to cast function types at runtime.

Add TorchScript graph importer.

---

include/npcomp/RefBackend/Runtime/UserAPI.h
lib/RefBackend/Runtime/Runtime.cpp

Although `refCount` is initialized as `std::atomic<int> refCount{0};` in
the definition of Tensor, our tail-allocating malloc would ignore it,
resulting in bogus values that led to leaks.
Caught with LeakSanitizer, but I added an assertion that the refcount is
non-negative to begin with, which should catch this bug in the future
fairly consistently (assuming the garbage refcount is negative half the
time).

[RefBackend] Properly initialize refbackrt::Tensor refcount.

---

.gitignore
frontends/pytorch/python/torch_mlir_utils/codegen/torch_signature_ods_gen.py

- Added `REG_OP_TYPE` and `SIGLIST_TYPE` to better characterize the registered ops data structure.
- Generally expanded typing.
- Add `pytype: disable` statements to make it green where it gets confused.
- Small typo fixes.
- Made yapf make slightly better decisions by using trailing commas:
```python
opdef.return_transforms(type_transforms={
"Tensor:0": "AnyTorchImmutableTensor",
},
flag_transforms={
":0": ["kImmutableTensor"],
})
```
```python
opdef.return_transforms(
type_transforms={
"Tensor:0": "AnyTorchImmutableTensor",
},
flag_transforms={
":0": ["kImmutableTensor"],
},
)    ^
```

Expand pytype coverage for torch_signature_ods_gen.py

---

.github/workflows/buildAndTest.yml
cmake/modules/NpcompDetectPythonEnv.cmake
frontends/pytorch/csrc/builder/acap_dispatch.cpp
frontends/pytorch/csrc/builder/func_builder.cpp
frontends/pytorch/csrc/builder/func_builder.h
frontends/pytorch/csrc/builder/graph_importer.cpp
frontends/pytorch/csrc/builder/mlir_utils.h

* Incorporates changes around LLVM StringRef.
* Ports fix in upstream pybind11 detection.
* Disables CI hack due to broken pybind detection.

Bump LLVM version to 4f5355ee73626f8b8fe6bf0dd6d167fea7628a2c.

---

frontends/pytorch/examples/cos_e2e.py
frontends/pytorch/examples/mm_e2e.py
frontends/pytorch/examples/mul_maximum_e2e.py
frontends/pytorch/examples/test_utils.py
python/npcomp/compiler/pytorch/backend/refjit.py

- Add `test_utils` to dedupe jit comparison code and make testing multiple inputs easier
- Use `refjit.CompilerBackend` to make things a bit more obvious for the clueless.
- Add `TorchJitModuleInvoker` to allow `torch.Tensor`s to be passed to module invocations
- Add `cos_e2e.py` which is "failing" due to #135.
I did a cursory dig through the bindings for `capture_function` but am not familiar enough with C++ debug this on my own.
Adding `torch.cos` because I hit a number of walls trying to add `torch.diag`.

Add cos_e2e.py, test_utils and support for tensor inputs

---

lib/RefBackend/Runtime/CMakeLists.txt
python/CMakeLists.txt

--version_script doesn't work on OSX.
Shared libs are .dylibs on OSX.
TEST=Build on iMac Pro. M1 has other issues will be fixed later
Change-Id: I2bda46349a878b8265e273c05d8db6b46c0df633

Fix OSX builds.

---

build_tools/cmake_configure.sh
build_tools/install_mlir.sh

TEST=Build on OSX systems without GNUutils + zsh
Change-Id: I573855b93a08e1746e0bb214be28b4a3ea8264ca

Use custom realpath. Its unavailable in newer OSX

---

CMakeLists.txt
frontends/pytorch/test/CMakeLists.txt
frontends/pytorch/test/lit.cfg.py
frontends/pytorch/test/lit.site.cfg.py.in
include/npcomp/Conversion/CMakeLists.txt
test/lit.cfg.py
test/lit.site.cfg.py.in

This allows building NPCOMP as an external project of LLVM, similar to
how CIRCT can be built: https://github.com/llvm/circt/pull/227.
The CMake options to use this build style look like this:
```
-DLLVM_EXTERNAL_PROJECTS=npcomp \
-DLLVM_EXTERNAL_NPCOMP_SOURCE_DIR=/path/to/mlir-npcomp \
```

Enable building using LLVM_EXTERNAL_PROJECTS.

---

frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/mlir_utils.h
frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/csrc/builder/op_builder.cpp
frontends/pytorch/csrc/builder/op_builder.h
frontends/pytorch/test/module_import/list.py
frontends/pytorch/test/module_import/object-identity-error-submodule.py
frontends/pytorch/test/module_import/object-identity-error.py
frontends/pytorch/test/module_import/object-identity-torch-bug.py
frontends/pytorch/test/module_import/object-identity.py
frontends/pytorch/test/module_import/prim.py
frontends/pytorch/test/module_import/submodules.py
include/npcomp-c/Types.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/Types.cpp
test/CAPI/ir.c

Handle object identity properly. Adds support for list to help testing non-Tensor cases where object identity matters.
Turns out TorchScript doesn't model it right (`object-identity-torch-bug.py`). If they fix their stuff our code will import it correctly though.
Recommend reviewing commits separately.

Object identity

---

frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/test/module_import/submodules-select.py

PyTorch added a Global variable `_is_full_backward_hook` recently which breaks most module importer tests.
See https://github.com/pytorch/pytorch/pull/46163

Add NoneType support for ivalue_importer

---

frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/test/graph_import/tuple.py
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
test/Dialect/Torch/globalize-object-graph-error.mlir
test/Dialect/Torch/globalize-object-graph-module-uses-error.mlir
test/Dialect/Torch/globalize-object-graph-module-uses.mlir

This happens in practice. With this, we can globalize slots for the
non-trivial classifier layer obtained from
https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb

Extend GlobalizeObjectGraph to handle torch.prim.GetAttr returning NnModuleType

---

frontends/pytorch/utils/pt_util.py
lib/Dialect/Basicpy/IR/BasicpyDialect.cpp
lib/Dialect/Torch/IR/TorchDialect.cpp

With this + manually setting private visibility on everything, a simple
classifier can be reduced to this IR, which is looking pretty lean and
mean:
https://gist.github.com/silvasean/19e7e2e21a61ff197aeac0dd864d188f
Also, include a utility script for importing `.pt` models.
```
pt_util.py --import classifier.pt | npcomp-opt -torch-globalize-object-graph
```

Add trivial inliner interfaces.

---

frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/test/node_import/prim.py
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td

With this, we can import BERT!
```
pt_util ~/tmp/bert.pt  --import --exported-name=forward \
| npcomp-opt -torch-globalize-object-graph -inline -symbol-dce
```
https://gist.github.com/silvasean/fe7735ff5d065cc9216f7b0346d0e977
The test case here is a bit unconventional -- it isn't actually valid
Python. To figure out how to generate it I had to go search the PyTorch
codebase for "NumToTensor" and work backward. In this case I found
this
[code](https://github.com/pytorch/pytorch/blob/649760e5f12b90a29559785ac2b3cb132cb3bf84/torch/csrc/jit/frontend/ir_emitter.cpp#L464)
which via a wild guess I was able to turn into a test case.
In this case it didn't take me too long, but when doing this kind of
"add a bunch of trivial stuff to bring up a real model", I'm starting to
think that we might …

Add support for prim.NumToTensor

---

include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
test/Dialect/Torch/globalize-object-graph-error.mlir
test/Dialect/Torch/globalize-object-graph-initializers.mlir
test/Dialect/Torch/globalize-object-graph-submodules.mlir
test/Dialect/Torch/globalize-object-graph.mlir

This is a much simpler representation than the ad-hoc initializer
function we had before. It is also less general, but given the rationale
in Passes.td it seems like the right tradeoff right now.
We can probably carry this representation for quite a while, and when we
can't, it likely means that TorchScript has fixed their object identity
bug and we probably need to just upgrade to a more general object graph
modeling (more general than GlobalizeObjectGraph).
In particular, we don't want to deal with defining and carrying around
this initializer function concept until we need it. For example, if we
want to constant-fold the global slots into uses, this is a much better
representation, and it plays better with symbol-dce (the initializer
function counts as a "use" of the symbol).
(the …

Give torch.global_slot an initializer region.

---

docker/pytorch-nightly/Dockerfile

The pybind11 comes with ubuntu 20.04  is version 2.4 but version 2.6 is required

install pybind11 through pip to get version 2.6

---

frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/test/ivalue_import/strings.py

* Add's support for importing String type's and corresponding test.
The existence of both a `basicpy.BytesType` and a `basicpy.StrType` is a little confusing since in this case we are creating a String in the torch test (which is unicode encoded by default in py3) but we have been using `basicpy.BytesType` for these constants so far for the `node_importer`. 
Let me know if we should be representing these as `basicpy.StrType` instead of `basicpy.BytesType`. If so I can go ahead and expose the `basicpy.StrType` to the C-API.

[torch] Add import support for IValue string Type(s)

---

include/npcomp/RefBackend/JITHelpers/JITModule.h
include/npcomp/RefBackend/Runtime/UserAPI.h
lib/Backend/RefJIT/PythonModule.cpp
lib/RefBackend/JITHelpers/JITModule.cpp
lib/RefBackend/Runtime/Runtime.cpp
tools/npcomp-run-mlir/npcomp-run-mlir.cpp

* Adds a new `RuntimeValue` struct at the Runtime abstraction (very similar to `torch::jit::IValue`)
* Adds the boilerplate to support more than just `Tensor`'s (still a TODO, but the api shouldn't need to change for each argument type now)
* Updates all the uses of `invoke` to use the new API.
Recommended review order:
- UserAPI.h for definition of the `RuntimeValue` struct and changes to invoke interface
- npcomp-run-mlir.cpp for changes to how `invoke` is called
- JITModule.h / Runtime.cpp for other updates to using `RuntimeValue`

[refbackrt] Update Invoke API to support more than just Tensor's

---

lib/Dialect/Basicpy/IR/BasicpyOps.cpp
lib/Dialect/Refbackrt/IR/RefbackrtOps.cpp
lib/RefBackend/Runtime/Runtime.cpp
tools/npcomp-run-mlir/npcomp-run-mlir.cpp

Motivated by https://github.com/llvm/circt/pull/749/commits/4bdd468179423cb860ee62294f3e90877261c797

Update .getAttrs to ->getAttrs as it is deprecated.

---

frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/test/ivalue_import/methods-derefine.py
frontends/pytorch/test/node_import/prim.py
include/npcomp-c/Types.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/Types.cpp

Model obtained from here: https://pytorch.org/hub/snakers4_silero-models_stt/
With https://github.com/llvm/mlir-npcomp/pull/184 we also can globalize it. IR: https://gist.github.com/silvasean/8ee109f2289cf721c679d0623a48bfca
The current inliner's cost model results in about 8x bloat, so the IR shown there has lots of missing inlining opportunities. Need to add a better cost model (even just "inline it if it is private and only one call" would probably do a lot of good).
Recommended review order: commit by commit

Get Silero speech-to-text model imported and globalized

---

include/npcomp/Dialect/Torch/IR/TorchOps.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/Transforms/Passes.h
include/npcomp/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
lib/Dialect/Torch/Transforms/Passes.cpp
lib/Dialect/Torch/Transforms/PrepareForGlobalizeObjectGraph.cpp
test/Dialect/Torch/globalize-object-graph-error.mlir
test/Dialect/Torch/globalize-object-graph-free-functions.mlir
test/Dialect/Torch/globalize-object-graph-methods.mlir
test/Dialect/Torch/globalize-object-graph-module-uses.mlir
test/Dialect/Torch/globalize-object-graph-multiple-instances-error.mlir
test/Dialect/Torch/globalize-object-graph-multiple-instances-multiple-module-args.mlir
test/Dialect/Torch/globalize-object-graph-multiple-instances.mlir
test/Dialect/Torch/prepare-for-globalize-object-graph.mlir

This happens in practice with e.g. ResNet from torchvision (multiple
instances of the same BatchNorm class).
The key observation is that for this program, and the expected set of
programs, we can convert the program to the same globalized form with a
bit more static analysis and effort to suitably monomorphize the
program. Though what we are doing here is fairly annoying to implement,
it saves any nontrivial later pass from having to do similar analyses
(or worse). E.g. shape inference would need to be object-graph aware,
mutation/lifetime analyses would have to be aware, etc. Additionally, it
would make us front-load what it means to have a !torch.nn.Module type
on an ABI boundary, which we are just not ready to handle.
I'm really, really hoping that in practice we can get away with …

Support multiple instances of a class in GlobalizeObjectGraph.

---

.github/workflows/buildAndTest.yml
frontends/pytorch/csrc/builder/acap_dispatch.cpp
frontends/pytorch/test/acap_export/test_export_nms.py

Without also fallback on autograd dispatch keys, `torchvision::nms` complains:
```
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'AutogradPrivateUse2' backend.
CPU: registered at /root/project/torchvision/csrc/ops/cpu/nms_kernel.cpp:111 [kernel]
PrivateUse2: registered at ../frontends/pytorch/csrc/builder/acap_dispatch.cpp:568 [backend fallback]
```
Not sure why it goes to 'AutogradPrivateUse2' backend instead of 'PrivateUse2' though.

Also fallback autograd dispatch keys for torchvision::nms

---

frontends/pytorch/examples/div_inplace_e2e.py
frontends/pytorch/examples/tanh_out_e2e.py
frontends/pytorch/python/torch_mlir_utils/codegen/torch_signature_ods_gen.py
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.cpp.inc
include/npcomp/Dialect/Numpy/IR/NumpyOps.td
include/npcomp/Dialect/Torch/IR/OpInterfaces.h
lib/Dialect/ATen/Transforms/RecognizeKernelsPass.cpp
python/npcomp/compiler/pytorch/backend/refjit.py
test/Dialect/ATen/recognize_aten_kernels.mlir
test/Dialect/Numpy/ops.mlir

We already had the `promoteTrailingOutTensor` flag, but weren't using
it. A inplaceVariantKernelName flag needed to be added.
This change is a little dissatisfying, as the conversions done by the
RecognizeKernelsPass are currently non-orthogonal. In particular,
`kDropResultAndAliasArg0` probably won't work as intended if mixed with
these (we probably need to promote kDropResultAndAliasArg0 to not be an
arg-level thing anyway, as we have done with promoteTrailingOutTensor).
This involved adding a new op `numpy.overwrite_array`.
```
numpy.overwrite_array %arg2 overwrites %arg0 : tensor<2x3xf32>, !numpy.ndarray<[2,3]:f32>
```
This models the destructive update behavior. Note that in the above op,
we cannot simply RAUW %arg0 with a suitably conveted %arg2 (for example,
%arg0 might have uses …

Add support for "trailing_" and "out" variants of various ops.

---

lib/CAPI/Registration.cpp
python/npcomp/compiler/pytorch/backend/refjit.py

Simple rejiggering of the python code to layer `"object graph" -> "acap-like" -> "tcf" -> ...`
Tested/developed locally on my e2e spike (unary tanh).

Add ability to compile from object graph ir.

---

include/npcomp/Dialect/Numpy/IR/NumpyOps.h
include/npcomp/Dialect/Numpy/IR/NumpyOps.td
include/npcomp/Dialect/Numpy/Transforms/Passes.h
include/npcomp/Dialect/Numpy/Transforms/Passes.td
include/npcomp/Dialect/Torch/Transforms/Passes.h
include/npcomp/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Numpy/IR/NumpyOps.cpp
lib/Dialect/Numpy/Transforms/ArrayToTensor.cpp
lib/Dialect/Numpy/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
lib/Dialect/Torch/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
lib/RefBackend/LowerToLLVM.cpp
python/npcomp/compiler/numpy/frontend.py
python/npcomp/compiler/pytorch/backend/refjit.py
python/npcomp/tracing/mlir_trace.py
test/Dialect/Numpy/array-to-tensor.mlir
test/Dialect/Numpy/canonicalizers.mlir
test/Dialect/Numpy/ops.mlir
test/Dialect/Torch/adjust-calling-conventions.mlir

Recommended review order: commit by commit.
Two main changes:
- pass that adjusts calling conventions to incorporate torch.type_bound (and eliminate dummy NoneType returns + tuples eventually)
- primitive ArrayToTensor pass
Next steps are to write shape/dtype refinement stuff and then we can run on refbackend (immediately after will pull in IREE an run e2e with that).

Progress on e2e lowering

---

frontends/pytorch/examples/test_utils.py
frontends/pytorch/examples/torchscript_tanh_e2e.py
include/npcomp/Dialect/Numpy/Transforms/Passes.h
include/npcomp/Dialect/Numpy/Transforms/Passes.td
include/npcomp/Dialect/Torch/Transforms/Passes.h
include/npcomp/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Numpy/Transforms/CMakeLists.txt
lib/Dialect/Numpy/Transforms/RefinePublicReturn.cpp
lib/Dialect/Torch/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/npcomp/compiler/pytorch/backend/refjit.py
test/Dialect/Numpy/refine-public-return.mlir
test/Dialect/Torch/refine-types.mlir

Recommended review order: commit by commit
Two main changes:
- type refinement pass (only does shape/dtype refinement; simple intraprocedural forward dataflow)
- "refine public return" pass (see description for why needed; it adjusts public calling conventions so needs careful attention)
This is a huge milestone!
```
silvasean@silvasean0:~/pg/mlir-npcomp/mlir-npcomp$ npcpy frontends/pytorch/examples/torchscript_tanh_e2e.py 
ninja: Entering directory `/home/silvasean/pg/mlir-npcomp/mlir-npcomp/build'
[1/1] Running utility command for NPCOMPPythonResources
Input args:
(tensor([[[0.4963],
[0.7682],
[0.0885]],
[[0.1320],
[0.3074],
[0.6341]]]),)
SUCCESS
PyTorch Result:
[[[0.45916808]
[0.6458943 ]
[0.08824728]]
[[0.1312686 ]
[0.29809073]
[0.5608543 ]]]
JIT Result:
[[[0.45916805]
[0.6458943 ] …
```

MILESTONE: TorchScript unary tanh runs on RefBackend

---

lib/Conversion/TCFToTCP/CMakeLists.txt

Trivial fix to a build error caused by `cmake` visiting TCF->TCP conversion before the TCP dialect.

Declare TCP dialect dependency in TCFToTCP conversion

---

frontends/pytorch/examples/cos_e2e.py
frontends/pytorch/examples/div_inplace_e2e.py
frontends/pytorch/examples/mm_e2e.py
frontends/pytorch/examples/mul_maximum_e2e.py
frontends/pytorch/examples/tanh_out_e2e.py
frontends/pytorch/examples/torchscript_tanh_e2e_iree.py
include/npcomp/Backend/IREE/CMakeLists.txt
include/npcomp/Backend/IREE/Passes.h
include/npcomp/Backend/IREE/Passes.td
include/npcomp/Backend/IREE/README.md
include/npcomp/CMakeLists.txt
lib/Backend/IREE/CMakeLists.txt
lib/Backend/IREE/LowerLinkage.cpp
lib/Backend/IREE/PassDetail.h
lib/Backend/IREE/Passes.cpp
lib/CAPI/Registration.cpp
lib/CMakeLists.txt
lib/InitAll.cpp
python/npcomp/compiler/pytorch/backend/frontend_lowering.py
python/npcomp/compiler/pytorch/backend/iree.py
test/Backend/Iree/Sample/simple_invoke.py
test/Backend/Iree/lower-linkage.mlir

Recommended review order:
- Changes in frontends/pytorch/examples/
- Changes in python/npcomp/compiler/pytorch/backend/
- Boilerplate for the `npcomp-iree-backend-lower-linkage` pass.
This change separates out a
`npcomp.compiler.pytorch.backend.frontend_lowering` module that does the
common lowering for all backends. The individual compiler backends
`npcomp.compiler.pytorch.backend.{refjit,iree}` now accept a loosely
defined "TCP + scalar code" IR mix that will be formalized in the
future as the interface to codegen backends.
This also required adding a small pass
`npcomp-iree-backend-lower-linkage` which adds `iree.module.export` onto
functions, and layering that into the frontend flow. The pass doesn't
require a C++-level dependency on IREE, which is nice for now. TBD how
we are going …

Add support for compiling through IREE.

---

frontends/pytorch/examples/torchscript_mm_e2e.py
include/npcomp/Conversion/ATenToLinalg/ATenToLinalg.h
include/npcomp/Conversion/Passes.td
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.td
lib/Conversion/ATenToLinalg/ATenToLinalg.cpp
lib/Conversion/ATenToLinalg/CMakeLists.txt
lib/Conversion/ATenToTCF/CoreOpConversionPatterns.cpp
lib/Conversion/CMakeLists.txt
lib/Conversion/Passes.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/npcomp/compiler/pytorch/backend/frontend_lowering.py
test/Conversion/ATenToLinalg/basic.mlir
test/Dialect/Torch/refine-types.mlir

This is our first op with error semantics, and stresses the system.
There are a few design notes of special interest:
- RefineTypes.cpp's note about shape inference in the presence of code
that dynamically produces and error, and it is provable statically.
- ATenToLinalg.cpp's notes about future automation of the ATen->linalg
path.
- The notes in Passes.td about using low-tech `std.assert` ops instead
of `shape.assuming`.
Note: Doesn't work on IREE yet due to the `std.assert` op (needs to be
lowered to `vm.fail` on the IREE side).

Add `aten.mm` to linalg lowering.

---

frontends/pytorch/python/torch_mlir_utils/codegen/torch_signature_ods_gen.py
include/npcomp/Dialect/ATen/IR/ATenOps.td
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.cpp.inc
include/npcomp/Dialect/ATen/IR/GeneratedATenOps.td
lib/Dialect/ATen/IR/ATenDialectOpStats.cpp
lib/Dialect/ATen/Transforms/RecognizeKernelsPass.cpp
lib/Dialect/Basicpy/IR/BasicpyDialect.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/ATen/recognize_aten_kernels.mlir
test/Dialect/Basicpy/canonicalize.mlir
test/Dialect/Torch/refine-types.mlir

This op has complex aliasing semantics, so it is kept mutable for now.
With this, we reduce ResNet18 to a single BB with all aten operators
having rank + dtype:
https://gist.github.com/silvasean/2fcb1c6e4d4ae27461204a43ae9c5031

Add flatten op recognition + shape refinement.

---

frontends/pytorch/csrc/builder/acap_dispatch.cpp
frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/op_builder.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/test/ivalue_import/annotations/arg-tensor-type-bound.py
frontends/pytorch/test/ivalue_import/functions-that-call-methods.py
frontends/pytorch/test/ivalue_import/methods-derefine.py
frontends/pytorch/test/ivalue_import/prim.py
frontends/pytorch/test/node_import/function-derefine.py
frontends/pytorch/test/node_import/if.py
frontends/pytorch/test/node_import/loop.py
frontends/pytorch/test/node_import/prim.py
frontends/pytorch/test/node_import/types-none.py
include/npcomp-c/Types.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/Types.cpp
lib/Dialect/Torch/IR/TorchDialect.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
test/Dialect/Torch/GlobalizeObjectGraph/module-uses.mlir
test/Dialect/Torch/GlobalizeObjectGraph/multiple-instances-error.mlir
test/Dialect/Torch/adjust-calling-conventions.mlir
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/ops.mlir

- Add `torch.constant.none` op to construct it (naming is chosen to be
analogous to Torch's representation of a prim::Constant with
NoneType, rather than using the "singleton" terminology of Basicpy).

Introduce native `!torch.none` type.

---

frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/test/ivalue_import/tuple.py
frontends/pytorch/test/node_import/prim.py
frontends/pytorch/test/node_import/tuple.py
include/npcomp-c/TorchTypes.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/TorchTypes.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
test/Dialect/Torch/ops.mlir

This further eliminates the need for the `basicpy` dependency.
This required adding `torch.prim.TupleConstruct` to replace
`basicpy.build_tuple`.

Add `!torch.tuple<T1, T2>` type.

---

frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
frontends/pytorch/test/ivalue_import/submodules-select.py
frontends/pytorch/test/node_import/elif.py
frontends/pytorch/test/node_import/if.py
frontends/pytorch/test/node_import/prim.py
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
include/npcomp/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/Passes.cpp
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/ops.mlir

This removes the use of `scf.if`, which required laundering back and
forth between `i1` and `!torch.bool` in the frontend. We will eventually
lower this op to `scf.if`, but this results in a cleaner IR and layering
at the frontend.
I also put in another commit for fixing a constant folding issue.
Recommended review order: commit by commit

Add `torch.prim.If`

---

frontends/pytorch/csrc/builder/func_builder.cpp
frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
frontends/pytorch/test/ivalue_import/primitives.py
frontends/pytorch/test/ivalue_import/quantization.py
frontends/pytorch/test/node_import/loop.py
include/npcomp-c/TorchTypes.h
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
include/npcomp/Dialect/Torch/IR/GeneratedPrimOps.td
include/npcomp/Dialect/Torch/IR/GeneratedQuantizedOps.td
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/TorchTypes.cpp
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/IR/TorchDialect.cpp
lib/Dialect/Torch/Transforms/BackendTypeConversion.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
test/Dialect/Torch/GlobalizeObjectGraph/basic.mlir
test/Dialect/Torch/GlobalizeObjectGraph/error.mlir
test/Dialect/Torch/GlobalizeObjectGraph/free-functions.mlir
test/Dialect/Torch/GlobalizeObjectGraph/methods.mlir
test/Dialect/Torch/GlobalizeObjectGraph/module-uses.mlir
test/Dialect/Torch/GlobalizeObjectGraph/submodules.mlir
test/Dialect/Torch/GlobalizeObjectGraph/visibility.mlir
test/Dialect/Torch/finalizing-backend-type-conversion.mlir
test/Dialect/Torch/func-backend-type-conversion.mlir
test/Dialect/Torch/ops.mlir
test/Dialect/Torch/prepare-for-globalize-object-graph.mlir

This removes the dependence of the `torch` dialect on the low-level
builtin types.
Now the `torch` dialect is a standalone layer, suitable for targeting
from higher-level Python abstractions without any premature lowering to
primitive types.

Add a !torch.float type.

---

frontends/pytorch/csrc/builder/acap_dispatch.cpp
frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/test/acap_export/test_arange.py
frontends/pytorch/test/acap_export/test_export_add3.py
frontends/pytorch/test/acap_export/test_export_conv2d_fwd.py
frontends/pytorch/test/ivalue_import/object-identity.py
frontends/pytorch/test/ivalue_import/quantization.py
frontends/pytorch/test/ivalue_import/tensors.py
include/npcomp/Dialect/Torch/IR/TorchOps.td
lib/Conversion/TorchToStd/TorchToStd.cpp
lib/Dialect/Torch/IR/TorchDialect.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
test/Conversion/TorchToStd/basic.mlir
test/Dialect/Torch/GlobalizeObjectGraph/basic.mlir
test/Dialect/Torch/GlobalizeObjectGraph/error.mlir
test/Dialect/Torch/inline-global-slots.mlir
test/Dialect/Torch/invalid.mlir
test/Dialect/Torch/ops.mlir
test/Dialect/Torch/reduce-op-variants.mlir

This op is much better behaved than the `torch.tensor.literal` op
(which is the new name of the `torch.tensor` op). In particular
`torch.tensor.literal`:
- always has a maximally refined type.
- always has value semantics.
- can be constant folded / CSE'd.
ReduceOpVariants is changed to perform the transformation from
`torch.tensor.literal` to `torch.vtensor.literal` (which in general
involves static information casts and copies.
This new op also allowed tightening up `torch.tensor.literal` to only
accept NonValueTensorType (instead of any tensor type).
This new ".literal" name is more descriptive. It was getting too
confusing seeing an op called just `torch.tensor` (we originally called
it that because that's the name of the similar function in the Torch
Python API, but it just doesn't …

Add `torch.vtensor.literal` op.

---

lib/Dialect/Torch/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/Passes.cpp

Recent changes in MLIR have changed the canonicalization for the `memref.dim` op. To clean it up, we now need the createResolveShapedTypeResultDimsPass().
This results in cleaner IR. In particular, Mlp2LayerModule e2e test has
a dim op that is eliminated by this change:
https://gist.github.com/silvasean/734f11a291ae6236c955f65cffae285f

Clean up `memref.dim` ops better.

---

frontends/pytorch/e2e_testing/torchscript/basic.py
include/npcomp/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

This removes most of the trivial cases that MaximizeValueSemantics needs
to handle, making it easier to see the nontrivial cases.

Make `torch.copy.tensor` canonicalization a bit smarter.

---

frontends/pytorch/e2e_testing/torchscript/batchnorm.py
frontends/pytorch/e2e_testing/torchscript/main.py
frontends/pytorch/python/torch_mlir/torchscript/e2e_test/reporting.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

1. Added a simplified version of torch.aten.batch_norm which only handles
inference and assumes the weight, bias, running_mean, running_var are not
None.
2. Removed the primitive types check in verifyLinalgCompatibleTypes check
since now we have proper type converter to handle torch types conversion.
The checks for RankedTensorType is kept because the type converter
doesn't guarantee the converted builtin tensor type is ranked. A
separate verification pass to verify the invariant expected by later
passes will need to be added before those can be removed as well.

Add torch.aten.batch_norm Linalg lowering support

---

include/npcomp/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/Passes.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/adjust-calling-conventions.mlir
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/maximize-value-semantics.mlir
test/Dialect/Torch/reduce-op-variants.mlir
test/Dialect/Torch/refine-public-return.mlir
test/Dialect/Torch/refine-types.mlir

This adds a pattern to MaximizeValueSemantics which does a simple
abstract interpretation within a block, which handles simple cases of
`torch.overwrite_tensor`, enough to remove all the unnecessary uses of
non-value tensors in ResNet right now.
Before/after IR:
[gist](https://gist.github.com/silvasean/a3e1ef625b19dfc63579f73cd3b543b6)
Also,
- Split `torch.copy.tensor` into `torch.copy.to_tensor` and
`torch.copy.to_vtensor` which convert between value and non-value
semantic tensors. This is a much cleaner factorization as they have
very separate use cases and properties (e.g. different side effects)
- Remove the various canonicalization patterns they had, which were
confusing because they resulted in limited forms of maximizing value
semantics throughout the pipeline. We should structure …

Make MaximizeValueSemantics a bit smarter.

---

README.md
frontends/pytorch/e2e_testing/torchscript/main.py
frontends/pytorch/e2e_testing/torchscript/xfail_sets.py
frontends/pytorch/examples/cos_e2e.py
frontends/pytorch/examples/div_inplace_e2e.py
frontends/pytorch/examples/mm_e2e.py
frontends/pytorch/examples/mul_maximum_e2e.py
frontends/pytorch/examples/tanh_out_e2e.py
frontends/pytorch/examples/torchscript_mm_e2e.py
frontends/pytorch/examples/torchscript_tanh_e2e.py
frontends/pytorch/examples/torchscript_tanh_e2e_iree.py
frontends/pytorch/python/torch_mlir/torchscript/e2e_test/configs/__init__.py
frontends/pytorch/python/torch_mlir/torchscript/e2e_test/configs/npcomp_backend.py
frontends/pytorch/python/torch_mlir/torchscript/e2e_test/reporting.py
frontends/pytorch/test/torchscript_e2e_test/basic.py
frontends/pytorch/test/torchscript_e2e_test/compilation_failure.py
frontends/pytorch/test/torchscript_e2e_test/miscompile.py
python/npcomp/compiler/pytorch/backend/__init__.py
python/npcomp/compiler/pytorch/backend/abc.py
python/npcomp/compiler/pytorch/backend/iree.py
python/npcomp/compiler/pytorch/backend/refjit.py
tools/torchscript_e2e_test.sh

- Add support for "expected failures" in test reporting. The new error
reports look like
[this](https://gist.github.com/silvasean/6ffd95e1d55302b699673da201da210d).
- We will now be able to put these tests into CI, since the harness
understand which tests are expected to pass and fail.
- Refactor RefBackendTestConfig to NpcompBackendTestConfig which
supports both RefBackend and IREE.
- Add instructions for installing IREE dependencies (both from packages
and for local builds of IREE)
- Add `tools/torchscript_e2e_test.sh` for invoking the e2e test
harness (this makes invoking a bit easier, as it doesn't rely on a
loose Python invocation).

Add IREE support in TorchScript e2e tests.

---

lib/Conversion/TCFToLinalg/TCFToLinalg.cpp
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/RefBackend/CMakeLists.txt
lib/RefBackend/LowerToLLVM.cpp
lib/RefBackend/RefBackend.cpp
test/Conversion/TCFToLinalg/basic.mlir
tools/npcomp-shlib/CMakeLists.txt

* Added additional *ToLLVM conversion patterns (they were disaggregated from standard).
* Misc renames.
* Spelling change on ConvNCHW op, and it now expects strides and dilations attributes.

Bump llvm-project to a085c23aa3c8f91866d7f4588d4f683407dc775d.

---

frontends/pytorch/python/torch_mlir/torchscript/e2e_test/framework.py
lib/RefBackend/Runtime/Runtime.cpp
python/npcomp/compiler/generic/backend/refjit.py
python/npcomp/types.py

* Change aligned_alloc -> malloc. It can fail (and does on MacOS) and is a bit over-aggressive optimization for a reference backend.
* Fixed a fragile test that prints -0.0 on MacOS.
* Fail the test (not the framework) on failure to trace (Torch on MacOS is missing features).
* Fix .so -> .dylib for compiler runtime.

Misc fixes for MacOS.

---

.gitignore
pyproject.toml
setup.py

* There will be a separate setup.py for the frontends/pytorch directory but a couple of things need to land for that first (we need to be able to build that standalone, include C headers in the npcomp-core package, and then wire it together).
* Should be sufficient to automate via cibuildwheel in order to get manylinux and multiple python versions.

Add basic setup.py file for the npcomp-core package.

---

frontends/pytorch/python/torch_mlir/torchscript/e2e_test/reporting.py

`Conv2dNoPaddingModule_basic` and `Conv2dWithPaddingModule_basic` start
failing because of results accuracy after changing conv_2d linalg ops from tc ops to 
yaml ops in upstream.

Lower accuracy to make e2e pass

---

tools/CMakeLists.txt
tools/npcomp-lsp-server/CMakeLists.txt
tools/npcomp-lsp-server/npcomp-lsp-server.cpp

To use, do `ninja npcomp-lsp-server`, copy `build/bin/npcomp-lsp-server`
into your PATH somewhere, and then add
```
"mlir.server_path": "npcomp-lsp-server",
```
to your settings.json.
Also bump llvm-project to 2d9759c7902c5cbc9a7e3ab623321d5578d51687 to
bring in latest `mlir-lsp-server` changes.

Add npcomp-lsp-server.

---

frontends/pytorch/e2e_testing/torchscript/main.py
frontends/pytorch/e2e_testing/torchscript/xfail_sets.py

ResNet works with static shapes. (our test is not static though).
All tests blocked on https://github.com/google/iree/issues/6629

Triage e2e IREE failures for npcetest.

---

build_tools/update_torch_ods.sh
frontends/pytorch/csrc/builder/ivalue_importer.cpp
frontends/pytorch/csrc/builder/node_importer.cpp
frontends/pytorch/csrc/builder/torch_to_mlir_utils.cpp
frontends/pytorch/test/ivalue_import/dict.py
frontends/pytorch/test/node_import/dict.py
frontends/pytorch/test/node_import/errors.py
frontends/pytorch/test/node_import/tuple.py
include/npcomp-c/TorchTypes.h
include/npcomp/Dialect/Torch/IR/TorchOps.td
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/TorchTypes.cpp
lib/Dialect/Torch/IR/TorchOps.cpp

This includes the following changes to import MT model into MLIR. There
are still a lot of work to do for actual compilation.
- Add `torch.dict<>`, `torch.any`, `torch.number` types
- Add `torch.prim.DictConstruct` op
- Fix `torch.prim.TupleConstruct` op assembly format to include resulting types

Import Machine Translation model to MLIR.

---

frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
frontends/pytorch/test/acap_export/test_conv_nllloss_grads.py
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
include/npcomp/Dialect/Torch/IR/GeneratedPrimOps.td
include/npcomp/Dialect/Torch/IR/TorchOps.h
include/npcomp/Dialect/Torch/IR/TorchTypes.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
test/Dialect/Torch/GlobalizeObjectGraph/basic.mlir
test/Dialect/Torch/GlobalizeObjectGraph/error.mlir
test/Dialect/Torch/canonicalize.mlir
tools/run_lit.sh

With the following changes the compilation can continue until
RefineTypes pass:
- Add operators without ODS into `torch_ods_gen.py`
- Add some new optional and list types in `TorchTypes.td`
- Add some folders for aten int type comparator ops
- Modify GlobalizeObjectGraph.cpp. For global slots that's not used,
dont check if an aliased value is stored in more than one of global
slots. This can work around a failure where the same tensor is stored
in multiple "version" slots which are not used.

Fix compilation errors from MT model

---

frontends/pytorch/e2e_testing/torchscript/elementwise.py
frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

Adds a pretty straightforward lowering for Sigmoid following the existing conventions for relu and tanh. 
Would it be appropriate to mirror the lit tests for tanh in ./test/Conversion/TorchToLinalg/elementwise.mlir and /test/Dialect/Torch/refine-types.mlir? Any other tests required for this kind of patch?

Sigmoid lowering to linalg

---

frontends/pytorch/e2e_testing/torchscript/elementwise.py
frontends/pytorch/e2e_testing/torchscript/main.py
frontends/pytorch/e2e_testing/torchscript/reduction.py
frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

Adds a lowering for the two versions of `torch.sum` (with and without dimensions specified). The lowering is based on the one used for `Tosa->Linalg` in `MLIR`.
In addition, this PR also includes a general `ConversionPattern` (`ConvertReduceOp`) that can be easily extended to include any other `torch` operations that result in a reduction of tensors.
The only problem I am having at the moment is that when I run the tests I wrote at the same time as the test for `ResNet18Module_basic` in https://github.com/llvm/mlir-npcomp/blob/main/frontends/pytorch/e2e_testing/torchscript/elementwise.py, at least one of the `sum` tests fails non-deterministically. If I run the test suite without the `ResNet18Module_basic`, my tests pass every single time.
In order to implement the version of `torch.sum` …

Torch.sum lowering to Linalg

---

frontends/pytorch/python/torch_mlir_torchscript/e2e_test/reporting.py
frontends/pytorch/test/torchscript_e2e_test/error_reports.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

We were not filling the `outs` with the neutral element of the
reduction, which resulted in reading uninitialized values (we were
getting lucky that sometimes the uninitialized buffers were all zero's).
Also,
- Slight tweak to error messages in the e2e framework.

Fix lowering of reduce ops

---

frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py
include/npcomp/Dialect/Torch/IR/GeneratedAtenOps.td
include/npcomp/Dialect/Torch/IR/GeneratedPrimOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/canonicalize.mlir

This contains the following changes:
- Fix optional knowledge propagation. The initial knowledge should
always be NotNone for the operations we implemented.
- Add Folder for `prim.dtype`

MT model compilation minor changes

---

frontends/pytorch/e2e_testing/torchscript/list_programs.py
frontends/pytorch/e2e_testing/torchscript/xfail_sets.py
frontends/pytorch/python/torch_mlir_torchscript_e2e_test_configs/npcomp_backend.py
include/npcomp/Backend/Common/Passes.h
include/npcomp/Backend/Common/Passes.td
include/npcomp/Dialect/TorchConversion/Transforms/Passes.h
include/npcomp/Dialect/TorchConversion/Transforms/Passes.td
lib/Backend/Common/CMakeLists.txt
lib/Backend/Common/DeleteDeadIREELists.cpp
lib/Dialect/TorchConversion/Transforms/AnnotateABI.cpp
lib/Dialect/TorchConversion/Transforms/CMakeLists.txt
lib/Dialect/TorchConversion/Transforms/Passes.cpp
lib/RefBackend/RefBackend.cpp
python/npcomp/compiler/pytorch/backend/iree.py
test/Dialect/TorchConversion/annotate-abi.mlir

This plumbs through a vertical slice of support for lists.
The main chunk of new code here is AnnotateABIPass which captures the
program signature at the Torch backend contract layer, right before we
start `TorchConversion`. The `TorchConversion` lowering process is lossy
w.r.t. types, so it's necessary to do this for all targets in general.
Like using `!iree.list` directly, we use IREE's ABI annotation
representation for this, although there is nothing very IREE-specific
about it (see
https://github.com/google/iree/blob/main/docs/developers/design_docs/function_abi.md)
We change `ListLiteralModule_basic` to use `!torch.int` because IREE
doesn't support f64 yet (and we don't yet have a way for users to say
that they want `!torch.float` to lower as f32).
Recommended review order:
- …

Add basic support for lists.

---

.github/workflows/buildAndTest.yml
python/CMakeLists.txt

This brings back `check-npcomp-all` and the refbackend e2e tests
coverage.

Bring CI back to life.

---

external/torch-mlir/python/CMakeLists.txt

Should fix issue noted in #304

Include the builtin and std dialects in the torch_mlir python build.

---

e2e_testing/torchscript/basic.py
external/torch-mlir/build_tools/build_standalone.sh
external/torch-mlir/include/torch-mlir/CMakeLists.txt
external/torch-mlir/include/torch-mlir/RefBackend/CMakeLists.txt
external/torch-mlir/include/torch-mlir/RefBackend/Passes.h
external/torch-mlir/include/torch-mlir/RefBackend/Passes.td
external/torch-mlir/lib/CMakeLists.txt
external/torch-mlir/lib/InitAll.cpp
external/torch-mlir/lib/RefBackend/CMakeLists.txt
external/torch-mlir/lib/RefBackend/PassDetail.h
external/torch-mlir/lib/RefBackend/RefBackend.cpp
external/torch-mlir/python/CMakeLists.txt
external/torch-mlir/python/TorchMLIRModule.cpp
external/torch-mlir/test/RefBackend/munge-calling-conventions.mlir
lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
lib/Dialect/TorchConversion/Transforms/Passes.cpp
python/npcomp/compiler/pytorch/backend/refjit.py
test/Conversion/TorchToIREE/basic.mlir
test/Dialect/TorchConversion/finalizing-backend-type-conversion.mlir

`tools/torchscript_e2e_test.sh` is all green.
This needs a few passes I put into torch-mlir/lib/RefBackend (not to be
confused with `npcomp/lib/RefBackend`, which will soon be deleted).
For the sake of review, since this brings together a lot of things, I
split this into its own commit. I temporarily commented out some "list"
stuff that we are going to remove as part of the torch-mlir refocus.

Bring up new RefBackend.

---

e2e_testing/torchscript/main.py
examples/torchfx/examples/example_add_tanh_sigmoid.py
examples/torchscript_resnet18_e2e.py
python/NpcompModule.h
python/npcomp/compiler/pytorch/backend/refbackend.py
python/torch_support/npcomp_torchscript_e2e_test_configs/npcomp_backend.py

We now use RefBackend/refbackend consistently.

Remove "refjit" terminology.

---

e2e_testing/torchscript/basic.py
external/torch-mlir/include/torch-mlir-c/TorchTypes.h
external/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchOps.td
external/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
external/torch-mlir/lib/CAPI/TorchTypes.cpp
external/torch-mlir/lib/Dialect/Torch/IR/TorchOps.cpp
external/torch-mlir/lib/Dialect/Torch/IR/TorchTypes.cpp
external/torch-mlir/lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
external/torch-mlir/lib/Dialect/Torch/Transforms/RefineTypes.cpp
external/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp
external/torch-mlir/test/Dialect/Torch/reduce-op-variants-error.mlir
external/torch-mlir/test/Dialect/Torch/reduce-op-variants.mlir
include/npcomp/Dialect/TorchConversion/IR/TorchConversionOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
test/Dialect/TorchConversion/ops.mlir

Also contain the following changes:
- Remove derefineOp canonicalizer because it's not safe.
- i64 dtype tensor arguement support for refbackend.
- Support for optional tensor and list tensors in reduceOpVariant. This
only works for some special detected and easy to handle cases. For list,
it covers the case list is got from a `ListConstruct`. For optional, it
covers the case optional is constructed from a `DerefineOp`.
- Remove the `inferReturnTypes` for `FromBuiltinTensorOp` because it's
not safe to deduce types from the input. For example, a built-in tensor
of i8 could be converted to si8 or ui8. It's better to let the user
specify the return type explicitly. Also, delete the `getFromShaped` from
{Non,}ValueTensorType.

E2e implementation for `aten.cat`,`aten.gather`, `aten.bmm`

---

examples/torchfx/examples/example_add_tanh_sigmoid.py

Fixes typo `import torchfx2iree ...` -> `import torchfx ...`, and updates example to use `numpy` types when using the `NpcompBackend`.

Fix import typo in torchfx example

---

build_tools/torchscript_e2e_heavydep_tests/bert_seq_classification.py
build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh
build_tools/torchscript_e2e_heavydep_tests/main.py
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp

Use torch tracing to get the module because the original model is not
TorchScriptable out of box.
IR: [here](https://gist.github.com/8744f903bc402ae45ea68086f0673d52)

Add BertSequenceClassification model to e2e

---

examples/lazytensor/README.md

Adds `README.md` file with information on currently missing op support in the TorchScript backend of the Lazy Tensor Core (LTC).
It is not yet clear to me that running the metrics report captures every single operation that takes place during a computation. In other words, could be that there are more unsupported ops that we are not seeing because LTC is simply ignoring them.

Notes on missing support for lazy tensor ops

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/xfail_sets.py

This is a simple way for externals to plug their backends into the test
suite. They just implement the `TestConfig` class for their backend and
write a small script that exposes it.
I have a pending PR for iree-samples that successfully integrates this.

Add --external-config option to tools/torchscript_e2e_test.sh

---

lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
test/RefBackend/munge-calling-conventions.mlir

I'm concerned that both of the following show up regardless of the functions return type:
func private @refbackend_consume_int64_func_return(memref<*xi64>) attributes {llvm.emit_c_interface}
func private @refbackend_consume_float32_func_return(memref<*xf32>) attributes {llvm.emit_c_interface}
Please don't hesitate with criticisms, definitely out of my "elementType" here = )

add i64 support to refbackend

---

e2e_testing/torchscript/basic.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Conversion/TorchToLinalg/basic.mlir

The lowering of `aten.Int.Tensor` op has been added.
The changes has been made as a part of `convert-torch-to-linalg` pass.

Add lowering of `aten.Int.Tensor` op.

---

e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

The lowering of `torch.log` op has been added.

Add lowering of `torch.log` op

---

e2e_testing/torchscript/basic.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp

This commit adds decomposition of `aten.Expand` to `aten.BroadcastTo`
op.

[TORCH][MLIR] Add E2E support for aten.expand

---

e2e_testing/torchscript/basic.py
lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
test/RefBackend/munge-calling-conventions.mlir

Support for returning elemental types. Previously, only
memref types as returning types was supported. All the hacky ways
to write tests which return elemental types should be taken care of.

Adding support for returning elemental types.

---

e2e_testing/torchscript/basic.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Conversion/TorchToLinalg/basic.mlir
test/Dialect/Torch/refine-types.mlir

This looks to be working, but this is the first time I've had to write a test case in mlir.

Add NumToTensor

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/type_conversion.py
e2e_testing/torchscript/type_promotion.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
python/torch_mlir_e2e_test/torchscript/reporting.py
test/Dialect/Torch/refine-types.mlir

This is to facilitate scalar type conversion in the TorchToLinalg. As
part of adding the helper, this PR also:
- Updated `AtenAddTensorOp`, `AtenSubTensorOp` to use the helpers to
support more type variants.
- Added e2e type promotion testing.
- Added i32 memref return/arg type to support e2e testing.

Add convertScalarToDtype helper.

---

e2e_testing/torchscript/backprop.py
e2e_testing/torchscript/basic.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

This PR also added a helper for scalar type conversion in the
TorchToLinalg file. Will need https://github.com/llvm/torch-mlir/pull/392 to add more complete testing for the helper.

Add e2e suport for aten._softmax_backward_data

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp
test/Conversion/TorchToTosa/basic.mlir

- Remove use of conversion construction macros
- Add mul and div op conversions
- Add corresponding tests

[mlir][tosa] Refactor conversions to use templates

---

e2e_testing/torchscript/basic.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

This commit fixes a bug with the way `ConvertAtenOnesOp` was matching on
the `pin_memory` bool argument, adds an error message for when the 
`pin_memory` is not false, and adds a unit test.
The reason the match was failing was because `matchPattern` was being given the
element from the `operands` list corresponding to `pin_memory`, which has been
casted to type `i1` by an `unrealized_conversion_cast`, instead of the operand from
`AtenOnesOp`. Since the `matchPattern` expected a `!torch.bool` the match
would always fail regardless of the value of `pin_memory`.

Fix bug in handling of pin_memory in AtenOnesOp conversion

---

e2e_testing/torchscript/backprop.py
e2e_testing/torchscript/basic.py
e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedPrimOps.td
include/torch-mlir/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
lib/Dialect/Torch/Transforms/Passes.cpp
lib/RefBackend/RefBackend.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
test/Dialect/Torch/adjust-calling-conventions.mlir
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/refine-public-return.mlir
test/RefBackend/munge-calling-conventions.mlir

This change is to unblock the work of some backprop ops returning more
than one tensors. We will need to think of a more scalable approach
in the future if more flexible return types combinations are needed.

Add support for multiple return values

---

e2e_testing/torchscript/backprop.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds new operation `aten.gelu_backward` in the aten
dialect and adds lowering of this operation from aten to linalg.

[TORCH][MLIR] Add E2E support for `aten.gelu_backward` operation.

---

e2e_testing/torchscript/mlp.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Now, aten::linear supports rank 3 inputs. This is a fix
for upcoming bert-inference task. The correct way should be
to support broadcasting in `aten.matmul` op and decompose
`aten.linear` into right ops.

Support aten::linear with rank 3 inputs

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds lowering of `aten.mul.Scalar` and also adds
decomposition of `aten.addmm` to `aten.mul.Scalar`, `aten.add.Tensor`
and `aten.mm` ops.

[MLIR][TORCH] Add E2E support for [`aten.mul.Scalar`|`aten.addmm`]

---

e2e_testing/torchscript/backprop.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

`aten.log_softmax_back_data` op lowering and required
tests has been added.

Add e2e test for `aten.log_softmax_back_data` op

---

e2e_testing/torchscript/basic.py
lib/Dialect/Torch/Transforms/RefineTypes.cpp

This commit fixes a type promotion bug when NumToTensor was given a
float as an argument. In particular, the rules for type promotion of a
scalar vary depending on if the scalar is part of a tensor op or
not. NumToTensor falls under the second category, but it was being
treated as part of the first category.
This bug was encountered here https://github.com/llvm/torch-mlir/pull/430.
@cathyzhyi PTAL.

Fix bug in NumToTensor handling of float values

---

e2e_testing/torchscript/elementwise.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

This commit adds lowering of `aten.div.Scalar`.

[MLIR][TORCH] Add E2E support for aten.div.Scalar

---

e2e_testing/torchscript/basic.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp

The lowering of aten.fill.Scalar has been added.
The changes have been made as a part of -torch-convert-to-linalg pass.

Add aten.fill.Scalar op lowering

---

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

This is to fold the common pattern from Bert inference like:
```
%111 = torch.prim.NumToTensor.Scalar %110 : !torch.int ->
!torch.vtensor<[],si64>
%112 = torch.aten.Int.Tensor %111 : !torch.vtensor<[],si64> ->
!torch.int
```

Add folder for torch.aten.Int.Tensor

---

e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

Support `aten.abs` and `aten.reciprocal` ops lowering to linalg.
I did not deal with the reciprocal of 0 especially. Is that necessary in `TrochToLinalg.cpp`?
Any suggestion would be grateful! Thanks!

aten.abs and aten.reciprocal to linalg

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/squeeze.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

This commit adds lowering of `aten.Squeeze` op into
`linalg.TensorCollapseShape` op. The size 1 dynamic dimensions are not
handled as a part of this commit.

[MLIR][TORCH] Add E2E support for `aten.squeeze` op

---

e2e_testing/torchscript/reduction.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

Many reduction ops take as an argument an optional output dtype that
can change the type of the input tensor before the reduction is
performed. This commit adds support for the optional dtype flag that
had been previously ignored.
Test:
/tools/torchscript_e2e_test.sh -f 'ReduceSumDtype'
/tools/torchscript_e2e_test.sh -f 'ReduceSumDImIntListDtype'

Add support for dtype argument in reduction ops

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/reduction.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

The lowering of `aten.mean` op has been added.

[MLIR][TORCH] Add E2E support for aten.mean op

---

e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds lowering of aten.bitwise_and.tensor
Signed-Off By: Vivek Khandelwal vivek@nod-labs.com

[MLIR][TORCH] Add E2E support for aten.bitwise_and.tensor

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/main.py
e2e_testing/torchscript/slice_like.py
e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/refine-types.mlir

Probably should have just kept dropout separate. One issue with dropout is that it has an argument called p, which is the probability an element is zero'd. This has a naming conflict the the asm printer p. I'm not sure what the best way to avoid this is, and am open to suggestion. Currently to work I just edited the generated cpp file, but that obviously isn't upstreamable.
I've tried so far to model slice in a way that it easily extends to other slice like ops. My plan is to continue to generalize things out of the `if (auto SliceTensor = dyn_cast<AtenSliceTensorOp>(op)) ` statement. 
There is currently an issue with AtenSliceTensor when there is a start and end for each dimension. For a reason I have yet to determine, the final dimension always maintains the shape of the original tensor …

Add lowering for slice and select int

---

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

There is an op name change that requires trivial changes.
Also, some of the warning has been fixed.

Bug fixes that pops up when updating generatedAten ops td

---

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h
include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h
lib/Conversion/TorchToTosa/CMakeLists.txt
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Conversion/TorchToTosa/basic.mlir

- Supports variants with multiple dims, one dim, all dime
- Leverages legalize_common and legalize_utils code from
TensorFlow-TOSA work

[tosa] Add Torch reduction operators

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/nll_loss.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

The op lowering has been added as a part of `torch-lower-to-linalg`
pass. This takes care of ignore_index but the weight and reduction
operand is still to be accounted for.

Add aten::nll_loss_forward op lowering.

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/xfail_sets.py
lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py

Support for passing memref of bool types as a function argument
and return type is added in the ref-backend.

Add support for passing & returning memref of bool types

---

e2e_testing/torchscript/conv.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Previously aten.conv2d was only lowered if there was no bias.
Here lowering is extended to support bias.

Linalg lowering for aten.conv2d(bias=True)

---

e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds lowering of `aten.gt.Scalar` and `aten.where.self` as a
part of element-wise ops lowering.

[TORCH][MLIR] Add E2E support for [`aten.gt.Scalar`|`aten.where.self`]

---

e2e_testing/torchscript/squeeze.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

This commit adds lowering of `aten.Squeeze.dim` op into
`linalg.TensorCollapseShape` op. The size 1 dynamic dimension is not
handled as a part of this commit.

[TORCH][MLIR] Add E2E support for `aten.squeeze.dim` op

---

e2e_testing/torchscript/batchnorm.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds support for aten.native_layer_norm operation. Here
the previous code for aten.layer_norm is tweaked a little bit to
accomodate both mean and variance values alongwith the layer norm
value. This commit also adds decomposition of aten.layer_norm into
aten.native_layer_norm, which was previously getting lowered directly
to linalg.
Signed-Off-By: Prateek Gupta<prateek@nod-labs.com>

[MLIR][TORCH] Add E2E support for `aten.native_layer_norm`.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This patch adds the where, gt, bucketize and reshape
ops to the Torch dialect. These ops are present in the histogram
calibration module.
TEST: Successfully lowers ops to Torch dialect in histogram module.

Add where, gt, bucketize and reshape ops to Torch dialect

---

e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds lowering of `aten.ceil` op as a part of element-wise
ops lowering.

[TORCH][MLIR] Add E2E support for `aten.ceil` op

---

e2e_testing/torchscript/elementwise.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

`aten.gt.Tensor` op has been added in torch dialect and the
lowering of the op has been done to the linalg dialect.

Add `aten.gt.Tensor` op

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/elementwise.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

- Templatize `aten.zeros` and `aten.ones` ops lowering.
- Add E2E support for `aten.empty` op.
- Add Integer type support in `aten.mul.Scalar` op lowering.

[TORCH][MLIR] Templatize lowering of [`aten.zeros|aten.ones|aten.empty`] ops

---

e2e_testing/torchscript/elementwise.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Support for integer types in gtScalar op has been added.
The code share same logic with gtTensor op and can be merged
which is added as a TODO.

Add support for int types in gtScalar op.

---

e2e_testing/torchscript/basic.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/refine-types.mlir

Add the required lowerings and correct test cases.
These op produce zero-d tensors and it was incorrectly mentioned in
refine types to produce 1d tensor of size 1.

Add aten.tensor.int and aten.tensor.float op lowerings.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit fixes the naming of results in the torch ODS generator
when dealing with multiple results. In particular, this commit appends
an index to each result name to guarantee that they are all unique.

Fix naming of results in ODS generator

---

e2e_testing/torchscript/slice_like.py
e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Adds a check for optional type, and covers the case where end < start. Thanks to @cathyzhyi for pointing these out.

Small fixes for slice edge cases

---

e2e_testing/torchscript/basic.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

This commit adds decomposition of `aten.empty_like` into `aten.empty`
op.

[TORCH][MLIR] Add E2E support for `aten.empty_like` op

---

e2e_testing/torchscript/view.py
include/torch-mlir/Dialect/Torch/IR/TorchOps.h
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

We only handle the expanding OR collapsing cases, we do not handle
expanding And collapsing happening at the same time or cases where
it's neither collapsing nor expanding like view of [2,3] for
3x2 tensor.
It's assumed that if a shape list element is got from
`aten.size(tensor, dim)` the corresponding dim is not splitted or
collapsed. This assumption makes it easier to deal with dynamic shapes.

Lower aten::view with linalg.collapse and linalg.expand

---

e2e_testing/torchscript/elementwise.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

`aten.add.Scalar` and `aten.sub.Scalar` op conversions have been added.
The changes have been made as a part of `-convert-torch-to-linalg` pass.

Add Add and Sub scalar op conversions.

---

e2e_testing/torchscript/arange.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds lowering of `aten.arange.start_step` op.
This commit decomposes `aten.arange` and `aten.arange.start` into
`aten.arange.start_step` op.

[MLIR][TORCH] Add E2E support for torch.arange op

---

e2e_testing/torchscript/conv.py
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/refine-types.mlir

In RefineTypes.cpp, the return `dtype` was being determined for conv2d and maxpool2d, but the shape was not. This code adds static shape computation then the operator arguments provide the required static details.
This may relate to/clash with other possible approaches to #415, where @silvasean talks about revamping shape inference to be more precise, but I don't know what @silvasean had in mind.

Refine static shapes for return tensors of conv2d and maxpool2d

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/class_annotator.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/get_registered_ops.cpp

This commit adds include statements of the file
`torch/csrc/jit/ir/ir.h` for files that use types from torch::jit.
Fixes https://github.com/llvm/torch-mlir/issues/506

Fix build error regarding missing types in torch::jit

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/constant_alloc.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

- This commit adds E2E support for `aten.ones_like` and
`aten.zeros_like` ops.
- Adds support for non-None `dtype` argument of `aten.empty_like` op.
- All the unit test cases related to constant tensor allocation like ops
are moved to a different file named `constant_alloc.py`.

[TORCH][MLIR] Add E2E support for `aten.[ones_like|zeros_like]`

---

e2e_testing/torchscript/elementwise.py
e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/promote-types.mlir
test/Dialect/Torch/refine-types.mlir

This involes the following 2 parts:
- Change refine type to propagate more static shape info.
- Get as much static shape info as possible when creating the result
tensor when converting to linalg.

Make broadcasting result shape more static

---

e2e_testing/torchscript/basic.py
lib/Conversion/TorchToStd/TorchToStd.cpp
lib/Dialect/TorchConversion/Transforms/VerifyLinalgOnTensorsBackendContract.cpp

The element type of tensor literal should be signless when converted to
builtin tensor types.

[MLIR][TORCH] Fix tensor literal int elem type to be signless

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/xfail_sets.py
lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
test/RefBackend/munge-calling-conventions.mlir

This commit adds support for two return values of type
memref f32 and i64.

Add support for two return values

---

e2e_testing/torchscript/xfail_sets.py
python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py

[tosa] Add tosa-to-standard before tosa-to-linalg pass

---

e2e_testing/torchscript/xfail_sets.py
python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py

[tosa] Enable tosa-to-linalg-named so Matmul works again

---

tools/torch-mlir-lsp-server/CMakeLists.txt
tools/torch-mlir-opt/CMakeLists.txt

In addition, use add_llvm_executable so that the relative rpath of
the installed binaries is set properly.

Install torch-mlir binaries

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

Refactor matmul into separate class and derive variants:
- matmul
- mm, bmm
- linear

[tosa] Implement torch.linear support.

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/table_batch_embedding.py
e2e_testing/torchscript/xfail_sets.py

This commit adds a test module specifically for table batch embedding
algorithm. This test case is in reference to the FBGEMM table batch
embedding:
https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/bench/split_table_batched_embeddings_benchmark.py#L270
(There are few modifications w.r.t the reference FBGEMM model to start with a simpler form of the model.)
`torch-mlir` dump of this model is here: https://gist.github.com/Shukla-Gaurav/ddde8cb0a31cb71a31fae1cd91695c62

[TORCH][MLIR] Add table batch embedding algorithm module

---

e2e_testing/torchscript/basic.py
include/torch-mlir/Dialect/Torch/IR/GeneratedPrimOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

The added e2e maxpool testcase from #545 was not getting a static shape
due to an unfolded prim.If when RefineTypes was called. This was because
of unfolded torch.iaten.__is__ and torch.prim.unchecked_cast operators
with torch.derefine operands.

Fold __is__ and unchecked_cast of derefine

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp
test/Conversion/TorchToTosa/basic.mlir

* [tosa] Support for AtenFlattenUsingIntsOp

---

e2e_testing/torchscript/reduction.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

In order to facilitate lowering of `aten.max.dim` op, a custom op i.e.,
`cutom.aten.max.dim` is introduced which makes the decomposition easy.

Add decomposition/lowering of `aten.max.dim` op.

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/rng.py
include/torch-mlir-c/TorchTypes.h
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td
include/torch-mlir/RefBackend/Passes.h
include/torch-mlir/RefBackend/Passes.td
lib/CAPI/TorchTypes.cpp
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
lib/Dialect/TorchConversion/Transforms/VerifyLinalgOnTensorsBackendContract.cpp
lib/RefBackend/RefBackend.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
python/torch_mlir_e2e_test/torchscript/reporting.py
test/Dialect/Torch/reduce-op-variants.mlir
test/Dialect/TorchConversion/finalizing-backend-type-conversion.mlir
test/Dialect/TorchConversion/func-backend-type-conversion.mlir
test/RefBackend/insert-rng-globals.mlir

This PR include the following pieces:
- Add torch `Generator` type. `Generator` type is converted to i64 in
refbackend type converter.
- Add seed managment support for the default global generator.
`torch_c.getNextSeed` op is used to get the seed. On refbackend, the
`torch_c.getNextSeed` is lowered to load/store from [0] of global
variable `default_generator` memref<i64> in `InsertRngGlobals` pass.
- Add `aten.uniform_` and testing as an example op RNG ops. Add
`torch.pseudo.aten.uniform` op. It has the same operands and return as
the `aten.uniform_` from the op registry except for value semantics.

[Torch][Linalg] Add basic support for RNG

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/reshape_like.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

This commit decomposes `aten.reshape` into `aten.view` op in the case of
value tensor type operand.

[TORCH][MLIR] Add E2E support for `aten.reshape` op

---

e2e_testing/torchscript/reduction.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
test/Dialect/Torch/decompose-complex-ops.mlir

The softmax decomposition is modified according to https://github.com/pytorch/functorch/blob/main/functorch/_src/decompositions.pytorch
to account for numerical stability. Also, modified aten.argmax lowering
to handle negative dimension.

Modify softmax decomposition to be more numerically stable.

---

e2e_testing/torchscript/nll_loss.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

The lowering of aten::nll_loss_backward op has been added
from torch to linalg dialect. The changes has been made as
a part of -torch-convert-to-linalg pass.

Add aten::nll_loss_backward op

---

e2e_testing/torchscript/type_conversion.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Conversion of torch.bool tensor type to float and integer type is
handled.

Convert bool to float or integer type.

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/norm_like.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

- This commit adds support for `aten.native_batch_norm` operation.
- The current implementation only supports inference mode of
`aten.native_batch_norm` op.
Signed-Off-By: Gaurav Shukla <gaurav@nod-labs.com>

[TORCH][MLIR] Add E2E support for `aten.native_batch_norm` op

---

e2e_testing/torchscript/reshape_like.py
e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds decomposition of `aten._unsafe_view` op into
`aten.view` op.
Signed-Off-By: Prateek Gupta<prateek@nod-labs.com>

[TORCH][MLIR] Add E2E support for `aten._unsafe_view` op.

---

e2e_testing/torchscript/vision_models.py
e2e_testing/torchscript/xfail_sets.py

Missing some simple ops like `hardtanh` `lt.float` etc to get the 2 models working.
[IR mobilenetv2](https://gist.github.com/5a7b0f77a217b928126bf69c59ff7dcb)
[IR mobilenetv3](https://gist.github.com/fb5ecb79b3d8b6f8f288dfa5e114e763)

Add mobilenetv2 and mobilenetv3 to e2e test

---

e2e_testing/torchscript/constant_alloc.py
lib/Dialect/Torch/Transforms/RefineTypes.cpp

This commit fixes an error in the refine types pass of constant
allocation ops. The function used to set the dtype,
`fillInDtypeGivenDtypeAndDataType`, takes two torch types as arguments,
but a torch type and a standard MLIR type were being passed into it.
This commit also fixes the way the dtype was calculated in
`visitAtenToDtypeOp`. This op was also passing a standard MLIR type as
an argument to the `fillInDtypeGivenDtypeAndDataType`
function. Moreover, since the op `aten.to.dtype` has the dtype
argument as not optional, all that is needed is to match
against the int value to extract the dtype.

Fix error in RefineTypes for constant alloc ops

---

e2e_testing/torchscript/elementwise.py
e2e_testing/torchscript/threshold.py
e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp
test/Conversion/TorchToTosa/basic.mlir

* [tosa] Support for AtenNe[Tensor|Scalar]Op, AtenLog2Op, AtenBitwiseAndTensorOp, AtenSquareOp and AtenThresholdOp
* Fix for Issue #532 - Mixed input types for few ops and updated few tests to use i32 instead of i64

[tosa] Support for some ops and fix for Issue #532

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp
test/python/importer/jit_ir/node_import/prim.py

Prior to this commit, importing a `prim::Constant` node with list type would result in an error since it was not supported. `ivalue_importer::importIValue` was modified to return the MlirValue corresponding to the root so its parent operation could be extracted.
Issue https://github.com/llvm/torch-mlir/issues/555
(cc: @cathyzhyi)

Added support for importing node prim::Constant with list type

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/rng.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

Some of the lowerings use the result type obtained from the op itself
to tell the `linalg::GenericOp` what the type of the result should be
rather than using the type of the result tensor given to the
`linalg::GenericOp`. This becomes a problem when the result type of
the op has static size information and the result tensor used in
`linalg::GenericOp` has dynamic dimensions, for `linalg::GenericOp`
expects the result type to be equal to the type of the output tensor.
This commit replaces the use of the result type from the op itself
with the type of the result tensor passed to `linalg::GenericOp`.
In order to not create too many dynamic/static versions of the same
e2e test, e2e tests have only been added to the ops that currently
fail when used with static sizes.

[LINALG] Fix linalg generic result type argument in TorchToLinalg

---

e2e_testing/torchscript/nll_loss.py

- The `self` name is being used as a keyword argument to the
`torch.ops.aten.nll_loss_backward` function call, which produces
name-conflict error with the python keyword `self` which is pointer to
the current object.
- This commit fixes this issue by replacing the keyword argument by
positional argument.

[LINALG] Fix name conflict of `self` keyword.

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/cast.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/RefBackend/RefBackend.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
test/Conversion/TorchToLinalg/basic.mlir
test/Dialect/Torch/canonicalize.mlir

- This commit adds lowering of `aten.Bool.Tensor` and
`aten.Float.Tensor` op as a part of `convert-torch-to-linalg` pass.
- It also adds support for returning bool types.
- It also fixes lowering of the `aten.Int.Tensor` op for non-zero rank
input tensors.
- If a scalar number is converted to a 0-d tensor and passed on to the
`aten.Float.Tensor` op, it folds to the scalar number.

[LINALG] Add E2E support for `aten.[Bool.Tensor|Float.Tensor]` op

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/scalar_comparison.py
lib/Conversion/TorchToStd/TorchToStd.cpp
test/Conversion/TorchToStd/basic.mlir

- This commit adds lowering of `aten.eq.int` op as a part of
`convert-torch-to-std` pass.
- It also refactors the code for binary comparison ops lowering.
Note: The build will fail as it is dependent on bool return support  addressed in #569.

[LINALG] Add E2E support for `aten.eq.int` op

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

Use roundtrip check in isInValidRange for double.

Fix compiler warning introduced in PR575

---

include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/reduce-op-variants.mlir

This commit adds the op `PseudoAtenBernoulliFloatOp` that represents
`AtenBernoulli_FloatOp` without the underscore. This is needed to make
sure that the `ReduceOpVariants` pass turns the in-place op into an op
that takes value tensors as inputs, otherwise the
`MaximizeValueSemantics` pass will not be able to add value semantics
correctly.

[LINALG] Add value tensor variant to `bernoulli_.float`

---

e2e_testing/torchscript/elementwise.py
e2e_testing/torchscript/elementwise_comparison.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

- This commit adds lowering of `aten.le.Scalar` and `aten.ge.Scalar` ops
as a part of `convert-torch-to-linalg` pass.
- It also creates a new test script `elementwise_comparison.py` for all
element-wise comparison ops.

[LINALG] Add E2E support for `aten.[le|ge].Scalar` ops

---

e2e_testing/torchscript/constant_alloc.py
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/reduce-op-variants.mlir

This commit adds the op `PseudoAtenFillScalarOp` that represents
`AtenFill_ScalarOp` without the underscore. The approach is the same
as in commit dd998fa4d4163af14519fed436f29e82e72673ae.
Adding this op allows for a simpler and more consistent version of the 
`empty` and `empty_like` op e2e tests.

[LINALG] Add value tensor variant to `fill_.Scalar`

---

e2e_testing/torchscript/basic.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
test/Dialect/Torch/decompose-complex-ops.mlir

`aten.log_softmax` is decomposed to be more numerically stable.

Modify aten._log_softmax op decomposition for numerical stability.

---

README.md
build_tools/build_standalone.sh

The external projects torch-mlir and torch-mlir-dialects should be
placed inside double quotes.

Cmake build commands fix.

---

lib/Dialect/Torch/Transforms/RefineTypes.cpp

The check for `self.hasSizes` was missing before performing `.size()`
operation.

Fix bug for aten_nll_loss op in the refine types pass

---

lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
test/Dialect/Torch/maximize-value-semantics.mlir

This commit adds handling to the `maximize-value-semantics` pass for
the case where a view-like op depends on a tensor that has been
overwritten by a value tensor. The approach for removing the
dependency is to change the input to the view-like op to be a copy of
the value tensor that is being used to overwrite.
This commit also removes `AtenFill_ScalarOp` and
`AtenBernoulli_FloatOp` from the list of view-like ops, since these
ops now have a corresponding op with value semantics into which they
get converted in the `reduce-op-variants` pass.

Fix handling of view-like ops in `maximize-value-semantics`

---

setup.py

According to the [PyTorch docs](https://pytorch.org/get-started/locally/#mac-python), the minimum Python version that PyTorch supports is version 3.7. However, the Torch-MLIR `setup.py` uses a feature in `shutil` that was added in version 3.8.
The change made in this PR checks the python version and uses the `dirs_exist_ok` argument if available, and uses an alternative if not available.

Fix setup.py backwards compatibiity

---

include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/invalid.mlir
test/Dialect/Torch/maximize-value-semantics.mlir
test/Dialect/Torch/reduce-op-variants.mlir
test/Dialect/Torch/refine-types.mlir

This commit fixes an issue with the way that the
`maximize-value-semantics` pass was handling the
`torch.overwrite.tensor` op. Before, the overwrite op would simply get
deleted and uses of the overwritten tensor would simply get replaced
with the overwriter tensor. This becomes a problem when one tensor has
a dynamic shape and the other has a static shape because ops that were
previously using the overwritten tensor will now get a tensor of a
different type.
To fix this, this commit adds a static cast to the overwriter tensor
so that it has the type of the overwritten tensor, and this casted
tensor is then used to replace the uses of the overwritten tensor.
Note: the reason I added the `aten.add.Tensor` op in the mlir test is to make sure that the insertion point for the cast is correct. …

Fix MaximizeValueSemantics handling of `torch.overwrite.tensor` op

---

CMakeLists.txt

This should be set elsewhere depending on the build configuration.
In particular, we need to be careful when cross-compiling to pick
up the host mlir-tblgen.

Don't override MLIR_TABLEGEN_EXE

---

CMakeLists.txt

Its unclear to me what the right layering is here: Are you expecting
torch-mlir-dialects to always get built with LLVM?  This is pretty
breaking for us, if so.

Ensure that torch-mlir-dialects is built when we're out of tree

---

e2e_testing/torchscript/nll_loss.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

This commit does a couple of things. First, it fixes a bug in the
`linalg.generic` body of the `nll_loss_forward` lowering where the
`ignoreIndex` was being compared with the loop index rather than the
current element of the `target` tensor. This was not being caught by
the tests because they were not testing the case where `ingnoreIndex`
actually corresponds to a value in `target`. This has been fixed.
Second, this commit adds support for the `reduction` argument in
`torch.nll_loss_forward` as well as support for 1-D inputs. In order
to simplify the lowering code, I've refactored the code that creates
the `linalg.generic` ops for elementwise and reduction ops into static
functions, to avoid having boilerplate code for indexing maps, etc
that can be very error prone.
Note: The function …

Add `reduction` support to `torch.nll_loss_forward`

---

e2e_testing/torchscript/constant_alloc.py
e2e_testing/torchscript/elementwise.py
include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

This commit adds support for the contiguous memory format for the ops
`AtenCloneOp` and `AtenEmptyMemoryFormatOp`.

[LINALG] Support for contiguous memory format in `clone` and `empty`

---

e2e_testing/torchscript/reshape_like.py
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp

The view op allows for the new shape argument to have a -1 value for
one of the dimensions, and the op is expected to deduce the size of
that dimension by looking at the sizes of the other dimensions and
comparing it to the total number of elements in the original
tensor. This commit adds this functionality.
Note: this only works when there is enough static information to deduce the dimension

[LINALG] Add handling of inferred dimension in size list of `view` op

---

lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
test/Conversion/TorchToLinalg/basic.mlir

This commit adds a lowering for `TensorStaicInfoCastOp` that simply
replaces the op with the `tensor::CastOp`.

[LINALG] Add torch-to-linalg lowering for `TensorStaticInfoCastOp`

---

external/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorInterfaces.td
external/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorOps.td
external/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.h
external/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.td
external/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
external/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/Transforms/Bufferize.cpp
external/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/Transforms/CMakeLists.txt
external/llvm-external-projects/torch-mlir-dialects/test/tmtensor/bufferize.mlir
external/llvm-external-projects/torch-mlir-dialects/test/tmtensor/convert_to_loops.mlir
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py

The pass is mostly borrowed from the BufferizeAnyLinalgOp pass in mlir
upstream with some minor changes. At a high level, it's a naive partial
bufferization pass which allocate new buffers for all the output
tensors. The initial value of an output buffer is copied from the
original buffer if there are uses of the original value.
One difference from linalg bufferization pass is the way to tell if
the loop body uses the init value of output operand. For TMTensor ops,
it differs from op to op because the payload region doesn't represent
the entire loop body.

Add bufferization pass for TMTensor ops

---

lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/refine-types.mlir

This commit adds static type information support to `aten.bmm`. This
is needed for the forward pass of Bert training.

Add static type information support to `aten.bmm`

---

e2e_testing/torchscript/rng.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

- This commit adds E2E support for `aten.rand_like` and
`aten.bernoulli_.Tensor` ops.
- Previously, the `aten.bernoulli(x)` was implemented as:
`aten.bernoulli(x) = rand_like(x) < 0.5`, assuming 0.5 as default
probability, whereas according to the pytorch documentation:
https://pytorch.org/docs/stable/generated/torch.bernoulli.html#torch.bernoulli
the input x in `aten.bernoulli(x)` is itself a tensor containing
probabilities to be used for drawing the binary random number.
- So this commit fixes the `aten.bernoulli(x)` implementation as:
`aten.bernoulli(x) = rand_like(x) < x`.
- It also fixes the case where the input to `aten.bernoulli_.float` is
an integer tensor. In that case the input must be casted to float type
before passing it as operand to `aten.rand_like` op. …

[LINALG] Fix `aten.bernoulli` op lowering

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/reduction.py
include/torch-mlir/Conversion/Passes.td
include/torch-mlir/Conversion/TorchToTMTensor/TorchToTMTensor.h
include/torch-mlir/Conversion/Utils/Utils.h
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Conversion/CMakeLists.txt
lib/Conversion/Passes.cpp
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Conversion/TorchToTMTensor/CMakeLists.txt
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Conversion/Utils/CMakeLists.txt
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Utils/Utils.cpp
lib/Dialect/TorchConversion/Transforms/CMakeLists.txt
lib/Dialect/TorchConversion/Transforms/Passes.cpp
lib/Dialect/TorchConversion/Transforms/VerifyLinalgOnTensorsBackendContract.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This pass is added to lower ops, which can not be lowered
via the TorchToLinalg pass, such as `embedding_dense_backward`
op. This pass also uses torch-mlir's TMTensor Dialect to lower the
complex ops.
Also add torch.bincount op lowering with the help of TMTensor dialect

[MLIR][TORCH] Add TorchToTMTensor pass

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp

The location of packed_params.h is changed in aten src.

[TORCH] Fix the location of packed_params.

---

include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Utils/Utils.cpp

This is code that we always want to treat as "foreign" and not get too
comfortable using in many functions. One way to accomplish that is to
make it a bit clunkier to use.
Also, fix Utils.cpp to match the LLVM/MLIR coding conventions (don't
define functions inside namespaces -- prefer `using` and explicit
qualification).

Avoid `using` the `torch_upstream` namespace.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/maximize-value-semantics.mlir

This commit adds value semantics support for ops such as
`aten.view_as` and `aten.expand_as` that take two tensors as input.
This is needed for the implementation of `aten.expand_as` that 
@vivekkhandelwal1 is currently working on.
I also simplified a few things in the implementation.

Add maximize-value-semantics support for ops with two tensor inputs

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/index_put.py
e2e_testing/torchscript/main.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir
test/Dialect/Torch/reduce-op-variants.mlir

This commit adds the op `PseudoAtenIndexPutImplOp` that represents
`Aten_IndexPutImpl_Op` without the underscore. This is needed to
make sure that the `ReduceOpVariants` pass turns the in-place op
into an op that takes value tensors as inputs, otherwise the
`MaximizeValueSemantics` pass will not be able to add value
semantics correctly.
This commit also adds the lowering of `PseudoAtenIndexPutImplOp` op.

[MLIR][TORCH] Add value tensor variant to aten::_index_put_impl_

---

e2e_testing/torchscript/norm_like.py
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py

This commit fixes the 2nd and 3rd return types of the `aten.native_layer_norm`.
Previously the mean and rSTD were returned with reduction dims removed.
This commit fixes this and keeps the reduction dims of the results.
Signed-Off-By: Prateek Gupta <prateek@nord-labs.com>
fixes: #665

[TORCH][MLIR] Fix the return types of `aten.native_layer_norm`.

---

lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

This commit adds support for type refinement when
`torch.tensor_static_info_cast`s are involved, even when there are
users of the casted tensor that don't allow type refinements.
Originally the canonicalization pattern for
`torch.tensor_static_info_cast` would check if all the users of the
casted tensor allowed type refinements before making any changes. This
means that if at least one of the users did not allow type
refinements, the pattern would fail. This becomes an issue when doing
shape calculations because the calculations need the shape information
of each input tensor to be available before the calculation can be
simplified.

Make conditions for type refinement of static cast less strict

---

e2e_testing/torchscript/basic.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit decomposes `aten.expand_as` op into `aten.broadcast_to` op.

[MLIR][TORCH] Add E2E support for aten.expand_as op

---

e2e_testing/torchscript/basic.py
include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir
test/Dialect/Torch/reduce-op-variants.mlir

This commit adds the op `ValsemVariantAtenCopyOp` that represents
`AtenCopy_Op` without the underscore. This is needed to make sure
that the `ReduceOpVariants` pass turns the in-place op into an op
that takes value tensors as inputs, otherwise the
`MaximizeValueSemantics` pass will not be able to add value
semantics correctly.
This commit also adds the lowering of `ValsemVariantAtenCopyOp`.

[MLIR][TORCH] Add value tensor variant to aten::copy_ op

---

e2e_testing/torchscript/basic.py
e2e_testing/torchscript/scalar.py
e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToStd/TorchToStd.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Conversion/TorchToStd/basic.mlir
test/Dialect/Torch/decompose-complex-ops.mlir

- This commit adds decomposition of `aten.dropout` op. It also covers the
training mode of the same op.
- It also adds lowering of `aten.sub.float` op.

[LINALG] Add decomposition of `aten.dropout` op

---

e2e_testing/torchscript/elementwise.py
e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/IR/UtilsForODSGenerated.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py

This PR adds non-default dtype support for elementwise math ops:
- AtenTanhOp
- AtenExpOp 
- AtenSinOp
- AtenCosOp
- AtenSigmoidOp
- AtenReciprocalOp 
- AtenLogOp
- AtenSqrtOp
- AtenLog2Op 
- AtenRsqrtOp 
- AtenErfOp
Changes:
- Fix type inference: set the output dtype to `float32`, except for `float64` and `null` input. 
- Fix Torch2Linalg conversion: add dtype conversion over input value before math op.
- Add test cases with `int32` input.
@ramiro050 @cathyzhyi

Add non-default dtype support for a few elementwise math ops.

---

lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToLinalg/Uncategorized.cpp

In order to make sure that the TorchToLinalg conversions leave the
graph in a valid state, the final result of the conversion has to be
casted to the result type of the op. This commit adds this cast to ops
that did not have it.

Add final cast to TorchToLinalg conversions missing it

---

e2e_testing/torchscript/reshape_like.py
lib/Conversion/TorchToLinalg/DataMovement.cpp

This commit adds support for the cases of view op where the rank and
the shapes of the input and result are equal.

[MLIR][TORCH] Add support for same input and output shapes for view op

---

lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
test/Dialect/Torch/simplify-shape-calculations.mlir

The logic in the rewriting phase had a bug in case of a read-only op
coming before mutation ops. The logic would use the op itself as the
"latest literal", but that is not correct, because later on we replace
the op itself with the *final* "latest literal", assuming that all uses
of the op have been rewritten -- that was working in general, except for
any read-only ops at the beginning.
Big thanks to @ljfitz for the tiny reproducer!
Fixes #704

[SimplifyShapeCalculations] Fix AbstractlyInterpretListOpsWithinABlock

---

include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
lib/Dialect/Torch/Utils/Utils.cpp
test/Dialect/Torch/simplify-shape-calculations.mlir

The reified code to compute the shape of `torch.aten.constant_pad_nd` uses negative indices when setting list elements. This was not converted to a positive offset in one place in `SimplifyShapeCalculations` which prevented computation of the static shape.
Additionally I added a utility function `getMatchedListDim()` to replace a number of equivalent pieces of code, as the same code was needed for the fix.

Improve list index normalization SimplifyShapeCalculations

---

include/torch-mlir-c/TorchTypes.h
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/TorchTypes.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
requirements.txt
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/ops.mlir
test/python/importer/jit_ir/node_import/union.py

A recent PyTorch commit made ConstantPad2d call a helper function with a
`Union[int, float]` type annotated. This commit adds minimal support for
representing and dealing with that.
https://github.com/pytorch/pytorch/pull/73287
Changes:
- Adding support for `!torch.union<T1, T2, T3>`/`Torch::UnionType`,
along with the importer and CAPI code.
- Add support in isValidSubtype for union types.
- Adding a canonicalizer for `torch.derefine` to help simplify some code
that derefines to a UnionType (this also fixes #664).
There is still more work to do for really supporting UnionType well,
such as canonicalizing UnionType's so that they can be compared with
pointer equality.

Add minimal support for Union types.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Conversion/TorchToLinalg/TensorConstructors.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/constant_alloc.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit decomposes `aten.new_empty` op into `aten.empty.memory_format` op.
This commit also made a dtype fix to the constant tensor allocation like ops.
Earlier the dtype for the result was inferred from the result type; now, it's
being evaluated as per the original definition of the op.

[MLIR][TORCH] Add E2E support for aten.new_empty op

---

lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/upstream_shape_helpers.py
test/Dialect/Torch/canonicalize.mlir

The issue was in the canonicalizer for torch.aten.ge.int -- in cases
where the operands were swapped, it would miscompile. This issue is
fixed and folding support generalized to `torch.aten.size.int < 0` as
well.
Fixes #716

Fix for 0-size dim inferred incorrectly.

---

CMakeLists.txt
externals/llvm-external-projects/torch-mlir-dialects/CMakeLists.txt
externals/llvm-external-projects/torch-mlir-dialects/test/CMakeLists.txt
externals/llvm-external-projects/torch-mlir-dialects/test/lit.cfg.py
externals/llvm-external-projects/torch-mlir-dialects/test/lit.site.cfg.py.in

This follows up on #623 for out-of-tree builds of torch-mlir, which added building `torch-mir-dialects` as a subdirectory.
We found that we needed some more `cmake` adaptions to make this work. We're initially opening this PR as a draft to gather opinions as to whether this approach suits at least the short-term `torch-mlir-dialects` goals.
Our goal is to support both in-tree and out-of-tree builds of `torch-mlir` with minimum hassle, for instance by using the same variable names in both setups. Specifically in `externals/llvm-external-projects/torch-mlir-dialects/CMakeLists.txt` :
- We use `MLIR_FOUND` to detect that it is being build as a subdirectory and the llvm+mlir cmake infrastructure is already set up (via find_package in the parent build) as opposed to an in-tree build.
- For …

Fix out-of-tree cmake build of `torch-mlir-dialects`

---

lib/Conversion/TorchToLinalg/Uncategorized.cpp
python/torch_mlir_e2e_test/test_suite/nll_loss.py

This commit adds the following support to the op `nll_loss_backward`:
- `input` tensor can be rank-1
- `weight` parameter
- `reduction` parameter
- `target`, `grad_output`, `total_weight` can be rank-0
- Checks that input tensors are of the expected type

Add 1D, weight, and reduction support to nll_loss_backward

---

.gitignore
utils/bazel/.bazelrc
utils/bazel/BUILD.bazel
utils/bazel/WORKSPACE.bazel
utils/bazel/configure.bzl
utils/bazel/overlay_directories.py
utils/bazel/torch-mlir-overlay/.bazelignore
utils/bazel/torch-mlir-overlay/BUILD.bazel

This PR adds rules for building the compiler part with bazel, 
a followup PRs will include rules for building the python bindings.
Towards fixing #660

Add bazel build support (1/N)

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/conv.py

Here's the implementation of `at::convolution` and a decomposition of `at::convolution_overrideable`. The 2D case is all that's implemented for `at::convolution`, since the 1D and 3D cases require changes to linalg. I don't think we need them right now, looking at our op list, but I need to look further into the list to be sure. `convolution_overrideable` just decomposes directly into `convolution`.

Add 2D case for at::convolution

---

python/test/eager_mode/normalize_args_kwargs.py
python/torch_mlir/eager_mode/torch_mlir_dispatch.py

Fixes a bug in use of upstream `normalize_function` in our `normalize_args_kwargs` (in eager mode) and introduces unit tests.
NB: `shouldnt_normalize` currently fails i.e., args *will* successfully normalize despite being incorrect due to an [upstream bug](https://github.com/pytorch/pytorch/issues/75342).

Fix misuse of `normalize_function` api

---

python/test/eager_mode/annotate_args.py
python/torch_mlir/eager_mode/torch_mlir_dispatch.py

Tensor kwargs are offset indexed (e.g., starting position `i=5`), and just `range`ing over wasn't correct.
Also add tests.
NB: this PR is stacked on top of https://github.com/llvm/torch-mlir/pull/745, so only the most recent commit is the actual diff.

Fix small bug in annotate args in eager

---

e2e_testing/torchscript/xfail_sets.py
lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

Fixes https://github.com/llvm/torch-mlir/issues/751 where `torch.bool` is parsed as signless `i1`.

Fix `torch.bool` parsed as signless `i1`

---

CMakeLists.txt
examples/CMakeLists.txt
examples/ltc_backend/CMakeLists.txt
examples/ltc_backend/ltc_backend/csrc/backend/backend_impl.cpp
examples/ltc_backend/ltc_backend/csrc/backend/backend_impl.h
examples/ltc_backend/ltc_backend/csrc/example_mlir_backend_pybind.cpp
examples/ltc_backend/ltc_backend/csrc/utils/sys_utils.h
examples/ltc_backend_mnist.py
python/torch_mlir/csrc/base_lazy_backend/backend_impl.cpp

Added example vendor implementation of MLIR LTC backend, which shows what information is exposed at the compile stage. Also included is a script which uses this backend implementation to demonstrate the full end-to-end flow from PyTorch model to MLIR.
**Note: This PR is based on https://github.com/llvm/torch-mlir/pull/724, but GitHub does not allow for setting the base to a fork while keeping this PR in the upstream repo, so there are several shared commits. Only the last three are specifically part of this PR.**
Marked as draft while waiting for a dependency PR to land: https://github.com/llvm/torch-mlir/pull/724

Added example Torch MLIR LTC Backend

---

build_tools/autogen_ltc_backend.py
examples/ltc_backend_mnist.py
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h
python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/function_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/function_importer.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/import_options.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.h

Previously, the intermediate JIT graph was generated without shape information, which caused generic `!torch.tensor` types to be scattered throughout the final MLIR. This PR improves the lowering by injecting each `jit::Value` of tensor type with its corresponding shape from the origin `lazy::Node`. Additionally, the MLIR parameter and return values are also generated with their respective shapes.
Example output for an FC MNIST model:
```
func @graph(%arg0: !torch.vtensor<[1,5],f32>, %arg1: !torch.vtensor<[1],si64>, %arg2: !torch.float, %arg3: !torch.int, %arg4: !torch.int, %arg5: !torch.int, %arg6: !torch.vtensor<[10,5],f32>, %arg7: !torch.vtensor<[10],f32>, %arg8: !torch.vtensor<*,f32>, %arg9: !torch.float) -> (!torch.vtensor<[1,5],f32>, !torch.vtensor<[1],si64>, …
```

Generate MLIR with shape information via LTC frontend

---

lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
test/Conversion/TorchToLinalg/basic.mlir

This PR contains two commits for `aten.neg`, one for adding the shape transfer function and another for translating the torch operation to the linalg dialect.

Add shape transfer function and lowering to linalg for aten.neg

---

e2e_testing/torchscript/main.py
e2e_testing/torchscript/xfail_sets.py
python/torch_mlir_e2e_test/test_suite/__init__.py

That way, downstreams don't have to duplicate this list.
Also, remove "external config" feature, since it is subsumed by just
importing the test suite.

Move COMMON_TORCH_MLIR_LOWERING_XFAILS into test_suite

---

.github/actions/setup-build/action.yml
.github/workflows/buildAndTest.yml
README.md

(OOT = out-of-tree)
Followup on #726 (#733 was the draft)
* Add instructions in the README to show how to build the project OOT
* Add a ci job that performs an OOT build with tests
* Part of the existing job (setup logic) has been extracted into a custom [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) in order to share it between the two jobs.
Both jobs run in parallel, on separate git clones of the project. I found no way to make them work on the same clone without making them entirely sequential.

Add README instructions for OOT build

---

build_tools/build_python_wheels.sh
setup.py

This avoids issues where PyTorch version drift has made things
incompatible.
One caveat is that you will need to specify
`-f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
--pre` on the command line for pip to know where to find the nightly
packages (there is no way around this) -- this is easiest to do by
simultaneously passing `-r requirements.txt` on the pip command line.

Pin the Python package to the exact PyTorch nightly.

---

.github/workflows/buildRelease.yml
.github/workflows/oneshotSnapshotPackage.yml
build_tools/python_deploy/build_linux_packages.sh
build_tools/python_deploy/build_macos_packages.sh
pyproject.toml
requirements.txt

Sets up auto-pinning of latest torch-nightly

Minor buildsystem fixes

---

.github/workflows/buildAndTest.yml
.github/workflows/releasePackage.yml

This switches to using the "Release Build" that builds linux/osx
binaries for the build and release of snapshots.
Moves buildAndTest.yml to be only on CI build + test.

Switch to using the new manylinux+macos Release builds

---

README.md

Prior to this patch, the top-level README did not include the line for
running the Python regression tests in `//python/test`.  This patch
fixes the problem by adding a line to run the `check-torch-mlir-python`
target.

doc: [nfc] add instruction for running Python regression tests

---

build_tools/torchscript_e2e_heavydep_tests/bert_functorch.py
build_tools/torchscript_e2e_heavydep_tests/fully_connected_backward.py
build_tools/torchscript_e2e_heavydep_tests/functorch_utils.py
build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh
build_tools/torchscript_e2e_heavydep_tests/main.py

Example to demonstrate the extraction of forward as well as
backward graph via Functorch's AOT module is added.

Generate backward graph via functorch-aot module

---

lib/Dialect/Torch/Transforms/RefineTypes.cpp
test/Dialect/Torch/refine-types.mlir

Prior to this patch, the result type for several tensor operations could
only be float32, float64, or null.  This patch adds bf16 to the list of
allowed result types.

types: allow bf16 as result type for various tensor ops

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/function_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.h
test/python/importer/jit_ir/node_import/function-block-arg-adjustment.py

Ensure that imported function input type and block arg types are consistent.
I wasn't able to find exactly what frontend situation created it, but
`torch.jit.trace` will sometimes create functions where the
`jit::Block`'s param node has refined tensor types. So we need to adjust
the function's formal param types to those refined types.

Ensure that imported function input type and block arg types are consistent

---

build_tools/autogen_ltc_backend.py
build_tools/autogen_ltc_backend.yaml
python/torch_mlir/csrc/base_lazy_backend/LazyShapeInference.cpp
python/torch_mlir/csrc/base_lazy_backend/LazyShapeInference.h
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h

Complements this upstream PyTorch PR: https://github.com/pytorch/pytorch/pull/75828
This PR adds support for mapping input and output tensors which alias each other. (e.g. maps input weight tensor in parameter to the same tensor in output after a training iteration)
```
MLIR: 
func @graph(%arg0: !torch.vtensor<[1,5],f32>, %arg1: !torch.vtensor<[1],si64>, ..., %arg6: !torch.vtensor<[10,5],f32>, %arg7: !torch.vtensor<[10],f32>, ...) {
...
return %arg0, %arg1, %17, %23, ... : !torch.vtensor<[1,5],f32>, !torch.vtensor<[1],si64>, !torch.vtensor<[10,5],f32>, !torch.vtensor<[10],f32>, ...
}
Input/Output Alias Mapping: 
Output: 0 -> Input: 0
Output: 1 -> Input: 1
Output: 2 -> Input: 6
Output: 3 -> Input: 7
```
The `aten::detach` op has also been disabled in this PR to fix the issue of tensors not …

Enable support for LTC Input/Output Mapping

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/index_put.py

This commit decomposes `aten.index_put.hacked_twin` op into
`valsem.aten.index_put_impl` op.

[MLIR][TORCH] Add E2E support for aten.index_put.hacked_twin op

---

python/torch_mlir_e2e_test/test_suite/index_put.py
python/torch_mlir_e2e_test/torchscript/framework.py

Fix the inplace update tensor issue we had
where the torchscript execution would update the input value inplace
resulting the actual test not being able to see the original input
value.

Fix the input tensors inplace update issue for e2e tests

---

build_tools/python_deploy/build_upload_m1_snapshot.sh

Uses the latest snapshot tags and adds the releases to same asset
directories so it can be run on a cronjob without a GH runner.

Add a script to build and upload M1 snapshots

---

lib/Conversion/TorchToSCF/TorchToSCF.cpp
lib/Dialect/TorchConversion/Transforms/Passes.cpp
lib/Dialect/TorchConversion/Transforms/VerifyLinalgOnTensorsBackendContract.cpp
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/control_flow.py
test/Conversion/TorchToSCF/basic.mlir

1. This commit adds lowering of while like prim loop to scf.while
operation.
2. Convert for-like prim loops into scf.for op.
Issue:  [#678](https://github.com/llvm/torch-mlir/issues/678)

[TORCH][MLIR]Add lowering for control flow.

---

lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
test/Conversion/TorchToLinalg/basic.mlir
test/python/importer/jit_ir/ivalue_import/tensors.py

This patch updates the `torch_mlir::convertTensorToMlirElementsAttr()`
method to enable the creation of tensors whose base type is BFloat16.
This patch also adds a test to validate the IR generation.
I admit that this patch is possibly contentious and/or incomplete.  Let me know if y'all would like to see any additions or changes.  Thanks!

importer: add initial support for loading BFloat16 tensors

---

lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir_e2e_test/test_suite/constant_alloc.py

This commit adds lowering of `aten.masked_fill.Scalar` op.
This commit also fixes the formatting of the file constant_alloc.py.

[MLIR][TORCH] Add E2E support for `aten.masked_fill.Scalar` op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/type_conversion.py
test/Dialect/Torch/canonicalize.mlir
test/Dialect/Torch/decompose-complex-ops.mlir

This commit decomposes `aten.to.dtype_layout` op into `aten.to.dtype` op.

[MLIR][TORCH] Add E2E support for `aten.to.dtype_layout` op

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/basic.py
python/torch_mlir_e2e_test/test_suite/reduction.py
python/torch_mlir_e2e_test/test_suite/stats.py

- This commit adds support for `aten.mean.dim` op.
- It also adds a new test script `stats.py` for statistics related ops.

[LINALG] Add E2E support for `aten.mean.dim` op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
include/torch-mlir/Dialect/Torch/Utils/TorchUpstream.h
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/refine-types.mlir

The main changes are:
- Added `ValueKnowledge.scalarType` to track scalar type information.
- Added `ValueKnowledge.kind` to indicate the value kind.
- Modified the meet and join helper functions. The ValueKnowledge has
slightly more complicated state now so the meet and join function need
to look at the `kind` field in addition to just the type field.

Add support for scalar type propagation

---

examples/ltc_backend/ltc_backend/csrc/backend/backend_impl.cpp
python/torch_mlir/csrc/base_lazy_backend/LazyShapeInference.h
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h

Previously, we returned dummy tensors in the example backend during its execution phase; however, this resulted in some unexpected bugs since the tensors contained incorrect data. 
To solve this, we will be using `GraphExecutor` with the `jit::Graph` to execute on the CPU, just like how it's done on the TorchScript backend. Of course, this is only for demonstration purposes, as each vendor will be expected to implement a custom execution flow for their device.

Use JIT GraphExecutor for execution in example backend

---

python/torch_mlir_e2e_test/test_suite/index_put.py
python/torch_mlir_e2e_test/torchscript/framework.py

This change makes the e2e testing parallel using the multiprocessing
python module.
This also fixes the inplace update tensor issue we had
where the torchscript execution would update the input value inplace
resulting the actual test not being able to see the original input
value.

Make e2e testing parallel

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This commit adds the op `ValsemVariantAtenDropoutOp` that represents
`AtenDropout_Op` without the underscore. This is needed to
make sure that the `ReduceOpVariants` pass turns the in-place op
into an op that takes value tensors as inputs, otherwise the
`MaximizeValueSemantics` pass will not be able to add value
semantics correctly.
This commit also adds the lowering of `ValsemVariantAtenDropoutOp` op.

[MLIR][TORCH] Modify aten::dropout op description

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/refine-types.mlir

Fix the type promotion code for scalar only operation to return
TorchType which is the type tracked in ValueKnowledge.scalarType.
- Fix `getPromotedResultScalarType` to return Torch type.
- Add `getBuiltInTypeForTorchScalar` helper to convert scalar type
to builtin type before passing to the next level type promotion
helper `updateResultTypeState`.
- Add `setScalarType` helper to make setting ValueKnowledge.scalarType
easier.

Fix type promotion code for scalar only operations

---

lib/Conversion/TorchToLinalg/TensorConstructors.cpp
python/torch_mlir_e2e_test/test_suite/constant_alloc.py

The preserve memory specifies that `If any of the input tensors is in channels_last format,
operator output should be in channels_last format` and hence can be
added as is in aten_empty_like op.

[LINALG] Add support for preserve memory format in aten_empty_like op.

---

examples/ltc_backend_bert.py
python/torch_mlir/csrc/base_lazy_backend/LazyShapeInference.cpp

This PR adds support for lowering a BERT model to MLIR using the Torch MLIR with LTC. As it currently stands, we can extract the forward graph for a [bert-base-cased](https://huggingface.co/bert-base-cased) model.
Many shape inference functions have been implemented, which may eventually be upstreamed to PyTorch.
Current printout using the example backend: https://gist.github.com/henrytwo/ec84705f24ec489e70319deebc97861b
cc: @ke1337 @antoniojkim

Enable BERT support for torch-mlir via LTC

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py

`aten.detach` op is folded and returns the first operand since it's an
identity function(kind of identity just remove the has_grad attribute).

[TORCH] Add lowering of aten.detach op.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py

This commit adds lowering of `aten.ScalarImplicit` op.

[MLIR][TORCH] Add E2E support for `aten.ScalarImplicit` op

---

lib/Conversion/TorchToLinalg/Pooling.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToLinalg/Utils.h
python/torch_mlir_e2e_test/test_suite/pooling.py

This commit adds support for aten.max_pool2d, aten.max_pool2d_with_indices,
and aten.avg_pool2d op for the cases where ceil_mode = true.

[MLIR][TORCH] Add support for ceil_mode = true for pooling ops

---

include/torch-mlir-c/TorchTypes.h
lib/CAPI/TorchTypes.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/import_options.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp

Previously scalar tensors were denoted with a type of `*` instead of `[]` in MLIR due to bug where an empty shape vector was interpreted as being an unranked tensor. The solution was to "key" the unranked case using a dimension number of -1.
Now that scalar tensor shapes are encoded explicitly, we found a previously unknown bug with JIT tuples. Since we inject shape information into the JIT graph ourselves, any previously constructed tuples will have outdated types. This related PR addresses those issues: https://github.com/pytorch/pytorch/pull/76919 Without it, the MLIR generated is illegal due to the aforementioned conflicting types.
cc: @ke1337 @antoniojkim

Add static shape for scalar tensors

---

e2e_testing/torchscript/main.py
python/torch_mlir_e2e_test/torchscript/framework.py

A user might want to avoid the extra layer of multiprocessing libary for
debugging purpose. In such cases, the -s flag can be used to force
sequential execution.

Add -s flag to run e2e tests sequentially

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir_e2e_test/test_suite/rng.py
test/Dialect/Torch/decompose-complex-ops.mlir

The op `aten.rand_like` was missing a shape function, unit tests, and
the `dtype` argument was being ignored in its decomposition. This
commit fixes all three things.

Add shape info to `rand_like` + support for `dtype` flag

---

python/test/compile_api/basic.py
python/torch_mlir/__init__.py

We do this by inroducing a TensorPlaceholder class, which can be used to
specify dynamic sizes. Internally, we canonicalize all example inputs
to TensorPlaceholder's.
This commit also adds some basic testing, which was missing before.
Fixes https://github.com/llvm/torch-mlir/issues/854

torch_mlir.compile: add support for dynamic sizes.

---

lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

In cases where a refinement/derefinement was needed, we didn't fold.
Fixes https://github.com/llvm/torch-mlir/issues/863

torch.prim.TupleIndex: Adjust tensor types when folding.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Reduction.cpp
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToLinalg/Utils.h
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/reduction.py

This PR has five commits, the first three of which introduce non-functional changes to prepare for the actual change.  The second-to-last commit introduces a torch dialect op for the `aten.linalg.vector_norm` operation, whereas the last commit lowers the torch dialect op to linalg on tensors.

Lower aten.linalg.vector_norm to linalg on tensors

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToStd/TorchToStd.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/scalar.py
test/Conversion/TorchToStd/basic.mlir
test/Dialect/Torch/canonicalize.mlir

This commit adds lowering of `aten.sqrt.int` op.

[MLIR][TORCH] Add E2E support for `aten.sqrt.int` op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToStd/TorchToStd.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/scalar.py
test/Conversion/TorchToStd/basic.mlir
test/Dialect/Torch/canonicalize.mlir

This commit adds lowering of `aten.Bool.float` and `aten.Bool.int` op.

[MLIR][TORCH] Add E2E support for `aten.Bool.[float|int]` op

---

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp

When compiling without assertions (i.e. in `NDEBUG` mode), a handful of
statements turn to NOPs, which results in warnings such as missing
return statement or unused variables and function.  This patch replaces
such statements with `llvm_unreachable()`, which informs the compiler
about program termination regardless of the `NDEBUG` mode.  This also
enables torch-mlir to be compiled using the flags `-Wall`, `-Wextra`,
`-Wpedantic`, and `-Werror`.

build: fix code so that the compiler does not emit warnings

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

The op `aten.unsqueeze` has a mutating variant. This commit adds
support for that variant.

Emit `aten.unsqueeze` with mutating variants

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Conversion/Utils/Utils.h
lib/Conversion/TorchToLinalg/Pooling.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir_e2e_test/test_suite/pooling.py
test/Conversion/TorchToLinalg/pooling.mlir
test/Conversion/TorchToTosa/basic.mlir
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds the decomposition of `aten.adaptive_avg_pool2d` op into
`aten.avg_pool2d` op. The current decomposition only supports cases where
input size is equal to the output size.

[MLIR][TORCH] Add decomposition of `aten.adaptive_avg_pool2d` op

---

lib/Dialect/Torch/Transforms/ShapeLibrary.cpp

The patch bumped up the LLVM tag made manual fixes to the code in
`ShapeLibrary.cpp`.  However, since that file is generated by the
`update_shape_lib.sh` script, its contents were reverted each time the
script was run.  This patch fixes the problem by removing the manual
changes to that file.

build: remove manual changes to ShapeLibrary.cpp

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR updates the codegen to allow for the `aten.native_layer_norm_backward` op in MLIR to be generated. The changes are based on PR https://github.com/llvm/torch-mlir/pull/570 by @gprateek93.
This op is used for tracing a full forward and backward graph for a HF BERT model using Lazy Tensor Core. We'd like to have this op in its current high-level form, rather than decomposing it.
e2e tests and type refinement functions have been excluded, since they aren't used by LTC. (Discussion: https://github.com/llvm/torch-mlir/issues/887)

Add support for native_layer_norm_backward op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR updates the codegen to allow for the `aten.native_batch_norm_backward` op in MLIR to be generated.
This op is used for tracing a full forward and backward graph for a HF BERT model using Lazy Tensor Core.
e2e tests and type refinement functions have been excluded, since they aren't used by LTC. (Discussion: https://github.com/llvm/torch-mlir/issues/887)

Add support for native_batch_norm_backward op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR updates the codegen to allow for the `aten.native_dropout` op in MLIR to be generated.
This op is used for tracing a full forward and backward graph for a HF BERT model using Lazy Tensor Core.
e2e tests and type refinement functions have been excluded, since they aren't used by LTC. (Discussion: https://github.com/llvm/torch-mlir/issues/887)

Add support for native_dropout op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR updates the codegen to allow for the `aten.native_dropout_backward` op in MLIR to be generated.
This op is used for tracing a full forward and backward graph for a HF BERT model using Lazy Tensor Core.
e2e tests and type refinement functions have been excluded, since they aren't used by LTC. (Discussion: https://github.com/llvm/torch-mlir/issues/887)

Add support for native_dropout_backward op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

PyTorch now supports functional ops such as `aten.zero.functional`, so torch-mlir specific ops such as `valsem.aten.zero` can be replaced now.

Replace valsem.aten.zero with aten.zero.functional

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/elementwise.py

WIP implementation of operator, `AtenLogicalOrOp`
Implemented for Integer tensors, need to implement for floating point tensors. 
Works for boolean tensors, failing on Integer tensors.

Add E2E Support for AtenLogicalOrOp. 

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR adds support for generaing the `aten.arange.start_out` op in MLIR.
Required to support HuggingFace Bert using the LTC backend.
CC: @henrytwo @ke1337

Add Support for `aten::arange.start_out`

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR adds support for generating the `aten.scatter_add` op in MLIR.
Required to support HuggingFace Bert using the LTC backend.
CC: @henrytwo @ke1337

Add Support for aten::scatter_add

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/elementwise.py

This commit adds lowering of `aten.div.Tensor_mode` op.
This commit also fixes formatting for the test file elementwise.py.

[MLIR][TORCH] Add E2E support for `aten.div.Tensor_mode` op

---

python/torch_mlir/compiler_utils.py

The flag for printing the IR after each pass is now prefixed with
"mlir". This commit updates the flag in the error reporting for the
compiler.

Update debug options in compilation errors

---

lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py

Now that upstream exposes them nicely, we can use them.
I noticed that we had added stuff into the upstream_shape_helpers.py
file (which was supposed to stay pristine), so some more shape functions
need to be upstreamed.
Going forward, all shape functions should be upstreamed similar to
https://github.com/pytorch/pytorch/pull/76889 instead of added in this
file.

Use upstream shape functions directly.

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

As discussed [here](https://github.com/llvm/torch-mlir/pull/893#issuecomment-1146938643), we should be using `emit_with_mutating_variants` to generate both underscore and non-underscore variants for functional ops.
The ODS generator had to be modified to exclude the `functional` suffix during the generation of underscore ops.
Additionally, this PR fixes some formatting issues for the `aten::arange.start_out` and `aten::scatter_add` ops in `GeneratedTorchOps.td`.
cc: @antoniojkim @ke1337 @silvasean

Generate underscore variant of functional ops

---

python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

Oops missed some single quotes from the review comment in https://github.com/llvm/torch-mlir/pull/915, so fixing it here

Use double quotes instead of single quotes

---

lib/Conversion/TorchToLinalg/Linear.cpp
python/torch_mlir_e2e_test/test_suite/mlp.py

Handles `bias=False` case by checking `bias.getType().isa<Torch::NoneType>()` and initing with zero in this case.

Handle `nn.Linear(..., bias=False)` case for TorchToLinalg

---

python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h
python/torch_mlir/csrc/base_lazy_backend/mlir_node.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp
python/torch_mlir/csrc/base_lazy_backend/ops/device_data.h

A follow up to https://github.com/pytorch/pytorch/pull/78273 which refactors and provides a longer term, more maintainable way to support lowering for non-native ops.

Refactor Node Lowering

---

requirements.txt

https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
is going to be deprecated via pip 22 since it is not html5.

Revert requirements.txt

---

build_tools/update_shape_lib.sh
build_tools/update_torch_ods.sh
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/CMakeLists.txt
lib/Conversion/TorchToLinalg/CustomOpExample.cpp
lib/Conversion/TorchToLinalg/PopulatePatterns.h
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/CMakeLists.txt
python/torch_mlir/_torch_mlir_custom_op_example/CMakeLists.txt
python/torch_mlir/_torch_mlir_custom_op_example/README.md
python/torch_mlir/_torch_mlir_custom_op_example/__init__.py
python/torch_mlir/_torch_mlir_custom_op_example/torch_mlir_custom_op_example.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/registry.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/custom_op_example.py

PyTorch allows new operators to be registered dynamically in modules. Torch-mlir already makes it fairly straightforward to add support for new operators, and this commit just extends that support to allow new PyTorch ops to come from an external module.
Previously, there was no hook to allow extensions to be loaded before querying the op registry, so extension ops would never be generated. Moreover, a bug caused ops imported from an extension to be impossible to support via shape inference.
This does *not* allow ops to be dynamically loaded into torch-mlir. Torch-mlir must still be compiled with support built-in.
This should make tasks like [this one](https://github.com/llvm/torch-mlir/issues/462#issuecomment-989036106) in #462 (and to a lesser extent #504) somewhat easier.

Support pytorch extensions

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp

Input TorchScript graph:
```
graph(%x.1_ : Float(requires_grad=0, device=cuda:0)):
%1 : int[] = prim::Constant[value=[2, 3, 224, 1]]()
%2 : bool = prim::Constant[value=0]() # :0:0
%3 : Float(2, 3, 224, 1, strides=[0, 0, 0, 0], requires_grad=0, device=cuda:0) = aten::expand(%x.1_, %1, %2) # test_broadcast.py:36:19
return (%3)
```
I want to get the following torch dialect module being imported, with the `%arg0` static cast to `!torch.tensor<[], f32>`:
```
module {
func @main(%arg0: !torch.tensor) -> !torch.tensor {
%0 = torch.tensor_static_info_cast %arg0 : !torch.tensor to !torch.tensor<[],f32>
%int2 = torch.constant.int 2
%int3 = torch.constant.int 3
%int224 = torch.constant.int 224
%int1 = torch.constant.int 1
%1 = torch.prim.ListConstruct %int2, %int3, %int224, %int1 : (!torch.int, …
```

Fix: 0 sizes tensor being regarded as unknown rank

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/elementwise.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds the decomposition of `aten.floor_divide` op into
`aten.div.Tensor_mode` op.

[MLIR][TORCH] Add decomposition of `aten.floor_divide` op

---

lib/Conversion/Utils/Utils.cpp
python/torch_mlir_e2e_test/test_suite/type_conversion.py

[MLIR][TORCH] Add support for dtype=torch.bool for `aten.to.dtype` op

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds the decomposition of `aten.numpy_T` op into
`aten.t` or `aten.permute` op.

[MLIR][TORCH] Add decomposition of `aten.numpy_T` op

---

lib/Conversion/Utils/Utils.cpp

Fix `verifyLinalgCompatibleTypes`, which currently doesn't successfully catch `torch.tensor`.

Fix `verifyLinalgCompatibleTypes`

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/DataMovement.cpp
python/torch_mlir_e2e_test/test_suite/reshape_like.py

This commit adds support for several size-1 dims in a row in an
expansion using `aten.view`.

[LINALG] Fix handling of size-1 dims in `aten.view`

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

https://github.com/llvm/torch-mlir/commit/829717c96eb09e6393813950532c71c2789718cc broke bazel build. hopefully this fixes.

Fix BUILD.bazel from llvm bump

---

lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir_e2e_test/test_suite/elementwise.py
test/Conversion/TorchToLinalg/elementwise.mlir

Prior to this patch, the torch dialect included `AtenTriuOp` for
computing the upper triangular part of the input matrix, but there was
no code for lowering the op to the linalg dialect.
This patch adds code to generate a `linalg.generic` operation that
compares indices (computed using `linalg.index`) to choose between zero
or the original value (using `arith.select`).  The lowering fails if the
number of dimensions are less than two.  This patch also adds a few
end-to-end tests.

linalg: lower `aten.triu` op to `linalg.generic`

---

lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py

This commit fixes the shape function for `index.Tensor`, adding
support for multiple index tensors and `None`s in the indices
list. This commit also adds support for input tensors of rank greater
than 1. The lowering for `index.Tensor` still has the the limitation
that only a single index tensor along the first dimension of the input
tensor is supported.

[LINALG] Fix shape function of index.Tensor + support N-rank inputs

---

python/torch_mlir/csrc/base_lazy_backend/shape_inference.cpp

This PR complements https://github.com/pytorch/pytorch/pull/79637 (should land by EOD today), which add `compute_shape_native_batch_norm` and `compute_shape_native_batch_norm_backward` to upstream PyTorch.

Upstream native_batch_norm and native_batch_norm_backward shape inference functions 

---

development.md

We recently noticed that it is necessary to update the shape lib while
doing an LLVM bump: https://github.com/llvm/torch-mlir/pull/973
We didn't have a place to document that this was a necessary step, so
add a basic section to hold that and the basic instructions for how to
do a bump.

development.md: updating the LLVM submodule

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToLinalg/Utils.h
lib/Conversion/TorchToTosa/TorchToTosa.cpp
python/torch_mlir_e2e_test/test_suite/matmul.py

This commit lowers `aten.matmul` to `linalg.BatchMatmul` under the
following conditions:
1. The result of matrix multiplication must have batch dimensions,
i.e., rank greater than 2.
2. The resultant matrix must have at most 1 dynamic batch dimension.
It also handles broadcasting of batch dimensions when batch dimensions
of the matrices are broadcastable.

[LINALG] Lower `aten.Matmul` to `linalg.BatchMatmul`

---

lib/Dialect/Torch/Transforms/DropShapeCalculations.cpp
test/Dialect/Torch/drop-shape-calculations.mlir

In the `pyhpc_turbulent_kinetic_energy` TorchBench benchmark, the shape
calculation occurs inside loops, but because `DropShapeCalculationsPass`
does not explicitly mark the Torch dialect as legal, the pass execution
fails.
This patch adds Torch to the list of legal dialects, and adds a test to
validate the translation.

torch: allow torch dialect ops after running drop-shape pass

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp

A tensor data can't be accessed from the host side if it's allocated on CUDA memory. This PR fixes it.

fix export torch.literal on gpu

---

development.md
include/torch-mlir-c/TorchTypes.h
include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
lib/CAPI/TorchTypes.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
test/Dialect/Torch/ops.mlir
test/python/importer/jit_ir/ivalue_import/tensors.py

I ran into this while poking around at
https://github.com/llvm/torch-mlir/issues/959
CC @JasonMaojinsong

Add support for ScalarType::QUInt8

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/DataMovement.cpp
python/torch_mlir_e2e_test/test_suite/reshape_like.py

A previous fix to the handling of size-1 dims in
`aten.view` (https://github.com/llvm/torch-mlir/pull/962) resulted in
the wrong grouping of dimensions when size-1 dims where between two
dims of size greater than 1. This commit fixes that.

[LINALG] Fix handling of size-1 dims in `aten.view` again.

---

build_tools/build_libtorch.sh
development.md
python/CMakeLists.txt

Add an option to cache libtorch/ releases if you don't want to
download the latest. Add an option to enable source builds.
Defaults to always build with latest libtorch. 
TESTS:
macOS: verify with / without cache downloads
verify source builds -- shared | static
Linux: Build Tests and Release builds

Enable libtorch caching and source builds

---

build_tools/build_libtorch.sh
build_tools/build_python_wheels.sh
build_tools/build_standalone.sh
build_tools/python_deploy/build_linux_packages.sh
build_tools/python_deploy/build_macos_packages.sh
build_tools/python_deploy/build_upload_m1_snapshot.sh
build_tools/python_deploy/install_macos_deps.sh
build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh
build_tools/update_shape_lib.sh
build_tools/update_torch_ods.sh
build_tools/write_env_file.sh
python/CMakeLists.txt
python/torch_mlir/dialects/torch/importer/jit_ir/cmake/modules/TorchMLIRPyTorch.cmake
tools/torchscript_e2e_test.sh

On my local machine, `unzip` didn't exist (producing a "command not
found" error), but CMake ignored the error.  Although the build did
succeed (because it found a previously-built version of libtorch), it
seems better to abort builds on such failures, so this patch checks the
return code of all external process invocations.
Along similar lines, this patch also updates the shell scripts in
`build_tools` to extensively use double-quoting to prevent unintentional
word splitting or globbing.  Since some of the scripts execute `rm`
while using shell variables, this patch also adds the preamble `set -u`
to abort execution if an undefined variable is referenced, so that we
reduce the chances of executing `rm -rf /` if the path expression
happens to refer to an undefined variable.

build: improve robustness of cmake and shell scripts

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

Fix segfault when lowering to tosa.matmul - outputs don't need to be reshaped
TOSA Representation of PyTorch matmul (rough)​
```
a1 = reshape(a0)
b1 = reshape(b0)
a2 = broadcast(a1) (optional)
b2 = broadcast(b1) (optional)
c0 = matmul(a2, b2)
c1 = reshape(c0) (optional)
```
The problem occurs when:
- the batch dimension of a0 is 1 
- a0 is rank 3 & b0 is rank 2 or vice versa.
​
Example 1/ `a0: <1,6,1>, b0:<1,4>`
​
There is a segmentation fault because this kind of tensor triggers a optional reshape to the output but does not trigger the optional broadcasting. The function to create the output reshape uses variables that are initialised in the optional broadcast - thus it fails.
The solution I've implemented is to ensure that no output reshape occurs for inputs like Example 1.
**Recreate …

Fix segfault when lowering to tosa.matmul - outputs don't need to be reshaped

---

lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

A prior patch (63538de2) that added support for bfloat16 type did not
add the canonicalization pattern to fold `torch.prim.dtype` operations
on bfloat16 tensors into the integer constant 15.  This patch fixes the
problem.

torch: fold prim.dtype(bf16) to integer constant 15

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py
test/Dialect/Torch/canonicalize.mlir

New contributor to torch-mlir; starting with adding support for the aten.len.str.

Add folding for aten.len.str and E2E test

---

lib/Dialect/Torch/IR/TorchOps.cpp

This patch replaces the use of raw integers like 6, 4, etc. (that
represent PyTorch's scalar types) with named values from the ScalarType
enum (e.g. `ScalarType::Float`, `ScalarType::Long`, etc.) in code for
folding `prim.dtype` ops into numeric constants.
This patch isn't strictly a non-functional change, since its use of
`Torch::getScalarTypeForType()` implies that the input type has to be
one among the supported types, otherwise compilation will abort, whereas
previously, compilation proceeded without folding the unsupported data
type into a numeric constant.

torch: use ScalarType enum instead of raw constants

---

python/torch_mlir/dialects/torch/importer/jit_ir/CMakeLists.txt

Temporarily revert to using PyTorch binaries until source builds
are ready to land.
USE_LOCAL_PYTORCH can be turned to OFF if you want to link against
libtorch and source builds. Once that is more stable we can toggle
back

Revert to using local PyTorch binaries

---

lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
test/Dialect/Torch/reduce-op-variants.mlir
test/Dialect/Torch/simplify-shape-calculations.mlir

This commit adds support for lists of type `list<optional<tensor>>`
where each element in the list is either a `!torch.tensor` or a
`!torch.none`.

Add basic support for list of optional tensors in reduce-op-variants

---

python/torch_mlir/dialects/torch/importer/jit_ir/CMakeLists.txt

Previously, `Torch_DIR` was set regardless of whether `TORCH_MLIR_USE_INSTALLED_PYTORCH` was on or off, which caused some linkage issues with Lazy Tensor Core. This PR modifies the build to only set this variable when `TORCH_MLIR_USE_INSTALLED_PYTORCH` is off.
cc: @antoniojkim

Only set Torch_DIR when TORCH_MLIR_USE_INSTALLED_PYTORCH is off

---

examples/torchscript_resnet18.py
examples/torchscript_resnet18_all_output_types.py
examples/torchscript_resnet_inference.ipynb
python/test/compile_api/output_type_spec.py
python/torch_mlir/__init__.py

A lot of code was super verbose with `torch_mlir.OutputType.XYZ`. Now,
you can simply do `"xyz"`. I updated a few examples.

torch_mlir.compile: Allow OutputType as a string.

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/conv.py

Here's a simple decomposition of `at::_convolution` to `at::convolution`. I'm not sure how much of the flags we want to support.

Add decomposition for at::_convolution

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit does three things:
1. Reverts some of the shape lib changes merged in
https://github.com/llvm/torch-mlir/pull/844
2. Updates the signature of `aten.sum_dim_IntList` that was recently
updated in
https://github.com/pytorch/pytorch/commit/23bdb570cf05f0cefdacdda5cbf73f58a2e574f4
3. Replaces `aten.zero.functional` with `aten.zero`, updated in https://github.com/pytorch/pytorch/commit/960758b0b78671b9c23d0dbe39fe863e1e48ede0

Undo shape lib changes + update function signature of sum + zero

---

build_tools/autogen_ltc_backend.yaml
e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

We need to blacklist `_convolution` since it conflicts with `convolution` during LTC codegen. Underscores are dropped when generating the C++ class name, which results in a compiler error.
`_convolution` should be decomposed to `convolution`, so blacklisting this op will not affect functionality.
This PR also fixes a rebase conflict, which resulted in a duplicated instance of `AtenSelectScatterOp`, `AtenSliceScatterOp`.

Blacklist _convolution op

---

include/torch-mlir/Dialect/Torch/Transforms/Passes.h
include/torch-mlir/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/CMakeLists.txt
lib/Dialect/Torch/Transforms/Passes.cpp
lib/Dialect/Torch/Transforms/VerifyConversionToValueSemantics.cpp
test/Dialect/Torch/verify-conversion-to-value-semantics.mlir

This patch adds a new pass `torch-verify-conversion-to-value-semantics`,
which looks for non-value semantics tensors to catch such tensors early
during compilation.
This pass requires `torch-refine-public-return` pass to ensure that
return operations are updated to use value tensors, followed by the
canonicalize pass to remove any dead ops that may use or produce
non-value tensors.

torch: add pass to catch non-value tensors

---

build_tools/build_libtorch.sh

Found while trying to build torch-mlir on an AArch64 Linux VM, worth
a belts and braces to prevent such cases.
@sjarus

Fail to install x86_64 linux libtorch.so on other architectures.

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

A previous patch added a new file
("VerifyConversionToValueSemantics.cpp") to the build, but it did not
add it to the list files known to bazel.  This patch fixes the problem.

build: fix bazel build after adding VerifyConversionToValueSemantics.cpp

---

build_tools/build_libtorch.sh
python/CMakeLists.txt
python/torch_mlir/dialects/torch/importer/jit_ir/CMakeLists.txt

Remove all the libtorch downloads. If the user sets
-DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF then just build from src.
Doesn't change developer workflow since we still default to local
PyTorch versions.
TEST: Build and verify all tests (except one xfail quant) pass on linux

Remove libtorch downloads

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/stats.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit adds the decomposition of `aten.var.dim` op.

[MLIR][TORCH] Add decomposition of `aten.var.dim` op

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

emitError is intended for error cases and not match failures of
patterns. notifyMatchFailure is intended where pattern reports reason
for not matching.
Op verification should also not happen inside patterns but as part of
verify, so left some of those as is to keep this change small.

Change to notifyMatchFailure

---

include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

This commit adds the canonicalization pattern for the `prim.ListUnpack` op.

[MLIR][TORCH] Add canonicalization pattern for `prim.ListUnpack` op

---

lib/Conversion/TorchToLinalg/DataMovement.cpp
python/torch_mlir_e2e_test/test_suite/basic.py
python/torch_mlir_e2e_test/test_suite/slice_like.py

This commit adds the support for negative dim cases for `aten.cat`,
`aten.slice.Tensor` and `aten.slice_scatter` op.

[MLIR][TORCH] Add negative dim support for `aten.cat` and `aten.slice` op

---

include/torch-mlir-c/Dialects.h
python/CMakeLists.txt
python/TorchMLIRModule.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/module_builder.cpp
python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py
python/torch_mlir_e2e_test/tosa_backends/linalg_on_tensors.py

This patch makes some rudimentary changes to torch-mlir's use of MLIR
Python bindings to work with the most recent LLVM code.  We can perhaps
do better by being more selective in what we link against, instead of
using `MLIRPythonExtension.RegisterEverything`.

bump llvm tag to 3580daa

---

lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

This patch still only supports a single indexing tensor.

Add support for index.Tensor on dimensions other than the first

---

python/torch_mlir/csrc/base_lazy_backend/backend_impl.cpp
python/torch_mlir/csrc/base_lazy_backend/backend_impl.h
python/torch_mlir/csrc/reference_lazy_backend/backend_impl.cpp

It has been brought to my attention that the https://github.com/pytorch/pytorch/pull/76517 will be adding a couple new methods to the backend interface. This will break the Torch-MLIR backend interface as they are pure virtual. Adding implementations for them to avoid breakage.
This PR will only be merged in after https://github.com/pytorch/pytorch/pull/76517 has been merged in.

Default Device Ordinal API

---

e2e_testing/torchscript/xfail_sets.py
lib/Conversion/TorchToLinalg/DataMovement.cpp
python/torch_mlir_e2e_test/test_suite/reshape_like.py

- Supports cases where the view op expands and collapses dims
simultaneously. This does not handle the case where it is neither
expanding nor collapsing (e.g. [2, 3] -> [3, 2])
- Additionally fixes a previous bug with adding 1-sized dims on both
sides of a tensor with aten.view

Allow expanding and collapsing in aten::view

---

include/torch-mlir-c/Registration.h
lib/CAPI/CMakeLists.txt
lib/CAPI/Registration.cpp
python/CMakeLists.txt
python/TorchMLIRModule.cpp
python/torch_mlir/_mlir_libs/_site_initialize_0.py
python/torch_mlir/dialects/torch/__init__.py
test/python/smoketest.py

In the interest of merging upstream LLVM quickly, a previous patch
(7f08169) updated the torch-mlir build to register all dialects and
passes through Python bindings.  This patch limits the dialects and
passes to only those that are used in torch-mlir.
Key to this change are the removal of
`MLIRPythonExtension.RegisterEverything` and the introduction of a new
Python module (`_mlir_libs/_site_initialize_0.py`), where we register
the dialects and passes used by torch-mlir.

python: trim registration and loading of dialects and passes

---

include/torch-mlir-c/Registration.h
lib/CAPI/CMakeLists.txt
lib/CAPI/Registration.cpp
python/CMakeLists.txt
python/TorchMLIRModule.cpp
python/torch_mlir/_mlir_libs/_site_initialize_0.py
python/torch_mlir/dialects/torch/__init__.py
test/python/smoketest.py

This reverts commit ad283c104339267fbe11cc7efefc02a6ad4d2d1e, since it's
causing nightly build failures for all platforms.

Revert "python: trim registration and loading of dialects and passes"

---

include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
test/Dialect/TorchConversion/ops.mlir

This commit adds verifiers to the ops `ToBuiltinTensorOp` and
`FromBuiltinTensorOp` that make sure that the input and output have
the same shape and data type.

Add verifiers for ToBuiltinTensorOp and FromBuiltinTensorOp

---

lib/Conversion/TorchToMhlo/CMakeLists.txt
lib/Conversion/TorchToMhlo/PopulatePatterns.h
lib/Conversion/TorchToMhlo/SliceLikeOps.cpp
lib/Conversion/TorchToMhlo/TorchToMhlo.cpp
test/Conversion/TorchToMhlo/slice_like.mlir

See RFC: https://github.com/llvm/torch-mlir/issues/999
Co-authored-by: Bairen Yi yibairen.byron@bytedance.com
Co-authored-by: Jiawei Wu xremold@gmail.com
Co-authored-by: Tianyou Guo tianyou.gty@alibaba-inc.com
Co-authored-by: Xu Yan yancey.yx@alibaba-inc.com
Co-authored-by: Ziheng Jiang ziheng.jiang@bytedance.com

[MHLO] Init MHLO slice like op patterns

---

lib/Conversion/TorchToMhlo/ViewLikeOps.cpp
test/Conversion/TorchToMhlo/view_like.mlir

See RFC https://github.com/llvm/torch-mlir/issues/999
Co-authored-by: Bairen Yi [yibairen.byron@bytedance.com](mailto:yibairen.byron@bytedance.com)
Co-authored-by: Jiawei Wu [xremold@gmail.com](mailto:xremold@gmail.com)
Co-authored-by: Tianyou Guo [tianyou.gty@alibaba-inc.com](mailto:tianyou.gty@alibaba-inc.com)
Co-authored-by: Xu Yan [yancey.yx@alibaba-inc.com](mailto:yancey.yx@alibaba-inc.com)
Co-authored-by: Ziheng Jiang [ziheng.jiang@bytedance.com](mailto:ziheng.jiang@bytedance.com)

[MHLO] Add [un]squeeze op patterns

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py
python/torch_mlir_e2e_test/test_suite/elementwise.py
test/Dialect/Torch/decompose-complex-ops.mlir

Adds a straightforward implementation of aten.softplus and log1p. Softplus is used in the [mish activation function](https://github.com/rwightman/pytorch-image-models/blob/326ade299983a1d72b0f4def1299da1bb0f6b6f2/timm/models/layers/activations.py#L29) and log1p is used to implement softplus.

Add lowering to linalg for softplus and log1p

---

development.md

Add source builds and remove deprecated libtorch information.

Update development.md with source builds

---

build_tools/autogen_ltc_backend.yaml
python/torch_mlir/csrc/base_lazy_backend/mlir_native_functions.cpp

In upstream PyTorch, they switched the tensor constructor to use `lift_fresh` instead of `lift` which silently broken LTC. Adding support for this op should fix the examples being broken.
The upstream fix for the TS backend: https://github.com/pytorch/pytorch/pull/81928

Add support for `lift_fresh` op

---

python/torch_mlir/csrc/base_lazy_backend/CMakeLists.txt

Currently the LTC headers are not being exported in the Python wheel. This means they aren't being distributed. This is something that is needed for vendors that do not intend to clone/build the Torch-MLIR repo in order to use the base lazy backend.

Export LTC Headers

---

utils/bazel/WORKSPACE.bazel
utils/bazel/torch-mlir-overlay/BUILD.bazel

- Adds `@mlir-hlo` repo to bazel Workspace.
- Builds TorchToMhlo conversion `torch-mlir/Conversion/TorchToMhlo`
This should fixes the current broken bazel builds.

Add mhlo to bazel build

---

python/torch_mlir_e2e_test/test_suite/stats.py

Fixes https://github.com/llvm/torch-mlir/issues/1121

Fix CI failure due to upstream PyTorch change in aten.mean.dim op

---

.github/workflows/buildAndTest.yml

test with fast-fail matrix builds

buildAndTest.yml for matrix builds

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/slice_like.py

Currently still under development, tests pass with a test with 3 dimensional arrays but not 2 dimensional arrays. (Compiler crash)
(Now fixed!)

[MLIR] [TORCH] Add E2E support for `aten::narrow` op

---

lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h
lib/Conversion/TorchToMhlo/ViewLikeOps.cpp

See RFC: https://github.com/llvm/torch-mlir/issues/999
Co-authored-by: Bairen Yi yibairen.byron@bytedance.com
Co-authored-by: Jiawei Wu xremold@gmail.com
Co-authored-by: Tianyou Guo tianyou.gty@alibaba-inc.com
Co-authored-by: Xu Yan yancey.yx@alibaba-inc.com
Co-authored-by: Ziheng Jiang ziheng.jiang@bytedance.com

[NFC][MHLO] move util funcs to MhloLegalizeUtils.h/cpp

---

lib/Conversion/TorchToMhlo/BasicOp.cpp
lib/Conversion/TorchToMhlo/CMakeLists.txt
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h
lib/Conversion/TorchToMhlo/TorchToMhlo.cpp
lib/Dialect/TorchConversion/Transforms/CMakeLists.txt
lib/Dialect/TorchConversion/Transforms/Passes.cpp
test/Conversion/TorchToMhlo/basic.mlir

See RFC #999 
This is a revision of PR #1116 . The main change is switching to use CHLO dialect to support dynamic shape when lowering basic op to MHLO dialect.

[MHLO] Support for dynamic shape in basic op conversion by introducing CHLO dialect

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/stats.py

PyTorch recently added support for `dim=None` in the `torch.mean`
op (https://github.com/pytorch/pytorch/commit/2bfae07a796187b047c6113b46d0aabbf319d990). This
commit adds the corresponding support in torch-mlir.

Add support for `dim=None` to `AtenMeanDimOp`

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

- The decency name changed in the recent update 55bbbec144334f77bece3595c7cbc9875b0be016

Fix mhlo bazel rule name

---

lib/Conversion/TorchToMhlo/BasicOp.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h
test/Conversion/TorchToMhlo/basic.mlir
test/Conversion/TorchToMhlo/elementwise.mlir

See RFC https://github.com/llvm/torch-mlir/issues/999
Co-authored-by: Bairen Yi yibairen.byron@bytedance.com
Co-authored-by: Jiawei Wu xremold@gmail.com
Co-authored-by: Tianyou Guo tianyou.gty@alibaba-inc.com
Co-authored-by: Xu Yan yancey.yx@alibaba-inc.com
Co-authored-by: Ziheng Jiang ziheng.jiang@bytedance.com

[MHLO] support non-constant torch scalar in BasicOps

---

lib/Conversion/TorchToMhlo/CMakeLists.txt
lib/Conversion/TorchToMhlo/PopulatePatterns.h
lib/Conversion/TorchToMhlo/ReductionOp.cpp
lib/Conversion/TorchToMhlo/TorchToMhlo.cpp
test/Conversion/TorchToMhlo/reduction.mlir

[MHLO] Init MHLO reduce-like op conversion

---

e2e_testing/torchscript/xfail_sets.py

This commit fixes the CI failure by temporarily adding the failing
test to xfail set.

[MLIR][TORCH] Fix CI failure

---

.github/workflows/buildAndTest.yml

This should enabling better caching of builds.

Fix cache-suffix name bug

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

- Fixes bazel build after commit 636f5acb103283522193f8673f411808ec475b95

[bazel build] Add recently added torch->mhlo conversion pass to bazel

---

lib/Conversion/TorchToLinalg/Linear.cpp
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/conv.py

Adds support for group sizes > 1 for at::convolution (and by extension the ops that decompose into it).

Add non-unit groups to aten::convolution

---

python/torch_mlir_e2e_test/test_suite/stats.py

To test the summation stability of `torch.aten.var`, add a large
constant to it, which increases the effective precision requirements.

Make numerical stability test more perverse

---

python/test/compile_api/tracing.py
python/torch_mlir/__init__.py
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/import_options.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/import_options_pybind.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/import_options_pybind.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/init_python_bindings.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/module_builder.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/module_builder.h
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp

In some cases, users know that a traced graph is valid for a wider set
of shapes than they originally traced it with. Provide an option for
users to ignore the shapes in the traced graph when they know it is
legal.
Fixes #997

torch_mlir.compile: Allow ignoring traced shapes

---

python/test/torchscript_e2e_test/error_reports.py
python/torch_mlir_e2e_test/torchscript/reporting.py

This helps to triage issues related to backends that don't support all
dtypes.

E2E framework: Report tensor dtype in summary

---

lib/Conversion/TorchToMhlo/Basic.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
test/Conversion/TorchToMhlo/elementwise.mlir
test/Dialect/Torch/decompose-complex-ops.mlir

See RFC https://github.com/llvm/torch-mlir/issues/999

[MHLO] fix tensor mode aten.div op pattern

---

lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp
test/Conversion/TorchToLinalg/basic.mlir
test/python/importer/jit_ir/ivalue_import/tensors.py

follow up #761:
This patch updates the `torch_mlir::convertTensorToMlirElementsAttr()`
method to enable the creation of tensors whose base type is Float16.
This patch also adds a test to validate the IR generation, and it
updates the test for importing tensors of various types.

importer: add initial support for loading Float16 tensors

---

.github/workflows/buildAndTest.yml
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt
setup.py

Addressing #1154 
I'm not entirely sure what changed... but it looks like out-of-tree build works even with LTC enabled now

Reenable LTC in out-of-tree build

---

lib/Conversion/TorchToMhlo/Linear.cpp
test/Conversion/TorchToMhlo/linear.mlir

See RFC #999 
This is a feature enhancement patch of PR #1152 to support transposed convolution conversion.

[MHLO] Add transposed convolution  conversion pattern

---

.github/workflows/buildAndTest.yml
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt
setup.py

Reverts llvm/torch-mlir#1177
Due to: https://github.com/llvm/torch-mlir/issues/1126#issuecomment-1208757895

Revert "Reenable LTC in out-of-tree build"

---

lib/Conversion/TorchToMhlo/Reduction.cpp

This PR fixed lowering failed on `ten::max_dim` with i32 shape type.

[MHLO]fix lowering failed on reduction op with i32 shape

---

lib/Dialect/Torch/IR/CMakeLists.txt

The Torch dialect has an include to `mlir/Dialect/Func/IR/FuncOps.h` and
should therefore have a CMake dependency to the MLIRFuncDialect.
Otherwise, the build can fail since it may occur that
`mlir/Dialect/Func/IR/FuncOps.h.inc` isn't generated yet.

Add CMake dep to Func dialect

---

CMakeLists.txt
externals/llvm-external-projects/torch-mlir-dialects/CMakeLists.txt

With llvm/llvm-project@112499f landed, `MLIR_TABLEGEN_EXE` is given as a
cache variable in the MLIR core project. Other external projects, such
as TORCH-MLIR, should not set the variable as this breaks
cross-compilation.

Don't set MLIR_TABLEGEN_EXE

---

utils/bazel/.bazelrc

Flip to C++17

---

.github/workflows/buildAndTest.yml

The matrix jobs in GHA are intended to be setup for checking "build + tests" for in-tree, but "build only" for out-of-tree workflows. However (as discovered [here](https://github.com/llvm/torch-mlir/issues/1162#issuecomment-1208762623)) at the moment building torch-mlir OOT is skipped in CI. We're just "building llvm" and "configuring cmake to build torch-mlir", but the build itself is [gated](https://github.com/llvm/torch-mlir/blob/f85ae9c685d6c9f2d43fe60fdad2ad5d3183ec52/.github/workflows/buildAndTest.yml#L103) for the OOT case with:
```
if: matrix.llvmtype == 'binary'
```
partly because it is combined with the unit test target which is skipped for OOT. 
As seen below, both build and test steps are skipped for OOT case:
This PR splits the build from `check-torch-mlir-all` and moves it …

Include torch-mlir builds in OOT workflow

---

.github/workflows/bazelBuildAndTest.yml

At the moment we don't gate torch-mlir PRs with bazel builds. This means bazel builds don't get run on open PRs, and so there's no good way to validate a fix PR which is meant to fix a broken bazel build. This option allows a bazel build to be manually triggered as needed on open PRs.

[Bazel] Allow workflow_dispatch manual trigger on bazel workflow

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

The torch-mlir bazel build is [failing](https://github.com/llvm/torch-mlir/runs/7737425906?check_suite_focus=true) since [this commit](https://github.com/llvm/torch-mlir/commit/504de5e70104c335dd45f6f2be695356d2b832fb) due to a linker failure (undefined symbol: `mlir::torch::Torch::createEraseModuleInitializerPass()`).
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/db599744cd37f8c161e5034d9b9cd520/external/torch-mlir/BUILD.bazel:845:10: Linking external/torch-mlir/torch-mlir-opt failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-11/bin/clang @bazel-out/k8-fastbuild/bin/external/torch-mlir/torch-mlir-opt-2.params
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: undefined symbol: …
```

[Bazel] Add EraseModuleInitializer to TorchMLIRTorchPasses library

---

lib/Conversion/TorchToMhlo/Basic.cpp
test/Conversion/TorchToMhlo/basic.mlir

See RFC #999 
This PR adds AtenCatOp conversion pattern to MHLO.

[MHLO] Add AtenCatOp conversion pattern to MHLO

---

.github/workflows/buildAndTest.yml
python/CMakeLists.txt

Add support for M1 cross compile. Also compile and test macos x86

mac m1 cross compile

---

development.md

Adding an example on how to extract MLIR output from the compilation
process in various different formats to the development documentation.
This should help developers trying to either debug torch_mlir or use it
for the purpose of extracting MLIR outputs for other testing.
Fixes #1175

Add note about MLIR compiled outputs in dev docs

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

The CI didn't catch the missing rename of TorchToArith until the
merge had happened. This is following up from #1163
Sorry about the failure.
@sjarus ,

Update TorchToStd to TorchtoArith in bazel files too.

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py

Add lowering for aten.to.device

---

lib/Conversion/TorchToMhlo/TorchToMhlo.cpp

All torch ops should be converted to mhlo after `TorchToMhlo` pass.

[MHLO]remove torch dialect from legal list

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/constant_alloc.py

`aten.masked.tensor` op has been decomposed to `aten.masked.scalar` op.

Add decomposition of `aten.masked.tensor` op.

---

requirements.txt

Building on a fresh environment + virtualenv + in-tree build errors out
becayse PyYaml isn't installed. Adding to requirements.txt fixes that.
Fixes #1173

Add PyYaml to requirements.txt

---

.github/actions/setup-build/action.yml
.github/workflows/bazelBuildAndTest.yml
.github/workflows/buildAndTest.yml
build_tools/build_libtorch.sh

Addresses https://github.com/llvm/torch-mlir/issues/1207. 
```
```
* ubuntu-x86_64 out-of-tree integration tests fail ([error](https://github.com/sjain-stanford/torch-mlir/runs/7781264029?check_suite_focus=true)); only run unit tests for now (tests are excluded in current CI too)
https://github.com/sjain-stanford/torch-mlir/actions/runs/2840676309

Simplify matrix configuration for CI workflows

---

.github/workflows/buildAndTest.yml

We're seeing flakiness of the macos-arm64 build with "pytorch source" enabled (passed on original PR but [failed](https://github.com/llvm/torch-mlir/actions/runs/2843475942/attempts/1) [twice](https://github.com/llvm/torch-mlir/actions/runs/2843475942/attempts/2) on main since, introducing increased overhead in landing PRs).
I'm leaning towards flipping this back to binary. This should help with the following:
* reduce the number of long running pytorch source builds to one job (ubuntu-OOT)
* reduce cache invalidations for macos builds to only llvm updates (which are weekly rather than hourly)
* speed-up fail-fast signal despite being decoupled from ubuntu matrix jobs

Use pytorch binary for macos-arm64 workflow

---

.github/workflows/buildAndTest.yml

My earlier[ PR](https://github.com/llvm/torch-mlir/pull/1213) had (among other things) decoupled ubuntu and macos builds into separate matrix runs. This is not working well due to limited number of MacOS GHA VMs causing long queue times and backlog. There are two reasons causing this backlog: 
1. macos arm64 builds with pytorch source are getting erratically cancelled due to resource / network constraints. This is addressed with this: https://github.com/llvm/torch-mlir/pull/1215
> "macos-arm64 (in-tree, OFF) The hosted runner: GitHub Actions 3 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error."
2. macos runs don't fail-fast when ubuntu runs fail due to being in …

Merge matrix runs to fail fast globally

---

.github/workflows/bazelBuildAndTest.yml
.github/workflows/buildAndTest.yml

We're seeing large CI queue times ([example](https://discord.com/channels/636084430946959380/742573221882364009/1007631811184164944)) especially with MacOS VMs on GHA. Part of the problem is follow-on commits to the same branch which trigger new runs while the previous runs are still in-progress, hogging on the scarce VMs.
This PR adds concurrency groups to the GHA workflow which ensures that only a single job or workflow using the same concurrency group will run at a time. This would cancel any in-progress jobs in the same github workflow and github ref (e.g. `refs/heads/main` or `refs/pull/<pr_number>/merge`).
As discussed on discord [thread](https://discord.com/channels/636084430946959380/1007787336848912386/1007787338895740928), once this lands we may have to closely monitor the …

[Build] Add concurrency groups to address long queue times

---

lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp

According to the documentation for
`torch.embedding_bag` (https://pytorch.org/docs/stable/generated/torch.nn.functional.embedding_bag.html),
the default value for `scale_grad_by_freq` is False.

Fix unused-variables warnings about EmbeddingBag ops

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

This PR generalizes the canonicalization pattern in PR #935 to fit more AtenOps (like `AtenSubTensorOp`, `AtenMulScalarOp`, and `AtenDivTensorModeOp`). The basic idea is eliminating these tensor ops when their tensor operands are zero-ranked tensors, which come from `ValueTensorLiteralOp` or `PrimNumToTensorScalarOp`, and replacing them with corresponding scalar ops. 
This PR also helps to solve issue #1182 .

Generalize canonicalization pattern for more aten.sub/div/mul/add op

---

CMakeLists.txt
python/test/lazy_backend/device_data_name.py
python/test/lazy_backend/run_test.py
python/test/lit.cfg.py
python/torch_mlir/csrc/base_lazy_backend/CMakeLists.txt
python/torch_mlir/csrc/base_lazy_backend/backend_impl.h
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h
python/torch_mlir/csrc/base_lazy_backend/ops/device_data.cpp
python/torch_mlir/csrc/base_lazy_backend/ops/device_data.h
python/torch_mlir/csrc/base_lazy_backend/utils/string_utils.h
python/torch_mlir/csrc/base_lazy_backend/utils/tensor_utils.h
python/torch_mlir/csrc/reference_lazy_backend/backend_impl.cpp
python/torch_mlir/csrc/reference_lazy_backend/reference_lazy_backend_pybind.cpp
python/torch_mlir_e2e_test/torchscript/configs/lazy_tensor_core.py
setup.py

Need to propagate device data names in order to be able to distinguish between inputs and weights.
An example of its intended usage has been added to the reference backend. The idea is to assign names to tensors on the python side (e.g. perhaps in the dataloader) so that you know which tensors are which in the actual compile
Also, export remaining headers that weren't exported before.

Propagate device data names

---

build_tools/update_shape_lib.sh
build_tools/update_torch_ods.sh
lib/Conversion/TorchToLinalg/CMakeLists.txt
lib/Conversion/TorchToLinalg/PopulatePatterns.h
lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
python/CMakeLists.txt
python/torch_mlir/_torch_mlir_custom_op_example/CMakeLists.txt
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/__init__.py

Re-enable custom op support (https://github.com/llvm/torch-mlir/pull/895) that was reverted due to MacOS builder issue.

Re-enable custom op support

---

lib/Conversion/TorchToMhlo/Basic.cpp
test/Conversion/TorchToMhlo/elementwise.mlir

See RFC #999 
This PR adds AtenRSubScalarOp conversion pattern from Torch dialect to MHLO dialect.

[MHLO] Add AtenRSubScalarOp conversion pattern to MHLO

---

build_tools/update_shape_lib.sh
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py

Bumps the shape library:
- The function signature for aten.arange.start_step was out of date
- upstream_shape_functions.mean_dim -> upstream_shape_functions.sum_mean_dim

Bump the shape lib to match the upstream functions currently in PyTorch

---

.github/workflows/bazelBuildAndTest.yml
development.md
utils/bazel/.bazelrc
utils/bazel/docker/Dockerfile
utils/bazel/docker/run_bazel_build.sh
utils/bazel/docker/run_docker.sh

This PR adds:
- A minimal docker wrapper to the bazel GHA workflow to make it reproducible locally
- Bazel cache to speed up GHA workflows (down to ~5 minutes from ~40+minutes)
This is a no-op for non-bazel workflows and an incremental improvement.

Dockerize and Cache Bazel {Local, CI} Builds

---

.github/workflows/bazelBuildAndTest.yml

This fixes a seeding issue with the [previous PR](https://github.com/llvm/torch-mlir/pull/1240) where bazel build's GHA cache is not present to begin with and one of the commands (chown) fails on it. Should get the Bazel build back to green.

[Bazel] Check cache directory exists before changing owners

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

Pass is introduced in [this commit](https://github.com/llvm/torch-mlir/commit/57681f794764a34c34e2be7f07f7dfbcafa683c1). Including it to the bazel targets to get a green build.

[Bazel] Add `LowerToBackendContract.cpp` to `TorchMLIRTorchPasses` bazel target

---

lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py

I recently fixed the handling of the `dim` argument in
`sum_mean_dim` (https://github.com/pytorch/pytorch/commit/59fccab85775da7a0ecf33bda241f81eade3ad4b). Therefore,
the checks that the `dim` input is `None` or `[]` are no longer needed.

Clean up shape functions that use `sum_mean_dim`

---

include/torch-mlir/Dialect/Torch/Transforms/Passes.h
include/torch-mlir/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
lib/Dialect/Torch/Transforms/Passes.cpp
test/Dialect/Torch/decompose-complex-ops-legal.mlir

This is a first step towards formalizing the set of ops in our backend
contract. The goal is to eventually formalize `torch` dialect ops into 3
categories:
1. Legal in backend contract
2. Illegal in backend contract
3. Conditionally legal in backend contract
The "conditionally legal" set are the ops that we can optionally
decompose for backends.
This patch adds relevant pass options for this throughout the compiler,
in preparation for a new set of traits which will formalize this
classification.

Add a concept of "backend legal ops".

---

lib/Dialect/Torch/Transforms/RefinePublicReturn.cpp
test/Dialect/Torch/refine-public-return.mlir

One of the simplifications made by the pass `RefinePublicReturn`
currently only happens if the tensor in question only has one
user. However, the current method of checking this does not correctly
handle the case of a user having multiple uses of the same
tensor. This commit makes sure only unique users are considered.

Add support for returning more than one copy of the same tensor

---

build_tools/python_deploy/build_linux_packages.sh

It should still build from anything 3.6+ (until MLIR changes the minimum version). We have seen zero downloads with Python 3.7.

Drop Python 3.7x from the nightly binary builds

---

lib/Conversion/TorchToMhlo/ViewLike.cpp
test/Conversion/TorchToMhlo/view_like.mlir

This PR passed an additional `output type` arg when converting AtenSliceTensorOp to MHLO dialect. Since mhlo.RealDynamicSliceOp's canonicalization pattern requires static output shape, the benefits of passing output type is to eliminate explicit output shape generating, which introduces dynamic shape even in static patterns, and thus helpful to canonicalize mhlo.RealDynamicSliceOp.

[MHLO] Eliminate explicit dynamic output shape generating in converting AtenSliceTensorOp

---

utils/bazel/WORKSPACE.bazel
utils/bazel/configure.bzl
utils/bazel/torch-mlir-overlay/BUILD.bazel

Lint all Bazel files (BUILD, WORKSPACE, .bzl, or .sky).
Steps followed:
```shell
./utils/bazel/run_docker.sh
git clone https://github.com/bazelbuild/buildtools.git
cd buildtools
bazel build //buildifier
./bazel-bin/buildifier/buildifier_/buildifier -r ../utils/bazel/
./bazel-bin/buildifier/buildifier_/buildifier --lint=fix -r ../utils/bazel/
```

[Bazel] Run buildifier

---

.github/workflows/buildAndTest.yml
CMakeLists.txt
build_tools/python_deploy/build_macos_packages.sh
python/CMakeLists.txt
python/torch_mlir/csrc/reference_lazy_backend/CMakeLists.txt
python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt
setup.py

This PR addresses https://github.com/llvm/torch-mlir/issues/1154 and https://github.com/llvm/torch-mlir/issues/1126, which means that LTC can build OOT -- which allows it to be included in our wheels 🎉 🎉 .
To summarize, a problem we were hitting before was that OOT build of LTC in CI would fail due to `TorchMLIRJITIRImporter` being switched to a `SHARED` library, in order to access some functions from LTC. This resulted in some nasty nasty pybind errors.
I was unable to root cause the source of the failure from changing the library type to `SHARED`; however, this PR gets around this problem by breaking up `TorchMLIRJITIRImporter` into two parts: a core library, and the pybind. This way, the pybind can remain ` MODULE`, which will prevent the original problem.
A new library called …

Reenable LTC in out-of-tree build (for real this time)

---

include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionOps.td
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
test/Dialect/TorchConversion/canonicalize.mlir

This PR adds folder for `ToF64Op` and `FromF64Op` in `TorchConversion` dialect, and helps to canonicalize IR pattern like this:
```mlir
%float1 = torch.constant.float 1.000000e+00
%0 = torch_c.to_f64 %float1
```
or:
```mlir
%c5_f64 = arith.constant 5.000000e+00 : f64
%0 = torch_c.from_f64 %c5_f64
```

Add folder for ToF64Op and FromF64Op

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/conv.py

This is also a simple decomposition of aten::_convolution.deprecated to aten::convolution following the PR #956.

Add lowering for _convolution.deprecated

---

CMakeLists.txt

With llvm/llvm-project@91b6f76, the variable `MLIR_PDLL_TABLEGEN_EXE` is
set as a cache variable in MLIR upstream.
Likely requires an update of externals/mlir-hlo to
tensorflow/mlir-hlo@4f2a00b or later.

Don't explicitly set MLIR_PDLL_TABLEGEN_EXE

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir/__init__.py
test/Dialect/Torch/decompose-complex-ops.mlir

Can you review for me @silvasean @powderluv. Thanks!

Add decomposition for aten.flatten.using_ints

---

e2e_testing/torchscript/xfail_sets.py
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
python/torch_mlir_e2e_test/test_suite/constant_alloc.py

This error was coming up for various models:
```
File "v_diffusion_model_only.py", line 208, in <module>
module = torch_mlir.compile(
File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 217, in compile
run_pipeline_with_repro_report(mb.module,
File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: type '!torch.Device' …
```

[MLIR][TORCH] Add torch.Device type to backend contract scalar types

---

examples/torchscript_mhlo_backend_resnet.py
examples/torchscript_mhlo_backend_tinybert.py

See RFC #999 
This PR adds bert-tiny and resnet18 e2e examples from torchscript to mhlo.

[MHLO] bert-tiny and resnet18 e2e example from torchscript to mhlo

---

e2e_testing/torchscript/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py
test/Dialect/Torch/decompose-complex-ops.mlir

1. Add `aten.roll` to torch_ods_gen.py
2. Add decomposition for aten.roll
3. Add decomposition filecheck for aten.roll
4. Add a e2e unit test

Add decomposition for aten.roll

---

python/torch_mlir/__init__.py

The use of numbers was arbitrary and was preventing the enum values from
being put in the natural order.

[cleanup] Change OutputType enum values to strings

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToLinalg/Utils.h
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/conv.py

Here's transposed support for convolution, both strided and unstrided.

Add transposed case for at::convolution

---

docs/ltc_examples.md
examples/ltc_backend_bert.py
examples/ltc_backend_mnist.py
python/test/lazy_backend/device_data_name.py
python/torch_mlir/csrc/base_lazy_backend/CMakeLists.txt
python/torch_mlir/csrc/reference_lazy_backend/CMakeLists.txt
python/torch_mlir_e2e_test/torchscript/configs/lazy_tensor_core.py

Addresses https://github.com/llvm/torch-mlir/issues/1271, which will allow LTC to work from the prebuild wheels without import issues.
Previously, we were missing some cmake macros to include `$ORIGIN` to the list of directories searched for shared libraries.
As part of this, the reference LTC backend + base LTC backend were moved to `_mlir_libs` to be consistent with our other libraries (and also because the both of the libs need to be in the same directory for linking).
cc: @ke1337 @antoniojkim

Fix LTC lib_torch_mlir_ltc.so import error

---

python/torch_mlir_e2e_test/test_suite/basic.py
python/torch_mlir_e2e_test/test_suite/cast.py
python/torch_mlir_e2e_test/test_suite/constant_alloc.py
python/torch_mlir_e2e_test/test_suite/control_flow.py
python/torch_mlir_e2e_test/test_suite/elementwise.py
python/torch_mlir_e2e_test/test_suite/elementwise_comparison.py
python/torch_mlir_e2e_test/test_suite/histogram_binning_calibration.py
python/torch_mlir_e2e_test/test_suite/index_put.py
python/torch_mlir_e2e_test/test_suite/nll_loss.py
python/torch_mlir_e2e_test/test_suite/pooling.py
python/torch_mlir_e2e_test/test_suite/reduction.py
python/torch_mlir_e2e_test/test_suite/scalar.py
python/torch_mlir_e2e_test/test_suite/scalar_comparison.py
python/torch_mlir_e2e_test/test_suite/slice_like.py
python/torch_mlir_e2e_test/test_suite/table_batch_embedding.py
python/torch_mlir_e2e_test/test_suite/threshold.py
python/torch_mlir_e2e_test/test_suite/type_conversion.py
python/torch_mlir_e2e_test/test_suite/type_promotion.py
python/torch_mlir_e2e_test/torchscript/framework.py

This commit adds a method to `TestUtils` that generates random integer
tensors with a similar interface to the `TestUtils.rand`. This commit
also replaces with `tu.randint` all test inputs generated with
`torch.randint`.

Add TestUtils.randint + replace torch.randint with tu.randint

---

docs/adding_an_e2e_test.md

This commit adds a file explaining the structure of an E2E test, as
well as useful things to keep in mind when adding new tests.

Add documentation for adding E2E tests

---

e2e_testing/torchscript/main.py
python/torch_mlir_e2e_test/torchscript/framework.py

Change logic so that we never run the multiprocessing codepath with only
1 worker. That configuration was causing all subsequent tests to
spuriously fail if one test failed with a crash (this was easy to see
after sorting the tests). That configuration was the one used by the CI.
Also, sort tests to make output nicer.
Also, make verbose mode more verbose so that it is easy to see in `-s`
mode which test is crashing.

Avoid cascading failures when compiler crashes

---

.github/workflows/buildAndTest.yml
CMakeLists.txt
setup.py

Tracked with the WIP https://github.com/llvm/torch-mlir/pull/1292

Disable LTC by default until upstream revert relands

---

lib/Dialect/Torch/Transforms/ReduceOpVariants.cpp

We used to not have "value-semantic" tensors but rather "immutable"
tensors

Rename an outdated class name

---

python/torch_mlir_e2e_test/framework.py

In the sequential case we weren't sorting, which was confusing.

Sort tests before anything else.

---

lib/Conversion/Utils/CMakeLists.txt

Caught in the wild here:
https://github.com/llvm/torch-mlir/runs/8046660640?check_suite_focus=true
It is common for a missing dependency to only surface as an issue on the
CI machines since they have fewer cores which prevents a "race" that
happens to cause the dependency to be built before the dependent.

Add some missing dependencies.

---

build_tools/python_deploy/build_linux_packages.sh
build_tools/update_shape_lib.sh
build_tools/update_torch_ods.sh

Also update the scripts to return 1 when there are changes. The tests can check and report if there are any changes. But you get a warning even when you run it outside of the CI. 
TEST:
The passing tests look like:
:::: Run shapelib update tests
Shape Lib is up to date
:::: Run torch_ods update tests
Torch ODS is up to date
Failing would like like:
```
~/github/torch-mlir % time ./build_tools/update_shape_lib.sh
PYTHONPATH=/home/anush/github/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir python -m torch_mlir.dialects.torch.importer.jit_ir.build_tools.shape_lib_gen --pytorch_op_extensions= --torch_transforms_cpp_dir=/home/anush/github/torch-mlir/lib/Dialect/Torch
/Transforms
Generated files are not up to date (see diff below)
>>> Please run ./build_tools/update_torch_ods.sh …
```

Add shapelib and Torch ODS gen tests

---

build_tools/build_libtorch.sh

This should speed up source builds and ccache. May cause issues on macOS (https://github.com/pytorch/pytorch/issues/80018)

Use pre-compiled headers for PyTorch Source builds

---

.github/actions/setup-build/action.yml

This is to debug what is causing the exactly ccache look up failures etc.

Set ccache logging to verbose temporarily

---

CMakeLists.txt
include/torch-mlir/Conversion/Passes.td
include/torch-mlir/Conversion/TorchToMhlo/TorchToMhlo.h
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Conversion/TorchToMhlo/Gather.cpp
lib/Conversion/TorchToMhlo/Linear.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h
lib/Conversion/TorchToMhlo/Pooling.cpp
lib/Conversion/TorchToMhlo/PopulatePatterns.h
lib/Conversion/TorchToMhlo/Reduction.cpp
lib/Conversion/TorchToMhlo/TorchToMhlo.cpp
lib/Conversion/TorchToMhlo/ViewLike.cpp

Related to https://github.com/llvm/torch-mlir/issues/1227
1. Reduce MHLO #ifdefs
2. Dismiss compilation warnings

[MHLO] refactor pass configurations

---

build_tools/python_deploy/build_linux_packages.sh

Shows low download count and we can add it back if people ask for it. Should save release artifacts space and Release build time.

Drop Python3.8 binary releases. Still builds from source.

---

build_tools/python_deploy/build_linux_packages.sh

We added both ipc=host and explicit ulimits. This _may_ be causing slow downs on GHA. Remove the ulimit setting still passes all the CI tests locally. `--ipc=host` is still required.
Fixes: https://github.com/llvm/torch-mlir/pull/1325

Remove setting ulimit for docker runs

---

include/torch-mlir/Dialect/TorchConversion/Transforms/CMakeLists.txt
include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h
include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.td
lib/Dialect/TorchConversion/Transforms/CMakeLists.txt
lib/Dialect/TorchConversion/Transforms/Passes.cpp
lib/Dialect/TorchConversion/Transforms/VerifyMhloBackendContract.cpp
utils/bazel/torch-mlir-overlay/BUILD.bazel

Related to https://github.com/llvm/torch-mlir/issues/1267

[MHLO] add VerifyMhloBackendContract

---

build_tools/python_deploy/build_linux_packages.sh

We were defaulting to building Release and running tests. Tests are spawned separately in parallel.

Fix release builds to only build release

---

docs/architecture.md

Recording was linking to specific time towards end of recording, changed to remove specific time.

Avoid linking to specific time

---

.github/workflows/buildAndTest.yml

Now that #1234 has landed and anyone can run CI / Release builds locally move GHA to use the same flow.

Move CIs to use docker builds

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToLinalg/DataMovement.cpp
python/torch_mlir_e2e_test/test_suite/reshape_like.py

(Currently Unfinished, will also be squashing commits later once the commit is in better shape)
Currently working on making a fix so that a view with dimensions [3,2] can be displayed as [2,3].

Implement Expand/Collapse Functionality for Aten.View

---

lib/Conversion/TorchToLinalg/Linear.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir/__init__.py

This commit adds decomposition of `aten.linear` op.
TODO: remove existing implementation and add a simple test case. Also handle the (3D,2D) case of matmul.
Signed-Off-by: Gaurav Shukla

[TORCH] Add decomposition of `aten.linear` op

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

The `-DTORCH_MLIR_ENABLE_MHLO` flag was recently introduced for `TorchMLIRTorchConversionPassesIncGen` [here](https://sourcegraph.com/github.com/llvm/torch-mlir@99093d0623c3d3e6fb961ad0c8fda5ee9fc264fe/-/blob/utils/bazel/torch-mlir-overlay/BUILD.bazel?L319) in [this recent PR](https://github.com/llvm/torch-mlir/pull/1321) (was already present for `TorchMLIRConversionPassesIncGen` [here](https://sourcegraph.com/github.com/llvm/torch-mlir@99093d0623c3d3e6fb961ad0c8fda5ee9fc264fe/-/blob/utils/bazel/torch-mlir-overlay/BUILD.bazel?L288)). Before this PR, the MHLO sources in TorchConversion were not being built. This indicates a build issue that pre-existed but didn’t trigger until this path was enabled recently. Disabling to get the build green for now, until we can diagnose and fix the build …

[Bazel] Remove MHLO enable flag

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/elementwise.py

This commit adds lowering of `aten.pow.Tensor_Tensor` op.

[MLIR][TORCH] Add E2E support for `aten.pow.Tensor_Tensor` op

---

include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h
lib/Dialect/TorchConversion/Transforms/Passes.cpp

Follow up on the comments, add enableI32Index and enableStaticShape options in the pipeline:
> We already have this registered there:
> 
> ```
> #ifdef TORCH_MLIR_ENABLE_MHLO
>   mlir::PassPipelineRegistration<Torch::TorchLoweringPipelineOptions>(
>       "torch-backend-to-mhlo-backend-pipeline",
>       "Pipeline lowering torch backend contract to MHLO backend "
>       "contract.",
>       TorchConversion::createTorchBackendToMhloBackendPipeline);
> #endif
> ```
> 
> You can replace `Torch::TorchLoweringPipelineOptions` with a new struct with options parallel to `def ConvertTorchToMhlo : Pass<"convert-torch-to-mhlo", "func::FuncOp"> {` (this is redundant but required in MLIR now).
https://github.com/llvm/torch-mlir/pull/1315#issuecomment-1233552315

[MHLO] add new options to pipeline

---

e2e_testing/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/type_conversion.py
test/Dialect/Torch/canonicalize.mlir

Folds away aten::type_as when input and output type are the same.

Fold away type_as

---

include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h
lib/Dialect/TorchConversion/Transforms/Passes.cpp

TorchLoweringPipelineOptions only applies to the frontend lowering pipeline.

Remove TorchLoweringPipelineOptions from TorchConversion pipelines

---

setup.py

Previously we `sudo rm -f` the non-universal zstd installed in the GHA. The CI has this fix but it doesn't take effect in the Release builds without this change.

Disable libzstd detection to fix M1 builds

---

include/torch-mlir/Dialect/Torch/IR/TorchBase.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
include/torch-mlir/Dialect/Torch/IR/TorchTraits.h
lib/Dialect/Torch/IR/TorchOps.cpp

This PR adds an `AllowedInModuleInitializer` trait to keep track of ops that are permitted in the module initializer. We have a handful of such ops that are produced by the IValue importer, and so this change avoids maintaining a list of ops in `TorchOps.cpp` that could lead to spurious merge conflicts, and help us integrate torch-mlir in our downstream compiler better. Please let me know if you'd prefer a better name for the trait itself. Feedback is welcome!

Add a `AllowedInModuleInitializer` trait to denote ops that are permitted in the module initializer

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Dialect/Torch/IR/TorchDialect.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/ShapeLibrary.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR is to solve issue #1305 .
A example IR is like:
```
%none = torch.constant.none
%int0 = torch.constant.int 0
%int5 = torch.constant.int 5
%0 = torch.aten.arange.start %int0, %int5, %none, %none, %none, %none : !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor
```
After shape simplification pipeline, %0 is unexpectedly deduced to have a dynamic shape.
```
...
%0 = torch.aten.arange.start %int0, %int5, %none, %none, %none, %none : !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[?],unk>
```
The solution in this PR can be briefly summarized as the following：
1. register aten.sub and aten.ceil.Scalar op, which is need in shape function of aten arange-like ops
2. design folder for aten.sub and …

Strength the shape inference for aten.arange-like op

---

build_tools/autogen_ltc_backend.py
build_tools/autogen_ltc_backend.yaml
build_tools/python_deploy/build_linux_packages.sh
python/torch_mlir/csrc/base_lazy_backend/mlir_native_functions.cpp
setup.py

Fix LTC issues caused by changes in upstream PyTorch
- A new `symint` key was added to the native functions yaml
- The `lift_fresh_copy` op was blacklisted in LTC as it is not yet supported
This PR depends on this upstream PR getting in first: https://github.com/pytorch/pytorch/pull/85029
Issue: https://github.com/llvm/torch-mlir/issues/1364

Fix symint ops and blacklist `lift_fresh_copy`

---

e2e_testing/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

This PR adds e2e support for `AtenArangeStartStepOp` in torch-to-mhlo conversion. Besides, this PR also adds a folder for `AtenDivOp`, which is missed in PR #1367 .

Add torch-to-mhlo e2e support for AtenArangeStartStepOp

---

CMakeLists.txt

Needed for external builds when we have an out-of-tree build (e.g. onnx-mlir)

Add build flag for out-of-tree builds

---

build_tools/python_deploy/build_linux_packages.sh
e2e_testing/main.py
python/torch_mlir_e2e_test/test_suite/pooling.py

This adds a very long and obnoxious option to disable crashing tests. The right fix here is to use the right multiprocessing techniques to ensure that segfaulting tests can be XFAILed like normal tests, but we currently don't know how to implement "catch a segfault" in Python (patches or even just ideas welcome).
Motivated by #1361, where we ended up removing two tests from *all* backends due to a failure in one backend, which is undesirable.

Add a way to turn off crashing tests

---

.github/workflows/gh-pages-releases.yml
build_tools/scrape_releases.py

This runs a github actions cron job every hour to scrape the releases API and generate a static releases page inside the `github-pages` branch.  This page is available at https://llvm.github.io/torch-mlir/ and can be used as a package index for pip.
See https://github.com/llvm/torch-mlir/issues/1374 for background.

Create github action for creating pip-compatible releases page

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
test/Dialect/Torch/canonicalize.mlir

`aten.slice.t` op lacks a canonicalizer. It will cause the shape-simplification pipeline fails to infer %3 to have a static shape in the following IR:
```
%0 = torch.tensor.literal(dense_resource<__elided__> : tensor<4x300xf32>) : !torch.tensor<[4,300],f32>
%1 = torch.prim.ListConstruct %int16, %int75, %int2, %int2 : (!torch.int, !torch.int, !torch.int, !torch.int) -> !torch.list<int>
%2 = torch.aten.slice.t %1, %int0, %int-2, %int1 : !torch.list<int>, !torch.int, !torch.int, !torch.int -> !torch.list<int>
%3 = torch.aten.view %0, %2 : !torch.tensor<[4,300],f32>, !torch.list<int> -> !torch.tensor<[?,?],f32>
```
This PR adds a canonicalizer for `aten.slice.t` op. The basic idea is replacing `aten.slice.t` op with a new `prim.ListConstruct` op, when the former's operand comes from …

[MLIR] Add canonicalizer for aten.slice.t op

---

docs/development.md

I was helping an engineer the other day who was attempting to use the Docker flow for interactive development and ran into countless issues. Add a note that it is not recommended for interactive development, and also move the Docker section down to avoid positioning it as the "default" that people should be using.

Make docker instructions a bit more scoped

---

e2e_testing/xfail_sets.py
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Utils/Utils.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

This commit adds support for TorchToTosa lowering of `aten.broadcast_to` op for cases:
1.) When the rank of input and output tensor is equal.
2.) When the rank of input tensor is zero.

[tosa] Add support for some cases of aten.broadcast_to op

---

build_tools/python_deploy/build_linux_packages.sh

`git diff` does not work by default on untracked files. Since the function `_check_file_not_changed_by` stores the new generated file in an untracked file, `git diff` was not catching any modifications in the new generated file. This commit adds the flag `--no-index` to make `git diff` work with untracked files.

Add `--no-index` to CI's git-diff check on generated files

---

.github/workflows/buildRelease.yml
.github/workflows/gh-pages-releases.yml

Remove the periodic update since there are no changes after the nightly and it just clutters the Github Actions.

Update releases pages after release builds

---

utils/bazel/docker/Dockerfile

Updates the bazel Dockerfile to match changes from https://github.com/llvm/torch-mlir/pull/1419. This should get the bazel build back to green.
Also triggered bazel build on GHA here: https://github.com/sjain-stanford/torch-mlir/actions/runs/3154741943. Let's wait for it to complete before landing this.

[Bazel] Make pytorch-requirements.txt available within the docker container

---

python/test/compile_api/tracing.py
python/torch_mlir/__init__.py

The underlying error message was misleading.  See https://github.com/llvm/torch-mlir/issues/1425

Reject dictionary inputs when tracing.

---

build_tools/autogen_ltc_backend.yaml
test/python/importer/jit_ir/node_import/prim.py

Removed `where` op from ltc blacklist. `torch.where` codegen successfully compiles and converts to torch-mlir.
@antoniojkim @ke1337

LTC aten.where support

---

lib/Conversion/TorchToLinalg/Reduction.cpp

This commit updates the linalg conversion of `AtenMaxDimOp` to use `arith.maxf` instead of `arith.select` to calculate the maximum. This allows better vectorization further downstream, since the operation can be converted to a simple max reduction when the `indices` result
is not used. See: https://github.com/iree-org/iree/issues/10666.

[LINALG] Make `AtenMaxDimOp` use `arith.maxf` to calculate maximum

---

.github/workflows/buildRelease.yml

Mac was finishing first, causing linux releases to be lagged a day behind.
Related discussion in https://github.com/llvm/torch-mlir/pull/1432

Publish releases page after both mac and linux builds.

---

python/test/compile_api/backend_legal_ops.py
python/torch_mlir/__init__.py

Allow customizing `backend_legal_ops` for "torch" output type, since we don't know which backend will be used (it might be a custom backend). We don't allow customizing the `backend_legal_ops` for the other output types (Linalg, TOSA, MHLO) since those backends control their set of legal ops directly.
Fixes #1418

torch_mlir.compile: allow custom backend_legal_ops set

---

build_tools/python_deploy/build_linux_packages.sh

This is the version Colab uses.

Publish Python 3.7 packages.

---

lib/Conversion/TorchToLinalg/Linear.cpp

This commit removes the `weight` tensor from the inputs of one of the `linalg.generic` ops generated by the `aten.convolution` linalg lowering, since the indexed values are not actually used by the body of the `linalg.generic`. Moreover, in general the `weight` tensor does not have the same shape as the output tensor of the `linalg.generic`, so both tensors being indexed by the same indexing maps is wrong.

Remove unused input tensor from linalg.generic in aten.convolution

---

docs/code_owners.md

As discussed in #1506, this should help to distribute the review load and ensure timely, high quality reviews.
Closes #1506

[docs] Initial code_owners.md

---

setup.py

This allows installing corresponding PyTorch CUDA / ROCM versions and using torch-mlir.

Relax the need for only CPU versions of PyTorch

---

.github/actions/setup-build/action.yml
.github/workflows/buildAndTest.yml
.github/workflows/buildRelease.yml
build_tools/python_deploy/build_windows.ps1
build_tools/python_deploy/build_windows_ci.ps1

Add a powershell script to build windows .whl packages Disable LTC as it doesn't build on Windows.
This works on my local Windows 11 setup. Will try to invoke from GHA next.

Add Windows CI and Release Builder

---

utils/bazel/torch-mlir-overlay/BUILD.bazel

- This should fix current broken bazel build (a commit was missing)
Run:
https://github.com/asaadaldien/torch-mlir/actions/runs/3330321809

[Bazel] Fix use gloab instead of explicit files

---

build_tools/python_deploy/build_linux_packages.sh

Since we added 3.7 for Collab drop 3.9 to keep build times under check.

Drop 3.9 binaries to keep under 6hrs build

---

lib/Conversion/TorchToLinalg/Pooling.cpp

The parameter "supportFPInputOnly" of function createPoolingOp() is supposed to be "supportNonFPInput", which was added to distinguish between "MaxPool2d" and "AvgPool2d" op in #718

[MLIR][TORCH] Fix wrong parameter name "supportFPInputOnly"

---

.github/workflows/RollPyTorch.yml
.github/workflows/buildAndTest.yml

If PyTorch build caches are created on a branch other than the main
branch, then GitHub does not share those caches with the main branch,
making every CI run that runs for each PR slow.  This patch resolves the
problem by letting only the main branch create and use PyTorch build
caches.

ci: restrict PyTorch cache to just the main branch

---

lib/Conversion/TorchToLinalg/Utils.cpp
test/Conversion/TorchToMhlo/basic.mlir
test/Conversion/TorchToMhlo/elementwise.mlir
test/Conversion/TorchToMhlo/pooling.mlir
test/Conversion/TorchToMhlo/reduction.mlir
test/Conversion/TorchToMhlo/view_like.mlir

This commit makes the following changes needed to update bump LLVM:
-  replace usages of `tensor::createPadScalarOp`; see https://reviews.llvm.org/D136493

build: update llvm tag to 74fb770d

---

.github/workflows/buildRelease.yml

We don't need to pass in optional tag information.

remove spurious ref in publish pages

---

lib/Dialect/Torch/Utils/CMakeLists.txt

lib/Dialect/Torch/Utils/Utils.cpp includes TorchOps.h, which, by way of
included header files, refers to both TorchOps.h.inc as well as
TorchTypes.h.inc.  However, the build rules do not specify the
dependency of the `TorchMLIRTorchUtils` target on the TableGen generated
header files, causing spurious build errors.
This patch fixes the problem by adding `MLIRTorchOpsIncGen` and
`MLIRTorchTypesIncGen` to the list of dependencies of
`TorchMLIRTorchUtils`.

mlir: add missing dependency on TableGen targets

---

build_tools/python_deploy/build_linux_packages.sh

This patch updates the build_linux_packages.sh script so that when
PyTorch needs to be built from source, it is built _before_ building
LLVM and before building Torch-MLIR.  The rationale behind this change
is that previously, when the PyTorch build was triggered through the
Torch-MLIR build, the PyTorch compilation added more entries to the
ccache artifacts.  However, since we cache the PyTorch _binary_ (i.e.
the WHL file), there is no need to add the PyTorch compilation to the
ccache artifacts.  By removing the PyTorch compilation files, we keep
the ccache artifact size small, thus reducing the number of evictions
when we exceed GitHub's allowed limit.

ci: build PyTorch before building Torch-MLIR

---

build_tools/python_deploy/build_linux_packages.sh

Reverts llvm/torch-mlir#1542 since it's causing post-merge CI failures.
See https://github.com/llvm/torch-mlir/actions/runs/3373219101/jobs/5597790989 for an example.

Revert "ci: build PyTorch before building Torch-MLIR"

---

.github/workflows/RollPyTorch.yml
.github/workflows/buildAndTest.yml

Until recently, we had to either risk feature branches creating PyTorch
build caches (which were unusable by the main branch or other parallel
feature branches because of GitHub's rules around sharing caches among
branches) or we had to limit the PyTorch build caches to only the main
branch, causing CI runs on feature branches to be terribly slow because
they had to rebuild PyTorch each time.
This patch enables the best of both worlds, by using a fork
(github.com/ashay/cache) of the GitHub's cache action, where the fork
adds an option (called `save`) which, when set, uploads a new cache
entry.  We thus set this `save` flag only when we're building PyTorch
from source in Torch-MLIR's main branch, whereas all other builds set
this `save` flag to `false`.
The ability to conditionally update …

ci: introduce read-only and read-write PyTorch build caches

---

.github/actions/setup-build/action.yml
.github/workflows/bazelBuildAndTest.yml
.github/workflows/buildAndTest.yml
.github/workflows/buildRelease.yml
.github/workflows/gh-pages-releases.yml
.github/workflows/releaseSnapshotPackage.yml

This PR contains four commits (see commit messages for details):
- ci: update versions of external actions
- ci: replace deprecated action with bash commands
- ci: use smaller ccache artifacts to reduce evictions
- ci: use consistent platform identifiers
@dellis23 I added you as a reviewer because I changed one of your workflows in the last commit so that the workflow runs on ubuntu-22.04 for consistency with the rest of the workflows.  Let me know if you'd like me to revert the change.  Thanks!

CI script improvements

---

build_tools/update_shape_lib.sh
build_tools/update_torch_ods.sh

Before this patch, the update_shape_lib.sh and update_torch_ods.sh
scripts only worked on in-tree builds, which implied that the
RollPyTorch action was forced to run the longer-running in-tree build.
As a result of this patch, we should be able to run through the basic
checks in the RollPyTorch action faster, while running the full suite of
tests off the critical path.
The key change in this patch is that the update scripts now look for the
directory that is most recently modified between in-tree or out-of-tree
build directories.  The change also correctly handles the case when only
one of the two directories exists.

build: enable update scripts to work with out-of-tree builds

---

python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp

Unless requested otherwise, PyTorch no longer installs most of the
header files under the caffe2 directory (see
https://github.com/pytorch/pytorch/pull/87986).  This breaks our
importer code since we need to use the `MakeGuard()` function to execute
statements in the event of exceptions.
To fix this issue, this patch implements a rudimentary version of
PyTorch's ScopeGuard, where once the class variable goes out of scope,
it executes a predefined method.

importer: fix usage after PyTorch update

---

requirements.txt

Going from ninja v1.10.2 to v1.11.1, there is a change that breaks
the CI builds with the following error:
```
CMake Error at CMakeLists.txt:47 (project):
Running
'/main_checkout/torch-mlir/docker_venv/bin/ninja' '--version'
failed with:
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
```
Ostensibly, the reason for the error about the ASM compiler is because
llvm-project/llvm/CMakeLists.txt includes ASM among the list of
languages used in the LLVM project. Adding `-DCMAKE_ASM_COMPILER=clang`                            
does not resolve the error.
Until we figure out why the new version of ninja causes the build
failures, this patch pins the ninja to the one that worked.

build: pin ninja pip version temporarily to resolve build failure

---

build_tools/python_deploy/build_windows.ps1

This file was removed as part of the PR that added build caching for Windows.  This PR gets the Release build working again.  See https://github.com/llvm/torch-mlir/actions/runs/3404807910 for an example.

ci: re-add powershell script for windows release builds

---

requirements.txt

Now that the ninja pip package issue has been resolved, this patch
removes the pinned version from requirements.txt so that we can go back
to using the most recent version of ninja.

build: un-pin the ninja pip package version

---

python/test/compile_api/multiple_methods.py
python/test/compile_api/tracing.py
python/torch_mlir/__init__.py

For AoT deployments models often have multiple exported methods. This patch enables something like this:
```
class TwoMethodsModule(torch.nn.Module):
def sin(self, x):
return torch.ops.aten.sin(x)
def cos(self, x):
return torch.ops.aten.cos(x)
example_args = torch_mlir.ExampleArgs()
example_args.add_method("sin", torch.ones(2, 3))
example_args.add_method("cos", torch.ones(2, 4))
print(torch_mlir.compile(TwoMethodsModule(), example_args))
```
In the
[long-term](https://github.com/llvm/torch-mlir/blob/main/docs/long_term_roadmap.md#tools-for-advanced-aot-deployments) we will need to reconcile this with our story for stateful models and the backend contract being purely functional. For now, this provides some basic infra that seems harmless. Arguably, we could tighten up the backend contract …

[torch_mlir.compile] Add support for multiple exported methods

---

utils/bazel/.bazelrc
utils/bazel/docker/Dockerfile
utils/bazel/docker/run_bazel_build.sh

* Update Ubuntu and clang in the docker container
* Specifically build just `@torch-mlir//:torch-mlir-opt`
Triggered GHA run:
https://github.com/sjain-stanford/torch-mlir/actions/runs/3317006870/jobs/5479411204

[Bazel] Update to Ubuntu-22.04 and clang-16 for Bazel build docker

---

build_tools/python_deploy/build_linux_packages.sh

We want each build to be reproducible regardless of prior builds and
prior package installations, but pip, by default, uses cached packages
from previous invocations of `pip install`.  As a result, the incorrect
dependencies downloaded in the RollPyTorch workflow in the main
repository cannot be reproduced in private forks of the repository.  To
resolve this problem, this patch adds a `--no-cache-dir` flag to pip, so
that it fetches and inspects each requested package independent or prior
installations.

ci: make pip skip cached packages while installing dependencies

---

.github/workflows/RollPyTorch.yml
pytorch-requirements.txt
requirements.txt

We currently pin the `torch` package to the latest nightly version, but
since `torchvision` depends on the `torch` package, the pip resolver
then has to run through an extensive list of `torchvision` packages that
can be installed with the pinned `torch` package.  This search fails in
the RollPyTorch action, causing pip to settle on an old version of
`torchvision` that does not work with our tests.  In reality, we are
only interested in a specific version of the `torchvision` package.
To make the dependency explicit and to prevent test failures because of
incorrect package installations, this patch makes two key changes:
1. `torchvision` is now pinned to the latest nightly release in
pytorch-requirements.txt along with the version of `torch` that is
necessary to install the requested …

build: pin torchvision to latest nightly

---

docs/development.md
utils/bazel/docker/Dockerfile
utils/bazel/docker/run_bazel_build.sh

Remove `run_bazel_build.sh`, simplify docker's entrypoint to start container at `utils/bazel` directory, update docs.

Simplify Bazel build workflow

---

.github/workflows/bazelBuildAndTest.yml

I accidentally broke bazel CI by forgetting to update the GHA workflow in my [previous PR](https://github.com/llvm/torch-mlir/pull/1587). This should get it back to green, my apologies.
Qualifying CI run: https://github.com/sjain-stanford/torch-mlir/actions/runs/3472523982

Fix bazel CI

---

docs/development.md
utils/bazel/WORKSPACE.bazel
utils/bazel/torch-mlir-overlay/BUILD.bazel

Formats bazel BUILD and .bzl files with a standard convention. 
Invoke using
```
bazel run @torch-mlir//:buildifier
```

Add Bazel buildifier to torch-mlir

---

.github/workflows/bazelBuildAndTest.yml

Some time ago, bazel builds in CI were being sped up fine with caching. However, over time the cache got stale because `actions/cache@v3` apparently doesn't update caches when it "hits" unless it is configured to do so specifically. This requires using a uniqued per-commit `key` (to force it to update cache after each successful run) and a relaxed `restore-keys` which is not unique per-commit so newer commits can restore from the nearest hit.
Test GHA run 1 (no cache hit): [1h 1m 52s](https://github.com/sjain-stanford/torch-mlir/actions/runs/3474770334/usage)
Test GHA run 2 (cache hit, same commit): [5m 14s](https://github.com/sjain-stanford/torch-mlir/actions/runs/3475132135/usage)
Test GHA run 3 (cache hit, different commit): [6m …

Fix cache bug with Bazel builds in CI

---

.github/workflows/bazelBuildAndTest.yml
docs/development.md

Bazel LIT test support was added in https://github.com/llvm/torch-mlir/pull/1585. This PR enables the tests in CI.
```
INFO: Build completed successfully, 254 total actions
@torch-mlir//test/Conversion:TorchToArith/basic.mlir.test                PASSED in 0.3s
@torch-mlir//test/Conversion:TorchToLinalg/basic.mlir.test               PASSED in 0.5s
@torch-mlir//test/Conversion:TorchToLinalg/elementwise.mlir.test         PASSED in 0.3s
@torch-mlir//test/Conversion:TorchToLinalg/flatten.mlir.test             PASSED in 0.3s
@torch-mlir//test/Conversion:TorchToLinalg/pooling.mlir.test             PASSED in 0.3s
@torch-mlir//test/Conversion:TorchToLinalg/unsqueeze.mlir.test           PASSED in 0.2s
@torch-mlir//test/Conversion:TorchToLinalg/view.mlir.test                PASSED in 0.3s …
```

Enable bazel LIT tests in CI

---

include/torch-mlir/Dialect/Torch/IR/TorchOps.h
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToLinalg/Pooling.cpp
lib/Conversion/TorchToLinalg/Reduction.cpp
lib/Conversion/TorchToLinalg/TensorConstructors.cpp
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Conversion/TorchToMhlo/Linear.cpp
lib/Conversion/TorchToMhlo/Pooling.cpp
lib/Conversion/TorchToMhlo/Reduction.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp

This commit renames the patterns used to match on lists of constant values to `m_TorchListOfConstant{valueType}s`. This is needed to avoid ambiguity for when `valueType` has `Optional` in it. In particular, it makes it clear whether the values in the list are optional or the list itself is optional.

`m_TorchConstant{Int/Bool}List` -> `m_TorchListOfConstant{Int/Bool}s`

---

CMakeLists.txt
externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/ScalarLoopOpInterface.td
externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
lib/Conversion/Passes.cpp
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToLinalg/Pooling.cpp
lib/Conversion/TorchToLinalg/Random.cpp
lib/Conversion/TorchToLinalg/Reduction.cpp
lib/Conversion/TorchToLinalg/TensorConstructors.cpp
lib/Conversion/TorchToLinalg/Uncategorized.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Conversion/TorchToMhlo/Gather.cpp
lib/Conversion/TorchToMhlo/Linear.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/Pooling.cpp
lib/Conversion/TorchToMhlo/Reduction.cpp
lib/Conversion/TorchToMhlo/TorchToMhlo.cpp
lib/Conversion/TorchToMhlo/ViewLike.cpp
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Dialect/TorchConversion/Transforms/Passes.cpp
lib/Dialect/TorchConversion/Transforms/VerifyMhloBackendContract.cpp
lib/RefBackend/RefBackend.cpp

1. Replace `string` iterator types by `IteratorType` enum. (https://github.com/llvm/llvm-project/commit/e6598b053dc71845423132ac0803b1ecd0b71d45)
2. Update `includes` wrt new directory layout of MLIR HLO codebase. (https://github.com/tensorflow/mlir-hlo/commit/9fd8d251a811f1bae0fde20744aef3e1817a11e8)
3. Update tags:
llvm: e864ac694540342d5e59f59c525c5082f2594fb8 
MHLO: eab364ba2a66bd0613efb94f8a738c1c97aaee92

llvm: update tag to e864ac6945

---

docs/adding_an_e2e_test.md
docs/architecture.md
docs/development.md

This PR fixes typos in `.md` files.

Fix typos in md files

---

python/torch_mlir/eager_mode/torch_mlir_tensor.py

Fix https://github.com/llvm/torch-mlir/issues/1618 by stripping `requires_grad` from results of view ops.
The error that pytorch produces implies the solution:
```
RuntimeError: Attempted to make a tensor into a differentiable view, 
but the tensor already had **autograd metadata** associated with it.  ...
```
cc @powderluv @pashu123

[MLIR][TORCH] Fix vision models

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
python/torch_mlir_e2e_test/test_suite/stats.py
test/Dialect/Torch/decompose-complex-ops.mlir

This commit fixes the aten.mean and aten.mean.dim op decomposition for supporting large-sized inputs.
This commit also fixes the formatting for the file stats.py

[MLIR][TORCH] Fix mean and mean.dim op for large-sized inputs

---

.github/workflows/RollPyTorch.yml

Until recently, the metadata file in the torchvision package included
the nightly version of the torch package, but since that is no longer
the case, our RollPyTorch workflow is broken.
As a workaround, this patch uses the `pip download` command's ability to
fetch the dependent torch package for the specified version of
torchvision, before peeking into the WHL file for the torch package to
determine the release version and the commit hash.

build: fetch PyTorch version using downloaded WHL file

---

e2e_testing/xfail_sets.py
python/torch_mlir/eager_mode/torch_mlir_tensor.py

[Re]fix https://github.com/llvm/torch-mlir/issues/1618 by stripping `requires_grad` from results of view ops (before the exception is thrown...)

[MLIR][TORCH] Refix differentiable view

---

build_tools/python_deploy/build_linux_packages.sh
e2e_testing/main.py
e2e_testing/xfail_sets.py
python/CMakeLists.txt
python/torch_mlir/dynamo.py
python/torch_mlir_e2e_test/configs/__init__.py
python/torch_mlir_e2e_test/configs/torchdynamo.py

This adds a basic e2e Config for TorchDynamo using Linalg-on-Tensors/RefBackend.
But TorchDynamo is pretty orthogonal to
various other pieces, so it should compose nicely with variations like:
- Switching out all the backends (Linalg-on-Tensors, TOSA, MHLO)
- PyTorch functionalization and decompositions
- Taking the example inputs and compiling with all dynamic or all static shapes without duplicating tests.
This adds it to the CI, but there are still a lot of XFAIL's.
This also adds a helper `from torch_mlir.dynamo import make_simple_dynamo_backend` which simplifies some of the steps for making a Torch-MLIR-based TorchDynamo backend. We include "simple" in the name because we are going to be exploring various things next from the long-term roadmap.
The next steps are:
- Burn down all the …

[torchdynamo] Initial TorchDynamo support

---

python/torch_mlir_e2e_test/eager_backends/refbackend.py

While running the example I am getting this error -
File "/home/mcw/shivam/mlir/torch-mlir/examples/eager_mode.py", line 23, in <module>
a = TorchMLIRTensor(torch_a)
File "/home/mcw/shivam/mlir/torch-mlir/mlir_venv/lib/python3.9/site-packages/torch_mlir/eager_mode/torch_mlir_tensor.py", line 102, in __new__
r.elem = backend.transfer_from_torch_to_device(elem)
File "/home/mcw/shivam/mlir/torch-mlir/mlir_venv/lib/python3.9/site-packages/torch_mlir_e2e_test/eager_backends/refbackend.py", line 91, in transfer_from_torch_to_device
return tensor.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
This PR is simple fix of that.

Fix RuntimeError while running examples/eager_mode.py

---

python/torch_mlir_e2e_test/framework.py

For reasons that I haven't yet fully tracked down, the TorchDynamo TestConfig seems to result in tensors that cannot be pickled. They seem to be holding some sort of weak handles to a `torch.fx.graph.Graph`.
Here is the object structure that leads to the unpickleable object:
```
(<function _rebuild_tensor_v2 at 0x7f56346d56c0>, <class 'torch.Tensor'>, ( 1.0...
{<object object at 0x7f557529e6b0>: <WeakKeyDictionary at 0x7f556a3efbb0>}
{'data': {<weakref at 0x7f5615372ed0; to 'PythonKeyTracer' at 0x7f556a3ee5c0>: _...
<class 'torch.fx.graph.Graph'>
<class 'torch._ops.OpOverloadPacket'>
TypeError("cannot pickle 'torch._C.FunctionSchema' object")
```
Upstream bug filed: https://github.com/pytorch/pytorch/issues/89626

Fix multiprocessing for `--config=torchdynamo`

---

python/torch_mlir_e2e_test/eager_backends/refbackend.py

`np.bool is bool` and will never be returned as a dtype of an `np.ndarray`, so we don't need to handle it here.
```
>>> a = np.ndarray([1], dtype=bool)
>>> a.dtype.type is np.bool_
True
```
More info here:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Remove deprecated np.bool

---

e2e_testing/xfail_sets.py
python/torch_mlir_e2e_test/test_suite/rng.py

There are a few e2e tests that take several very large tensors as input, which leads to the e2e test suite leaking too much memory. Running things locally resulted in a total memory usage of 12.5 GB when running the suite sequentially on the refbackend.
Many of the tests that take large tensors don't actually need such large tensors to pass, and some that take several large tensors as input are just doing the same thing multiple times. This commit reduces the size of some of the tensors and removes repetitive parts of tests to reduce the memory usage to a total of 3 GB.

Reduce memory usage of e2e tests by reducing input sizes

---

lib/RefBackend/RefBackend.cpp
python/torch_mlir_e2e_test/test_suite/basic.py
python/torch_mlir_e2e_test/test_suite/rng.py
test/RefBackend/insert-rng-globals.mlir

The current implementation sets the `nextSeed` value to `temp & 127`, which is wrong. The last step of the LCG algorithm for the multiplier and increment chosen should be `temp % 2^{64} = temp & (1 << 63)`. However, because we are dealing with i64 values, the modulus operation happens automatically, so it is not needed.
See Donald Knuth's values for LCG here:
https://en.wikipedia.org/wiki/Linear_congruential_generator

Fix modulus calculation in LCG algorithm of refbackend

---

lib/Dialect/Torch/Transforms/RefineTypes.cpp

-- This commit adds Float16Type dtype knowledge support for trivial ops.
Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>

[RefineTypes] Add Float16Type dtype knowledge support for trivial ops

---

include/torch-mlir/Conversion/Utils/Utils.h
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToLinalg/IndirectDataMovement.cpp
lib/Conversion/TorchToLinalg/Linear.cpp
lib/Conversion/TorchToLinalg/Reduction.cpp
lib/Conversion/TorchToLinalg/Utils.cpp
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/InlineGlobalSlots.cpp
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
test/Conversion/TorchToTosa/basic.mlir
test/Dialect/Torch/decompose-complex-ops.mlir

- Update call to `hasNoEffect` utility
- Make fix for the dynamic dims, since `kDynamicSize` value changed to `std::numeric_limits<int64_t>::min()` from `-1` in llvm
- `makeShapeLLVMCompatible` and `makeShapeTorchCompatible` utilities convert shapes in order to remain consistent with the Torch and MLIR semantics.
- Update tags llvm: 147fe9de29dc13c14835127b35280c4d95c8e8ba mhlo: 1944b5fa6062ec4c065d726c9c5d64f1487ee8c5

build: update llvm tag to 147fe9de

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToLinalg/Random.cpp
python/torch_mlir_e2e_test/test_suite/rng.py

This commit replaces the LCG algorithm that was being used by the `TorchToLinalg` lowering of `AtenUniformOp` to generate random numbers with the `squares64` algorithm, for the LCG algorithm was producing tensors that were highly correlated with one another.
Squares64 algorithm: https://arxiv.org/abs/2004.06278
Closes https://github.com/llvm/torch-mlir/issues/1608

Replace LCG algorithm with squares64 algorithm in AtenUniformOp

---

externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
include/torch-mlir/Conversion/Utils/Utils.h
lib/Conversion/TorchToMhlo/Linear.cpp
lib/Conversion/TorchToMhlo/Pooling.cpp
lib/Conversion/TorchToMhlo/ViewLike.cpp
lib/Conversion/Utils/Utils.cpp

- Change ShapedType::kDynamicSize -> ShapedType::kDynamic
- llvm::NoneType has been deprecated, change convertScalarToDtype to use llvm::None
New submodule hashes:
2c1fa734598c9470139720565fbf624a5156ec03 externals/llvm-project (llvmorg-16-init-12026-g2c1fa734598c)
dabc58a95b8bcd1140ffb0062730b81745d41724 externals/mlir-hlo (remotes/origin/greencommit/2022-11-28-2c1fa734)

Update LLVM Tag to 2c1fa734

---

python/test/debug/lockstep_basic.py
python/torch_mlir_e2e_test/debug/lockstep.py

Thanks to TorchDynamo's great layering and design, this is only about 100 lines of code for a basic lockstep debugger.
This should allow us to deprecate eager_mode, since AFAIK the only interesting use case that it was really supporting is for downstream users to write lockstep debuggers.
NOTE: The exact reporting and interface here is subject to change. Please try it out and provide feedback (or patches :) ).
- make_fx should not drop source locations: https://github.com/pytorch/pytorch/issues/90276
- Report tensors better (huge tensors should be summarized)
- Maybe don't abort, but just warn?
- Allow customizing atol/rtol.
- How best to print the failing node? And include surrounding graph context?

[torchdynamo] Add "lockstep" numerical accuracy debugger.

---

examples/torchdynamo_resnet18.py
python/torch_mlir_e2e_test/configs/torchdynamo.py

This is a minor variation on our other resnet18 examples swapping in TorchDynamo.
We replicate the refbackend_torchdynamo_backend out of the e2e test config to avoid making that appear like a public API.
Also, some minor cleanups to TorchDynamoTestConfig.

[torchdynamo] Add ResNet18 example with TorchDynamo

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
test/Dialect/Torch/decompose-complex-ops.mlir
test/Dialect/Torch/lower-to-backend-contract-error.mlir

The current implementation of `DecomposeComplexOps` fails if an op expected to be decomposed does not get decomposed in the first iteration of the `createTorchSimplificationPipeline` in `LowerToBackendContractPass`. However, some graphs require multiple iterations of `createTorchSimplificationPipeline` to fully propagate all statically knowable information, such as dtypes and shapes, to the entire graph, sometimes resulting in the need to run `DecomposeComplexOps` more than once.
This commit changes `DecomposeComplexOps` to use a greedy algorithm for pattern application and moves the legalization check of ops to the `LowerToBackendContractPass` to allow for the `DecomposeComplexOps` to run more than once.

Allow running DecomposeComplexOps more than once

---

include/torch-mlir/Conversion/Utils/Utils.h
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
lib/Dialect/Torch/Utils/Utils.cpp
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
utils/bazel/torch-mlir-overlay/BUILD.bazel

A circular dependency was introduced in https://github.com/llvm/torch-mlir/commit/e7edcc62fde300d026674af64fbb24f3f76caf2a. 
Specifically, the `makeShapeLLVMCompatible` and `makeShapeTorchCompatible` utilities were being called from `lib/Dialect/Torch/IR/TorchTypes.cpp` and `lib/Dialect/Torch/IR/TorchOps.cpp` defined under the `:TorchMLIRTorchDialect` bazel target, leading it to take a dependency on `:TorchMLIRConversionUtils` which already depends on `:TorchMLIRTorchDialect`, hence creating a circular dependency.
This commit resolves the same by moving said utilities from `lib/Conversion/Utils/Utils.cpp` to `lib/Dialect/Torch/Utils/Utils.cpp`. Please LMK if there's a better way to fix this and I will update the code.
This commit also adds the required targets to support building the new …

[Bazel] Resolve circular dependency and add targets for conversion to MLProgram dialect

---

e2e_testing/main.py

This is the more predominant style in the codebase. I'm sure there are more in other parts of the codebase but it's hard to search/replace.

[cleanup] Use `"` instead of `'` for string literals

---

.github/workflows/RollPyTorch.yml

The RollPyTorch action often takes more than 1.5 hours to finish.
During this time, if another PR is merged, then the RollPyTorch action
needs to first pull the merged changes before committing the updates to
the PyTorch commit hash and version files.  This patch adds the required
`git pull` statement, without which, the subsequent `git push` statement
fails, causing the RollPyTorch action to fail as well.

ci: run `git pull` before committing pytorch version updates

---

include/torch-mlir/Conversion/Utils/Utils.h
include/torch-mlir/Dialect/Torch/IR/TorchOps.h
lib/CAPI/TorchTypes.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Utils/Utils.cpp
lib/Dialect/TorchConversion/Transforms/BackendTypeConversion.cpp
lib/RefBackend/RefBackend.cpp

- Replace `llvm::None` with `std::nullopt`, since the former is deprecated
(https://reviews.llvm.org/D139763)
- Use setter for symbol visibility instead of passing string attribute when
creating FuncOp
---
@powderluv @silvasean I am not sure if these changes are sufficient, since the ./build_tools/update_*.sh scripts fail at my end, but most of the lit and e2e tests pass.  If the build fails, feel free to take over.

build: update llvm tag to 3a020527

---

include/torch-mlir/Dialect/Torch/Transforms/Passes.h
include/torch-mlir/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
test/Dialect/Torch/verify-backend-contract-error.mlir

In order to verify if a given IR satisfies the backend contract, the verifier needs to know if decompositions took place, and if so, which ops were decomposed and which were not.
This commit adds two arguments to `verifyBackendContractPass` to specify if decompositions took place and which ops to consider backend legal, similar to the arguments of `LowerToBackendContractPass`.

Pass op legality info to verifyBackendContractPass

---

lib/Dialect/Torch/Utils/Utils.cpp

Functions like `getTypeForScalarType` that do a mapping from one set of types to another should not fail, and if they do it should be obvious to the developer that that function has an unhandled case.
Instead of silently failing when encountering an unsupported type, this commit adds a `report_fatal_error` at the end, similar to other type translation functions in this file.

Add `report_fatal_error` to `getTypeForScalarType`

---

lib/Conversion/Passes.cpp
utils/bazel/torch-mlir-overlay/BUILD.bazel
utils/bazel/torch-mlir-overlay/test/BUILD.bazel

This PR adds the bazel rules needed to build Tcp dialect and TorchtoTcp as well as TcpToLinalg conversions.

[Tcp] Updated bazel rules to build Tcp related targets

---

.github/workflows/RollPyTorch.yml

Now that the RollPyTorch tracker issue exists, we can automate the job
of notifying folks of failures instead of having to do it manually.
This patch adds a step to the workflow to post such a message.

ci: post comment on RollPyTorch tracker issue upon build failure

---

include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h
include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h
include/torch-mlir/Conversion/Utils/Utils.h
include/torch-mlir/Dialect/Torch/IR/TorchOps.h
include/torch-mlir/Dialect/Torch/IR/TorchTypes.h
include/torch-mlir/Dialect/Torch/IR/TorchTypes.td
include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/CAPI/TorchTypes.cpp
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp
lib/Conversion/TorchToMhlo/MhloLegalizeUtils.h
lib/Conversion/TorchToMhlo/Reduction.cpp
lib/Conversion/TorchToMhlo/ViewLike.cpp
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
lib/Conversion/Utils/Utils.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/SimplifyDtypeCalculations.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
lib/Dialect/Torch/Utils/Utils.cpp
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp

- LLVM now includes <optional> instead of "llvm/ADT/Optional.h" in most
(although not all) places
(https://reviews.llvm.org/rG541ef3d61e9341cd38420c0dbca9250c4d0ea04c).
This patch replaces the affected instances of `llvm::Optional` with
`std::optional`.
- In the usages of llvm::Optional that remain, llvm::Optional::value()
is deprecated, so this patch replaces them with a dereference

build: update llvm tag to 7ccbb4df

---

e2e_testing/xfail_sets.py
lib/Dialect/Torch/Transforms/RefineTypes.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

-- The dtype of the result of `aten.embedding` should match that of
the `weight` operand's (operand[0]) instead of hardcoding to f32.
-- This commit aims to provide a fix for the same.
Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>

[RefineTypes] Fix knowledge dtype for `aten.embedding` op

---

e2e_testing/xfail_sets.py
include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeCommon.h
include/torch-mlir/Conversion/Utils/Utils.h
include/torch-mlir/Dialect/Torch/IR/TorchOps.h
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/Utils/Utils.cpp
test/Conversion/TorchToTosa/basic.mlir

https://github.com/llvm/torch-mlir/pull/1610
This issue is found when converting deberta model https://github.com/nod-ai/SHARK/issues/493.
Here is the tf style [gathernd.mlir](https://gist.github.com/AmosLewis/a2957a0cf1894f2c870ba2d58e5e17e7) for the test convertGatherNdOp function seperately. 
Here is the torch style [gathernd_torch.mlir](https://gist.github.com/AmosLewis/2f18434397025211da4491735bcc6db6) for testing the whole pipleline.
Command for testing and debugging:
torch-mlir-opt -convert-torch-to-tosa /tmp/gather.mlir -mlir-print-ir-after-all -mlir-disable-threading --debug --mlir-print-ir-before-all
The final tosa should look like the test in [tf_gather_nd_to_tosa](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir#: …

[TOSA] Add aten.gather support for tosa

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToMhlo/Basic.cpp
test/Conversion/TorchToMhlo/basic.mlir

[MHLO] Evaluate RuntimeAssertOp at compile time, since MHLO doesn't support runtime assertion.
It further enabled `aten.std.correction` op to be lowered to MHLO, and made one of the MHLO tests pass.

[MHLO] Evaluate RuntimeAssertOp at compile time

---

lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp

There are several decompositions that assume the operands of the op have dtypes available; however, the only time dtypes are guaranteed to be present is when the graph has reached the backend contract. In general, every pass that happens before reaching the backend contract should not assume dtypes are available and should use `hasDtype` to check first.
This commit adds `hasDtype` checks to every decomposition that uses dtypes.

Add `hasDtype` checks everywhere dtypes are used in decompositions

---

setup.py

After a recent LLVM tag update, the Windows Release build failed even
though pre- and post-merge Windows CI builds passed.  This patch makes
the Windows Release build use the same flags as the Window CI build to
try and address the Release build failures in the future.
---
@powderluv This was the only difference I found between Windows CI and Windows Release builds.  I'm not sure if it will resolve the Release build issue, but it's worth a try.
The Release builds for all platforms completed successfully with this patch [https://github.com/llvm/torch-mlir/actions/runs/3823707248], but of course, the true impact of this patch will only be visible once we update the LLVM tag.

build: match windows CI and Release build steps

---

.github/workflows/buildRelease.yml
build-requirements.txt
build_tools/python_deploy/build_windows.ps1
requirements.txt
utils/bazel/docker/Dockerfile
whl-requirements.txt

- Use v3 of actions/checkout, since the version we use (v2) uses
Node.js 12, which is deprecated by GitHub.
- Source the PowerShell venv sctipt (instead of the bash sript) since
the calling script is a PowerShell script.  Without this, the build
doesn't use venv at all.
- Make the build dependencies in whl-requirements.txt (used by
setup.py) match those in requirements.txt.  To that end, this patch
creates a build-requirements.txt that is referenced by
requirements.txt and whl-requirements.txt.

CI: miscellaneous fixes for Release builds

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/__init__.py
python/torch_mlir_e2e_test/test_suite/norm_like.py

Added support for `aten::norm.ScalarOpt_dim` which is required by `torch.nn.functional.normalize`.

Added support for aten::norm.ScalarOpt_dim

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp
test/Conversion/TorchToTosa/basic.mlir

This PR fixes a couple of issues with the conversion of `torch.aten.unsqueeze` to `tosa.reshape`.
* When input dim < 0, the conversion to positive is off by 1. 
* When input dim == rank, 1 does not get appended to the output shape.

Fix unsqueeze in Torch to Tosa conversion

---

lib/Conversion/CMakeLists.txt
lib/Conversion/Passes.cpp
lib/Conversion/TorchToMhlo/Linear.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Conversion/TorchToTosa/TosaLegalizeCommon.cpp
lib/Conversion/TorchToTosa/TosaLegalizeUtils.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/SimplifyDtypeCalculations.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
test/Conversion/TorchToTosa/basic.mlir

Credit to @vivekkhandelwal1 for finding the necessary changes.
- Switch Tosa_IntArrayAttr[N], Tosa_IntArrayAttrUpto[N] to DenseI64ArrayAttr.
- Replace kNoIterationLimit with kNoLimit. (https://reviews.llvm.org/D140525)
- Add dependency on MhloPasses when MHLO is enabled
- Specify result type when using mhlo::DotOp
--
cc: @GlebKazantaev

build: update llvm tag to de3f0f7f

---

include/torch-mlir/Dialect/Torch/Utils/Utils.h
lib/Conversion/TorchToLinalg/TensorConstructors.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/SimplifyDtypeCalculations.cpp
lib/Dialect/Torch/Utils/Utils.cpp

One of the potential values for a `torch_upstream::ScalarType` is `Undefined`. This means that conversion of a `ScalarType` to another type is a computation that can fail. To enforce handling of the failure case, this commit makes the two helper functions that convert `ScalarType`s into other types return `failure()` when the `ScalarType` is `Undefined`.

Make `getTypeForScalarType` safer by returning `FailureOr<Type>`

---

lib/CAPI/TorchTypes.cpp

`llvm::makeArrayRef` is now deprecated and can be
replaced by the newly introduced `ArrayRef` deduction guides.
Fixes: #1808

Using `ArrayRef` deduction guides.

---

build_tools/python_deploy/build_windows.ps1

Use the delvewheel to package our windows whl. It is similar to auditwheel in Linux.
Test: Import and run the samples via torch-mlir on windows
Fixes https://github.com/llvm/torch-mlir/issues/1819

Use delvewheel to package windows DLLs

---

build_tools/python_deploy/build_linux_packages.sh

Previously, torchvision had not released WHL files for Python v3.8,
causing failures in torch-mlir python package builds, so we had disabled
building for Python v3.8.
Now that the WHL files are back, this patch re-enables v3.8 builds.

CI: build torch-mlir python package for Python v3.8

---

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorInterfaces.h
externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorInterfaces.td
externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
include/torch-mlir/Dialect/Torch/IR/TorchOps.td
lib/Conversion/TorchConversionToMLProgram/TorchConversionToMLProgram.cpp
lib/Dialect/Torch/IR/TorchDialect.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp
lib/Dialect/Torch/Transforms/EraseModuleInitializer.cpp
lib/Dialect/Torch/Transforms/GlobalizeObjectGraph.cpp
lib/Dialect/Torch/Transforms/InlineGlobalSlots.cpp
lib/Dialect/Torch/Transforms/PrepareForGlobalizeObjectGraph.cpp
lib/Dialect/Torch/Transforms/RefineTypes.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
lib/Dialect/TorchConversion/IR/TorchConversionDialect.cpp
lib/Dialect/TorchConversion/Transforms/BackendTypeConversionPasses.cpp

Rename BlockAndValueMapping to IRMapping
*TODO* Dropped TypesMatchedWith Trait from Torch_PrimTupleConstructOp.
Upstream change https://reviews.llvm.org/D141231 creates a new
inferReturnTypes method that fails to compile for this Op. It appears to not support a mix of Variadic operands/non-variadic return type.

update llvm to d23516e9ad477527a9db4d06b1fa9566680ac67c

---

externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorBase.td
externals/llvm-external-projects/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
include/torch-mlir/Dialect/Torch/IR/TorchBase.td
include/torch-mlir/Dialect/TorchConversion/IR/TorchConversionBase.td
lib/Conversion/TorchToLinalg/DataMovement.cpp
lib/Conversion/TorchToMhlo/Basic.cpp
lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
lib/Conversion/TorchToTosa/TorchToTosa.cpp
lib/Dialect/Torch/IR/TorchOps.cpp
lib/Dialect/Torch/IR/TorchTypes.cpp
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
lib/Dialect/Torch/Transforms/SimplifyShapeCalculations.cpp
lib/Dialect/TorchConversion/IR/TorchConversionOps.cpp
lib/RefBackend/RefBackend.cpp
test/Dialect/Torch/invalid.mlir

This commit makes the following changes:
- Update dialects to use fold API `kEmitFoldAdaptorFolder` and update signature of `fold` methods (see PSA
https://discourse.llvm.org/t/psa-new-improved-fold-method-signature-has-landed-please-update-your-downstream-projects/67618)
- Replace `makeArrayRef` with `ArrayRef` (see https://reviews.llvm.org/D140896)
- Remove `TypeRange{}` arg from `b.create<scf::IfOp>` since builder no longer takes that argument
- Make `func`s in `Torch/invalid.mlir` private, since symbol
declarations cannot be public. (see https://discourse.llvm.org/t/rfc-symbol-definition-declaration-x-visibility-checks/2140)

build: update llvm tag to 9acc2f37

---

include/torch-mlir/Dialect/Torch/Transforms/Passes.h
include/torch-mlir/Dialect/Torch/Transforms/Passes.td
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
python/torch_mlir/csrc/base_lazy_backend/CMakeLists.txt
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp
python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.h
python/torch_mlir/csrc/base_lazy_backend/utils/jit_utils.cpp
python/torch_mlir/csrc/base_lazy_backend/utils/jit_utils.h
test/Dialect/Torch/verify-backend-contract-error.mlir

In this PR I enable `VerifyBackendContract` pass as a part of LTC backend contract to check that MLIR satisfies backend requirements. See https://github.com/llvm/torch-mlir/issues/1460 for more details.
* Update `TorchMlirLoweringContext::Build` with `VerifyBackendContract` pass execution.
* Updated `TorchMlirComputation` to accept `MlirModule`.
* Removed useless `VerifyBackendContract` pass parametrization.
This PR depends on changes in PyTorch https://github.com/pytorch/pytorch/pull/92095 so once they land I will mark this PR as ready for review.

Enable VerifyBackendContract in LTC backend

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToMhlo/Pooling.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

This PR supports lowering `aten.cumsum` op to the MHLO backend. The static-shape cumsum e2e test has passed in MHLO config.

[MHLO] Support cumsum op in mhlo backend

---

e2e_testing/xfail_sets.py

This update caused the issue as well: https://github.com/llvm/torch-mlir/issues/1859
I had to add ConvolutionModule2DGroups_basic to xfail_sets to pass all CI.

build: update llvm tag to ba8b8a73f

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp

Find this in OPT model : https://github.com/nod-ai/SHARK/issues/865
If you have an elementwise op, those support implicit broadcasting, so you could choose one that shouldn't affect the result and use that. It's a bit tricky with FP to find that right op.
In TOSA, elementwise ops like ADD are defined to broadcast where needed along axis of size 1. You could add a constant tensor of 0 to your tensor with the right shape [1,1,128,1], and that should get a result tensor of [1,1,128,128].
https://gist.github.com/AmosLewis/2890afedc18b40f2860fc9605bf272e0
```
func.func @torch.aten.broadcast_to(%arg0: !torch.vtensor<[1,1,1,128],i1>) -> !torch.vtensor<[1,1,128,128],i1> {
%int1 = torch.constant.int 1
%int128 = torch.constant.int 128
%1 = torch.prim.ListConstruct %int1, %int1, %int128, %int128 : …
```

[TOSA] Fix broadcast_to input and output different shape support

---

CMakeLists.txt
build-requirements.txt
python/CMakeLists.txt
requirements.txt
setup.py
test/python/smoketest.py
whl-requirements.txt

```shell
$ rm -rf venv
$ python -m venv venv
$ source venv/bin/activate
(venv) $ python test/python/smoketest.py
File "test/python/smoketest.py", line 3, in <module>
import torch_mlir.ir
ModuleNotFoundError: No module named 'torch_mlir'
$ pip install -r build-requirements.txt
$ TORCH_MLIR_ENABLE_ONLY_MLIR_PYTHON_BINDINGS=1 CMAKE_GENERATOR=Ninja python setup.py bdist_wheel -d wheelhouse
<STUFF HAPPENS>
(venv) $ pip install wheelhouse/torch-mlir.whl
<STUFF HAPPENS>
(venv) $ python test/python/smoketest.py
module {
%none = torch.constant.none
}
(venv) $ pip freeze | grep torch
torch-mlir==0.0.1
```
Note the absense of `torch==2.0.0.dev20230205`.

BUILD: No PyTorch dep

---

pytorch-requirements.txt

rollback to yesterday's pytorch since today's torchvision depends on yesterday's torch.

Set torch / torchvision versions in sync. 

---

.github/actions/setup-build/action.yml
.github/workflows/RollPyTorch.yml
build_tools/python_deploy/build_macos_packages.sh
build_tools/python_deploy/build_windows.ps1
requirements.txt
test-requirements.txt
torchvision-requirements.txt

We want to ensure that pip packages required for building torch-mlir
should be included in the dependencies of torch-mlir, but we don't want
the pip packages required for _testing_ of torch-mlir to be included
among the dependencies.  To be able to specify and install one set of
dependencies and not the other, this patch separates the pip packages
into two files: build-requirements.txt and test-requirements.txt.
This patch also updates references to the requirements.txt file so that
CI builds that run end-to-end tests install test-related pip
dependencies while everything else (including WHL builds) sticks to just
the build-related pip dependencies.
Despite this change, this patch should not affect a torch-mlir
developer's workflow.  More precisely, since this patch makes the
top-level …

python: separate build- and test-related pip dependencies
